### ISSUE TITLE
List[yara.Matches] = self.rules.match(data=f.read(), timeout=self.options.timeout) yara.Error: internal error: 34

### ISSUE THREAD

**Issue by HughLu** [MobSF/Mobile-Security-Framework-MobSF#1013]
[ERROR] 23/Jul/2019 06:12:49 - Error Performing Static Analysis
Traceback (most recent call last):
  File "./Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/static_analyzer.py", line 188, in static_analyzer
    'app_dir'], app_dic['app_path'], app_dic['app_name'])
  File "./Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/apkid.py", line 42, in apkid_analysis
    res = scanner.scan_file(apk_file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/apkid/apkid.py", line 120, in scan_file
    matches: List[yara.Matches] = self.rules.match(data=f.read(), timeout=self.options.timeout)
yara.Error: internal error: 34
[ERROR] 23/Jul/2019 06:12:49 - internal error: 34
[ERROR] 23/Jul/2019 06:12:49 - Internal Server Error: /StaticAnalyzer/
[ERROR] 23/Jul/2019 06:12:49 - "GET /StaticAnalyzer/?

## ENVIRONMENT

```
OS and Version:
Python Version:
MobSF Version:
```

## EXPLANATION OF THE ISSUE

```
What happens, under which versions, under what conditions, when, and what were you expecting instead.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step
2. This is the second step
3. Further steps, etc.
```

## LOG FILE

```
Paste the contents of logs/debug.log here or attach the log file.
```

**Comment by HughLu** [comment]
OS and Version: MacOS Mojave 10.14.5
Python Version: 3.7
MobSF Version: Master
