### ISSUE TITLE
[geny] Missing File location for adb

### ISSUE THREAD

**Issue by specters312** [MobSF/Mobile-Security-Framework-MobSF#1071]
Good evening I hope all is well I just started playing with the geny branch of Mobsf and wanted to check on a possible bug.

## ENVIRONMENT

```
OS and Version: Darwin-18.6.0-x86_64-i386-64bit or MacOs 10.14.5 (18F132)
Python Version: Python 3.7.4
MobSF Version: Mobsf Geny v1.1.6 Beta
```

## EXPLANATION OF THE ISSUE

```
Looks like a file path is possibly missing or pointed wrong in setup.sh just wanted to let you know in case you were not aware.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. Fresh install of Mobsf branch [geny] `git clone --single-branch --branch geny https://github.com/MobSF/Mobile-Security-Framework-MobSF.git`
2. chmod +x setup.sh && ./setup.sh 
3. Look for error
```
```
[ERROR] 22/Aug/2019 05:19:49 - Getting ADB Location
Traceback (most recent call last):
File "/Users/nrivera/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 432, in get_adb     
    os.chmod(adb_dir, 0o744)
FileNotFoundError: [Errno 2] No such file or directory: 
/Users/nrivera/Mobile-Security-Framework-MobSF/DynamicAnalyzer/tools/adb/mac/
```

## SECTION OF LOG FILE

```
[INFO] 22/Aug/2019 05:19:49 - Mobile Security Framework v1.1.6 Beta
REST API Key: b638b6f88a342f39c4d78933f520521959cfbdd9ca0dc31b0a4ac37c332847f5
[INFO] 22/Aug/2019 05:19:49 - OS: Darwin
[INFO] 22/Aug/2019 05:19:49 - Platform: Darwin-18.6.0-x86_64-i386-64bit
[INFO] 22/Aug/2019 05:19:49 - MobSF Basic Environment Check
[ERROR] 22/Aug/2019 05:19:49 - Getting ADB Location
Traceback (most recent call last):
  File "/Users/nrivera/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 432, in get_adb
    os.chmod(adb_dir, 0o744)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nrivera/Mobile-Security-Framework-MobSF/DynamicAnalyzer/tools/adb/mac/'
[INFO] 22/Aug/2019 05:19:49 - Checking for Update.
```

**Comment by specters312** [comment]
Checking for possible file path as adb might be there just under a different folder.

**Comment by specters312** [comment]
I had to create both /adb and /mac
```
/Users/nrivera/Mobile-Security-Framework-MobSF/DynamicAnalyzer/tools/adb/mac/
```

**Comment by specters312** [comment]
This issue is actually irrelevant. sorry

**Comment by ajinabraham** [comment]
There is some stale code. For ADB checking. We stopped shipping adb since we are using the one provided by Genymotion. I will make few commits. So that you won't see this error.

**Comment by specters312** [comment]
No its fine I completely forgot geny was being used when I made this issue. Maybe it would be good to check this directory instead though 
```/Applications/Genymotion.app/Contents/MacOS/tools/adb```
And then just throw the error install geny or change the settings file to genys adb.
