### ISSUE TITLE
'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by s2339956** [MobSF/Mobile-Security-Framework-MobSF#1073]
```
OS and Version: Darwin-15.6.0-x86_64-i386-64bit
Python Version: 3.7
MobSF Version: v1.1.6 Beta
```

## EXPLANATION OF THE ISSUE

```
V0.9.5.5 Beta version can be used, v1.1.6 Beta error
```

## STEPS TO REPRODUCE THE ISSUE

```
1. Upload file
2. Waiting for analysis
3. An error occurred
```

## LOG FILE

```
[WARNING] 23/Aug/2019 07:28:40 - Could not find VirtualBox path
[INFO] 23/Aug/2019 07:28:40 - MobSF Basic Environment Check
[INFO] 23/Aug/2019 07:28:40 - Checking for Update.
[INFO] 23/Aug/2019 07:28:41 - No updates available.
[INFO] 23/Aug/2019 07:28:55 - MIME Type: application/octet-stream FILE: test_uuu.ipa
[INFO] 23/Aug/2019 07:28:56 - Performing Static Analysis of iOS IPA
[INFO] 23/Aug/2019 07:28:56 - iOS Static Analysis Started
[INFO] 23/Aug/2019 07:28:56 - iOS Binary (IPA) Analysis Started
[INFO] 23/Aug/2019 07:28:56 - Generating Hashes
[INFO] 23/Aug/2019 07:28:56 - Extracting IPA
[INFO] 23/Aug/2019 07:28:56 - Unzipping
[INFO] 23/Aug/2019 07:28:57 - Get Files, BIN Plist -> XML, and Normalize
[INFO] 23/Aug/2019 07:28:57 - iOS Info.plist Analysis Started
[INFO] 23/Aug/2019 07:28:57 - Finding Info.plist in iOS Binary
[INFO] 23/Aug/2019 07:28:57 - Checking Permissions
[INFO] 23/Aug/2019 07:28:57 - Checking for Insecure Connections
[INFO] 23/Aug/2019 07:28:57 - Fetching Details from App Store: tw.gov.post.guard
[WARNING] 23/Aug/2019 07:28:58 - Unable to get app details
[INFO] 23/Aug/2019 07:28:58 - Starting Binary Analysis
[WARNING] 23/Aug/2019 07:28:58 - MobSF Cannot find binary in /Users/digicentre/Mobile-Security-Framework-MobSF/uploads/a9b35b6f9832daeeae2be49bff523a6c/Payload/test_UUU.app/test_UUU
[WARNING] 23/Aug/2019 07:28:58 - Skipping Otool, Classdump and Strings
[INFO] 23/Aug/2019 07:28:58 - Connecting to DB
[INFO] 23/Aug/2019 07:28:58 - Saving to Database
[ERROR] 23/Aug/2019 07:28:58 - Saving to DB
Traceback (most recent call last):
  File "/Users/digicentre/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/db_interaction.py", line 174, in create_db_entry_ipa
    MACHOINFO=bin_dict['macho'],
KeyError: 'macho'
[ERROR] 23/Aug/2019 07:28:58 - Rendering to Template
Traceback (most recent call last):
  File "/Users/digicentre/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/db_interaction.py", line 46, in get_context_from_analysis_ipa
    'binary_info': bin_dict['macho'],
KeyError: 'macho'
[ERROR] 23/Aug/2019 07:28:58 - Error Perfroming Static Analysis
Traceback (most recent call last):
  File "/Users/digicentre/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/static_analyzer.py", line 181, in static_analyzer_ios
    context['VT_RESULT'] = None
TypeError: 'NoneType' object does not support item assignment
[ERROR] 23/Aug/2019 07:28:58 - 'NoneType' object does not support item assignment
[ERROR] 23/Aug/2019 07:28:58 - Internal Server Error: /StaticAnalyzer_iOS/
```

**Comment by superpoussin22** [comment]
did you run setup .sh ?  perhaps you could switch to slack channel to exchange on this

**Comment by s2339956** [comment]
> did you run setup .sh ? perhaps you could switch to slack channel to exchange on this

yes, I tried to reinstall, the result is so.

**Comment by ajinabraham** [comment]
This is because
`MobSF Cannot find binary in /Users/digicentre/Mobile-Security-Framework-MobSF/uploads/a9b35b6f9832daeeae2be49bff523a6c/Payload/test_UUU.app/test_UUU`

Can you share the IPA for debugging.

**Comment by ajinabraham** [comment]
got the ipa in email. Debugging this.

**Comment by ajinabraham** [comment]
Fixed in latest master
