### ISSUE TITLE
Error Performing Static Analysis

### ISSUE THREAD

**Issue by ReaperSlayer** [MobSF/Mobile-Security-Framework-MobSF#1080]
[ERROR] 08/Sep/2019 16:25:14 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/static_analyzer.py", line 186, in static_analyzer
    'app_dir'], app_dic['app_path'], app_dic['app_name'])
  File "/root/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/apkid.py", line 42, in apkid_analysis
    res = scanner.scan_file(apk_file)
  File "/usr/local/lib/python3.7/dist-packages/apkid/apkid.py", line 120, in scan_file
    matches: List[yara.Matches] = self.rules.match(data=f.read(), timeout=self.options.timeout)
yara.Error: internal error: 34
[ERROR] 08/Sep/2019 16:25:14 - internal error: 34
[ERROR] 08/Sep/2019 16:25:14 - Internal Server Error: /StaticAnalyzer/
[ERROR] 08/Sep/2019 16:25:14 - "GET /StaticAnalyzer/?name=com.myairtelapp_4483_apkplz.net.apk&type=apk&checksum=91cf9a320c919d5e7002e750af0e00a8 HTTP/1.1" 500 4796

**Comment by ReaperSlayer** [comment]
Getting it for all apks

**Comment by ajinabraham** [comment]
This comes from an incomplete APKiD installation. Delete your venv and re-run setup.sh. If the error persist, you will have to manually install APKiD separately inside the venv.
