### ISSUE TITLE
"OSError: [Errno 22] Invalid argument: " Dynamic Analysis - Windows 10 - MobSF v.2.0

### ISSUE THREAD

**Issue by ghub101** [MobSF/Mobile-Security-Framework-MobSF#1086]
## ENVIRONMENT

```
OS and Version: Windows 10
Python Version: 3.7.4
MobSF Version: 2.0
```

## EXPLANATION OF THE ISSUE

```
What happens, under which versions, under what conditions, when, and what were you expecting instead.
When executing "run.bat" and OSError occurs.

 It appears to related the "com.crashlytics.sdk.android:answers:settings.xml" which contains colons which is causing an error in Windows 10
```

## STEPS TO REPRODUCE THE ISSUE

```
start MobSF with "run.bat"
```

## LOG FILE

```
[INFO] 22/Sep/2019 16:04:30 - Getting app files
[ERROR] 22/Sep/2019 16:04:30 - Tar extraction failed
Traceback (most recent call last):
  File "C:\Users\Gilbert.Hazel\Documents\GitHub\Mobile-Security-Framework-MobSF\DynamicAnalyzer\views\android\analysis.py", line 174, in get_app_files
    tar.extractall(untar_dir)
  File "C:\Users\Gilbert.Hazel\Anaconda3\lib\tarfile.py", line 2002, in extractall
    numeric_owner=numeric_owner)
  File "C:\Users\Gilbert.Hazel\Anaconda3\lib\tarfile.py", line 2044, in extract
    numeric_owner=numeric_owner)
  File "C:\Users\Gilbert.Hazel\Anaconda3\lib\tarfile.py", line 2114, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\Users\Gilbert.Hazel\Anaconda3\lib\tarfile.py", line 2155, in makefile
    with bltn_open(targetpath, "wb") as target:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\testuser\\Documents\\GitHub\\Mobile-Security-Framework-MobSF\\uploads\\28f3efeb40baaecf8f88cd21993ec250\\DYNAMIC_DeviceData\\data\\data\\com.sainsburys.gol\\shared_prefs\\com.crashlytics.sdk.android:answers:settings.xml'
[INFO] 22/Sep/2019 16:04:30 - Generating Download
```

**Comment by ajinabraham** [comment]
This looks like a windows problem as colons in filenames are reserved characters in Windows. We don't like the idea of renaming the actual file for the sake of supporting in Windows. We will look into alternatives and track this as an enhancement separately.

**Comment by ajinabraham** [comment]
Should be handled by the new pathlib
