### ISSUE TITLE
Inappropriate argument type.  'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by mekhaleraj** [MobSF/Mobile-Security-Framework-MobSF#1087]
## ENVIRONMENT

```
OS and Version: Windows 7
Python Version: 3.7.4
MobSF Version: 2.0
```

## EXPLANATION OF THE ISSUE

```
While performing static code analysis faced -  Inappropriate argument type. 'NoneType' object is not subscriptable error.
```
Static analyzer working fine for same apk in docker. Need to perform Dynamic test 

## STEPS TO REPRODUCE THE ISSUE

```
1. Installed MobSF v 2.0 on windows 7
2. Started it and uploaded apk to analyze 
3. While performing static code analysis error thrown
```

## LOG FILE

```
[INFO] 02/Oct/2019 10:34:42 -
  __  __       _    ____  _____         ____    ___
 |  \/  | ___ | |__/ ___||  ___| __   _|___ \  / _ \
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / __) || | | |
 | |  | | (_) | |_) |__) |  _|    \ V / / __/ | |_| |
 |_|  |_|\___/|_.__/____/|_|       \_/ |_____(_)___/

[INFO] 02/Oct/2019 10:34:42 - Mobile Security Framework v2.0.0 Beta
REST API Key: ccf43543721bbdbb44b925239b0efc3091223d7f009aa87765cd1e14b60858ad
[INFO] 02/Oct/2019 10:34:42 - OS: Windows
[INFO] 02/Oct/2019 10:34:42 - Platform: Windows-7-6.1.7601-SP1
[INFO] 02/Oct/2019 10:34:42 - MobSF Basic Environment Check
[WARNING] 02/Oct/2019 10:34:42 - Dynamic Analysis related functions will not work.
Make sure a Genymotion Android VM is running before performing Dynamic Analyis.
[INFO] 02/Oct/2019 10:34:42 - Checking for Update.
[INFO] 02/Oct/2019 10:34:42 - No updates available.
[INFO] 02/Oct/2019 10:34:50 - MIME Type: application/vnd.android.package-archive FILE: be.telenet.phubd_1.0.apk
[INFO] 02/Oct/2019 10:34:50 - Performing Static Analysis of Android APK
[INFO] 02/Oct/2019 10:34:50 - Starting Analysis on : be.telenet.phubd_1.0.apk
[INFO] 02/Oct/2019 10:34:50 - Generating Hashes
[INFO] 02/Oct/2019 10:34:50 - Unzipping
[INFO] 02/Oct/2019 10:34:58 - Getting Hardcoded Certificates/Keystores
[INFO] 02/Oct/2019 10:34:58 - APK Extracted
[INFO] 02/Oct/2019 10:34:58 - Converting AXML to XML
[INFO] 02/Oct/2019 10:35:20 - Reading Android Manifest
[INFO] 02/Oct/2019 10:35:20 - Parsing AndroidManifest.xml
[INFO] 02/Oct/2019 10:35:20 - Fetching icon path
[INFO] 02/Oct/2019 10:35:21 - Extracting Manifest Data
[INFO] 02/Oct/2019 10:35:21 - Fetching Details from Play Store: be.telenet.phubd
[WARNING] 02/Oct/2019 10:35:22 - Unable to get app details.
[INFO] 02/Oct/2019 10:35:22 - Manifest Analysis Started
[INFO] 02/Oct/2019 10:35:22 - Static Android Binary Analysis Started
[INFO] 02/Oct/2019 10:35:22 - Static Android Resource Analysis Started
[INFO] 02/Oct/2019 10:35:22 - Reading Code Signing Certificate
[INFO] 02/Oct/2019 10:35:22 - Running APKiD 2.0.3
[INFO] 02/Oct/2019 10:35:28 - Trackers Database is outdated!
[INFO] 02/Oct/2019 10:35:28 - Updating Trackers Database....
[INFO] 02/Oct/2019 10:35:28 - Detecting Trackers
[INFO] 02/Oct/2019 10:35:32 - APK -> JAVA
[INFO] 02/Oct/2019 10:35:32 - Decompiling to Java with jadx
[INFO] 02/Oct/2019 10:39:07 - DEX -> SMALI
[INFO] 02/Oct/2019 10:39:07 - Converting classes.dex to Smali Code
[INFO] 02/Oct/2019 10:39:07 - Converting classes2.dex to Smali Code
[INFO] 02/Oct/2019 10:39:07 - Static Android Code Analysis Started
[INFO] 02/Oct/2019 10:39:07 - Code Analysis Started on - java_source
[ERROR] 02/Oct/2019 10:40:21 - Performing Code Analysis
Traceback (most recent call last):
  File "C:\Users\rm\Documents\Mobile-Security-Framework-MobSF-master\StaticAnalyzer\views\android\code_analysis.py", line 63, in code_analysis
    errors='ignore',
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\rm\\Documents\\Mobile-Security-Framework-MobSF-master\\uploads/8b4f97d396f54b4b8e32469d9f96a45c/java_source/be\\telenet\\phubd\\presentation\\common\\messaging\\PhubdMessagingServiceModuleKt$phubdForegroundServiceModule$1$$special$$inlined$singleton$1.java'
[INFO] 02/Oct/2019 10:40:21 - Extracting Strings from APK
[ERROR] 02/Oct/2019 10:40:25 - Error Performing Static Analysis
Traceback (most recent call last):
  File "C:\Users\rm\Documents\Mobile-Security-Framework-MobSF-master\StaticAnalyzer\views\android\static_analyzer.py", line 209, in static_analyzer
    code_an_dic['urls_list'].extend(
TypeError: 'NoneType' object is not subscriptable
[ERROR] 02/Oct/2019 10:40:25 - 'NoneType' object is not subscriptable
[ERROR] 02/Oct/2019 10:40:25 - Internal Server Error: /StaticAnalyzer/
ERROR:django.request:Internal Server Error: /StaticAnalyzer/




```

**Comment by superpoussin22** [comment]
which version of python exactly ?  on windows I think 3.7 is required

**Comment by mekhaleraj** [comment]
Python 3.7.4

**Comment by superpoussin22** [comment]
did you runsetup.bat without error ?

**Comment by mekhaleraj** [comment]
yes.

**Comment by ajinabraham** [comment]
Looks like file name issue in Windows. Can you share the APK?

**Comment by mekhaleraj** [comment]
Won't be able to share current APK, belongs to office.

I'll check with demo application and share APK and error details with you.

**Comment by mekhaleraj** [comment]
Won't be able to share current APK, belongs to office.

I'll check with demo application and share APK and error details with you.

**Comment by mekhaleraj** [comment]
APK shared via email

**Comment by ajinabraham** [comment]
The APK shared works fine for me on Mac. Looks like a possible windows filename issue. I am gonna take a look in windows environment soon.

**Comment by mekhaleraj** [comment]
Thanks.

**Comment by mekhaleraj** [comment]
Shared actual APK and error details on mail.

**Comment by ajinabraham** [comment]
@mekhaleraj It's due to windows filename restrictions

```
>>> from pathvalidate import ValidationError, validate_filename
>>> validate_filename('C:\\Users\\rm\\Documents\\Mobile-Security-Framework-MobSF-master\\uploads/8b4f97d396f54b4b8e32469d9f96a45c/java_source/be\\telenet\\phubd\\presentation\\common\\messaging\\PhubdMessagingServiceModuleKt$phubdForegroundServiceModule$1$$special$$inlined$singleton$1.java')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ajinabraham/Code/venv/lib/python3.6/site-packages/pathvalidate/_file.py", line 476, in validate_filename
    FileNameSanitizer(platform=platform, min_len=min_len, max_len=max_len).validate(filename)
  File "/Users/ajinabraham/Code/venv/lib/python3.6/site-packages/pathvalidate/_file.py", line 238, in validate
    "filename is too long: expected<={:d}, actual={:d}".format(self.max_len, value_len)
pathvalidate.error.InvalidLengthError: filename is too long: expected<=255, actual=256, reason=INVALID_LENGTH
```

You might want to consider using a docker image on windows or consider setting up MobSF in Mac/Linux where this filename restrictions doesn't apply. 
Also moving `C:\\Users\\rm\\Documents\\Mobile-Security-Framework-MobSF-master` to `C:\\Mobile-Security-Framework-MobSF-master` can reduce the file length a bit.

**Comment by OzAven** [comment]
Hi,

I just got the same error running MobSF from the latest docker on Ubuntu 18.04.
Any idea if there is a none windows related fix?

Thx

**Comment by OzAven** [comment]
[ERROR] 02/Oct/2019 17:04:33 - Saving to DB
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py", line 255, in create_db_entry
    CERT_INFO=cert_dic['cert_info'],
TypeError: 'NoneType' object is not subscriptable
[ERROR] 02/Oct/2019 17:04:33 - Rendering to Template
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py", line 120, in get_context_from_analysis
    'certinfo': cert_dic['cert_info'],
TypeError: 'NoneType' object is not subscriptable
[ERROR] 02/Oct/2019 17:04:33 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/static_analyzer.py", line 271, in static_analyzer
    'security_score'] = score(context['findings'])
TypeError: 'NoneType' object is not subscriptable
[ERROR] 02/Oct/2019 17:04:33 - 'NoneType' object is not subscriptable
[ERROR] 02/Oct/2019 17:04:33 - Internal Server Error: /StaticAnalyzer/

**Comment by ajinabraham** [comment]
it's not the same. different cause. due to certificate analysis failure. Also incomplete information.

**Comment by OzAven** [comment]
Thanks for the quick response.
What additional information is needed?

**Comment by ajinabraham** [comment]
The full logs and os , version etc as mentioned in a bug report.. Please open a separate issue.

**Comment by nishapatil-lab** [comment]
I m facing issue while uploading apk..I m getting error saying inappropriate content..can not unpack non iterable..need a help ..using windows 10

**Comment by alexhak1** [comment]
Any update, with windows10?

**Comment by agrawalsmart7** [comment]
Same with Windows 11.  Please get this resolve, wasted lot of time on this.
