### ISSUE TITLE
No check if virtualenv was created in setup.sh

### ISSUE THREAD

**Issue by reox** [MobSF/Mobile-Security-Framework-MobSF#1091]
ENVIRONMENT

```
OS and Version: Debian Buster
Python Version: 3.7
MobSF Version: master
```

## EXPLANATION OF THE ISSUE

```
When you run `setup.sh` but something fails, all other commands are executed regardless.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. git clone https://github.com/MobSF/Mobile-Security-Framework-MobSF.git
2. cd Mobile-Security-Framework-MobSF
3. ./setup.sh
```

## LOG FILE

```
$ ./setup.sh
[INSTALL] Found Python3
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)
[INSTALL] Found pip
Cache entry deserialization failed, entry ignored
Collecting pip
  Using cached https://files.pythonhosted.org/packages/30/db/9e38760b32e3e7f40cce46dd5fb107b8c73840df38f0046d8e6514e675a1/pip-19.2.3-py2.py3-none-any.whl
Installing collected packages: pip
Successfully installed pip-19.2.3
[INSTALL] Using venv
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/home/android/git/Mobile-Security-Framework-MobSF/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

./setup.sh: line 43: venv/bin/activate: No such file or directory
[INSTALL] Installing APKiD requirements - yara-python
./setup.sh: line 46: pip: command not found
./setup.sh: line 47: pip: command not found
./setup.sh: line 48: pip: command not found
[INSTALL] Installing Requirements
./setup.sh: line 51: pip: command not found
[INSTALL] Clean Up

=======================MobSF Clean Script for Unix=======================
Running this script will delete the Scan database, all files uploaded and generated.

Deleting all Uploads
Deleting all Downloads
Deleting Static Analyzer Migrations
Deleting Dynamic Analyzer Migrations
Deleting MobSF Migrations
Deleting python byte code files
Deleting temp and log files
Deleting DB
Deleting Secret File
Done
[INSTALL] Migrating Database
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
Download and Install wkhtmltopdf for PDF Report Generation - https://wkhtmltopdf.org/downloads.html
[INSTALL] Installation Complete

```

**Comment by ajinabraham** [comment]
It's clearly mentioned in the Documentation to preinstall requirements. Follow official documentation https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#static-analysis

**Comment by reox** [comment]
What if something else is broken? Like the disk is full.
Sorry to say but not checking return values is bad practise.

**Comment by ajinabraham** [comment]
There are a lot of things that can go wrong with a setup scripts in untested OS and environments. But there are things that can avoided by following the documentation correctly. I agree that improvements can be made to setup/install scripts and we are open to Pull Requests.

**Comment by siloed** [comment]
looking at the above error message posted it seems similar to my issue. so just install what's missing:
apt-get install python3-venv

the requirements section does not seem to mention this above at the time of writing:
https://mobsf.github.io/docs/#/requirements

and also may need this on kali:
apt-get install wkhtmltopdf

**Comment by ajinabraham** [comment]
@siloed The requirements already mention a lot of things. You might have missed it.
![Screenshot_20200430-070003](https://user-images.githubusercontent.com/4301109/80703287-82b50500-8ab0-11ea-81a6-25e2663bca2d.jpg)
![Screenshot_20200430-065954__01](https://user-images.githubusercontent.com/4301109/80703291-834d9b80-8ab0-11ea-84c4-f282df4d7da0.jpg)

**Comment by siloed** [comment]
> @siloed The requirements already mention a lot of things. You might have missed it.
ah yes, you are correct. I seem to have missed that.
