### ISSUE TITLE
MobSFy reports success, even if it fails

### ISSUE THREAD

**Issue by reox** [MobSF/Mobile-Security-Framework-MobSF#1092]
## ENVIRONMENT

```
OS and Version: Debian Buster
Python Version: 3.7
MobSF Version: master
```

## EXPLANATION OF THE ISSUE

```
When clicking the button MobSFy, it returns success, even if the adb command fails
```

## STEPS TO REPRODUCE THE ISSUE

```
1. bring genymotion VM into non working state (i.e. during booting)
2. run MobSFy
```

## LOG FILE

The website says:
```

MobSFying Android Runtime
Sucessfully created MobSF Dynamic Analysis environment.
MobSF agents and Frida server installed.
```

The log says:
```
[INFO] 25/Sep/2019 11:43:25 - OS: Linux
[INFO] 25/Sep/2019 11:43:25 - Platform: Linux-4.19.0-6-amd64-x86_64-with-debian-10.1
[INFO] 25/Sep/2019 11:43:25 - Dist: ('debian', '10.1', '')
[INFO] 25/Sep/2019 11:43:25 - MobSF Basic Environment Check
[INFO] 25/Sep/2019 11:43:25 - Checking for Update.
[INFO] 25/Sep/2019 11:43:25 - No updates available.
[INFO] 25/Sep/2019 11:50:23 - MobSFying Android instance
[INFO] 25/Sep/2019 11:50:24 - ADB Restarted
[INFO] 25/Sep/2019 11:50:24 - Waiting for 2 seconds...
[INFO] 25/Sep/2019 11:50:26 - Connecting to Android 192.168.57.101:5555
[INFO] 25/Sep/2019 11:50:26 - Remounting /system
[INFO] 25/Sep/2019 11:50:26 - Android Version identified as 7.1
[INFO] 25/Sep/2019 11:50:26 - Android instance architecture identified as x86
[INFO] 25/Sep/2019 11:50:26 - Copying frida server
[INFO] 25/Sep/2019 11:50:27 - Installing MobSF RootCA
[INFO] 25/Sep/2019 11:50:27 - Installing MobSF Clipboard Dumper
adb: failed to install /home/android/git/Mobile-Security-Framework-MobSF/DynamicAnalyzer/tools/onDevice/mobsf_agents/ClipDump.apk: Can't find service: package
[ERROR] 25/Sep/2019 11:50:27 - Error Running ADB Command
Traceback (most recent call last):
  File "/home/android/git/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/environment.py", line 68, in adb_command
    result = subprocess.check_output(args)
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/genymobile/genymotion/tools/adb', '-s', '192.168.57.101:5555', 'install', '-r', '/home/android/git/Mobile-Security-Framework-MobSF/DynamicAnalyzer/tools/onDevice/mobsf_agents/ClipDump.apk']' returned non-zero exit status 1.
[INFO] 25/Sep/2019 11:50:27 - MobSFying Completed!
```

**Comment by ajinabraham** [comment]
`Can't find service: package` something wrong with your VM. Kindly retry the steps. Looking into it to see why the exception was ignored.

**Comment by reox** [comment]
the genymotion VM is in a broken state and will not handle adb correctly. but the Webinterface gives OK.

**Comment by ajinabraham** [comment]
That's why we recommend to run a Genymotion Android VM before attempting dynamic analysis,  if it's booting, things won't work.

**Comment by superpoussin22** [comment]
nice to see you here @reox and thanks for your work on Androguard
