### ISSUE TITLE
Reading Code SIgning Certificate error - depreciated function used in master branch?

### ISSUE THREAD

**Issue by gclair** [MobSF/Mobile-Security-Framework-MobSF#1105]
## ENVIRONMENT

```
OS and Version: KUbuntu 18.04
Python Version: 3.6
MobSF Version: master branch (2.0.0 Beta)
```

## EXPLANATION OF THE ISSUE

```
Ran the docker version for static analysis of an APK with no issues. Wanted to try the dynamic analysis
 so followed instructions (At least I think i did!) to clone from github and ran setup/run  to analyze the
same APK and it errors out saying the asn1crypto.keys.PublicKeyInfo() is removed (using asn1crypto
1.0.0 as installed by pip in venv).
```

## STEPS TO REPRODUCE THE ISSUE

```
1. Cloned from github, ran ./setup.sh no errors 
2. ran ./run.sh and analyzed apk 
3. Ran docker image for static analysis, worked with no errors on same apk.
4. docker pull opensecurity/mobile-security-framework-mobsf && 
   docker run -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest
```

## LOG FILE

```
[INFO] 03/Oct/2019 02:35:15 - Generating Hashes
[INFO] 03/Oct/2019 02:35:15 - Unzipping
[INFO] 03/Oct/2019 02:35:15 - Getting Hardcoded Certificates/Keystores
[INFO] 03/Oct/2019 02:35:15 - APK Extracted
[INFO] 03/Oct/2019 02:35:15 - Converting AXML to XML
[INFO] 03/Oct/2019 02:35:18 - Reading Android Manifest
[INFO] 03/Oct/2019 02:35:18 - Parsing AndroidManifest.xml
[INFO] 03/Oct/2019 02:35:19 - Fetching icon path
[INFO] 03/Oct/2019 02:35:19 - Extracting Manifest Data
[INFO] 03/Oct/2019 02:35:19 - Fetching Details from Play Store: com.everbridge.mobile.iv.recipient
[WARNING] 03/Oct/2019 02:35:19 - Unable to get app details.
[INFO] 03/Oct/2019 02:35:19 - Manifest Analysis Started
[INFO] 03/Oct/2019 02:35:19 - Static Android Binary Analysis Started
[INFO] 03/Oct/2019 02:35:19 - Static Android Resource Analysis Started
[INFO] 03/Oct/2019 02:35:19 - Reading Code Signing Certificate
[ERROR] 03/Oct/2019 02:35:20 - Reading Code Signing Certificate
Traceback (most recent call last):
  File "/home/gclair/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/cert_analysis.py", line 111, in cert_info
    binascii.hexlify(x509_public_key.fingerprint).decode('utf-8')))
  File "/home/gclair/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/asn1crypto/keys.py", line 1212, in fingerprint
    'asn1crypto.keys.PublicKeyInfo().fingerprint has been removed, '
asn1crypto._errors.APIException: asn1crypto.keys.PublicKeyInfo().fingerprint has been removed, please use oscrypto.asymmetric.PublicKey().fingerprint instead
[INFO] 03/Oct/2019 02:35:21 - Trackers Database is outdated!
[INFO] 03/Oct/2019 02:35:21 - Updating Trackers Database....
[INFO] 03/Oct/2019 02:35:21 - Detecting Trackers
[INFO] 03/Oct/2019 02:35:22 - APK -> JAVA
[INFO] 03/Oct/2019 02:35:22 - Decompiling to Java with jadx
[INFO] 03/Oct/2019 02:35:31 - DEX -> SMALI
[INFO] 03/Oct/2019 02:35:31 - Converting classes2.dex to Smali Code
[INFO] 03/Oct/2019 02:35:31 - Converting classes.dex to Smali Code
[INFO] 03/Oct/2019 02:35:31 - Static Android Code Analysis Started
[INFO] 03/Oct/2019 02:35:31 - Code Analysis Started on - java_source
[INFO] 03/Oct/2019 02:35:38 - Finished Code Analysis, Email and URL Extraction
[INFO] 03/Oct/2019 02:35:38 - Extracting Strings from APK
[INFO] 03/Oct/2019 02:35:40 - Detecting Firebase URL(s)
[INFO] 03/Oct/2019 02:35:40 - Performing Malware Check on extracted Domains
[INFO] 03/Oct/2019 02:35:41 - Malware Database is up-to-date
[INFO] 03/Oct/2019 02:35:41 - Generating Java and Smali Downloads
[INFO] 03/Oct/2019 02:35:41 - Generating Downloads
[INFO] 03/Oct/2019 02:35:41 - Zipping
[INFO] 03/Oct/2019 02:35:41 - Zipping
[INFO] 03/Oct/2019 02:35:42 - Connecting to Database
[INFO] 03/Oct/2019 02:35:42 - Saving to Database
[ERROR] 03/Oct/2019 02:35:42 - Saving to DB
Traceback (most recent call last):
  File "/home/gclair/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py", line 255, in create_db_entry
    CERT_INFO=cert_dic['cert_info'],
TypeError: 'NoneType' object is not subscriptable
[ERROR] 03/Oct/2019 02:35:42 - Rendering to Template
Traceback (most recent call last):
  File "/home/gclair/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py", line 120, in get_context_from_analysis
    'certinfo': cert_dic['cert_info'],
TypeError: 'NoneType' object is not subscriptable
[ERROR] 03/Oct/2019 02:35:42 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/home/gclair/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/static_analyzer.py", line 271, in static_analyzer
    'security_score'] = score(context['findings'])
TypeError: 'NoneType' object is not subscriptable
[ERROR] 03/Oct/2019 02:35:42 - 'NoneType' object is not subscriptable
[ERROR] 03/Oct/2019 02:35:42 - Internal Server Error: /StaticAnalyzer/
```

**Comment by ajinabraham** [comment]
Fixed in latest master https://github.com/MobSF/Mobile-Security-Framework-MobSF/commit/4cd95cbfde400ab1651060deded65d9229e78b69

**Comment by gclair** [comment]
Verified fixed. Thank you!
