### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by normaler** [MobSF/Mobile-Security-Framework-MobSF#1139]
Hi,

Encountered some TypeError: 'NoneType' object is not subscriptable. Thank you.

[ERROR] 24/Oct/2019 03:07:34 - Saving to DB
Traceback (most recent call last):
  File "/Users/xxxxx/MobSF/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py", line 255, in create_db_entry
    CERT_INFO=cert_dic['cert_info'],
TypeError: 'NoneType' object is not subscriptable
[ERROR] 24/Oct/2019 03:07:34 - Rendering to Template
Traceback (most recent call last):
  File "/Users/xxxxx/MobSF/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py", line 120, in get_context_from_analysis
    'certinfo': cert_dic['cert_info'],
TypeError: 'NoneType' object is not subscriptable
[ERROR] 24/Oct/2019 03:07:34 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/Users/*****/MobSF/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/static_analyzer.py", line 271, in static_analyzer
    'security_score'] = score(context['findings'])
TypeError: 'NoneType' object is not subscriptable
[ERROR] 24/Oct/2019 03:07:34 - 'NoneType' object is not subscriptable
[ERROR] 24/Oct/2019 03:07:34 - Internal Server Error: /StaticAnalyzer/

**Comment by superpoussin22** [comment]
can you provide more info and also the apk ?

**Comment by ajinabraham** [comment]
Incomplete details. Report bugs as requested.
