### ISSUE TITLE
Error While Installing MObSF- please help

### ISSUE THREAD

**Issue by Rollingsmoke** [MobSF/Mobile-Security-Framework-MobSF#1140]
## ENVIRONMENT

```
OS and Version:
Python Version:
MobSFt:Mobile-Security-Framework-MobSF dilipkumar.s01$ ./run.sh
[2019-10-25 14:38:24 +0530] [41919] [INFO] Starting gunicorn 19.9.0
[2019-10-25 14:38:24 +0530] [41919] [INFO] Listening at: http://0.0.0.0:8000 (41919)
[2019-10-25 14:38:24 +0530] [41919] [INFO] Using worker: threads
[2019-10-25 14:38:24 +0530] [41922] [INFO] Booting worker with pid: 41922
[2019-10-25 14:38:24 +0530] [41922] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/dilipkumar.s01/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/dilipkumar.s01/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 104, in init_process
    super(ThreadWorker, self).init_process()
  File "/Users/dilipkumar.s01/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/dilipkumar.s01/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/dilipkumar.s01/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/dilipkumar.s01/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/Users/dilipkumar.s01/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/dilipkumar.s01/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/dilipkumar.s01/Desktop/Mobile-Security-Framework-MobSF/MobSF/wsgi.py", line 17, in <module>
    application = WhiteNoise(get_wsgi_application(),
  File "/Users/dilipkumar.s01/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/Users/dilipkumar.s01/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/Users/dilipkumar.s01/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/Users/dilipkumar.s01/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/dilipkumar.s01/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/dilipkumar.s01/Desktop/Mobile-Security-Framework-MobSF/MobSF/settings.py", line 12, in <module>
    from MobSF.utils import (find_java_binary, first_run,
  File "/Users/dilipkumar.s01/Desktop/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 21, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
[2019-10-25 14:38:24 +0530] [41922] [INFO] Worker exiting (pid: 41922)
[2019-10-25 14:38:24 +0530] [41919] [INFO] Shutting down: Master
[2019-10-25 14:38:24 +0530] [41919] [INFO] Reason: Worker failed to boot.
blrkec007836dt:Mobile-Security-Framework-MobSF dilipkumar.s01$ 
```

## EXPLANATION OF THE ISSUE

```
What happens, under which versions, under what conditions, when, and what were you expecting instead.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step
2. This is the second step
3. Further steps, etc.
```

## LOG FILE

```
Paste the contents of logs/debug.log here or attach the log file.
```

**Comment by Rollingsmoke** [comment]
OS : mac 
Have tried installing psutil manually using brew install psutils
and pip install psutil 

even though im getting the same error 
i have python 2.7 as well in my mac

**Comment by superpoussin22** [comment]
you must use python 3.6 or python 3.7 and run setup.sh

**Comment by Rollingsmoke** [comment]
No it doesnt fix the error
Installing collected packages: sqlparse, pytz, Django, pdfkit, click, colorama, future, pygments, pyparsing, pydot, decorator, networkx, lxml, six, cycler, numpy, python-dateutil, kiwisolver, matplotlib, asn1crypto, backcall, pickleshare, appnope, ptyprocess, pexpect, ipython-genutils, traitlets, wcwidth, prompt-toolkit, parso, jedi, ipython, androguard, pyasn1, rsa, biplist, certifi, urllib3, idna, chardet, requests, soupsieve, beautifulsoup4, bs4, colorlog, altgraph, macholib, google-play-scraper, whitenoise, waitress, gunicorn, frida, psutil, shelljob, oscrypto, hpack, hyperframe, h2, pycparser, cffi, cryptography, pyOpenSSL, urwid, passlib, blinker, tornado, ldap3, pyperclip, brotlipy, h11, wsproto, ruamel.yaml, sortedcontainers, kaitaistruct, mitmproxy, http-tools
    Running setup.py install for future ... done
    Running setup.py install for backcall ... done
    Running setup.py install for biplist ... done
    Running setup.py install for bs4 ... done
    Running setup.py install for google-play-scraper ... done
    Running setup.py install for frida ... done
    Running setup.py install for psutil ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/dilipkumar.s01/Desktop/Mobile-Security-Framework-MobSF/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/dm/9dllh3pn39z_xpwgz2r4qgf00000gp/T/pip-install-ust7v9vj/psutil/setup.py'"'"'; __file__='"'"'/private/var/folders/dm/9dllh3pn39z_xpwgz2r4qgf00000gp/T/pip-install-ust7v9vj/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/dm/9dllh3pn39z_xpwgz2r4qgf00000gp/T/pip-record-zrbghjyk/install-record.txt --single-version-externally-managed --compile --install-headers /Users/dilipkumar.s01/Desktop/Mobile-Security-Framework-MobSF/venv/include/site/python3.7/psutil
         cwd: /private/var/folders/dm/9dllh3pn39z_xpwgz2r4qgf00000gp/T/pip-install-ust7v9vj/psutil/
    Complete output (50 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14-x86_64-3.7
    creating build/lib.macosx-10.14-x86_64-3.7/psutil
    copying psutil/_pswindows.py -> build/lib.macosx-10.14-x86_64-3.7/psutil
    copying psutil/_common.py -> build/lib.macosx-10.14-x86_64-3.7/psutil
    copying psutil/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/psutil
    copying psutil/_psosx.py -> build/lib.macosx-10.14-x86_64-3.7/psutil
    copying psutil/_psbsd.py -> build/lib.macosx-10.14-x86_64-3.7/psutil
    copying psutil/_psaix.py -> build/lib.macosx-10.14-x86_64-3.7/psutil
    copying psutil/_pslinux.py -> build/lib.macosx-10.14-x86_64-3.7/psutil
    copying psutil/_compat.py -> build/lib.macosx-10.14-x86_64-3.7/psutil
    copying psutil/_psposix.py -> build/lib.macosx-10.14-x86_64-3.7/psutil
    copying psutil/_pssunos.py -> build/lib.macosx-10.14-x86_64-3.7/psutil
    creating build/lib.macosx-10.14-x86_64-3.7/psutil/tests
    copying psutil/tests/test_contracts.py -> build/lib.macosx-10.14-x86_64-3.7/psutil/tests
    copying psutil/tests/test_connections.py -> build/lib.macosx-10.14-x86_64-3.7/psutil/tests
    copying psutil/tests/runner.py -> build/lib.macosx-10.14-x86_64-3.7/psutil/tests
    copying psutil/tests/test_unicode.py -> build/lib.macosx-10.14-x86_64-3.7/psutil/tests
    copying psutil/tests/test_misc.py -> build/lib.macosx-10.14-x86_64-3.7/psutil/tests
    copying psutil/tests/test_posix.py -> build/lib.macosx-10.14-x86_64-3.7/psutil/tests
    copying psutil/tests/test_linux.py -> build/lib.macosx-10.14-x86_64-3.7/psutil/tests
    copying psutil/tests/test_sunos.py -> build/lib.macosx-10.14-x86_64-3.7/psutil/tests
    copying psutil/tests/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/psutil/tests
    copying psutil/tests/test_aix.py -> build/lib.macosx-10.14-x86_64-3.7/psutil/tests
    copying psutil/tests/test_process.py -> build/lib.macosx-10.14-x86_64-3.7/psutil/tests
    copying psutil/tests/test_bsd.py -> build/lib.macosx-10.14-x86_64-3.7/psutil/tests
    copying psutil/tests/test_system.py -> build/lib.macosx-10.14-x86_64-3.7/psutil/tests
    copying psutil/tests/test_osx.py -> build/lib.macosx-10.14-x86_64-3.7/psutil/tests
    copying psutil/tests/test_memory_leaks.py -> build/lib.macosx-10.14-x86_64-3.7/psutil/tests
    copying psutil/tests/test_windows.py -> build/lib.macosx-10.14-x86_64-3.7/psutil/tests
    copying psutil/tests/__main__.py -> build/lib.macosx-10.14-x86_64-3.7/psutil/tests
    running build_ext
    building 'psutil._psutil_osx' extension
    creating build/temp.macosx-10.14-x86_64-3.7
    creating build/temp.macosx-10.14-x86_64-3.7/psutil
    creating build/temp.macosx-10.14-x86_64-3.7/psutil/arch
    creating build/temp.macosx-10.14-x86_64-3.7/psutil/arch/osx
    Compiling with an SDK that doesn't seem to exist: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk
    Please check your Xcode installation
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/opt/openssl/include -arch x86_64 -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=563 -DPSUTIL_OSX=1 -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/Users/dilipkumar.s01/Desktop/Mobile-Security-Framework-MobSF/venv/include -I/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c psutil/_psutil_common.c -o build/temp.macosx-10.14-x86_64-3.7/psutil/_psutil_common.o
    clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk' [-Wmissing-sysroot]
    In file included from psutil/_psutil_common.c:9:
    /usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m/Python.h:25:10: fatal error: 'stdio.h' file not found
    #include <stdio.h>
             ^~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/dilipkumar.s01/Desktop/Mobile-Security-Framework-MobSF/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/dm/9dllh3pn39z_xpwgz2r4qgf00000gp/T/pip-install-ust7v9vj/psutil/setup.py'"'"'; __file__='"'"'/private/var/folders/dm/9dllh3pn39z_xpwgz2r4qgf00000gp/T/pip-install-ust7v9vj/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/dm/9dllh3pn39z_xpwgz2r4qgf00000gp/T/pip-record-zrbghjyk/install-record.txt --single-version-externally-managed --compile --install-headers /Users/dilipkumar.s01/Desktop/Mobile-Security-Framework-MobSF/venv/include/site/python3.7/psutil Check the logs for full command output.

**Comment by Rollingsmoke** [comment]
File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/dilipkumar.s01/Desktop/Mobile-Security-Framework-MobSF/MobSF/settings.py", line 12, in <module>
    from MobSF.utils import (find_java_binary, first_run,
  File "/Users/dilipkumar.s01/Desktop/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 21, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
./setup.sh: line 65: wkhtmltopdf: command not found
Download and Install wkhtmltopdf for PDF Report Generation - https://wkhtmltopdf.org/downloads.html
[INSTALL] Installation Complete

**Comment by Rollingsmoke** [comment]
Psutil drives me crazy im trying all possible outcomes doesn't work .. please look into this

**Comment by Rollingsmoke** [comment]
If u can see only the installation of ps util is getting failed for some reason ...

 Running setup.py install for psutil ... error

**Comment by superpoussin22** [comment]
did you install xcode command line utility ?

**Comment by ajinabraham** [comment]
@Rollingsmoke this is not a MobSF issue. Please reach-out to corresponding library developer to fix the issues the dependencies.

**Comment by Rollingsmoke** [comment]
Yes I have xcode for Mac .. I don't know what to do
