### ISSUE TITLE
Dynamic Analysis Error Running ADB Command

### ISSUE THREAD

**Issue by Senanfurkan** [MobSF/Mobile-Security-Framework-MobSF#1154]
## ENVIRONMENT

```
OS and Version: Mac Os Mojave 10.14.6
Python Version: python3.7
MobSF Version: 2.0 / Latest master
```

## EXPLANATION OF THE ISSUE

```
When I click on the Start Dynamic Analysis button. The error below shows up and "Dynamic Analysis Failed" warning appeared on the web application.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. I use the latest Genymotion 3.0.3, created a custom 8.0 API android device.
2. Edited the MobSF/settings.py and wrote the device ip address which is 192.168.56.102
3. Started the MobSF.
4. Click on the dynamic analysis. (I did the static analysis without problem)
5. Error appeared.
```

## LOG FILE

```
[WARNING] 31/Oct/2019 21:39:57 - Dynamic Analysis related functions will not work. 
Make sure a Genymotion Android VM is running before performing Dynamic Analyis.
[INFO] 31/Oct/2019 21:39:57 - Checking for Update.
[INFO] 31/Oct/2019 21:39:58 - No updates available.
[2019-11-01 00:40:02 +0300] [42107] [INFO] Handling signal: winch
[2019-11-01 00:40:02 +0300] [42107] [INFO] Handling signal: winch
[2019-11-01 00:40:02 +0300] [42107] [INFO] Handling signal: winch
[INFO] 31/Oct/2019 21:40:08 - Creating Dynamic Analysis Environment
[ERROR] 31/Oct/2019 21:40:08 - Getting ADB Location
Traceback (most recent call last):
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 461, in get_adb
    adb_loc = find_process_by('adb')
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 423, in find_process_by
    for p in psutil.process_iter(attrs=['name', 'exe', 'cmdline']):
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/__init__.py", line 1566, in process_iter
    yield add(pid)
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/__init__.py", line 1543, in add
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/__init__.py", line 638, in as_dict
    ret = meth()
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/__init__.py", line 773, in exe
    exe = self._proc.exe()
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 339, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 420, in exe
    return cext.proc_exe(self.pid)
FileNotFoundError: [Errno 2] No such file or directory
[WARNING] 31/Oct/2019 21:40:08 - Dynamic Analysis related functions will not work. 
Make sure a Genymotion Android VM is running before performing Dynamic Analyis.
[ERROR] 31/Oct/2019 21:40:08 - Getting ADB Location
Traceback (most recent call last):
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 461, in get_adb
    adb_loc = find_process_by('adb')
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 423, in find_process_by
    for p in psutil.process_iter(attrs=['name', 'exe', 'cmdline']):
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/__init__.py", line 1566, in process_iter
    yield add(pid)
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/__init__.py", line 1543, in add
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/__init__.py", line 638, in as_dict
    ret = meth()
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/__init__.py", line 773, in exe
    exe = self._proc.exe()
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 339, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 420, in exe
    return cext.proc_exe(self.pid)
FileNotFoundError: [Errno 2] No such file or directory
[WARNING] 31/Oct/2019 21:40:08 - Dynamic Analysis related functions will not work. 
Make sure a Genymotion Android VM is running before performing Dynamic Analyis.
* daemon not running; starting now at tcp:5037
ADB server didn't ACK
Full server startup log: /var/folders/mp/vx4zqgnx6ds22ctcwxxdc58w0000gn/T//adb.501.log
Server had pid: 42142
--- adb starting (pid 42142) ---
adb I 10-31 21:40:08 42142 3104382 main.cpp:60] Android Debug Bridge version 1.0.41
adb I 10-31 21:40:08 42142 3104382 main.cpp:60] Version 29.0.4-5871666
adb I 10-31 21:40:08 42142 3104382 main.cpp:60] Installed as /usr/local/bin/adb
adb I 10-31 21:40:08 42142 3104382 main.cpp:60] 
adb E 10-31 21:40:08 42142 3104385 usb_osx.cpp:159] Unable to create an interface plug-in (e00002be)
adb I 11-01 00:40:08 42140 3104372 auth.cpp:436] adb_auth_init...
adb F 10-31 21:40:09 42142 3104382 main.cpp:144] could not install *smartsocket* listener: Address already in use

* failed to start daemon
error: cannot connect to daemon
[ERROR] 31/Oct/2019 21:40:09 - Error Running ADB Command
Traceback (most recent call last):
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/environment.py", line 68, in adb_command
    result = subprocess.check_output(args)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['adb', '-s', '192.168.56.102', 'start-server']' returned non-zero exit status 255.
[INFO] 31/Oct/2019 21:40:09 - ADB Restarted
[INFO] 31/Oct/2019 21:40:09 - Waiting for 2 seconds...
[INFO] 31/Oct/2019 21:40:11 - Connecting to Android 192.168.56.102
[ERROR] 31/Oct/2019 21:40:11 - Getting ADB Location
Traceback (most recent call last):
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 461, in get_adb
    adb_loc = find_process_by('adb')
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 423, in find_process_by
    for p in psutil.process_iter(attrs=['name', 'exe', 'cmdline']):
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/__init__.py", line 1566, in process_iter
    yield add(pid)
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/__init__.py", line 1543, in add
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/__init__.py", line 638, in as_dict
    ret = meth()
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/__init__.py", line 773, in exe
    exe = self._proc.exe()
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 339, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 420, in exe
    return cext.proc_exe(self.pid)
FileNotFoundError: [Errno 2] No such file or directory
[WARNING] 31/Oct/2019 21:40:11 - Dynamic Analysis related functions will not work. 
Make sure a Genymotion Android VM is running before performing Dynamic Analyis.
[INFO] 31/Oct/2019 21:40:11 - Remounting /system
[ERROR] 31/Oct/2019 21:40:11 - Getting ADB Location
Traceback (most recent call last):
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 461, in get_adb
    adb_loc = find_process_by('adb')
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 423, in find_process_by
    for p in psutil.process_iter(attrs=['name', 'exe', 'cmdline']):
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/__init__.py", line 1566, in process_iter
    yield add(pid)
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/__init__.py", line 1543, in add
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/__init__.py", line 638, in as_dict
    ret = meth()
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/__init__.py", line 773, in exe
    exe = self._proc.exe()
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 339, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 420, in exe
    return cext.proc_exe(self.pid)
FileNotFoundError: [Errno 2] No such file or directory
[WARNING] 31/Oct/2019 21:40:11 - Dynamic Analysis related functions will not work. 
Make sure a Genymotion Android VM is running before performing Dynamic Analyis.
error: device '192.168.56.102' not found
[ERROR] 31/Oct/2019 21:40:11 - Error Running ADB Command
Traceback (most recent call last):
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/environment.py", line 68, in adb_command
    result = subprocess.check_output(args)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['adb', '-s', '192.168.56.102', 'shell', 'mount', '-o', 'rw,remount', '/system']' returned non-zero exit status 1.
[ERROR] 31/Oct/2019 21:40:11 - Getting ADB Location
Traceback (most recent call last):
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 461, in get_adb
    adb_loc = find_process_by('adb')
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 423, in find_process_by
    for p in psutil.process_iter(attrs=['name', 'exe', 'cmdline']):
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/__init__.py", line 1566, in process_iter
    yield add(pid)
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/__init__.py", line 1543, in add
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/__init__.py", line 638, in as_dict
    ret = meth()
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/__init__.py", line 773, in exe
    exe = self._proc.exe()
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 339, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/psutil/_psosx.py", line 420, in exe
    return cext.proc_exe(self.pid)
FileNotFoundError: [Errno 2] No such file or directory
[WARNING] 31/Oct/2019 21:40:11 - Dynamic Analysis related functions will not work. 
Make sure a Genymotion Android VM is running before performing Dynamic Analyis.
error: device '192.168.56.102' not found
[ERROR] 31/Oct/2019 21:40:11 - Error Running ADB Command
Traceback (most recent call last):
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/environment.py", line 68, in adb_command
    result = subprocess.check_output(args)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['adb', '-s', '192.168.56.102', 'shell', 'getprop', 'ro.build.version.release']' returned non-zero exit status 1.
[ERROR] 31/Oct/2019 21:40:11 - Dynamic Analyzer
Traceback (most recent call last):
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic_analyzer.py", line 87, in dynamic_analyzer
    version = env.get_android_version()
  File "/Users/f/tools/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/environment.py", line 228, in get_android_version
    and_version = out.decode('utf-8').rstrip()
AttributeError: 'NoneType' object has no attribute 'decode'
[ERROR] 31/Oct/2019 21:40:11 - Dynamic Analysis Failed.
[ERROR] 31/Oct/2019 21:40:11 - Internal Server Error: /android_dynamic/
```

**Comment by ajinabraham** [comment]
```
[WARNING] 31/Oct/2019 21:39:57 - Dynamic Analysis related functions will not work. 
Make sure a Genymotion Android VM is running before performing Dynamic Analysis.
```

You don't have to give the IP of the VM in settings.py. MobSF can auto detect if a Genymotion VM is running. Make sure the VM is running before attempting Dynamic Analysis. 

`FileNotFoundError: [Errno 2] No such file or directory`

Looks like either Genymotion was not running or MobSF couldn't find adb path. You need to set ADB path in `settings.py`. The adb has to be the one used by Genymotion. And it's a good idea to update Genymotion to the latest.

**Comment by ajinabraham** [comment]
For discussions, use slack channel

**Comment by Kizito-Ugo** [comment]
Hello everyone, I'm getting an error when trying to perform dynamic analysis on an app. Please assist, see the error below


[ERROR] 22/Mar/2023 15:42:25 - Error Running ADB Command
Traceback (most recent call last):
  File "C:\Users\HOME\Mobile-Security-Framework-MobSF\mobsf\DynamicAnalyzer\views\android\environment.py", line 154, in adb_command
    result = subprocess.check_output(
  File "C:\Users\HOME\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\HOME\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\Genymobile\\Genymotion\\tools\\adb.exe', '-s', 'emulator-5554', 'push', 'C:\\Users\\HOME\\.mitmproxy\\mitmproxy-ca-cert.pem', '/system/etc/security/cacerts/c8750f0d.0']' returned non-zero exit status 1.

**Comment by Five81** [comment]
Have you solved this problem? I encountered the same problem, how did you solve it? @Kizito-Ugo

**Comment by GoonsD** [comment]
MobSF was developed for unix system, so it do have difficulties running on windows environment. I suggest you use a linux desktop for this implementation. You can see a guide [here](https://medium.com/p/281964e305df) .
I hope this helps.
