### ISSUE TITLE
error with MOBSF on Mac

### ISSUE THREAD

**Issue by unmesh92** [MobSF/Mobile-Security-Framework-MobSF#1159]
Traceback (most recent call last):

  File "/Library/Python/2.7/site-packages/django/core/servers/basehttp.py", line 283, in run
    self.result = application(self.environ, self.start_response)

  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/handlers.py", line 68, in __call__
    return self.application(environ, start_response)

  File "/Library/Python/2.7/site-packages/django/core/handlers/wsgi.py", line 273, in __call__
    response = self.get_response(request)

  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 82, in get_response
    urlconf = settings.ROOT_URLCONF

  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 277, in __getattr__
    return getattr(self._wrapped, name)

AttributeError: 'Settings' object has no attribute 'ROOT_URLCONF'

I am getting flowing error after opening the url

Django version 1.3, using settings 'MobSF.settings'
Development server is running at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/servers/basehttp.py", line 283, in run
    self.result = application(self.environ, self.start_response)
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/handlers.py", line 68, in __call__
    return self.application(environ, start_response)
  File "/Library/Python/2.7/site-packages/django/core/handlers/wsgi.py", line 273, in __call__
    response = self.get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 82, in get_response
    urlconf = settings.ROOT_URLCONF
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 277, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'ROOT_URLCONF'
[07/Nov/2019 06:40:57] "GET / HTTP/1.1" 500 829

**Comment by ajinabraham** [comment]
Read Documentation. MobSF needs Python 3.6+
