### ISSUE TITLE
while installing MobSF it throws frida error and nomodule like Psutil

### ISSUE THREAD

**Issue by rakeshraks** [MobSF/Mobile-Security-Framework-MobSF#1168]
## ENVIRONMENT

```
OS and Version:Mac 
Python Version:3.6.3
MobSF Version:latest version (installing)
```

## EXPLANATION OF THE ISSUE

```
while installing mobsf it the frida error thrown and not installing, "No module named PSutil" thrown.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. i have intalled all the requirements.
2. run the command ./setup.sh
3. it throws error.

![Uploading Nomodule_Psutil.png…]()

```

## LOG FILE

```
 Running setup.py install for future ... done
    Running setup.py install for backcall ... done
    Running setup.py install for biplist ... done
    Running setup.py install for bs4 ... done
    Running setup.py install for google-play-scraper ... done
    Running setup.py install for frida ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/cybersecuritycenter/Mobile-Security-Framework-MobSF/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/dd/f44vw3n11rn_gf4jkhh_5thw0000gn/T/pip-install-_gt79zqc/frida/setup.py'"'"'; __file__='"'"'/private/var/folders/dd/f44vw3n11rn_gf4jkhh_5thw0000gn/T/pip-install-_gt79zqc/frida/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/dd/f44vw3n11rn_gf4jkhh_5thw0000gn/T/pip-record-503p3efw/install-record.txt --single-version-externally-managed --compile --install-headers /Users/cybersecuritycenter/Mobile-Security-Framework-MobSF/venv/include/site/python3.6/frida
         cwd: /private/var/folders/dd/f44vw3n11rn_gf4jkhh_5thw0000gn/T/pip-install-_gt79zqc/frida/
    Complete output (16 lines):
    /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-3.6
    creating build/lib.macosx-10.6-intel-3.6/frida
    copying frida/__init__.py -> build/lib.macosx-10.6-intel-3.6/frida
    copying frida/core.py -> build/lib.macosx-10.6-intel-3.6/frida
    running build_ext
    querying pypi for available prebuilds
    network query failed
    looking for prebuilt extension in home directory, i.e. /Users/cybersecuritycenter/frida-12.7.5-py3.6-macosx-10.6-intel.egg
    no prebuilt extension found in home directory
    error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/cybersecuritycenter/Mobile-Security-Framework-MobSF/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/dd/f44vw3n11rn_gf4jkhh_5thw0000gn/T/pip-install-_gt79zqc/frida/setup.py'"'"'; __file__='"'"'/private/var/folders/dd/f44vw3n11rn_gf4jkhh_5thw0000gn/T/pip-install-_gt79zqc/frida/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/dd/f44vw3n11rn_gf4jkhh_5thw0000gn/T/pip-record-503p3efw/install-record.txt --single-version-externally-managed --compile --install-headers /Users/cybersecuritycenter/Mobile-Security-Framework-MobSF/venv/include/site/python3.6/frida Check the logs for full command output.

[INSTALL] Migrating Database
Traceback (most recent call last):
  File "/Users/cybersecuritycenter/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/cybersecuritycenter/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/Users/cybersecuritycenter/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/cybersecuritycenter/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/cybersecuritycenter/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/cybersecuritycenter/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/core/checks/templates.py", line 29, in check_string_if_invalid_is_string
    for conf in settings.TEMPLATES:
  File "/Users/cybersecuritycenter/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/Users/cybersecuritycenter/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/cybersecuritycenter/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/cybersecuritycenter/Mobile-Security-Framework-MobSF/MobSF/settings.py", line 12, in <module>
    from MobSF.utils import (find_java_binary, first_run,
  File "/Users/cybersecuritycenter/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 21, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)

```

**Comment by ajinabraham** [comment]
Not MobSF issue. You need to update Python3
Use: https://www.python.org/ftp/python/3.7.5/python-3.7.5-macosx10.6.pkg

**Comment by rakeshraks** [comment]
i tried with pyrhon 3.7.5 also.
the same error occurs . particularly while starting "Running setup.py install for frida ... error"

**Comment by Jonnyleage** [comment]
Same lmao
