### ISSUE TITLE
[Errno 2] No such file or directory: '/root/.MobSF/signatures/exodus_trackers'

### ISSUE THREAD

**Issue by yztale** [MobSF/Mobile-Security-Framework-MobSF#1169]
Chinese users, using the docker deployment environment, when using mobsf to upload apk, the following error will occur, I hope to help me.think you
![image](https://user-images.githubusercontent.com/45749015/68633913-98e4fe00-052e-11ea-999e-8617e3429218.png)

![image](https://user-images.githubusercontent.com/45749015/68633946-b023eb80-052e-11ea-96a1-c3d795011364.png)

```
[INFO] 12/Nov/2019 01:22:51 - Starting Analysis on : XP框架 root 版.apk
[INFO] 12/Nov/2019 01:22:51 - Generating Hashes
[INFO] 12/Nov/2019 01:22:51 - Unzipping
[INFO] 12/Nov/2019 01:22:51 - Getting Hardcoded Certificates/Keystores
[INFO] 12/Nov/2019 01:22:51 - APK Extracted
[INFO] 12/Nov/2019 01:22:51 - Reading Android Manifest
[INFO] 12/Nov/2019 01:22:51 - Parsing AndroidManifest.xml
[INFO] 12/Nov/2019 01:22:51 - Fetching icon path
[INFO] 12/Nov/2019 01:22:51 - Extracting Manifest Data
[INFO] 12/Nov/2019 01:22:51 - Fetching Details from Play Store: de.robv.android.xposed.installer
[WARNING] 12/Nov/2019 01:22:52 - Unable to get app details.
[INFO] 12/Nov/2019 01:22:52 - Manifest Analysis Started
[INFO] 12/Nov/2019 01:22:52 - Static Android Binary Analysis Started
[INFO] 12/Nov/2019 01:22:52 - Static Android Resource Analysis Started
[INFO] 12/Nov/2019 01:22:52 - Reading Code Signing Certificate
[INFO] 12/Nov/2019 01:22:52 - Running APKiD 2.0.3
[ERROR] 12/Nov/2019 01:22:57 - [ERROR] Trackers DB Update
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 334, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 164, in _new_conn
    % (self.host, self.timeout),
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa3765bb5f8>, 'Connection to www.google.com timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa3765bb5f8>, 'Connection to www.google.com timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/Trackers.py", line 37, in _update_tracker_db
    if not is_internet_available():
  File "/root/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 349, in is_internet_available
    proxies=proxies, verify=verify)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa3765bb5f8>, 'Connection to www.google.com timed out. (connect timeout=5)'))
[INFO] 12/Nov/2019 01:22:57 - Detecting Trackers
[ERROR] 12/Nov/2019 01:22:57 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/static_analyzer.py", line 189, in static_analyzer
    tracker_res = tracker.get_trackers()
  File "/root/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/Trackers.py", line 168, in get_trackers
    trackers = self.detect_trackers()
  File "/root/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/Trackers.py", line 162, in detect_trackers
    self.load_trackers_signatures()
  File "/root/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/Trackers.py", line 93, in load_trackers_signatures
    errors='ignore') as flip:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.MobSF/signatures/exodus_trackers'
[ERROR] 12/Nov/2019 01:22:57 - [Errno 2] No such file or directory: '/root/.MobSF/signatures/exodus_trackers'
[ERROR] 12/Nov/2019 01:22:57 - Internal Server Error: /StaticAnalyzer/
[2019-11-12 01:23:09 +0000] [1] [INFO] Handling signal: winch
```

**Comment by ajinabraham** [comment]
This is not a MobSF issue, but network restriction at your end. You should install MobSF in host instead of docker. You will have to replace this function: https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/MobSF/utils.py#L342-L358
with
```
def is_internet_available():
    try:
        proxies, verify = upstream_proxy('https')
    except Exception:
        logger.exception('Setting upstream proxy')
    try:
         requests.get('https://www.baidu.com/', timeout=5, proxies=proxies, verify=verify)
         return True
    except requests.exceptions.HTTPError:
         return False
    return False
```

**Comment by yztale** [comment]
If I find the file utils.py change code in the dock container, can I use it normally?

**Comment by yztale** [comment]
![image](https://user-images.githubusercontent.com/45749015/68686063-fff1c980-05a5-11ea-9b5c-73b66f59bc39.png)

```
[ERROR] 12/Nov/2019 15:40:10 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/static_analyzer.py", line 186, in static_analyzer
    'app_dir'], app_dic['app_path'], app_dic['app_name'])
  File "/root/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/apkid.py", line 42, in apkid_analysis
    res = scanner.scan_file(apk_file)
  File "/root/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/apkid/apkid.py", line 120, in scan_file
    matches: List[yara.Matches] = self.rules.match(data=f.read(), timeout=self.options.timeout)
yara.Error: internal error: 34
[ERROR] 12/Nov/2019 15:40:10 - internal error: 34
[ERROR] 12/Nov/2019 15:40:10 - Internal Server Error: /StaticAnalyzer/

```

**Comment by ajinabraham** [comment]
`If I find the file utils.py change code in the dock container, can I use it normally?`
- You will have to restart MobSF which will kill the container. If you need a docker container, you need to build one yourself after modifying the code.

**Comment by ajinabraham** [comment]
```
yara.Error: internal error: 34
[ERROR] 12/Nov/2019 15:40:10 - internal error: 34
```

yara-python is not installed properly. Can you share the output of `./setup.sh`

**Comment by ajinabraham** [comment]
If you use the latest master, the exception regarding google should be fixed.

**Comment by itsecforu** [comment]
The same error in Version v3.0.3 Beta

**Comment by muYoz** [comment]
你可以: cp /Mobile-Security-Framework-MobSF/signatures/exodus_trackers  /root/.MobSF/signatures/

**Comment by Ch3nYe** [comment]
MobSF seem to be not friendly for cn user, our internet, you know. Maybe Soft routing is a good solution. 😢

**Comment by ajinabraham** [comment]
@Ch3nYe For CN users we have a fail back to baidu https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/MobSF/utils.py#L354

But if your ISP or Firewall other URLs like these https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/MobSF/settings.py#L338-L347 then we are pretty much help less. You might need to disable these, or use a VPN

**Comment by oxr463** [comment]
This is happening to me but I am not in China.

```
docker run -it --rm -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest

[ . . . TRUNCATED . . . ]

[ERROR] 30/Sep/2020 20:28:48 - [ERROR] Trackers DB Update
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/Trackers.py", line 52, in _update_tracker_db
    data = json.loads(resp.decode('utf-8', 'ignore'))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[INFO] 30/Sep/2020 20:28:48 - Detecting Trackers
[ERROR] 30/Sep/2020 20:28:48 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/static_analyzer.py", line 191, in static_analyzer
    tracker_res = tracker.get_trackers()
  File "/root/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/Trackers.py", line 175, in get_trackers
    trackers = self.detect_trackers()
  File "/root/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/Trackers.py", line 166, in detect_trackers
    self.load_trackers_signatures()
  File "/root/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/Trackers.py", line 94, in load_trackers_signatures
    with io.open(self.tracker_db,
FileNotFoundError: [Errno 2] No such file or directory: '/root/.MobSF/signatures/exodus_trackers'
[ERROR] 30/Sep/2020 20:28:48 - [Errno 2] No such file or directory: '/root/.MobSF/signatures/exodus_trackers'
[ERROR] 30/Sep/2020 20:28:48 - Internal Server Error: /StaticAnalyzer/
```

**Comment by royalsniffer** [comment]
Hi Ajin, 

I am getting this error while installing MobiSF 

FileNotFoundError: [Errno 2] No such file or directory: 'mobsf\\MobSF\\settings.py'
