### ISSUE TITLE
 Error  Inappropriate argument type.  'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by amiralkizaru** [MobSF/Mobile-Security-Framework-MobSF#1172]
## ENVIRONMENT
Linux DESKTOP-75EI56B 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
```
OS and Version:
Ubuntu 18.04
Python Version:
3.6.8
MobSF Version:
Mobile Security Framework v2.0.7 Beta
```

## EXPLANATION OF THE ISSUE

```
I ran setup no error
  ran ./run.sh no error
  I tried diva-beta apk for test purposes
I got an error
```

## LOG FILE

```
[INFO] 16/Nov/2019 09:22:34 - Mobile Security Framework v2.0.7 Beta
[INFO] 16/Nov/2019 09:22:34 - OS: Linux
[INFO] 16/Nov/2019 09:22:34 - Platform: Linux-4.4.0-18362-Microsoft-x86_64-with-Ubuntu-18.04-bionic
[INFO] 16/Nov/2019 09:22:34 - Dist: ubuntu 18.04 bionic
[INFO] 16/Nov/2019 09:22:34 - MobSF Basic Environment Check
[WARNING] 16/Nov/2019 09:22:34 - Dynamic Analysis related functions will not work.
Make sure a Genymotion Android VM is running before performing Dynamic Analyis.
[INFO] 16/Nov/2019 09:22:34 - Checking for Update.
[INFO] 16/Nov/2019 09:22:34 - MIME Type: application/octet-stream FILE: diva-beta.apk
[INFO] 16/Nov/2019 09:22:34 - Performing Static Analysis of Android APK
[INFO] 16/Nov/2019 09:22:34 - Starting Analysis on : diva-beta.apk
[INFO] 16/Nov/2019 09:22:34 - Generating Hashes
[INFO] 16/Nov/2019 09:22:34 - Unzipping
[INFO] 16/Nov/2019 09:22:34 - Getting Hardcoded Certificates/Keystores
[INFO] 16/Nov/2019 09:22:34 - APK Extracted
[INFO] 16/Nov/2019 09:22:34 - Reading Android Manifest
[INFO] 16/Nov/2019 09:22:34 - Parsing AndroidManifest.xml
[INFO] 16/Nov/2019 09:22:34 - Fetching icon path
[INFO] 16/Nov/2019 09:22:34 - Extracting Manifest Data
[INFO] 16/Nov/2019 09:22:34 - Fetching Details from Play Store: jakhar.aseem.diva
[INFO] 16/Nov/2019 09:22:35 - No updates available.
[INFO] 16/Nov/2019 09:22:35 - Manifest Analysis Started
[INFO] 16/Nov/2019 09:22:35 - Static Android Binary Analysis Started
[INFO] 16/Nov/2019 09:22:35 - Static Android Resource Analysis Started
[INFO] 16/Nov/2019 09:22:35 - Reading Code Signing Certificate
[ERROR] 16/Nov/2019 09:22:35 - Reading Code Signing Certificate
Traceback (most recent call last):
  File "/opt/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/cert_analysis.py", line 70, in cert_info
    cert_path) if os.path.isfile(os.path.join(cert_path, f))]
FileNotFoundError: [Errno 2] No such file or directory: '/opt/Mobile-Security-Framework-MobSF/uploads/77a9be5009f7ca26534b58fe57f8d712/META-INF/'
[INFO] 16/Nov/2019 09:22:35 - Running APKiD 2.0.3
[INFO] 16/Nov/2019 09:22:38 - Trackers Database is up-to-date
[INFO] 16/Nov/2019 09:22:38 - Detecting Trackers
[INFO] 16/Nov/2019 09:22:42 - APK -> JAVA
[INFO] 16/Nov/2019 09:22:42 - Decompiling to Java with jadx
[INFO] 16/Nov/2019 09:23:00 - DEX -> SMALI
[INFO] 16/Nov/2019 09:23:00 - Converting classes.dex to Smali Code
[INFO] 16/Nov/2019 09:23:00 - Static Android Code Analysis Started
[INFO] 16/Nov/2019 09:23:12 - Code Analysis Started on - java_source
[INFO] 16/Nov/2019 09:23:12 - Finished Code Analysis, Email and URL Extraction
[INFO] 16/Nov/2019 09:23:12 - Extracting Strings from APK
[INFO] 16/Nov/2019 09:23:12 - Detecting Firebase URL(s)
[INFO] 16/Nov/2019 09:23:12 - Performing Malware Check on extracted Domains
[INFO] 16/Nov/2019 09:23:17 - Malware Database is up-to-date
[INFO] 16/Nov/2019 09:23:17 - Connecting to Database
[INFO] 16/Nov/2019 09:23:17 - Saving to Database
[ERROR] 16/Nov/2019 09:23:17 - Saving to DB
Traceback (most recent call last):
  File "/opt/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py", line 255, in create_db_entry
    CERT_INFO=cert_dic['cert_info'],
TypeError: 'NoneType' object is not subscriptable
[ERROR] 16/Nov/2019 09:23:17 - Rendering to Template
Traceback (most recent call last):
  File "/opt/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py", line 120, in get_context_from_analysis
    'certinfo': cert_dic['cert_info'],
TypeError: 'NoneType' object is not subscriptable
[ERROR] 16/Nov/2019 09:23:17 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/opt/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/static_analyzer.py", line 267, in static_analyzer
    'security_score'] = score(context['findings'])
TypeError: 'NoneType' object is not subscriptable
[ERROR] 16/Nov/2019 09:23:17 - 'NoneType' object is not subscriptable
[ERROR] 16/Nov/2019 09:23:17 - Internal Server Error: /StaticAnalyzer/
```

**Comment by amiralkizaru** [comment]
It was an APK file with no signature that causes me this error I will self close this
