### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by luziang0603** [MobSF/Mobile-Security-Framework-MobSF#1221]
Traceback (most recent call last):
  File "C:\Users\qq\Desktop\appscan2.5\appscan3\venv2\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\qq\Desktop\appscan2.5\appscan3\venv2\lib\site-packages\django\core\management\commands\runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "C:\Users\qq\Desktop\appscan2.5\appscan3\venv2\lib\site-packages\django\core\management\base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "C:\Users\qq\Desktop\appscan2.5\appscan3\venv2\lib\site-packages\django\core\management\commands\runserver.py", line 67, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "C:\Users\qq\Desktop\appscan2.5\appscan3\venv2\lib\site-packages\django\conf\__init__.py", line 76, in __getattr__
    self._setup(name)
  File "C:\Users\qq\Desktop\appscan2.5\appscan3\venv2\lib\site-packages\django\conf\__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\qq\Desktop\appscan2.5\appscan3\venv2\lib\site-packages\django\conf\__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\qq\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\qq\Desktop\appscan2.5\Mobile-Security-Framework-MobSF-master\MobSF\settings.py", line 12, in <module>
    from MobSF.utils import (find_java_binary, first_run,
  File "C:\Users\qq\Desktop\appscan2.5\Mobile-Security-Framework-MobSF-master\MobSF\utils.py", line 23, in <module>
    import psutil
  File "C:\Users\qq\Desktop\appscan2.5\appscan3\venv2\lib\site-packages\psutil\__init__.py", line 142, in <module>
    from . import _pswindows as _psplatform
  File "C:\Users\qq\Desktop\appscan2.5\appscan3\venv2\lib\site-packages\psutil\_pswindows.py", line 17, in <module>
    from . import _psutil_windows as cext
ImportError: cannot import name '_psutil_windows' from 'psutil' (C:\Users\qq\Desktop\appscan2.5\appscan3\venv2\lib\site-packages\psutil\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/qq/Desktop/appscan2.5/Mobile-Security-Framework-MobSF-master/manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\qq\Desktop\appscan2.5\appscan3\venv2\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\qq\Desktop\appscan2.5\appscan3\venv2\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\qq\Desktop\appscan2.5\appscan3\venv2\lib\site-packages\django\core\management\base.py", line 341, in run_from_argv
    connections.close_all()
  File "C:\Users\qq\Desktop\appscan2.5\appscan3\venv2\lib\site-packages\django\db\utils.py", line 225, in close_all
    for alias in self:
  File "C:\Users\qq\Desktop\appscan2.5\appscan3\venv2\lib\site-packages\django\db\utils.py", line 219, in __iter__
    return iter(self.databases)
  File "C:\Users\qq\Desktop\appscan2.5\appscan3\venv2\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\qq\Desktop\appscan2.5\appscan3\venv2\lib\site-packages\django\db\utils.py", line 153, in databases
    self._databases = settings.DATABASES
  File "C:\Users\qq\Desktop\appscan2.5\appscan3\venv2\lib\site-packages\django\conf\__init__.py", line 76, in __getattr__
    self._setup(name)
  File "C:\Users\qq\Desktop\appscan2.5\appscan3\venv2\lib\site-packages\django\conf\__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\qq\Desktop\appscan2.5\appscan3\venv2\lib\site-packages\django\conf\__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\qq\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\qq\Desktop\appscan2.5\Mobile-Security-Framework-MobSF-master\MobSF\settings.py", line 12, in <module>
    from MobSF.utils import (find_java_binary, first_run,
  File "C:\Users\qq\Desktop\appscan2.5\Mobile-Security-Framework-MobSF-master\MobSF\utils.py", line 23, in <module>
    import psutil
  File "C:\Users\qq\Desktop\appscan2.5\appscan3\venv2\lib\site-packages\psutil\__init__.py", line 142, in <module>
    from . import _pswindows as _psplatform
  File "C:\Users\qq\Desktop\appscan2.5\appscan3\venv2\lib\site-packages\psutil\_pswindows.py", line 17, in <module>
    from . import _psutil_windows as cext
ImportError: cannot import name '_psutil_windows' from 'psutil' (C:\Users\qq\Desktop\appscan2.5\appscan3\venv2\lib\site-packages\psutil\__init__.py)

python version is 3.7.6 and all the requirements have been installed. Could you help me to solve this problem?THX!

**Comment by superpoussin22** [comment]
this it not Mobsf !
