### ISSUE TITLE
 Getting Manifest file issue

### ISSUE THREAD

**Issue by aa-ux** [MobSF/Mobile-Security-Framework-MobSF#1260]
## ENVIRONMENT
OS and Version: Windows-10-10.0.18362-SP0
Python Version: 3.7
MobSF Version: Mobile Security Framework v3.0.4 Beta
```

## EXPLANATION OF THE ISSUE

[ERROR] 12/Feb/2020 18:36:15 - Getting Manifest file
Traceback (most recent call last):
  File "C:\XXXXXXXXXX\mobSF\StaticAnalyzer\views\android\manifest_analysis.py", line 885, in get_manifest_file
    subprocess.check_output(args)
  File "c:\users\XXXXXXXXXX\appdata\local\programs\python\python37-32\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "c:\users\XXXXXXXXXX\appdata\local\programs\python\python37-32\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['java', '-jar', 'C:\\XXXXXXXXXX\\mobSF\\StaticAnalyzer/tools/apktool_2.4.1.jar', '--match-original', '--frame-path', 'C:\\Users\\XXXXXXXXXX\\AppData\\Local\\Temp', '-f', '-s', 'd', 'C:\\!SK-Tools!\\mobSF\\uploads/976d050d0eb4f4865009d8c8e308da43/976d050d0eb4f4865009d8c8e308da43.apk', '-o', 'C:\\XXXXXXXXXX\\mobSF\\uploads/976d050d0eb4f4865009d8c8e308da43/apktool_out']' returned non-zero exit status 1.
[ERROR] 12/Feb/2020 18:36:15 - Reading Manifest file
Traceback (most recent call last):
  File "C:\XXXXXXXXXX\mobSF\StaticAnalyzer\views\android\manifest_analysis.py", line 831, in read_manifest
    if is_file_exists(manifest):
  File "C:\XXXXXXXXXX\mobSF\MobSF\utils.py", line 392, in is_file_exists
    if os.path.isfile(file_path):
  File "c:\users\XXXXXXXXXX\appdata\local\programs\python\python37-32\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
[INFO] 12/Feb/2020 18:36:15 - Parsing AndroidManifest.xml
[ERROR] 12/Feb/2020 18:36:15 - apktool failed to extract AndroidManifest.xml or parsing failed
Traceback (most recent call last):
  File "C:\XXXXXXXXXX\mobSF\StaticAnalyzer\views\android\manifest_analysis.py", line 35, in get_manifest
    manifest = minidom.parseString(dat)
  File "c:\users\XXXXXXXXXX\appdata\local\programs\python\python37-32\lib\xml\dom\minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "c:\users\XXXXXXXXXX\appdata\local\programs\python\python37-32\lib\xml\dom\expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "c:\users\XXXXXXXXXX\appdata\local\programs\python\python37-32\lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
TypeError: a bytes-like object is required, not 'NoneType'
[WARNING] 12/Feb/2020 18:36:15 - Using Fake XML to continue the Analysis

## STEPS TO REPRODUCE THE ISSUE

JUST UPLOAD APK AND SCAN

**Comment by superpoussin22** [comment]
can you share the apk ?

**Comment by aa-ux** [comment]
sure, its more than 10M, so here is a link https://paybox-paybox.en.aptoide.com/

**Comment by ajinabraham** [comment]
Works fine for me. MobSF couldn't detect Java path or you don't have correct version of Java Installed and Environment variables configured.
[Uploading download.pdf…]()
