### ISSUE TITLE
has no column named ICON_FOUND

### ISSUE THREAD

**Issue by blshkv** [MobSF/Mobile-Security-Framework-MobSF#1270]
Hi I'm using the latest git and missed a migration probably.
Could you point out which migration should I apply to fix the following error:

```
[INFO] 19/Feb/2020 07:21:55 - Performing Malware Check on extracted Domains
[INFO] 19/Feb/2020 07:21:56 - Malware Database is up-to-date
[INFO] 19/Feb/2020 07:22:06 - Finished URL and Email Extraction
[INFO] 19/Feb/2020 07:22:06 - Detecting Firebase URL(s)
[INFO] 19/Feb/2020 07:22:06 - Connecting to DB
[INFO] 19/Feb/2020 07:22:06 - Saving to Database
[ERROR] 19/Feb/2020 07:22:06 - Updating DB
Traceback (most recent call last):                                                                                    
  File "/usr/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute                         
    return self.cursor.execute(sql, params)                                                                           
  File "/usr/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: table StaticAnalyzer_staticanalyzerios has no column named ICON_FOUND

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/pt/mobile/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/db_interaction.py", line 153, in save_or_update
    StaticAnalyzerIOS.objects.create(**values)
  File "/usr/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/lib64/python3.6/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib64/python3.6/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/usr/lib64/python3.6/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/lib64/python3.6/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/usr/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib64/python3.6/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/lib64/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/lib64/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: table StaticAnalyzer_staticanalyzerios has no column named ICON_FOUND
```

**Comment by superpoussin22** [comment]
can you try : 
`source` venv/bin/activate
python manage.py makemigrations
python manage.py makemigrations StaticAnalyzer
python manage.py migrate
deactivate
run.sh

**Comment by blshkv** [comment]
Yes, managed to upgrade it:
```Migrations for 'StaticAnalyzer':
  StaticAnalyzer/migrations/0002_staticanalyzerios_icon_found.py
    - Add field ICON_FOUND to staticanalyzerios
```

Thanks!
