### ISSUE TITLE
Error with static analysis on certain APK's

### ISSUE THREAD

**Issue by Ekultek** [MobSF/Mobile-Security-Framework-MobSF#1293]
## ENVIRONMENT

```
OS and Version: Windows 10
Python Version: Python 3.7x
MobSF Version: 3.0.4beta
```

## EXPLANATION OF THE ISSUE

When using the static analysis on an APK you get an issue where
```
            for filename, matches in results.items():
                match_results = self._build_match_results(matches)
                if len(match_results) == 0:
                    continue
                result = {
                    'filename': filename,
                    'matches': match_results,
                }
```
Throws an AttributeError. This is because the type of object passed to it is a list instead of a dict so you can't iterate over the items. (Only tested with a single APK)

Errors:
```
[ERROR] 03/Mar/2020 18:05:37 - Error Performing Static Analysis
Traceback (most recent call last):
  File "C:\Users\Salty\bin\python\Mobile-Security-Framework-MobSF\MalwareAnalyzer\views\apkid.py", line 45, in apkid_ana
lysis
    findings = output._build_json_output(res)['files']
AttributeError: 'OutputFormatter' object has no attribute '_build_json_output'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Salty\bin\python\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\static_analyzer.py", line
 188, in static_analyzer
    'app_dir'], app_dic['app_path'], app_dic['app_name'])
  File "C:\Users\Salty\bin\python\Mobile-Security-Framework-MobSF\MalwareAnalyzer\views\apkid.py", line 48, in apkid_ana
lysis
    findings = output.build_json_output(res)['files']
  File "c:\users\salty\bin\python\mobile-security-framework-mobsf\venv\lib\site-packages\apkid\output.py", line 117, in
build_json_output
    for filename, matches in results.items():
AttributeError: 'list' object has no attribute 'items'
[ERROR] 03/Mar/2020 18:05:37 - 'list' object has no attribute 'items'
[ERROR] 03/Mar/2020 18:05:37 - Internal Server Error: /StaticAnalyzer/
```

## STEPS TO REPRODUCE THE ISSUE

I can't give you specific steps of the actual APK due to security of the client, but it happens when you start performing the analysis, right after:

```
[INFO] 03/Mar/2020 18:05:34 - Reading Code Signing Certificate
[INFO] 03/Mar/2020 18:05:35 - Running APKiD 2.1.0
```

## LOG FILE

```
[INFO] 03/Mar/2020 18:05:34 - Static Android Resource Analysis Started
[INFO] 03/Mar/2020 18:05:34 - Reading Code Signing Certificate
[INFO] 03/Mar/2020 18:05:35 - Running APKiD 2.1.0
[ERROR] 03/Mar/2020 18:05:37 - Error Performing Static Analysis
Traceback (most recent call last):
  File "C:\Users\Salty\bin\python\Mobile-Security-Framework-MobSF\MalwareAnalyzer\views\apkid.py", line 45, in apkid_ana
lysis
    findings = output._build_json_output(res)['files']
AttributeError: 'OutputFormatter' object has no attribute '_build_json_output'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Salty\bin\python\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\static_analyzer.py", line
 188, in static_analyzer
    'app_dir'], app_dic['app_path'], app_dic['app_name'])
  File "C:\Users\Salty\bin\python\Mobile-Security-Framework-MobSF\MalwareAnalyzer\views\apkid.py", line 48, in apkid_ana
lysis
    findings = output.build_json_output(res)['files']
  File "c:\users\salty\bin\python\mobile-security-framework-mobsf\venv\lib\site-packages\apkid\output.py", line 117, in
build_json_output
    for filename, matches in results.items():
AttributeError: 'list' object has no attribute 'items'
[ERROR] 03/Mar/2020 18:05:37 - 'list' object has no attribute 'items'
[ERROR] 03/Mar/2020 18:05:37 - Internal Server Error: /StaticAnalyzer/
[INFO] 03/Mar/2020 18:09:25 -
```

I came up with a little work around that isn't extremely useful since it just changes the name to `n/a` but if anyone else comes across this issue do the following:

```
    def build_json_output(self, results: Dict[str, List[yara.Match]]):
        output = {
            'apkid_version': self.version,
            'rules_sha256': self.rules_hash,
            'files': [],
        }
        try:
            for filename, matches in results.items():
                match_results = self._build_match_results(matches)
                if len(match_results) == 0:
                    continue
                result = {
                    'filename': filename,
                    'matches': match_results,
                }
                output['files'].append(result)
        except AttributeError:
            for matches in results:
                match_results = self._build_match_results(matches)
                if len(match_results) == 0:
                    continue
                result = {
                    'filename': 'n/a',
                    'matches': match_results
                }
                output['files'].append(result)
        return output
```

**Comment by ajinabraham** [comment]
We can't help much here without reproducing the issue at our end. You could also disable APKiD from `MobSF/settings.py` if you are not using this feature. Thanks for the work around.

**Comment by Ekultek** [comment]
@ajinabraham I understand, just figured I'd provide a little workaround for anyone having the same issue, love MobSF it's my favorite thing ever and you are a God.

Also disabling APKiD does indeed help with the issue, I was able to completely get rid of the issue by downloading the latest release, and disabling APKiD. Haven't seen it since.
