### ISSUE TITLE
Some IPA Binary does not work with jtool

### ISSUE THREAD

**Issue by ajinabraham** [MobSF/Mobile-Security-Framework-MobSF#1297]
## ENVIRONMENT

```
OS and Version: Docker Ubuntu 16
Python Version: 3.6
MobSF Version: 3.0.4
```

## EXPLANATION OF THE ISSUE

```
Jtool fails on some binaries. The binary is shared in PM.

ERROR] 04/Mar/2020 18:29:12 - Performing Object Analysis of Binary
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/otool_analysis.py", line 76, in otool_analysis
    tools_dir, 'libs', bin_path, bin_dir)
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/otool_analysis.py", line 41, in get_otool_out
    libs = subprocess.check_output(args).decode('utf-8', 'ignore')
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/mac/jtool.ELF64', '-arch', 'arm', '-L', '-v', '/root/.MobSF/uploads/38c51fe993e3a205930d81502a6d0073/Payload/AppStudioApp.app/AppStudioApp']' died with <Signals.SIGBUS: 7>.
[ERROR] 04/Mar/2020 18:29:12 - iOS Binary Analysis
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/binary_analysis.py", line 151, in binary_analysis
    bin_type = detect_bin_type(otool_dict['libs'])
TypeError: 'NoneType' object is not subscriptable
```
This looks to me like a bug in jtool. We are not sure if can fix it as it's a third party issue. We will see if we can do graceful handling in this case.

## STEPS TO REPRODUCE THE ISSUE

```
Run static analysis on provided IPA
```

## LOG FILE

```
Paste the contents of logs/debug.log here or attach the log file.
```

**Comment by superpoussin22** [comment]
it could perhaps be solved by jtool2 but jtool2 supports only  64b binaries and the arch tag is no more available

**Comment by ajinabraham** [comment]
Fixed in https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1311
