### ISSUE TITLE
Error: Attribute not found. 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by PaxPrz** [MobSF/Mobile-Security-Framework-MobSF#1310]
## ENVIRONMENT

```
OS and Version: Kali linux 5.2
Python Version: Python 3.7.6
MobSF Version: v3.0 beta
```

## EXPLANATION OF THE ISSUE

Sometimes the app crashes with following error. Problem solves when app is reinstalled. Screenshot [here](https://imgur.com/4Zc3flk)

## STEPS TO REPRODUCE THE ISSUE

```
1. Add app to static analyzer.
2. Got this error
```

## LOG FILE

```
[INFO] 07/Mar/2020 23:50:56 - MIME Type: application/vnd.android.package-archive
 FILE: apk-editor-pro-v1.10.0-patched-www.rexdl.com.apk
[INFO] 07/Mar/2020 23:50:56 - Performing Static Analysis of Android APK
[INFO] 07/Mar/2020 23:50:56 - Starting Analysis on : APK-Editor-Pro-v1.10.0-Patc
hed-www.ReXdl.com.apk
[INFO] 07/Mar/2020 23:50:56 - Generating Hashes
[INFO] 07/Mar/2020 23:50:56 - Unzipping
[INFO] 07/Mar/2020 23:50:57 - Getting Hardcoded Certificates/Keystores
[INFO] 07/Mar/2020 23:50:57 - APK Extracted
[INFO] 07/Mar/2020 23:50:57 - Converting AXML to XML
[INFO] 07/Mar/2020 23:51:02 - Reading Android Manifest
[INFO] 07/Mar/2020 23:51:02 - Parsing AndroidManifest.xml
[INFO] 07/Mar/2020 23:51:02 - Fetching icon path
[INFO] 07/Mar/2020 23:51:03 - Extracting Manifest Data
[INFO] 07/Mar/2020 23:51:03 - Fetching Details from Play Store: com.gmail.heagoo
.apkeditor.pro
[INFO] 07/Mar/2020 23:51:03 - Manifest Analysis Started
[INFO] 07/Mar/2020 23:51:03 - Static Android Binary Analysis Started
[INFO] 07/Mar/2020 23:51:03 - Static Android Resource Analysis Started
[INFO] 07/Mar/2020 23:51:03 - Reading Code Signing Certificate
[INFO] 07/Mar/2020 23:51:03 - Running APKiD 2.1.0
[ERROR] 07/Mar/2020 23:51:03 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/opt/MobSF/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/apkid.py", line 45, in apkid_analysis
    findings = output._build_json_output(res)['files']
AttributeError: 'OutputFormatter' object has no attribute '_build_json_output'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/MobSF/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/static_analyzer.py", line 188, in static_analyzer
    'app_dir'], app_dic['app_path'], app_dic['app_name'])
  File "/opt/MobSF/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/apkid.py", line 48, in apkid_analysis
    findings = output.build_json_output(res)['files']
  File "/usr/lib/python3.7/site-packages/apkid/output.py", line 117, in build_json_output
    for filename, matches in results.items():
AttributeError: 'list' object has no attribute 'items'
[ERROR] 07/Mar/2020 23:51:03 - 'list' object has no attribute 'items'
[ERROR] 07/Mar/2020 23:51:03 - Internal Server Error: /StaticAnalyzer/

```

**Comment by ajinabraham** [comment]
Duplicate https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1293
Make sure you are using latest version of MobSF 3.0.5

Otherwise run setup.sh after updating.

If you still see the issue, share the APK and respond here.
