### ISSUE TITLE
Android R apps Static Analysis Not Working

### ISSUE THREAD

**Issue by maverickNerd** [MobSF/Mobile-Security-Framework-MobSF#1328]
Running Docker instance of latest container:

On dragging an app made for android R, getting error as below:
Error
Inappropriate argument value (of correct type).

invalid literal for int() with base 10: 'R'

# docker logs f71b0b346ae3

[INFO] 24/Mar/2020 10:38:28 - Reading Android Manifest
[INFO] 24/Mar/2020 10:38:28 - Parsing AndroidManifest.xml
[ERROR] 24/Mar/2020 10:38:28 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/static_analyzer.py", line 151, in static_analyzer
    True,
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/static_analyzer.py", line 533, in get_app_name
    a = apk.APK(app_path)
  File "/usr/local/lib/python3.6/dist-packages/androguard/core/bytecodes/apk.py", line 294, in __init__
    self._apk_analysis()
  File "/usr/local/lib/python3.6/dist-packages/androguard/core/bytecodes/apk.py", line 370, in _apk_analysis
    "aosp_permissions", self.get_target_sdk_version())
  File "/usr/local/lib/python3.6/dist-packages/androguard/core/androconf.py", line 369, in load_api_specific_resource_module
    ret = loader[resource_name](api)
  File "/usr/local/lib/python3.6/dist-packages/androguard/core/api_specific_resources/__init__.py", line 37, in load_permissions
    apilevel = int(apilevel)
ValueError: invalid literal for int() with base 10: 'R'
[ERROR] 24/Mar/2020 10:38:28 - invalid literal for int() with base 10: 'R'
[ERROR] 24/Mar/2020 10:38:28 - Internal Server Error: /StaticAnalyzer/

**Comment by ajinabraham** [comment]
please share the APK for troubleshooting

**Comment by maverickNerd** [comment]
I cannot share the APK as it is proprietary. Anything else I can help with.

**Comment by ajinabraham** [comment]
Without an APK that replicate the issue, I cannot help. This is an issue in thrid party dependency. 
Closing the report
