### ISSUE TITLE
(Potential) [ERROR] Getting Manifest file / Converting AXML to XML and Parsing AndroidManifest.xml

### ISSUE THREAD

**Issue by cibermike20** [MobSF/Mobile-Security-Framework-MobSF#1330]
Hi everyone,

I'm running MobSF on the following environment:

OS and Version: macOS Catalina
Python Version: 3.6
MobSF Version: MobSF v3.0.5 Beta

I think that it is correctly configured as when I perform a static analysis on standard .APK files, it finishes fine without errors (for example, for Chrome). The problem comes when I run it on a specific banking APP where I receive the following errors during the process of Converting AXML to XML and Parsing AndroidManifest.xml:

Exception in thread "main" java.lang.NullPointerException
	at brut.androlib.res.decoder.AXmlResourceParser.getNonDefaultNamespaceUri(AXmlResourceParser.java:312)
	at brut.androlib.res.decoder.AXmlResourceParser.getAttributeNamespace(AXmlResourceParser.java:299)
	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeNamespace(XmlPullParserDelegate.java:176)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:84)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:142)
	at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:141)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:121)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:258)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:129)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
	at brut.apktool.Main.cmdDecode(Main.java:170)
	at brut.apktool.Main.main(Main.java:76)
[ERROR] 25/Mar/2020 11:25:54 - Getting Manifest file
Traceback (most recent call last):

...

[INFO] 25/Mar/2020 11:25:54 - Parsing AndroidManifest.xml
[ERROR] 25/Mar/2020 11:25:54 - apktool failed to extract AndroidManifest.xml or parsing failed
Traceback (most recent call last):

...

[WARNING] 25/Mar/2020 11:25:54 - Using Fake XML to continue the Analysis
Name 'android:versionName' starts with 'android:' prefix! The Manifest seems to be broken? Removing prefix.
Name 'android:UNKNOWN_SYSTEM_ATTRIBUTE_01010572' starts with 'android:' prefix! The Manifest seems to be broken? Removing prefix.
Name 'android:UNKNOWN_SYSTEM_ATTRIBUTE_01010573' starts with 'android:' prefix! The Manifest seems to be broken? Removing prefix.

...

XML Seems to be packed, operations on the AndroidManifest.xml might fail.
Failed to get the attribute 'name' on tag 'uses-permission' with namespace. But found the same attribute without namespace!
Failed to get the attribute 'name' on tag 'uses-permission' with namespace. But found the same attribute without namespace!
Failed to get the attribute 'name' on tag 'uses-permission' with namespace. But found the same attribute without namespace!

...

[INFO] 25/Mar/2020 11:25:55 - Fetching icon path
Name 'android:versionName' starts with 'android:' prefix! The Manifest seems to be broken? Removing prefix.
Name 'android:UNKNOWN_SYSTEM_ATTRIBUTE_01010572' starts with 'android:' prefix! The Manifest seems to be broken? Removing prefix.
Name 'android:UNKNOWN_SYSTEM_ATTRIBUTE_01010573' starts with 'android:' prefix! The Manifest seems to be broken? Removing prefix.

...

[INFO] 25/Mar/2020 11:26:48 - Extracting Strings from APK
Name 'android:versionName' starts with 'android:' prefix! The Manifest seems to be broken? Removing prefix.
Name 'android:UNKNOWN_SYSTEM_ATTRIBUTE_01010572' starts with 'android:' prefix! The Manifest seems to be broken? Removing prefix.
Name 'android:UNKNOWN_SYSTEM_ATTRIBUTE_01010573' starts with 'android:' prefix! The Manifest seems to be broken? Removing prefix.

Although MobSF extracts some information (Signer Certificate, Shared Library Binary Analysis, Android Java API, Code Analysis issues, APKiD Analysis, etc), the part of activities and services appear as empty (although with Drozer I can see that it is not empty) and analysis appears as Failed (Package Name, Android Version Name, etc.).

In the part of the APKiD ANALYSIS I see the following findings are detected: Anti Debug Code, Anti Disassembly Code, Anti-V; Code and Obfuscator (DexGuard). 

Do I receive these errors due to the protection applied in the analysed APK to prevent reverse engineering or due to MobSF limitations parsing the manifest? Is there any way to overcome this?

Thank you in advance!

**Comment by superpoussin22** [comment]
can you share the apk ?
also can you use slack channel ?

**Comment by ajinabraham** [comment]
This is an instance of the 3rd party tools not supporting the APK. We won't be able to fix this unless they fix it. Use slack for further discussions. Closing this.
