### ISSUE TITLE
'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by nas3f** [MobSF/Mobile-Security-Framework-MobSF#1332]
## ENVIRONMENT

```
OS and Version: Platform: Linux-5.2.0-kali2-686-pae-i686-with-debian-kali-rolling
Python Version: Python 3.7.4
MobSF Version: Mobile Security Framework v2.0.7 Beta
```

## EXPLANATION OF THE ISSUE

```
When I use .ipa and try to upload it it gives me the error 



Error

Inappropriate argument type.

'NoneType' object does not support item assignment

```

## STEPS TO REPRODUCE THE ISSUE

```
1. Open 0.0.0.0:8000
2. Upload .ipa File (DVIAv2 is this case)
3. it gives the error
```

## LOG FILE

```
  __  __       _    ____  _____         ____    ___  
 |  \/  | ___ | |__/ ___||  ___| __   _|___ \  / _ \ 
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / __) || | | |
 | |  | | (_) | |_) |__) |  _|    \ V / / __/ | |_| |
 |_|  |_|\___/|_.__/____/|_|       \_/ |_____(_)___/ 

[INFO] 26/Mar/2020 09:13:15 - [1m[34mMobile Security Framework v2.0.7 Beta[0m
[INFO] 26/Mar/2020 09:13:15 - OS: Linux
[INFO] 26/Mar/2020 09:13:15 - Platform: Linux-5.2.0-kali2-686-pae-i686-with-debian-kali-rolling
[INFO] 26/Mar/2020 09:13:16 - Dist: kali 2019.3 kali-rolling
[INFO] 26/Mar/2020 09:13:16 - MobSF Basic Environment Check
[WARNING] 26/Mar/2020 09:13:16 - Dynamic Analysis related functions will not work. 
Make sure a Genymotion Android VM is running before performing Dynamic Analyis.
[INFO] 26/Mar/2020 09:13:16 - Checking for Update.
[INFO] 26/Mar/2020 09:13:16 - MIME Type: application/octet-stream FILE: issuu.ipa
[INFO] 26/Mar/2020 09:13:16 - Performing Static Analysis of iOS IPA
[INFO] 26/Mar/2020 09:13:16 - iOS Static Analysis Started
[INFO] 26/Mar/2020 09:13:16 - iOS Binary (IPA) Analysis Started
[INFO] 26/Mar/2020 09:13:16 - Generating Hashes
[INFO] 26/Mar/2020 09:13:16 - Extracting IPA
[INFO] 26/Mar/2020 09:13:16 - Unzipping
[WARNING] 26/Mar/2020 09:13:16 - A new version of MobSF is available, Please update to v3.0.5 Beta from master branch.
[INFO] 26/Mar/2020 09:13:18 - Get Files, BIN Plist -> XML, and Normalize
[INFO] 26/Mar/2020 09:13:19 - iOS Info.plist Analysis Started
[INFO] 26/Mar/2020 09:13:19 - Finding Info.plist in iOS Binary
[INFO] 26/Mar/2020 09:13:19 - Checking Permissions
[INFO] 26/Mar/2020 09:13:19 - Checking for Insecure Connections
[INFO] 26/Mar/2020 09:13:19 - Fetching Details from App Store: com.issuu.app
[INFO] 26/Mar/2020 09:13:20 - Starting Binary Analysis
[INFO] 26/Mar/2020 09:13:20 - Getting Binary Information
[INFO] 26/Mar/2020 09:13:20 - Running Object Analysis of Binary : Issuu
[ERROR] 26/Mar/2020 09:13:20 - Performing Object Analysis of Binary
Traceback (most recent call last):
  File "/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/binary_analysis.py", line 85, in otool_analysis
    tools_dir, 'libs', bin_path, bin_dir)
  File "/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/binary_analysis.py", line 50, in get_otool_out
    libs = subprocess.check_output(args).decode('utf-8', 'ignore')
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/mac/jtool.ELF64'
[ERROR] 26/Mar/2020 09:13:20 - iOS Binary Analysis
Traceback (most recent call last):
  File "/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/binary_analysis.py", line 535, in binary_analysis
    bin_type = detect_bin_type(otool_dict['libs'])
TypeError: 'NoneType' object is not subscriptable
[INFO] 26/Mar/2020 09:13:20 - Connecting to DB
[INFO] 26/Mar/2020 09:13:20 - Saving to Database
[ERROR] 26/Mar/2020 09:13:20 - Saving to DB
Traceback (most recent call last):
  File "/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/db_interaction.py", line 163, in create_db_entry_ipa
    BIN_ANAL=bin_dict['bin_res'],
TypeError: 'NoneType' object is not subscriptable
[ERROR] 26/Mar/2020 09:13:20 - Rendering to Template
Traceback (most recent call last):
  File "/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/db_interaction.py", line 34, in get_context_from_analysis_ipa
    'bin_anal': bin_dict['bin_res'],
TypeError: 'NoneType' object is not subscriptable
[ERROR] 26/Mar/2020 09:13:20 - Error Perfroming Static Analysis
Traceback (most recent call last):
  File "/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/static_analyzer.py", line 181, in static_analyzer_ios
    context['VT_RESULT'] = None
TypeError: 'NoneType' object does not support item assignment
[ERROR] 26/Mar/2020 09:13:20 - 'NoneType' object does not support item assignment
[ERROR] 26/Mar/2020 09:13:20 - Internal Server Error: /StaticAnalyzer_iOS/
[INFO] 26/Mar/2020 09:16:31 - MIME Type: application/octet-stream FILE: dvia-v2-swift.ipa
[INFO] 26/Mar/2020 09:16:32 - Performing Static Analysis of iOS IPA
[INFO] 26/Mar/2020 09:16:32 - iOS Static Analysis Started
[INFO] 26/Mar/2020 09:16:32 - iOS Binary (IPA) Analysis Started
[INFO] 26/Mar/2020 09:16:32 - Generating Hashes
[INFO] 26/Mar/2020 09:16:32 - Extracting IPA
[INFO] 26/Mar/2020 09:16:32 - Unzipping
[INFO] 26/Mar/2020 09:16:33 - Get Files, BIN Plist -> XML, and Normalize
[INFO] 26/Mar/2020 09:16:33 - iOS Info.plist Analysis Started
[INFO] 26/Mar/2020 09:16:33 - Finding Info.plist in iOS Binary
[INFO] 26/Mar/2020 09:16:33 - Checking Permissions
[INFO] 26/Mar/2020 09:16:33 - Checking for Insecure Connections
[INFO] 26/Mar/2020 09:16:33 - Fetching Details from App Store: com.highaltitudehacks.DVIAswiftv2
[WARNING] 26/Mar/2020 09:16:34 - Unable to get app details.
[INFO] 26/Mar/2020 09:16:34 - Starting Binary Analysis
[INFO] 26/Mar/2020 09:16:34 - Getting Binary Information
[INFO] 26/Mar/2020 09:16:34 - Running Object Analysis of Binary : DVIA-v2
[ERROR] 26/Mar/2020 09:16:34 - Performing Object Analysis of Binary
Traceback (most recent call last):
  File "/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/binary_analysis.py", line 85, in otool_analysis
    tools_dir, 'libs', bin_path, bin_dir)
  File "/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/binary_analysis.py", line 50, in get_otool_out
    libs = subprocess.check_output(args).decode('utf-8', 'ignore')
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/mac/jtool.ELF64'
[ERROR] 26/Mar/2020 09:16:34 - iOS Binary Analysis
Traceback (most recent call last):
  File "/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/binary_analysis.py", line 535, in binary_analysis
    bin_type = detect_bin_type(otool_dict['libs'])
TypeError: 'NoneType' object is not subscriptable
[INFO] 26/Mar/2020 09:16:34 - Connecting to DB
[INFO] 26/Mar/2020 09:16:34 - Saving to Database
[ERROR] 26/Mar/2020 09:16:34 - Saving to DB
Traceback (most recent call last):
  File "/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/db_interaction.py", line 163, in create_db_entry_ipa
    BIN_ANAL=bin_dict['bin_res'],
TypeError: 'NoneType' object is not subscriptable
[ERROR] 26/Mar/2020 09:16:34 - Rendering to Template
Traceback (most recent call last):
  File "/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/db_interaction.py", line 34, in get_context_from_analysis_ipa
    'bin_anal': bin_dict['bin_res'],
TypeError: 'NoneType' object is not subscriptable
[ERROR] 26/Mar/2020 09:16:34 - Error Perfroming Static Analysis
Traceback (most recent call last):
  File "/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/static_analyzer.py", line 181, in static_analyzer_ios
    context['VT_RESULT'] = None
TypeError: 'NoneType' object does not support item assignment
[ERROR] 26/Mar/2020 09:16:34 - 'NoneType' object does not support item assignment
[ERROR] 26/Mar/2020 09:16:34 - Internal Server Error: /StaticAnalyzer_iOS/
```

**Comment by superpoussin22** [comment]
please upgrade to the latest version of MobSF

**Comment by nas3f** [comment]
I've upgraded to the latest version but an new error happend . 
Deleted MobSF and recloned the repo with setup and run and the new error keep happening .
 ``` ModuleNotFoundError: No module named 'distro'```

I did pip install distro
and pip3 install distro
but it keep telling me 

 ```Requirement already satisfied: distro in /usr/local/lib/python3.7/dist-packages (1.4.0) ```

**Comment by ajinabraham** [comment]
Have you installed it inside the venv? 
Alternatively you could run setup.sh again but it will remove old scan results

**Comment by nas3f** [comment]
I've deleted the whole MobSF and downloaded the last version but it gives me the same error

``` |  \/  | ___ | |__/ ___||  ___|_   _|___ / / _ \ 
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| | | |
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | |_| |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/

[INFO] 26/Mar/2020 13:25:05 - Mobile Security Framework v3.0.5 Beta
REST API Key: 2f52bd8d641f91af3e9a71388fe0771aee30c3b2d41b0ab7d9ed7b51a2dd0605
[INFO] 26/Mar/2020 13:25:05 - OS: Linux
[INFO] 26/Mar/2020 13:25:05 - Platform: Linux-5.2.0-kali2-686-pae-i686-with-debian-kali-rolling
[INFO] 26/Mar/2020 13:25:05 - Dist: kali 2019.3 kali-rolling
[INFO] 26/Mar/2020 13:25:05 - MobSF Basic Environment Check
[WARNING] 26/Mar/2020 13:25:05 - Dynamic Analysis related functions will not work. 
Make sure a Genymotion Android VM is running before performing Dynamic Analyis.
[INFO] 26/Mar/2020 13:25:05 - Checking for Update.
[INFO] 26/Mar/2020 13:25:06 - No updates available.
[INFO] 26/Mar/2020 13:25:52 - MIME Type: application/octet-stream FILE: issuu.ipa
[INFO] 26/Mar/2020 13:25:52 - Performing Static Analysis of iOS IPA
[INFO] 26/Mar/2020 13:25:52 - iOS Static Analysis Started
[INFO] 26/Mar/2020 13:25:52 - iOS Binary (IPA) Analysis Started
[INFO] 26/Mar/2020 13:25:52 - Generating Hashes
[INFO] 26/Mar/2020 13:25:52 - Extracting IPA
[INFO] 26/Mar/2020 13:25:52 - Unzipping
[INFO] 26/Mar/2020 13:25:54 - Get Files, BIN Plist -> XML, and Normalize
[INFO] 26/Mar/2020 13:25:54 - iOS Info.plist Analysis Started
[INFO] 26/Mar/2020 13:25:54 - Finding Info.plist in iOS Binary
[INFO] 26/Mar/2020 13:25:54 - Checking Permissions
[INFO] 26/Mar/2020 13:25:54 - Checking for Insecure Connections
[INFO] 26/Mar/2020 13:25:54 - Fetching Details from App Store: com.issuu.app
[INFO] 26/Mar/2020 13:25:55 - Starting Binary Analysis
[INFO] 26/Mar/2020 13:25:55 - Getting Binary Information
[INFO] 26/Mar/2020 13:25:55 - Running Object analysis of binary: Issuu
[ERROR] 26/Mar/2020 13:25:55 - Performing Object analysis of binary
Traceback (most recent call last):
  File "/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/otool_analysis.py", line 46, in get_otool_out
    libs = subprocess.check_output(args2).decode('utf-8', 'ignore')
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/ios/jtool2.ELF64'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/otool_analysis.py", line 101, in otool_analysis
    bin_dir)
  File "/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/otool_analysis.py", line 48, in get_otool_out
    libs = subprocess.check_output(args).decode('utf-8', 'ignore')
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/ios/jtool.ELF64'
[INFO] 26/Mar/2020 13:25:55 - Dumping classes
[INFO] 26/Mar/2020 13:25:55 - Running jtool against the binary for dumping classes
[ERROR] 26/Mar/2020 13:25:55 - iOS Binary Analysis
Traceback (most recent call last):
  File "/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/binary_analysis.py", line 104, in binary_analysis
    object_data['bindata'] + cdump,
TypeError: can only concatenate str (not "bytes") to str
[INFO] 26/Mar/2020 13:25:55 - Fetching icon path
[ERROR] 26/Mar/2020 13:25:55 - Error Perfroming Static Analysis
Traceback (most recent call last):
  File "/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/static_analyzer.py", line 113, in static_analyzer_ios
    bin_analysis_dict['strings'])
TypeError: 'NoneType' object is not subscriptable
[ERROR] 26/Mar/2020 13:25:55 - 'NoneType' object is not subscriptable
[ERROR] 26/Mar/2020 13:25:55 - Internal Server Error: /StaticAnalyzer_iOS/
```

Please notice that I've used dvia2.ipa again and tried multiple other ipa

**Comment by nas3f** [comment]
It only happens when I try to upload .ipa file

the last log 

```  __  __       _    ____  _____       _____  ___  
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / _ \ 
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| | | |
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | |_| |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/

[INFO] 26/Mar/2020 13:31:16 - [1m[34mMobile Security Framework v3.0.5 Beta[0m
[INFO] 26/Mar/2020 13:31:16 - OS: Linux
[INFO] 26/Mar/2020 13:31:16 - Platform: Linux-5.2.0-kali2-686-pae-i686-with-debian-kali-rolling
[INFO] 26/Mar/2020 13:31:16 - Dist: kali 2019.3 kali-rolling
[INFO] 26/Mar/2020 13:31:16 - MobSF Basic Environment Check
[WARNING] 26/Mar/2020 13:31:16 - Dynamic Analysis related functions will not work. 
Make sure a Genymotion Android VM is running before performing Dynamic Analyis.
[INFO] 26/Mar/2020 13:31:16 - Checking for Update.
[INFO] 26/Mar/2020 13:31:16 - iOS Static Analysis Started
[INFO] 26/Mar/2020 13:31:16 - iOS Binary (IPA) Analysis Started
[INFO] 26/Mar/2020 13:31:16 - Generating Hashes
[INFO] 26/Mar/2020 13:31:17 - Extracting IPA
[INFO] 26/Mar/2020 13:31:17 - Unzipping
[INFO] 26/Mar/2020 13:31:17 - No updates available.
[INFO] 26/Mar/2020 13:31:18 - Get Files, BIN Plist -> XML, and Normalize
[INFO] 26/Mar/2020 13:31:18 - iOS Info.plist Analysis Started
[INFO] 26/Mar/2020 13:31:18 - Finding Info.plist in iOS Binary
[INFO] 26/Mar/2020 13:31:18 - Checking Permissions
[INFO] 26/Mar/2020 13:31:18 - Checking for Insecure Connections
[INFO] 26/Mar/2020 13:31:18 - Fetching Details from App Store: com.issuu.app
[INFO] 26/Mar/2020 13:31:19 - Starting Binary Analysis
[INFO] 26/Mar/2020 13:31:19 - Getting Binary Information
[INFO] 26/Mar/2020 13:31:19 - Running Object analysis of binary: Issuu
[ERROR] 26/Mar/2020 13:31:19 - Performing Object analysis of binary
Traceback (most recent call last):
  File "/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/otool_analysis.py", line 46, in get_otool_out
    libs = subprocess.check_output(args2).decode('utf-8', 'ignore')
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/ios/jtool2.ELF64'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/otool_analysis.py", line 101, in otool_analysis
    bin_dir)
  File "/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/otool_analysis.py", line 48, in get_otool_out
    libs = subprocess.check_output(args).decode('utf-8', 'ignore')
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/ios/jtool.ELF64'
[INFO] 26/Mar/2020 13:31:19 - Dumping classes
[INFO] 26/Mar/2020 13:31:19 - Running jtool against the binary for dumping classes
[ERROR] 26/Mar/2020 13:31:19 - iOS Binary Analysis
Traceback (most recent call last):
  File "/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/binary_analysis.py", line 104, in binary_analysis
    object_data['bindata'] + cdump,
TypeError: can only concatenate str (not "bytes") to str
[INFO] 26/Mar/2020 13:31:19 - Fetching icon path
[ERROR] 26/Mar/2020 13:31:19 - Error Perfroming Static Analysis
Traceback (most recent call last):
  File "/root/Desktop/tools/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/static_analyzer.py", line 113, in static_analyzer_ios
    bin_analysis_dict['strings'])
TypeError: 'NoneType' object is not subscriptable
[ERROR] 26/Mar/2020 13:31:19 - 'NoneType' object is not subscriptable
[ERROR] 26/Mar/2020 13:31:19 - Internal Server Error: /StaticAnalyzer_iOS/```

**Comment by ajinabraham** [comment]
You are on a 32 bit os `Linux-5.2.0-kali2-686-pae-i686-with-debian-kali-rolling` please use a 64 bit OS. This caused the IPA error as you are trying to run jtool 64bit on a 32 bit os. Not a bug hence closing the issue.

**Comment by ajinabraham** [comment]
If you need to discuss further, please use our slack channel.
