### ISSUE TITLE
Error Attribute not found.  'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by Lay-wang** [MobSF/Mobile-Security-Framework-MobSF#1335]
## ENVIRONMENT

```
OS and Version:WIN10
Python Version:3.7
MobSF Version:3.05beta
```

## STEPS TO REPRODUCE THE ISSUE

No matter what kind of apk I try, it always shows this prompt. I have tried “run setup.sh after updating”.But it still dosn't  work.
These apks I used to test：
https://drive.google.com/open?id=1LgjwoEfmob4Q3JDpAZpAtQIvlGmP0q19

## LOG FILE

[INFO] 29/Mar/2020 02:06:13 - MIME Type: application/vnd.android.package-archive FILE: ibiliplayer-bili.apk
[INFO] 29/Mar/2020 02:06:14 - Performing Static Analysis of Android APK
[INFO] 29/Mar/2020 02:06:14 - Starting Analysis on : iBiliPlayer-bili.apk
[INFO] 29/Mar/2020 02:06:14 - Generating Hashes
[INFO] 29/Mar/2020 02:06:14 - Unzipping
[INFO] 29/Mar/2020 02:06:22 - Getting Hardcoded Certificates/Keystores
[INFO] 29/Mar/2020 02:06:22 - APK Extracted
[INFO] 29/Mar/2020 02:06:22 - Converting AXML to XML
[INFO] 29/Mar/2020 02:06:37 - Reading Android Manifest
[INFO] 29/Mar/2020 02:06:37 - Parsing AndroidManifest.xml
[INFO] 29/Mar/2020 02:06:39 - Extracting Manifest Data
[INFO] 29/Mar/2020 02:06:39 - Fetching Details from Play Store: tv.danmaku.bili
[INFO] 29/Mar/2020 02:06:39 - Manifest Analysis Started
[INFO] 29/Mar/2020 02:06:39 - Static Android Binary Analysis Started
[INFO] 29/Mar/2020 02:06:39 - Static Android Resource Analysis Started
[INFO] 29/Mar/2020 02:06:39 - Reading Code Signing Certificate
[INFO] 29/Mar/2020 02:06:39 - Running APKiD 2.1.0
Exception scanning C:\Mobile-Security-Framework\uploads/e3be063ff08333b5e441f00b2cdab0fe/e3be063ff08333b5e441f00b2cdab0fe.apk: Traceback (most recent call last):
  File "c:\mobile-security-framework\venv\lib\site-packages\apkid\apkid.py", line 123, in scan_file
    results: Dict[str, List[yara.Match]] = self.scan_file_obj(f, file_path)
  File "c:\mobile-security-framework\venv\lib\site-packages\apkid\apkid.py", line 139, in scan_file_obj
    matches: List[yara.Matches] = self.rules.match(data=file.read(), timeout=self.options.timeout)
yara.Error: internal error: 34

[ERROR] 29/Mar/2020 02:06:40 - Error Performing Static Analysis
Traceback (most recent call last):
  File "C:\Mobile-Security-Framework\MalwareAnalyzer\views\apkid.py", line 45, in apkid_analysis
    findings = output._build_json_output(res)['files']
AttributeError: 'OutputFormatter' object has no attribute '_build_json_output'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Mobile-Security-Framework\StaticAnalyzer\views\android\static_analyzer.py", line 188, in static_analyzer
    'app_dir'], app_dic['app_path'], app_dic['app_name'])
  File "C:\Mobile-Security-Framework\MalwareAnalyzer\views\apkid.py", line 48, in apkid_analysis
    findings = output.build_json_output(res)['files']
  File "c:\mobile-security-framework\venv\lib\site-packages\apkid\output.py", line 117, in build_json_output
    for filename, matches in results.items():
AttributeError: 'list' object has no attribute 'items'
[ERROR] 29/Mar/2020 02:06:40 - 'list' object has no attribute 'items'
[ERROR] 29/Mar/2020 02:06:40 - Internal Server Error: /StaticAnalyzer/
ERROR:django.request:Internal Server Error: /StaticAnalyzer/

**Comment by ajinabraham** [comment]
Not a bug, Use slack for discussions.
Incomplete installation 
```
yara.Error: internal error: 34
```
Make sure you have the correct yara-python fork installed and remove any other versions.

**Comment by aph3rson** [comment]
@ajinabraham This is a real bug, and merits a bit more investigation than an instant-close.

I followed the exact instructions listed in the [installation guide](https://mobsf.github.io/docs/#/installation?id=windows) on a fresh installation (fresh venv, as well), and this issue still occurs. `yara-python` is installed, as required by the `apkid` package:  
```
(venv) C:\tools\mobsf>pipdeptree -r -p yara-python                                                                                                                                                                                                                                        yara-python==3.11.0                                                                                                                                                                                                                                                                         - apkid==2.1.0 [requires: yara-python==3.11.0]
```

However, I get the exact same error as @Lay-wang did earlier. Here's my output:  
```
(venv) C:\tools\mobsf>.\run.bat                                                                                                                                                                                                                                                           Serving on http://DESKTOP-Q7GD3Q6:8000                                                                                                                                                                                                                                                    Serving on http://DESKTOP-Q7GD3Q6:8000                                                                                                                                                                                                                                                    [INFO] 11/Apr/2020 16:45:29 -                                                                                                                                                                                                                                                               __  __       _    ____  _____       _____  ___                                                                                                                                                                                                                                           |  \/  | ___ | |__/ ___||  ___|_   _|___ / / _ \                                                                                                                                                                                                                                          | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| | | |                                                                                                                                                                                                                                         | |  | | (_) | |_) |__) |  _|  \ V / ___) | |_| |                                                                                                                                                                                                                                         |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   [INFO] 11/Apr/2020 16:45:29 - Mobile Security Framework v3.0.7 Beta                                                                                                                                                                                                                       REST API Key: [snip]
[INFO] 11/Apr/2020 16:45:29 - OS: Windows                                                                                                                                                                                                                                                 [INFO] 11/Apr/2020 16:45:29 - Platform: Windows-10-10.0.18362-SP0                                                                                                                                                                                                                         [INFO] 11/Apr/2020 16:45:29 - Dist:                                                                                                                                                                                                                                                       [INFO] 11/Apr/2020 16:45:29 - MobSF Basic Environment Check                                                                                                                                                                                                                               [WARNING] 11/Apr/2020 16:45:30 - Dynamic Analysis related functions will not work.                                                                                                                                                                                                        Make sure a Genymotion Android VM/Android Studio Emulator is running before performing Dynamic Analyis.                                                                                                                                                                                   [INFO] 11/Apr/2020 16:45:30 - Checking for Update.                                                                                                                                                                                                                                        [INFO] 11/Apr/2020 16:45:30 - No updates available.                                                                                                                                                                                                                                       [INFO] 11/Apr/2020 16:45:39 - MIME Type: application/vnd.android.package-archive FILE: [snip].apk                                                                                                                                                            [INFO] 11/Apr/2020 16:45:39 - Performing Static Analysis of Android APK                                                                                                                                                                                                                   [INFO] 11/Apr/2020 16:45:39 - Starting Analysis on : [snip].apk                                                                                                                                                                                              [INFO] 11/Apr/2020 16:45:39 - Generating Hashes                                                                                                                                                                                                                                           [INFO] 11/Apr/2020 16:45:40 - Unzipping                                                                                                                                                                                                                                                   [INFO] 11/Apr/2020 16:45:41 - Getting Hardcoded Certificates/Keystores                                                                                                                                                                                                                    [INFO] 11/Apr/2020 16:45:41 - APK Extracted                                                                                                                                                                                                                                               [INFO] 11/Apr/2020 16:45:41 - Converting AXML to XML                                                                                                                                                                                                                                      W: Cant find 9patch chunk in file: "drawable-hdpi-v4/menu1_down2.9.png". Renaming it to *.png.                                                                                                                                                                                            W: Cant find 9patch chunk in file: "drawable-hdpi-v4/menu1_normal2.9.png". Renaming it to *.png.                                                                                                                                                                                          [INFO] 11/Apr/2020 16:45:46 - Reading Android Manifest                                                                                                                                                                                                                                    [INFO] 11/Apr/2020 16:45:46 - Parsing AndroidManifest.xml                                                                                                                                                                                                                                 [INFO] 11/Apr/2020 16:45:47 - Fetching icon path                                                                                                                                                                                                                                          [INFO] 11/Apr/2020 16:45:47 - Extracting Manifest Data                                                                                                                                                                                                                                    [INFO] 11/Apr/2020 16:45:47 - Fetching Details from Play Store: [snip]                                                                                                                                                                                                        [INFO] 11/Apr/2020 16:45:47 - Manifest Analysis Started                                                                                                                                                                                                                                   [INFO] 11/Apr/2020 16:45:47 - Static Android Binary Analysis Started                                                                                                                                                                                                                      [INFO] 11/Apr/2020 16:45:47 - Static Android Resource Analysis Started                                                                                                                                                                                                                    [INFO] 11/Apr/2020 16:45:47 - Reading Code Signing Certificate                                                                                                                                                                                                                            [INFO] 11/Apr/2020 16:45:48 - Running APKiD 2.1.0                                                                                                                                                                                                                                         Exception scanning C:\tools\mobsf\uploads/[snip]/[snip].apk: Traceback (most recent call last):                                                                                                                                         File "c:\tools\mobsf\venv\lib\site-packages\apkid\apkid.py", line 123, in scan_file                                                                                                                                                                                                         results: Dict[str, List[yara.Match]] = self.scan_file_obj(f, file_path)                                                                                                                                                                                                                 File "c:\tools\mobsf\venv\lib\site-packages\apkid\apkid.py", line 139, in scan_file_obj                                                                                                                                                                                                     matches: List[yara.Matches] = self.rules.match(data=file.read(), timeout=self.options.timeout)                                                                                                                                                                                        yara.Error: internal error: 34                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      [ERROR] 11/Apr/2020 16:45:49 - Error Performing Static Analysis                                                                                                                                                                                                                           Traceback (most recent call last):                                                                                                                                                                                                                                                          File "C:\tools\mobsf\MalwareAnalyzer\views\apkid.py", line 45, in apkid_analysis                                                                                                                                                                                                            findings = output._build_json_output(res)['files']                                                                                                                                                                                                                                    AttributeError: 'OutputFormatter' object has no attribute '_build_json_output'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      During handling of the above exception, another exception occurred:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Traceback (most recent call last):                                                                                                                                                                                                                                                          File "C:\tools\mobsf\StaticAnalyzer\views\android\static_analyzer.py", line 189, in static_analyzer                                                                                                                                                                                         'app_dir'], app_dic['app_path'], app_dic['app_name'])                                                                                                                                                                                                                                   File "C:\tools\mobsf\MalwareAnalyzer\views\apkid.py", line 48, in apkid_analysis                                                                                                                                                                                                            findings = output.build_json_output(res)['files']                                                                                                                                                                                                                                       File "c:\tools\mobsf\venv\lib\site-packages\apkid\output.py", line 117, in build_json_output                                                                                                                                                                                                for filename, matches in results.items():                                                                                                                                                                                                                                             AttributeError: 'list' object has no attribute 'items'                                                                                                                                                                                                                                    [ERROR] 11/Apr/2020 16:45:49 - 'list' object has no attribute 'items'                                                                                                                                                                                                                     [ERROR] 11/Apr/2020 16:45:49 - Internal Server Error: /StaticAnalyzer/                                                                                                                                                                                                                    ERROR:django.request:Internal Server Error: /StaticAnalyzer/
```

Note that this also indicates some pretty poor exception handling from APKiD - if it fails, perhaps it could be skipped, rather than crashing the analysis process.

**Comment by ajinabraham** [comment]
@aph3rson This is due to incorrect setup.
We run tests on windows: https://travis-ci.com/github/MobSF/Mobile-Security-Framework-MobSF/jobs/318471694#L595
`yara.Error: internal error: 34` occurs when you have not installed the patched APKID and yara-python that mobsf uses.

This is how we install APKID

https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/setup.bat#L40-L45

You need to make sure that setup script completes without any errors.
