### ISSUE TITLE
Error Performing Static Analysis

### ISSUE THREAD

**Issue by elbae** [MobSF/Mobile-Security-Framework-MobSF#1340]
## ENVIRONMENT

```
OS and Version: Microsoft Windows 10 Pro 10.0.18362 N/D build 18362
Python Version: Python 3.7.4
MobSF Version: MobSF v3.0.6 Beta
```

## EXPLANATION OF THE ISSUE

```
Error during static analysis.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. Upload apk
2. Upload complete
3. Static analysis starts
4. Error Performing Static Analysis
```

## LOG FILE

```
[INFO] 01/Apr/2020 09:20:10 - MIME Type: application/octet-stream FILE: first.apk
[INFO] 01/Apr/2020 09:20:10 - Performing Static Analysis of Android APK
[INFO] 01/Apr/2020 09:20:10 - Starting Analysis on : first.apk
[INFO] 01/Apr/2020 09:20:10 - Generating Hashes
[INFO] 01/Apr/2020 09:20:11 - Unzipping
[INFO] 01/Apr/2020 09:20:14 - Getting Hardcoded Certificates/Keystores
[INFO] 01/Apr/2020 09:20:14 - APK Extracted
[INFO] 01/Apr/2020 09:20:14 - Converting AXML to XML
[ERROR] 01/Apr/2020 09:20:15 - Getting Manifest file
Traceback (most recent call last):
  File "C:\MobSF2\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\manifest_analysis.py", line 885, in get_manifest_file
    subprocess.check_output(args)
  File "c:\programdata\anaconda3\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "c:\programdata\anaconda3\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Program Files\\Java\\jdk-13.0.1\\bin\\java.exe', '-jar', 'C:\\MobSF2\\Mobile-Security-Framework-MobSF\\StaticAnalyzer/tools/apktool_2.4.1.jar', '--match-original', '--frame-path', 'C:\\Users\\Undisclosed\\AppData\\Local\\Temp', '-f', '-s', 'd', 'C:\\MobSF2\\Mobile-Security-Framework-MobSF\\uploads/ded524d566140a28ba9de80a6bf3fa85/ded524d566140a28ba9de80a6bf3fa85.apk', '-o', 'C:\\MobSF2\\Mobile-Security-Framework-MobSF\\uploads/ded524d566140a28ba9de80a6bf3fa85/apktool_out']' returned non-zero exit status 1.
[ERROR] 01/Apr/2020 09:20:15 - Reading Manifest file
Traceback (most recent call last):
  File "C:\MobSF2\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\manifest_analysis.py", line 831, in read_manifest
    if is_file_exists(manifest):
  File "C:\MobSF2\Mobile-Security-Framework-MobSF\MobSF\utils.py", line 392, in is_file_exists
    if os.path.isfile(file_path):
  File "c:\programdata\anaconda3\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
[INFO] 01/Apr/2020 09:20:15 - Parsing AndroidManifest.xml
[ERROR] 01/Apr/2020 09:20:15 - apktool failed to extract AndroidManifest.xml or parsing failed
Traceback (most recent call last):
  File "C:\MobSF2\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\manifest_analysis.py", line 35, in get_manifest
    manifest = minidom.parseString(dat)
  File "c:\programdata\anaconda3\lib\xml\dom\minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "c:\programdata\anaconda3\lib\xml\dom\expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "c:\programdata\anaconda3\lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
TypeError: a bytes-like object is required, not 'NoneType'
[WARNING] 01/Apr/2020 09:20:15 - Using Fake XML to continue the Analysis
[INFO] 01/Apr/2020 09:20:17 - Extracting Manifest Data
[INFO] 01/Apr/2020 09:20:17 - Fetching Details from Play Store: Fail
[INFO] 01/Apr/2020 09:20:17 - Manifest Analysis Started
[INFO] 01/Apr/2020 09:20:17 - Static Android Binary Analysis Started
[INFO] 01/Apr/2020 09:20:18 - Static Android Resource Analysis Started
[INFO] 01/Apr/2020 09:20:18 - Reading Code Signing Certificate
[INFO] 01/Apr/2020 09:20:19 - Running APKiD 2.1.0
[ERROR] 01/Apr/2020 09:20:19 - Error Performing Static Analysis
Traceback (most recent call last):
  File "C:\MobSF2\Mobile-Security-Framework-MobSF\MalwareAnalyzer\views\apkid.py", line 45, in apkid_analysis
    findings = output._build_json_output(res)['files']
AttributeError: 'OutputFormatter' object has no attribute '_build_json_output'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\MobSF2\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\static_analyzer.py", line 188, in static_analyzer
    'app_dir'], app_dic['app_path'], app_dic['app_name'])
  File "C:\MobSF2\Mobile-Security-Framework-MobSF\MalwareAnalyzer\views\apkid.py", line 48, in apkid_analysis
    findings = output.build_json_output(res)['files']
  File "C:\Users\Undisclosed\AppData\Roaming\Python\Python37\site-packages\apkid\output.py", line 117, in build_json_output
    for filename, matches in results.items():
AttributeError: 'list' object has no attribute 'items'
[ERROR] 01/Apr/2020 09:20:20 - 'list' object has no attribute 'items'
[ERROR] 01/Apr/2020 09:20:20 - Internal Server Error: /StaticAnalyzer/
[INFO] 01/Apr/2020 09:20:30 - MIME Type: application/octet-stream FILE: first.apk
[INFO] 01/Apr/2020 09:20:30 - Performing Static Analysis of Android APK
[INFO] 01/Apr/2020 09:20:30 - Starting Analysis on : first.apk
[INFO] 01/Apr/2020 09:20:30 - Generating Hashes
[INFO] 01/Apr/2020 09:20:31 - Unzipping
[INFO] 01/Apr/2020 09:20:33 - Getting Hardcoded Certificates/Keystores
[INFO] 01/Apr/2020 09:20:33 - APK Extracted
[INFO] 01/Apr/2020 09:20:33 - Converting AXML to XML
[ERROR] 01/Apr/2020 09:20:34 - Getting Manifest file
Traceback (most recent call last):
  File "C:\MobSF2\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\manifest_analysis.py", line 885, in get_manifest_file
    subprocess.check_output(args)
  File "c:\programdata\anaconda3\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "c:\programdata\anaconda3\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Program Files\\Java\\jdk-13.0.1\\bin\\java.exe', '-jar', 'C:\\MobSF2\\Mobile-Security-Framework-MobSF\\StaticAnalyzer/tools/apktool_2.4.1.jar', '--match-original', '--frame-path', 'C:\\Users\\Undisclosed\\AppData\\Local\\Temp', '-f', '-s', 'd', 'C:\\MobSF2\\Mobile-Security-Framework-MobSF\\uploads/ded524d566140a28ba9de80a6bf3fa85/ded524d566140a28ba9de80a6bf3fa85.apk', '-o', 'C:\\MobSF2\\Mobile-Security-Framework-MobSF\\uploads/ded524d566140a28ba9de80a6bf3fa85/apktool_out']' returned non-zero exit status 1.
[ERROR] 01/Apr/2020 09:20:34 - Reading Manifest file
Traceback (most recent call last):
  File "C:\MobSF2\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\manifest_analysis.py", line 831, in read_manifest
    if is_file_exists(manifest):
  File "C:\MobSF2\Mobile-Security-Framework-MobSF\MobSF\utils.py", line 392, in is_file_exists
    if os.path.isfile(file_path):
  File "c:\programdata\anaconda3\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
[INFO] 01/Apr/2020 09:20:34 - Parsing AndroidManifest.xml
[ERROR] 01/Apr/2020 09:20:34 - apktool failed to extract AndroidManifest.xml or parsing failed
Traceback (most recent call last):
  File "C:\MobSF2\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\manifest_analysis.py", line 35, in get_manifest
    manifest = minidom.parseString(dat)
  File "c:\programdata\anaconda3\lib\xml\dom\minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "c:\programdata\anaconda3\lib\xml\dom\expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "c:\programdata\anaconda3\lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
TypeError: a bytes-like object is required, not 'NoneType'
[WARNING] 01/Apr/2020 09:20:34 - Using Fake XML to continue the Analysis
[INFO] 01/Apr/2020 09:20:36 - Extracting Manifest Data
[INFO] 01/Apr/2020 09:20:36 - Fetching Details from Play Store: Fail
[INFO] 01/Apr/2020 09:20:36 - Manifest Analysis Started
[INFO] 01/Apr/2020 09:20:36 - Static Android Binary Analysis Started
[INFO] 01/Apr/2020 09:20:36 - Static Android Resource Analysis Started
[INFO] 01/Apr/2020 09:20:36 - Reading Code Signing Certificate
[INFO] 01/Apr/2020 09:20:37 - Running APKiD 2.1.0
[ERROR] 01/Apr/2020 09:20:38 - Error Performing Static Analysis
Traceback (most recent call last):
  File "C:\MobSF2\Mobile-Security-Framework-MobSF\MalwareAnalyzer\views\apkid.py", line 45, in apkid_analysis
    findings = output._build_json_output(res)['files']
AttributeError: 'OutputFormatter' object has no attribute '_build_json_output'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\MobSF2\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\static_analyzer.py", line 188, in static_analyzer
    'app_dir'], app_dic['app_path'], app_dic['app_name'])
  File "C:\MobSF2\Mobile-Security-Framework-MobSF\MalwareAnalyzer\views\apkid.py", line 48, in apkid_analysis
    findings = output.build_json_output(res)['files']
  File "C:\Users\Undisclosed\AppData\Roaming\Python\Python37\site-packages\apkid\output.py", line 117, in build_json_output
    for filename, matches in results.items():
AttributeError: 'list' object has no attribute 'items'
[ERROR] 01/Apr/2020 09:20:38 - 'list' object has no attribute 'items'
[ERROR] 01/Apr/2020 09:20:38 - Internal Server Error: /StaticAnalyzer/
[INFO] 01/Apr/2020 09:21:47 - MIME Type: application/octet-stream FILE: second.apk
[INFO] 01/Apr/2020 09:21:47 - Performing Static Analysis of Android APK
[INFO] 01/Apr/2020 09:21:47 - Starting Analysis on : second.apk
[INFO] 01/Apr/2020 09:21:47 - Generating Hashes
[INFO] 01/Apr/2020 09:21:47 - Unzipping
[INFO] 01/Apr/2020 09:21:48 - Getting Hardcoded Certificates/Keystores
[INFO] 01/Apr/2020 09:21:48 - APK Extracted
[INFO] 01/Apr/2020 09:21:48 - Converting AXML to XML
[INFO] 01/Apr/2020 09:21:55 - Reading Android Manifest
[INFO] 01/Apr/2020 09:21:55 - Parsing AndroidManifest.xml
[INFO] 01/Apr/2020 09:21:55 - Fetching icon path
[INFO] 01/Apr/2020 09:21:56 - Extracting Manifest Data
[INFO] 01/Apr/2020 09:21:56 - Fetching Details from Play Store: com.undisclosed.undisclosed
[INFO] 01/Apr/2020 09:21:56 - Manifest Analysis Started
[INFO] 01/Apr/2020 09:21:56 - Static Android Binary Analysis Started
[INFO] 01/Apr/2020 09:21:56 - Static Android Resource Analysis Started
[INFO] 01/Apr/2020 09:21:56 - Reading Code Signing Certificate
[INFO] 01/Apr/2020 09:21:56 - Running APKiD 2.1.0
[ERROR] 01/Apr/2020 09:21:57 - Error Performing Static Analysis
Traceback (most recent call last):
  File "C:\MobSF2\Mobile-Security-Framework-MobSF\MalwareAnalyzer\views\apkid.py", line 45, in apkid_analysis
    findings = output._build_json_output(res)['files']
AttributeError: 'OutputFormatter' object has no attribute '_build_json_output'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\MobSF2\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\static_analyzer.py", line 188, in static_analyzer
    'app_dir'], app_dic['app_path'], app_dic['app_name'])
  File "C:\MobSF2\Mobile-Security-Framework-MobSF\MalwareAnalyzer\views\apkid.py", line 48, in apkid_analysis
    findings = output.build_json_output(res)['files']
  File "C:\Users\Undisclosed\AppData\Roaming\Python\Python37\site-packages\apkid\output.py", line 117, in build_json_output
    for filename, matches in results.items():
AttributeError: 'list' object has no attribute 'items'
[ERROR] 01/Apr/2020 09:21:57 - 'list' object has no attribute 'items'
[ERROR] 01/Apr/2020 09:21:57 - Internal Server Error: /StaticAnalyzer/
[INFO] 01/Apr/2020 09:22:13 - MIME Type: application/octet-stream FILE: second.apk
[INFO] 01/Apr/2020 09:22:13 - Performing Static Analysis of Android APK
[INFO] 01/Apr/2020 09:22:13 - Starting Analysis on : second.apk
[INFO] 01/Apr/2020 09:22:13 - Generating Hashes
[INFO] 01/Apr/2020 09:22:13 - Unzipping
[INFO] 01/Apr/2020 09:22:14 - Getting Hardcoded Certificates/Keystores
[INFO] 01/Apr/2020 09:22:14 - APK Extracted
[INFO] 01/Apr/2020 09:22:14 - Reading Android Manifest
[INFO] 01/Apr/2020 09:22:14 - Parsing AndroidManifest.xml
[INFO] 01/Apr/2020 09:22:14 - Fetching icon path
[INFO] 01/Apr/2020 09:22:15 - Extracting Manifest Data
[INFO] 01/Apr/2020 09:22:15 - Fetching Details from Play Store: com.undisclosed.undisclosed
[INFO] 01/Apr/2020 09:22:16 - Manifest Analysis Started
[INFO] 01/Apr/2020 09:22:16 - Static Android Binary Analysis Started
[INFO] 01/Apr/2020 09:22:16 - Static Android Resource Analysis Started
[INFO] 01/Apr/2020 09:22:16 - Reading Code Signing Certificate
[INFO] 01/Apr/2020 09:22:16 - Running APKiD 2.1.0
[ERROR] 01/Apr/2020 09:22:16 - Error Performing Static Analysis
Traceback (most recent call last):
  File "C:\MobSF2\Mobile-Security-Framework-MobSF\MalwareAnalyzer\views\apkid.py", line 45, in apkid_analysis
    findings = output._build_json_output(res)['files']
AttributeError: 'OutputFormatter' object has no attribute '_build_json_output'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\MobSF2\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\static_analyzer.py", line 188, in static_analyzer
    'app_dir'], app_dic['app_path'], app_dic['app_name'])
  File "C:\MobSF2\Mobile-Security-Framework-MobSF\MalwareAnalyzer\views\apkid.py", line 48, in apkid_analysis
    findings = output.build_json_output(res)['files']
  File "C:\Users\Undisclosed\AppData\Roaming\Python\Python37\site-packages\apkid\output.py", line 117, in build_json_output
    for filename, matches in results.items():
AttributeError: 'list' object has no attribute 'items'
[ERROR] 01/Apr/2020 09:22:16 - 'list' object has no attribute 'items'
[ERROR] 01/Apr/2020 09:22:16 - Internal Server Error: /StaticAnalyzer/
```

**Comment by ajinabraham** [comment]
Please share the APK. Are you seeing this issue only for a particular APK?
Also the APKiD setup looks incomplete. You need to ensure that setup.bat runs successfully without any errors.

**Comment by elbae** [comment]
I'm sorry but unfortunately I can't share the APK.
Btw you were right, I tried the installation (again) and found an error while executing these lines:
```
pip wheel --wheel-dir=yara-python --build-option="build" --build-option="--enable-dex" git+https://github.com/VirusTotal/yara-python.git@v3.11.0 
pip install --no-index --find-links=yara-python yara-python 
```
I managed to bypass the error with the following one-line addition:
`python -m pip install --upgrade pip`
after
`.\venv\Scripts\activate`

Cheers

**Comment by ajinabraham** [comment]
Can't troubleshoot without the APK. Hence closing the issue.
