### ISSUE TITLE
First Time MobSFy Failure

### ISSUE THREAD

**Issue by ajinabraham** [MobSF/Mobile-Security-Framework-MobSF#1352]
## ENVIRONMENT

```
OS and Version: *
Python Version: *
MobSF Version: 3.0.6
```

## EXPLANATION OF THE ISSUE

```
MobSFy Android Instance Traceback (most recent call last): File "C:\Users\Lijoy KFH\Mobile-Security-Framework-MobSF-master\DynamicAnalyzer\views\android\environment.py", line 408, in mobsfy_init self.mobsf_agents_setup('frida') File "C:\Users\Lijoy KFH\Mobile-Security-Framework-MobSF-master\DynamicAnalyzer\views\android\environment.py", line 418, in mobsf_agents_setup self.install_mobsf_ca('install') File "C:\Users\Lijoy KFH\Mobile-Security-Framework-MobSF-master\DynamicAnalyzer\views\android\environment.py", line 140, in install_mobsf_ca pem = open(get_ca_dir(), 'rb').read() FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Lijoy KFH\\.mitmproxy\\mitmproxy-ca-cert.pem' [ERROR] 12/Apr/2020 18:53:11 – Failed to MobSFy the instance [ERROR] 12/Apr/2020 18:53:11 – Internal Server Error: /android_dynamic/"
```

## STEPS TO REPRODUCE THE ISSUE

```
1. MobSFy first time on a system without mitmproxy installed
```

## LOG FILE

```
Paste the contents of logs/debug.log here or attach the log file.
```

**Comment by Lijoyr** [comment]
[debug.log](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/4466867/debug.log)
OS version : Platform: Windows-10-10.0.18362-SP0
Python version - Python 3.8.2

**Comment by ajinabraham** [comment]
Python 3.8 is not supported

**Comment by Lijoyr** [comment]
Thank you Ajin. You can close the case.

**Comment by ajinabraham** [comment]
This is an issue w.r.t dynamic analysis that needs to be addressed.

**Comment by ajinabraham** [comment]
This still is an issue w.r.t to Dynamic Analyzer

**Comment by Lijoyr** [comment]
Let me check that as well..
