### ISSUE TITLE
Mobsf error

### ISSUE THREAD

**Issue by parteeksingh005** [MobSF/Mobile-Security-Framework-MobSF#1369]
I am getting an error while analyzing the APK. Please refer to the below error. Please help me with this error why I am getting this error. i am runnning mobsf in windows 10 . 

Exception scanning E:\Software\mobile tools\Mobile-Security-Framework-MobSF\uploads/d4bd53ec6f7b624072121ad724e26a68/d4bd53ec6f7b624072121ad724e26a68.apk: Traceback (most recent call last):
  File "e:\software\mobile tools\mobile-security-framework-mobsf\venv\lib\site-packages\apkid\apkid.py", line 123, in scan_file
    results: Dict[str, List[yara.Match]] = self.scan_file_obj(f, file_path)
  File "e:\software\mobile tools\mobile-security-framework-mobsf\venv\lib\site-packages\apkid\apkid.py", line 139, in scan_file_obj
    matches: List[yara.Matches] = self.rules.match(data=file.read(), timeout=self.options.timeout)
yara.Error: internal error: 34

[ERROR] 22/Apr/2020 12:44:42 - Error Performing Static Analysis
Traceback (most recent call last):
  File "E:\Software\mobile tools\Mobile-Security-Framework-MobSF\MalwareAnalyzer\views\apkid.py", line 45, in apkid_analysis
    findings = output._build_json_output(res)['files']
AttributeError: 'OutputFormatter' object has no attribute '_build_json_output'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Software\mobile tools\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\static_analyzer.py", line 189, in static_analyzer
    'app_dir'], app_dic['app_path'], app_dic['app_name'])
  File "E:\Software\mobile tools\Mobile-Security-Framework-MobSF\MalwareAnalyzer\views\apkid.py", line 48, in apkid_analysis
    findings = output.build_json_output(res)['files']
  File "e:\software\mobile tools\mobile-security-framework-mobsf\venv\lib\site-packages\apkid\output.py", line 117, in build_json_output
    for filename, matches in results.items():
AttributeError: 'list' object has no attribute 'items'
[ERROR] 22/Apr/2020 12:44:42 - 'list' object has no attribute 'items'
[ERROR] 22/Apr/2020 12:44:42 - Internal Server Error: /StaticAnalyzer/
ERROR:django.request:Internal Server Error: /StaticAnalyzer/

**Comment by superpoussin22** [comment]
Apkid Is not installed correctly, please use slack channel to discuss this, cause this is not a bug
