### ISSUE TITLE
Am having an error whiles trying to run dynamic analysis 

### ISSUE THREAD

**Issue by joeBENTIL** [MobSF/Mobile-Security-Framework-MobSF#1382]
[INFO] 30/Apr/2020 11:39:04 - Android Version identified as 7.0
[INFO] 30/Apr/2020 11:39:04 - Android OS architecture identified as x86
[INFO] 30/Apr/2020 11:39:04 - Copying frida server for x86
[ERROR] 30/Apr/2020 11:39:05 - Failed to MobSFy Android Instance
Traceback (most recent call last):
File "C:\Users\Richmond Bentil\Mobile-Security-Framework-MobSF\DynamicAnalyzer\views\android\environment.py", line 408, in mobsfy_init
    self.mobsf_agents_setup('frida')
 File "C:\Users\Richmond Bentil\Mobile-Security-Framework-MobSF\DynamicAnalyzer\views\android\environment.py", line 418, in mobsf_agents_setup
    self.install_mobsf_ca('install')
  File "C:\Users\Richmond Bentil\Mobile-Security-Framework-MobSF\DynamicAnalyzer\views\android\environment.py", line 140, in install_mobsf_ca
    pem = open(get_ca_dir(), 'rb').read()
  File "C:\Users\Richmond Bentil\Mobile-Security-Framework-MobSF\DynamicAnalyzer\tools\webproxy.py", line 67, in get_ca_dir
    from mitmproxy import ctx
  File "c:\users\richmond bentil\mobile-security-framework-mobsf\venv\lib\site-packages\mitmproxy\__init__.py", line 8, in <module>
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
AttributeError: module 'asyncio' has no attribute 'WindowsSelectorEventLoopPolicy'
[ERROR] 30/Apr/2020 11:39:05 - Failed to MobSFy the instance
[ERROR] 30/Apr/2020 11:39:05 - Internal Server Error: /android_dynamic/

**Comment by superpoussin22** [comment]
can you switch to slack and provide the full log on slack ?

**Comment by ajinabraham** [comment]
This is not a bug, missing module or improper python version. GitHub issues are only for bugs. Please use slack channel for support and troubleshooting.
