### ISSUE TITLE
[ERROR] Exception in worker process

### ISSUE THREAD

**Issue by tea9** [MobSF/Mobile-Security-Framework-MobSF#1390]
[2020-05-12 06:51:11 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2020-05-12 06:51:11 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2020-05-12 06:51:11 +0000] [1] [INFO] Using worker: threads
[2020-05-12 06:51:11 +0000] [8] [INFO] Booting worker with pid: 8
[2020-05-12 06:51:11 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/gthread.py", line 104, in init_process
    super(ThreadWorker, self).init_process()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
    apt install python3-pip
ModuleNotFoundError: No module named 'MobSF.wsgi'
[2020-05-12 06:51:11 +0000] [8] [INFO] Worker exiting (pid: 8)
[2020-05-12 06:51:11 +0000] [1] [INFO] Shutting down: Master
[2020-05-12 06:51:11 +0000] [1] [INFO] Reason: Worker failed to boot.

**Comment by ajinabraham** [comment]
This is an incorrect setup issue, not a bug. Use slack channel for support.
