### ISSUE TITLE
Error performing static analysis 

### ISSUE THREAD

**Issue by danhillcode** [MobSF/Mobile-Security-Framework-MobSF#1391]
Hi,

Out put from terminal provided below. I came across a blog post about updating the paths in the settings.py I have done this so a bit stuck what to try next. Any help or direction would be great.

Thanks,
Dan

Error: Unable to access jarfile /Users/danielhill/Desktop/H1-Projects/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/apktool_2.4.1.jar
[ERROR] 12/May/2020 15:32:06 - Getting Manifest file
Traceback (most recent call last):
  File "/Users/danielhill/Desktop/H1-Projects/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/manifest_analysis.py", line 885, in get_manifest_file
    subprocess.check_output(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/java', '-jar', '/Users/danielhill/Desktop/H1-Projects/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/apktool_2.4.1.jar', '--match-original', '--frame-path', '/var/folders/t9/97b1s22x66d6cg9_ysjcmp3r0000gn/T', '-f', '-s', 'd', '/Users/danielhill/Desktop/H1-Projects/Mobile-Security-Framework-MobSF/uploads/5ee4829065640f9c936ac861d1650ffc/5ee4829065640f9c936ac861d1650ffc.apk', '-o', '/Users/danielhill/Desktop/H1-Projects/Mobile-Security-Framework-MobSF/uploads/5ee4829065640f9c936ac861d1650ffc/apktool_out']' returned non-zero exit status 1.
[ERROR] 12/May/2020 15:32:06 - Reading Manifest file
Traceback (most recent call last):
  File "/Users/danielhill/Desktop/H1-Projects/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/manifest_analysis.py", line 831, in read_manifest
    if is_file_exists(manifest):
  File "/Users/danielhill/Desktop/H1-Projects/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 392, in is_file_exists
    if os.path.isfile(file_path):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
[INFO] 12/May/2020 15:32:06 - Parsing AndroidManifest.xml
[ERROR] 12/May/2020 15:32:06 - apktool failed to extract AndroidManifest.xml or parsing failed
Traceback (most recent call last):
  File "/Users/danielhill/Desktop/H1-Projects/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/manifest_analysis.py", line 35, in get_manifest
    manifest = minidom.parseString(dat)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/dom/minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
TypeError: a bytes-like object is required, not 'NoneType'
[WARNING] 12/May/2020 15:32:06 - Using Fake XML to continue the Analysis
[INFO] 12/May/2020 15:32:07 - Fetching icon path
[INFO] 12/May/2020 15:32:07 - Extracting Manifest Data
[INFO] 12/May/2020 15:32:07 - Fetching Details from Play Store: Failed
[INFO] 12/May/2020 15:32:07 - Manifest Analysis Started
[INFO] 12/May/2020 15:32:07 - Static Android Binary Analysis Started
[INFO] 12/May/2020 15:32:07 - Static Android Resource Analysis Started
[INFO] 12/May/2020 15:32:07 - Reading Code Signing Certificate
[INFO] 12/May/2020 15:32:07 - Running APKiD 2.1.0
[INFO] 12/May/2020 15:32:10 - Trackers Database is up-to-date
[INFO] 12/May/2020 15:32:10 - Detecting Trackers
Error: Unable to access jarfile /Users/danielhill/Desktop/H1-Projects/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/baksmali-2.4.0.jar
[ERROR] 12/May/2020 15:32:10 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/Users/danielhill/Desktop/H1-Projects/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/static_analyzer.py", line 192, in static_analyzer
    tracker_res = tracker.get_trackers()
  File "/Users/danielhill/Desktop/H1-Projects/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/Trackers.py", line 172, in get_trackers
    trackers = self.detect_trackers()
  File "/Users/danielhill/Desktop/H1-Projects/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/Trackers.py", line 164, in detect_trackers
    eclasses = self.get_embedded_classes()
  File "/Users/danielhill/Desktop/H1-Projects/Mobile-Security-Framework-MobSF/MalwareAnalyzer/views/Trackers.py", line 121, in get_embedded_classes
    args, universal_newlines=True).splitlines()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/java', '-jar', '/Users/danielhill/Desktop/H1-Projects/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/baksmali-2.4.0.jar', 'list', 'classes', '/Users/danielhill/Desktop/H1-Projects/Mobile-Security-Framework-MobSF/uploads/5ee4829065640f9c936ac861d1650ffc/classes.dex']' returned non-zero exit status 1.
[ERROR] 12/May/2020 15:32:10 - Command '['/usr/bin/java', '-jar', '/Users/danielhill/Desktop/H1-Projects/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/baksmali-2.4.0.jar', 'list', 'classes', '/Users/danielhill/Desktop/H1-Projects/Mobile-Security-Framework-MobSF/uploads/5ee4829065640f9c936ac861d1650ffc/classes.dex']' returned non-zero exit status 1.
[ERROR] 12/May/2020 15:32:10 - Internal Server Error: /StaticAnalyzer/

**Comment by ajinabraham** [comment]
This is not a bug, please use slack for support.
