### ISSUE TITLE
ModuleNotFoundError at /

### ISSUE THREAD

**Issue by ganesh2183** [MobSF/Mobile-Security-Framework-MobSF#1405]
![image](https://user-images.githubusercontent.com/41476297/82735568-4cca1000-9d40-11ea-87bd-d7e74900174d.png)

 
Environment:
Request Method: GET
Request URL: http://hp:8080/

Django Version: 3.0.6
Python Version: 3.8.3
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'StaticAnalyzer',
 'DynamicAnalyzer',
 'MobSF',
 'MalwareAnalyzer')
Installed Middleware:
('MobSF.views.api.rest_api_middleware.RestApiAuthMiddleware',)

Traceback (most recent call last):
  File "c:\mobile-security-framework-mobsf\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "c:\mobile-security-framework-mobsf\venv\lib\site-packages\django\core\handlers\base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "c:\mobile-security-framework-mobsf\venv\lib\site-packages\django\urls\resolvers.py", line 544, in resolve
    for pattern in self.url_patterns:
  File "c:\mobile-security-framework-mobsf\venv\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "c:\mobile-security-framework-mobsf\venv\lib\site-packages\django\urls\resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\mobile-security-framework-mobsf\venv\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "c:\mobile-security-framework-mobsf\venv\lib\site-packages\django\urls\resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    <source code not available>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    <source code not available>
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    <source code not available>
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    <source code not available>
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
    <source code not available>
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    <source code not available>
  File "C:\Mobile-Security-Framework-MobSF\MobSF\urls.py", line 3, in <module>
    from DynamicAnalyzer.views.android import dynamic_analyzer as dz
  File "C:\Mobile-Security-Framework-MobSF\DynamicAnalyzer\views\android\dynamic_analyzer.py", line 14, in <module>
    from DynamicAnalyzer.views.android.environment import Environment
  File "C:\Mobile-Security-Framework-MobSF\DynamicAnalyzer\views\android\environment.py", line 13, in <module>
    from OpenSSL import crypto

Exception Type: ModuleNotFoundError at /
Exception Value: No module named 'OpenSSL'

**Comment by ajinabraham** [comment]
Please stick with official docs . Python 3.8 is not supported
