### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by harri35** [MobSF/Mobile-Security-Framework-MobSF#1477]
## ENVIRONMENT

```
OS and Version: Windows 10 version 1909
Python Version: Python 3.6.2
MobSF Version: v3.0.9 Beta
```

## EXPLANATION OF THE ISSUE
I am the developer of a library. Then I try to analyse my tester app which includes the library MobSF gets an error:
```
[INFO] 21/Jul/2020 10:18:02 - Decompiling to Java with jadx
[ERROR] 21/Jul/2020 10:18:04 - Decompiling to JAVA
Traceback (most recent call last):
  File "D:\m\gitrepo\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\converter.py", line 70, in apk_2_java
    shutil.rmtree(output)
  File "D:\dev\python-36-32\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "D:\dev\python-36-32\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "D:\dev\python-36-32\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "D:\dev\python-36-32\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 3 more times]
  File "D:\dev\python-36-32\lib\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "D:\dev\python-36-32\lib\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\m\\gitrepo\\Mobile-Security-Framework-MobSF\\uploads/480154b5d181204ae81a6067a6991eb2/java_source/ee\\company\\libname\\app\\smoketest\\testcase\\rprequest\\$$Lambda$ConfirmAuthAndSignRPRequestWithAllInteractionTypesViaGetOperationTransactionSmokeTestCase$QQlGOS3Bve9hJW7JQIJ7SoY.java'
[INFO] 21/Jul/2020 10:18:04 - DEX -> SMALI
[INFO] 21/Jul/2020 10:18:04 - Converting classes.dex to Smali Code
[INFO] 21/Jul/2020 10:18:04 - Converting classes2.dex to Smali Code
[INFO] 21/Jul/2020 10:18:04 - Converting classes3.dex to Smali Code
[INFO] 21/Jul/2020 10:18:04 - Static Android Code Analysis Started
[INFO] 21/Jul/2020 10:18:04 - Code Analysis Started on - java_source
[ERROR] 21/Jul/2020 10:18:04 - Performing Code Analysis
Traceback (most recent call last):
  File "D:\m\gitrepo\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\code_analysis.py", line 75, in code_analysis
    errors='ignore',
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\m\\gitrepo\\Mobile-Security-Framework-MobSF\\uploads/480154b5d181204ae81a6067a6991eb2/java_source/ee\\company\\libname\\app\\smoketest\\testcase\\rprequest\\$$Lambda$ConfirmAuthAndSignRPRequestWithAllInteractionTypesViaGetOperationTransactionSmokeTestCase$QQlGOS3Bve9hJW7JQIJ7SoY.java'
[INFO] 21/Jul/2020 10:18:04 - Extracting Strings from APK
WARNING:androguard.core.api_specific_resources:Requested API level 29 is larger than maximum we have, returning API level 28 instead.
[ERROR] 21/Jul/2020 10:18:07 - Error Performing Static Analysis
Traceback (most recent call last):
  File "D:\m\gitrepo\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\static_analyzer.py", line 205, in static_analyzer
    code_an_dic['urls_list'].extend(
TypeError: 'NoneType' object is not subscriptable
[ERROR] 21/Jul/2020 10:18:09 - 'NoneType' object is not subscriptable
[ERROR] 21/Jul/2020 10:18:10 - Internal Server Error: /StaticAnalyzer/
ERROR:django.request:Internal Server Error: /StaticAnalyzer/

```
When I analyse another app that includes my library then that works fine.
Note: The ConfirmAuthAndSignRPRequestWithAllInteractionTypesViaGetOperationTransactionSmokeTestCase class is part of a integration test suite the tester includes.

My goal here is to analyze my library and the parts it adds to the app of the integrator. But as MobSF does not allow to analyze *.arr files then as a workaround my plan is the use the tester app and analyse that and just ignore all the warnings that are generated purely because of something in the tester app code. 

## STEPS TO REPRODUCE THE ISSUE

```
1. I select my apk in MobiSF
2. Static analyzer fails and displays
Error
Inappropriate argument type.
'NoneType' object is not subscriptable
```

## LOG FILE

```
[INFO] 21/Jul/2020 10:28:26 - 
  __  __       _    ____  _____       _____  ___  
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / _ \ 
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| | | |
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | |_| |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/

[INFO] 21/Jul/2020 10:28:26 - Mobile Security Framework v3.0.9 Beta
[INFO] 21/Jul/2020 10:28:26 - OS: Windows
[INFO] 21/Jul/2020 10:28:26 - Platform: Windows-10-10.0.18362-SP0
[INFO] 21/Jul/2020 10:28:26 - Dist:   
[INFO] 21/Jul/2020 10:28:26 - MobSF Basic Environment Check
[INFO] 21/Jul/2020 10:28:27 - Checking for Update.
[INFO] 21/Jul/2020 10:28:28 - No updates available.
[INFO] 21/Jul/2020 10:28:33 - MIME Type: application/vnd.android.package-archive FILE: productname-demoui-20.0.1206-mobi-public1.apk
[INFO] 21/Jul/2020 10:28:33 - Performing Static Analysis of Android APK
[INFO] 21/Jul/2020 10:28:33 - Starting Analysis on : productname-demoui-20.0.1206-mobi-public1.apk
[INFO] 21/Jul/2020 10:28:33 - Generating Hashes
[INFO] 21/Jul/2020 10:28:33 - Unzipping
[INFO] 21/Jul/2020 10:28:33 - Getting Hardcoded Certificates/Keystores
[INFO] 21/Jul/2020 10:28:33 - APK Extracted
[INFO] 21/Jul/2020 10:28:33 - Reading Android Manifest
[INFO] 21/Jul/2020 10:28:33 - Parsing AndroidManifest.xml
[INFO] 21/Jul/2020 10:28:34 - Fetching icon path
[INFO] 21/Jul/2020 10:28:34 - Extracting Manifest Data
[INFO] 21/Jul/2020 10:28:34 - Fetching Details from Play Store: ee.company.libname.app
[INFO] 21/Jul/2020 10:28:35 - Manifest Analysis Started
[INFO] 21/Jul/2020 10:28:35 - Static Android Binary Analysis Started
[INFO] 21/Jul/2020 10:28:35 - Static Android Resource Analysis Started
[INFO] 21/Jul/2020 10:28:35 - Reading Code Signing Certificate
[INFO] 21/Jul/2020 10:28:35 - Running APKiD 2.1.0
[INFO] 21/Jul/2020 10:28:39 - Trackers Database is up-to-date
[INFO] 21/Jul/2020 10:28:39 - Detecting Trackers
[INFO] 21/Jul/2020 10:28:42 - APK -> JAVA
[INFO] 21/Jul/2020 10:28:42 - Decompiling to Java with jadx
[ERROR] 21/Jul/2020 10:28:42 - Decompiling to JAVA
Traceback (most recent call last):
  File "D:\m\gitrepo\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\converter.py", line 70, in apk_2_java
    shutil.rmtree(output)
  File "D:\dev\python-36-32\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "D:\dev\python-36-32\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "D:\dev\python-36-32\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "D:\dev\python-36-32\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 3 more times]
  File "D:\dev\python-36-32\lib\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "D:\dev\python-36-32\lib\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\m\\gitrepo\\Mobile-Security-Framework-MobSF\\uploads/480154b5d181204ae81a6067a6991eb2/java_source/ee\\company\\libname\\app\\smoketest\\testcase\\rprequest\\$$Lambda$ConfirmAuthAndSignRPRequestWithAllInteractionTypesViaGetOperationTransactionSmokeTestCase$QQlGOS3Bve9hJW7JQIJ7SoY.java'
[INFO] 21/Jul/2020 10:28:42 - DEX -> SMALI
[INFO] 21/Jul/2020 10:28:42 - Converting classes.dex to Smali Code
[INFO] 21/Jul/2020 10:28:42 - Converting classes2.dex to Smali Code
[INFO] 21/Jul/2020 10:28:42 - Converting classes3.dex to Smali Code
[INFO] 21/Jul/2020 10:28:42 - Static Android Code Analysis Started
[INFO] 21/Jul/2020 10:28:42 - Code Analysis Started on - java_source
[ERROR] 21/Jul/2020 10:28:42 - Performing Code Analysis
Traceback (most recent call last):
  File "D:\m\gitrepo\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\code_analysis.py", line 75, in code_analysis
    errors='ignore',
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\m\\gitrepo\\Mobile-Security-Framework-MobSF\\uploads/480154b5d181204ae81a6067a6991eb2/java_source/ee\\company\\libname\\app\\smoketest\\testcase\\rprequest\\$$Lambda$ConfirmAuthAndSignRPRequestWithAllInteractionTypesViaGetOperationTransactionSmokeTestCase$QQlGOS3Bve9hJW7JQIJ7SoY.java'
[INFO] 21/Jul/2020 10:28:42 - Extracting Strings from APK
[ERROR] 21/Jul/2020 10:28:45 - Error Performing Static Analysis
Traceback (most recent call last):
  File "D:\m\gitrepo\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\android\static_analyzer.py", line 205, in static_analyzer
    code_an_dic['urls_list'].extend(
TypeError: 'NoneType' object is not subscriptable
[ERROR] 21/Jul/2020 10:28:46 - 'NoneType' object is not subscriptable
[ERROR] 21/Jul/2020 10:28:47 - Internal Server Error: /StaticAnalyzer/

```

**Comment by harri35** [comment]
I installed MobSF to a VirtualBox VM with Ubuntu 19.10 eoan and static analysis works fine.
I guess this is either my Windows setup specific issue or a Windows-specific issue

**Comment by ajinabraham** [comment]
This is a windows limitation. Certain file names with special characters like `D:\\m\\gitrepo\\Mobile-Security-Framework-MobSF\\uploads/480154b5d181204ae81a6067a6991eb2/java_source/ee\\company\\libname\\app\\smoketest\\testcase\\rprequest\\$$Lambda$ConfirmAuthAndSignRPRequestWithAllInteractionTypesViaGetOperationTransactionSmokeTestCase$QQlGOS3Bve9hJW7JQIJ7SoY.java` are not supported in windows. Also we do not support Python 3.6. We have a story to track this, hence closing this.
