### ISSUE TITLE
[FEATURE] MobSF SAST support in Github Actions and Gitlab CI/CD

### ISSUE THREAD

**Issue by ajinabraham** [MobSF/Mobile-Security-Framework-MobSF#1509]
If you're requesting a new feature/enhancement, explain why you'd like it to be added and it's importance.

**Is your feature request related to a problem? Please describe.**
Since we have the docker image, it is easy to support Github/Gitlab CICD pipelines.

**Describe the solution you'd like**
Create Github Action and instruction
Create a sample Gitlab CI/CD file

**Comment by inm-certi** [comment]
I could advance a little, and it now it is crashing on MobSF Analisys

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[INFO] 19/Aug/2020 14:12:05 - 
API Key read from environment variable
[INFO] 19/Aug/2020 14:12:05 - 
  __  __       _    ____  _____       _____  _ 
REST API Key: 45ccbf14aca709d874da62fb5ffba096012eed2c09cfc4718e7ce59364f6082e
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / |
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \ | |
 | |  | | (_) | |_) |__) |  _|  \ V / ___) || |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)_|

[INFO] 19/Aug/2020 14:12:05 - Mobile Security Framework v3.1.2 Beta
[INFO] 19/Aug/2020 14:12:05 - 
API Key read from environment variable
[INFO] 19/Aug/2020 14:12:05 - OS: Linux
[INFO] 19/Aug/2020 14:12:05 - Platform: Linux-3.10.0-957.27.2.el7.x86_64-x86_64-with-glibc2.29
[INFO] 19/Aug/2020 14:12:05 - Dist: ubuntu 20.04 focal
[INFO] 19/Aug/2020 14:12:05 - MobSF Basic Environment Check
[INFO] 19/Aug/2020 14:12:05 - Checking for Update.
  __  __       _    ____  _____       _____  _ 
REST API Key: 45ccbf14aca709d874da62fb5ffba096012eed2c09cfc4718e7ce59364f6082e
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / |
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \ | |
 | |  | | (_) | |_) |__) |  _|  \ V / ___) || |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)_|

[INFO] 19/Aug/2020 14:12:05 - Mobile Security Framework v3.1.2 Beta
[INFO] 19/Aug/2020 14:12:05 - 
API Key read from environment variable
[INFO] 19/Aug/2020 14:12:05 - OS: Linux
[INFO] 19/Aug/2020 14:12:05 - Platform: Linux-3.10.0-957.27.2.el7.x86_64-x86_64-with-glibc2.29
[INFO] 19/Aug/2020 14:12:05 - Dist: ubuntu 20.04 focal
[INFO] 19/Aug/2020 14:12:05 - MobSF Basic Environment Check
[INFO] 19/Aug/2020 14:12:05 - Checking for Update.

 59 21.9M    0     0   59 13.0M      0  53.9M --:--:-- --:--:-- --:--:-- 53.9M[INFO] 19/Aug/2020 14:12:05 - No updates available.
[INFO] 19/Aug/2020 14:12:05 - MIME Type: application/octet-stream FILE: app-patient_dev-release.apk
[INFO] 19/Aug/2020 14:12:05 - Performing Static Analysis of Android APK

100 21.9M    0   108  100 21.9M    200  40.7M --:--:-- --:--:-- --:--:-- 40.7M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0[INFO] 19/Aug/2020 14:12:05 - 
API Key read from environment variable
[ERROR] 19/Aug/2020 14:12:05 - Internal Server Error: /api/v1/scan
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/Mobile-Security-Framework-MobSF/MobSF/views/helpers.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/root/Mobile-Security-Framework-MobSF/MobSF/views/api/rest_api.py", line 100, in api_scan
    return response
UnboundLocalError: local variable 'response' referenced before assignment

100 73397    0 73338  100    59   918k    756 --:--:-- --:--:-- --:--:--  918k
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="robots" content="NONE,NOARCHIVE">
  <title>UnboundLocalError
          at /api/v1/scan</title>
  <style type="text/css">
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font:small sans-serif; background-color:#fff; color:#000; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; }
    h2 { margin-bottom:.8em; }
    h3 { margin:1em 0 .5em 0; }
    h4 { margin:0 0 .5em 0; font-weight: normal; }
    code, pre { font-size: 100%; white-space: pre-wrap; }
    table { border:1px solid #ccc; border-collapse: collapse; width:100%; background:white; }
    tbody td, tbody th { vertical-align:top; padding:2px 3px; }
    thead th {
      padding:1px 6px 1px 3px; background:#fefefe; text-align:left;
      font-weight:normal; font-size:11px; border:1px solid #ddd;
    }
    tbody th { width:12em; text-align:right; color:#666; padding-right:.5em; }
    table.vars { margin:5px 0 2px 40px; }
    table.vars td, table.req td { font-family:monospace; }
    table td.code { width:100%; }
    table td.code pre { overflow:hidden; }
    table.source th { color:#666; }
    table.source td { font-family:monospace; white-space:pre; border-bottom:1px solid #eee; }
    ul.traceback { list-style-type:none; color: #222; }
    ul.traceback li.frame { padding-bottom:1em; color:#4f4f4f; }
    ul.traceback li.user { background-color:#e0e0e0; color:#000 }
    div.context { padding:10px 0; overflow:hidden; }
    div.context ol { padding-left:30px; margin:0 10px; list-style-position: inside; }
    div.context ol li { font-family:monospace; white-space:pre; color:#777; cursor:pointer; padding-left: 2px; }
    div.context ol li pre { display:inline; }
    div.context ol.context-line li { color:#464646; background-color:#dfdfdf; padding: 3px 2px; }
    div.context ol.context-line li span { position:absolute; right:32px; }
    .user div.context ol.context-line li { background-color:#bbb; color:#000; }
    .user div.context ol li { color:#666; }
    div.commands { margin-left: 40px; }
    div.commands a { color:#555; text-decoration:none; }
    .user div.commands a { color: black; }
    #summary { background: #ffc; }
    #summary h2 { font-weight: normal; color: #666; }
    #explanation { background:#eee; }
    #template, #template-not-exist { background:#f6f6f6; }
    #template-not-exist ul { margin: 0 0 10px 20px; }
    #template-not-exist .postmortem-section { margin-bottom: 3px; }
    #unicode-hint { background:#eee; }
    #traceback { background:#eee; }
    #requestinfo { background:#f6f6f6; padding-left:120px; }
    #summary table { border:none; background:transparent; }
    #requestinfo h2, #requestinfo h3 { position:relative; margin-left:-100px; }
    #requestinfo h3 { margin-bottom:-1em; }
    .error { background: #ffc; }
    .specific { color:#cc3300; font-weight:bold; }
    h2 span.commands { font-size:.7em; font-weight:normal; }
    span.commands a:link {color:#5E5694;}
    pre.exception_value { font-family: sans-serif; color: #575757; font-size: 1.5em; margin: 10px 0 10px 0; }
    .append-bottom { margin-bottom: 10px; }
    .fname { user-select: all; }
  </style>
  
  <script>
    function hideAll(elems) {
      for (var e = 0; e < elems.length; e++) {
        elems[e].style.display = 'none';
      }
    }
    window.onload = function() {
      hideAll(document.querySelectorAll('table.vars'));
      hideAll(document.querySelectorAll('ol.pre-context'));
      hideAll(document.querySelectorAll('ol.post-context'));
      hideAll(document.querySelectorAll('div.pastebin'));
    }
    function toggle() {
      for (var i = 0; i < arguments.length; i++) {
        var e = document.getElementById(arguments[i]);
        if (e) {
          e.style.display = e.style.display == 'none' ? 'block': 'none';
        }
      }
      return false;
    }
    function varToggle(link, id) {
      toggle('v' + id);
      var s = link.getElementsByTagName('span')[0];
      var uarr = String.fromCharCode(0x25b6);
      var darr = String.fromCharCode(0x25bc);
      s.textContent = s.textContent == uarr ? darr : uarr;
      return false;
    }
    function switchPastebinFriendly(link) {
      s1 = "Switch to copy-and-paste view";
      s2 = "Switch back to interactive view";
      link.textContent = link.textContent.trim() == s1 ? s2: s1;
      toggle('browserTraceback', 'pastebinTraceback');
      return false;
    }
  </script>
  
</head>
<body>
<div id="summary">
  <h1>UnboundLocalError
       at /api/v1/scan</h1>
  <pre class="exception_value">local variable &#x27;response&#x27; referenced before assignment</pre>
  <table class="meta">

    <tr>
      <th>Request Method:</th>
      <td>POST</td>
    </tr>
    <tr>
      <th>Request URL:</th>
      <td>http://localhost:8000/api/v1/scan</td>
    </tr>

    <tr>
      <th>Django Version:</th>
      <td>3.1</td>
    </tr>

    <tr>
      <th>Exception Type:</th>
      <td>UnboundLocalError</td>
    </tr>


    <tr>
      <th>Exception Value:</th>
      <td><pre>local variable &#x27;response&#x27; referenced before assignment</pre></td>
    </tr>


    <tr>
      <th>Exception Location:</th>
      <td><span class="fname">/root/Mobile-Security-Framework-MobSF/MobSF/views/api/rest_api.py</span>, line 100, in api_scan</td>
    </tr>

    <tr>
      <th>Python Executable:</th>
      <td>/usr/bin/python3</td>
    </tr>
    <tr>
      <th>Python Version:</th>
      <td>3.8.2</td>
    </tr>
    <tr>
      <th>Python Path:</th>
      <td><pre>[&#x27;/root/Mobile-Security-Framework-MobSF&#x27;,
 &#x27;/usr/local/bin&#x27;,
 &#x27;/usr/lib/python38.zip&#x27;,
 &#x27;/usr/lib/python3.8&#x27;,
 &#x27;/usr/lib/python3.8/lib-dynload&#x27;,
 &#x27;/usr/local/lib/python3.8/dist-packages&#x27;,
 &#x27;/usr/lib/python3/dist-packages&#x27;]</pre></td>
    </tr>
    <tr>
      <th>Server time:</th>
      <td>Wed, 19 Aug 2020 14:12:05 +0000</td>
    </tr>
  </table>
</div>




<div id="traceback">
  <h2>Traceback <span class="commands"><a href="#" onclick="return switchPastebinFriendly(this);">
    Switch to copy-and-paste view</a></span>
  </h2>
  <div id="browserTraceback">
    <ul class="traceback">
      
        
        <li class="frame django">
          <code class="fname">/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py</code>, line 47, in inner

          
            <div class="context" id="c140714746477504">
              
                <ol start="40" class="pre-context" id="pre140714746477504">
                
                  <li onclick="toggle('pre140714746477504', 'post140714746477504')"><pre>                response = await sync_to_async(response_for_exception)(request, exc)</pre></li>
                
                  <li onclick="toggle('pre140714746477504', 'post140714746477504')"><pre>            return response</pre></li>
                
                  <li onclick="toggle('pre140714746477504', 'post140714746477504')"><pre>        return inner</pre></li>
                
                  <li onclick="toggle('pre140714746477504', 'post140714746477504')"><pre>    else:</pre></li>
                
                  <li onclick="toggle('pre140714746477504', 'post140714746477504')"><pre>        @wraps(get_response)</pre></li>
                
                  <li onclick="toggle('pre140714746477504', 'post140714746477504')"><pre>        def inner(request):</pre></li>
                
                  <li onclick="toggle('pre140714746477504', 'post140714746477504')"><pre>            try:</pre></li>
                
                </ol>
              
              <ol start="47" class="context-line">
                <li onclick="toggle('pre140714746477504', 'post140714746477504')"><pre>                response = get_response(request)</pre> <span>…</span></li>
              </ol>
              
                <ol start='48' class="post-context" id="post140714746477504">
                  
                  <li onclick="toggle('pre140714746477504', 'post140714746477504')"><pre>            except Exception as exc:</pre></li>
                  
                  <li onclick="toggle('pre140714746477504', 'post140714746477504')"><pre>                response = response_for_exception(request, exc)</pre></li>
                  
                  <li onclick="toggle('pre140714746477504', 'post140714746477504')"><pre>            return response</pre></li>
                  
                  <li onclick="toggle('pre140714746477504', 'post140714746477504')"><pre>        return inner</pre></li>
                  
                  <li onclick="toggle('pre140714746477504', 'post140714746477504')"><pre></pre></li>
                  
                  <li onclick="toggle('pre140714746477504', 'post140714746477504')"><pre></pre></li>
                  
              </ol>
              
            </div>
          

          
            <div class="commands">
                
                    <a href="#" onclick="return varToggle(this, '140714746477504')"><span>&#x25b6;</span> Local vars</a>
                
            </div>
            <table class="vars" id="v140714746477504">
              <thead>
                <tr>
                  <th>Variable</th>
                  <th>Value</th>
                </tr>
              </thead>
              <tbody>
                
                  <tr>
                    <td>exc</td>
                    <td class="code"><pre>UnboundLocalError(&quot;local variable &#x27;response&#x27; referenced before assignment&quot;)</pre></td>
                  </tr>
                
                  <tr>
                    <td>get_response</td>
                    <td class="code"><pre>&lt;bound method BaseHandler._get_response of &lt;django.core.handlers.wsgi.WSGIHandler object at 0x7ffab44de400&gt;&gt;</pre></td>
                  </tr>
                
                  <tr>
                    <td>request</td>
                    <td class="code"><pre>&lt;WSGIRequest: POST &#x27;/api/v1/scan&#x27;&gt;</pre></td>
                  </tr>
                
              </tbody>
            </table>
          
        </li>
      
        
        <li class="frame django">
          <code class="fname">/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py</code>, line 179, in _get_response

          
            <div class="context" id="c140714746477632">
              
                <ol start="172" class="pre-context" id="pre140714746477632">
                
                  <li onclick="toggle('pre140714746477632', 'post140714746477632')"><pre></pre></li>
                
                  <li onclick="toggle('pre140714746477632', 'post140714746477632')"><pre>        if response is None:</pre></li>
                
                  <li onclick="toggle('pre140714746477632', 'post140714746477632')"><pre>            wrapped_callback = self.make_view_atomic(callback)</pre></li>
                
                  <li onclick="toggle('pre140714746477632', 'post140714746477632')"><pre>            # If it is an asynchronous view, run it in a subthread.</pre></li>
                
                  <li onclick="toggle('pre140714746477632', 'post140714746477632')"><pre>            if asyncio.iscoroutinefunction(wrapped_callback):</pre></li>
                
                  <li onclick="toggle('pre140714746477632', 'post140714746477632')"><pre>                wrapped_callback = async_to_sync(wrapped_callback)</pre></li>
                
                  <li onclick="toggle('pre140714746477632', 'post140714746477632')"><pre>            try:</pre></li>
                
                </ol>
              
              <ol start="179" class="context-line">
                <li onclick="toggle('pre140714746477632', 'post140714746477632')"><pre>                response = wrapped_callback(request, *callback_args, **callback_kwargs)</pre> <span>…</span></li>
              </ol>
              
                <ol start='180' class="post-context" id="post140714746477632">
                  
                  <li onclick="toggle('pre140714746477632', 'post140714746477632')"><pre>            except Exception as e:</pre></li>
                  
                  <li onclick="toggle('pre140714746477632', 'post140714746477632')"><pre>                response = self.process_exception_by_middleware(e, request)</pre></li>
                  
                  <li onclick="toggle('pre140714746477632', 'post140714746477632')"><pre>                if response is None:</pre></li>
                  
                  <li onclick="toggle('pre140714746477632', 'post140714746477632')"><pre>                    raise</pre></li>
                  
                  <li onclick="toggle('pre140714746477632', 'post140714746477632')"><pre></pre></li>
                  
                  <li onclick="toggle('pre140714746477632', 'post140714746477632')"><pre>        # Complain if the view returned None (a common error).</pre></li>
                  
              </ol>
              
            </div>
          

          
            <div class="commands">
                
                    <a href="#" onclick="return varToggle(this, '140714746477632')"><span>&#x25b6;</span> Local vars</a>
                
            </div>
            <table class="vars" id="v140714746477632">
              <thead>
                <tr>
                  <th>Variable</th>
                  <th>Value</th>
                </tr>
              </thead>
              <tbody>



```

**Comment by ajinabraham** [comment]
`response` is not set only if scan type is not provided correctly
https://github.com/inm-certi/mobsf-action/blob/master/entrypoint.sh#L75

**Comment by inm-certi** [comment]
Oh.. thanks...

In fact I did check "scan type"
```
mobSFAnalyse input_file_name: dev/mobile_app/build/app/outputs/apk/patient_dev/release/app-patient_dev-release.apk, scan_type: apk, output_file_name: mobsf-report
```

but with your statement I reviewed the code and found this: https://github.com/inm-certi/mobsf-action/blob/af2e2e1905cf49b7753d3a6f145554951d203c71/entrypoint.sh#L68

**Comment by ajinabraham** [comment]
I am going to clone the repo and see if I can fix it.

**Comment by inm-certi** [comment]
There is no need! I could fix it fixing that line (uppercase)

It is working now!

**Comment by inm-certi** [comment]
Well.. I fixed the lowercase issue and it didn't crash anymore, but something still have a problem.

```
[ERROR] 20/Aug/2020 19:14:59 - Hash match failed or Invalid file extension or file type
[ERROR] 20/Aug/2020 19:14:59 - Internal Server Error: /api/v1/scan

100   131    0    69  100    62  13800  12400 --:--:-- --:--:-- --:--:-- 32750
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0[INFO] 20/Aug/2020 19:14:59 - 
API Key read from environment variable
[WARNING] 20/Aug/2020 19:14:59 - Not Found: /api/v1/report_json

100    67    0    30  100    37   3333   4111 --:--:-- --:--:-- --:--:--  8375
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0[INFO] 20/Aug/2020 19:14:59 - 
API Key read from environment variable
[WARNING] 20/Aug/2020 19:14:59 - Not Found: /api/v1/download_pdf
```

**Comment by ajinabraham** [comment]
` Hash match failed or Invalid file extension or file type` make sure you are passing correct parameters.

**Comment by ajinabraham** [comment]
In headless mode, we will disable all the Web UI routes and enable only REST API routes that are protected by API key. Hence suggested using a random key. I know Github action runners are short-lived and probably not exposed to the internet, but as a best practice, it's recommended to use random API keys.

**Comment by inm-certi** [comment]
Sure, I agree. I've updated the code on this PR: https://github.com/inm-certi/mobsf-action/pull/1

**Comment by ajinabraham** [comment]
Thanks for https://github.com/marketplace/actions/github-action-for-mobsf I will document this

**Comment by ajinabraham** [comment]
MobSF is available in Gitlab as well
https://gitlab.com/gitlab-org/security-products/analyzers/mobsf
