### ISSUE TITLE
windows setup.bat failed 

### ISSUE THREAD

**Issue by Cr-cm** [MobSF/Mobile-Security-Framework-MobSF#1519]
[INFO] 20/Aug/2020 16:37:49 - No updates available.
[INFO] 20/Aug/2020 16:37:51 -
  __  __       _    ____  _____       _____  _
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / |
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \ | |
 | |  | | (_) | |_) |__) |  _|  \ V / ___) || |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)_|

[INFO] 20/Aug/2020 16:37:51 - Mobile Security Framework v3.1.2 Beta
REST API Key: fbe3ed5e322e76db5992bd142af0c469124bbefe07bc1d488bede4ae2408cfb1
[INFO] 20/Aug/2020 16:37:51 - OS: Windows
[INFO] 20/Aug/2020 16:37:51 - Platform: Windows-2012ServerR2-6.3.9600-SP0
[INFO] 20/Aug/2020 16:37:51 - Dist:
[INFO] 20/Aug/2020 16:37:51 - MobSF Basic Environment Check
[WARNING] 20/Aug/2020 16:37:51 - Dynamic Analysis related functions will not wor
k.
Make sure a Genymotion Android VM/Android Studio Emulator is running before perf
orming Dynamic Analysis.
[INFO] 20/Aug/2020 16:37:51 - Checking for Update.
Operations to perform:
  Synchronize unmigrated apps: DynamicAnalyzer, MalwareAnalyzer, MobSF, messages
, staticfiles
  Apply all migrations: StaticAnalyzer, auth, contenttypes, sessions
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  No migrations to apply.
[ERROR] 20/Aug/2020 16:37:59 - Cannot Check for updates.
Traceback (most recent call last):
  File "E:\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\urllib3
\response.py", line 436, in _error_catcher
    yield
  File "E:\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\urllib3
\response.py", line 518, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Python38\lib\http\client.py", line 458, in read
    n = self.readinto(b)
  File "C:\Python38\lib\http\client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "C:\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\request
s\models.py", line 751, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "E:\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\urllib3
\response.py", line 575, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "E:\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\urllib3
\response.py", line 540, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "E:\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\urllib3
\response.py", line 441, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='raw.githubusercon
tent.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Mobile-Security-Framework-MobSF-master\MobSF\utils.py", line 110, in
check_update
    response = requests.get(github_url, timeout=5,
  File "E:\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\request
s\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "E:\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\request
s\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\request
s\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\request
s\sessions.py", line 685, in send
    r.content
  File "E:\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\request
s\models.py", line 829, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "E:\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\request
s\models.py", line 758, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercon
tent.com', port=443): Read timed out.
[*] Reading config file..
[*] Creating other folders...
[*] Downloading nuget..
[*] Saving to File nuget.exe

**Comment by Cr-cm** [comment]
After above ，another error ：

[*] Reading config file..
[*] Creating other folders...
[*] Downloading nuget..
[*] Saving to File nuget.exe
Traceback (most recent call last):
  File "manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "E:\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\django\
core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "E:\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\django\
core\management\__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "E:\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\django\
conf\__init__.py", line 83, in __getattr__
    self._setup(name)
  File "E:\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\django\
conf\__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "E:\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\django\
conf\__init__.py", line 177, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\Mobile-Security-Framework-MobSF-master\MobSF\settings.py", line 108,
in <module>
    SECRET_KEY = first_run(SECRET_FILE, BASE_DIR, MobSF_HOME)
  File "E:\Mobile-Security-Framework-MobSF-master\MobSF\init.py", line 31, in fi
rst_run
    windows_config_local(mobsf_home)
  File "E:\Mobile-Security-Framework-MobSF-master\install\windows\setup.py", lin
e 58, in windows_config_local
    install_locally(path)
  File "E:\Mobile-Security-Framework-MobSF-master\install\windows\setup.py", lin
e 404, in install_locally
    tools_nuget()
  File "E:\Mobile-Security-Framework-MobSF-master\install\windows\setup.py", lin
e 154, in tools_nuget
    nuget_file_local.write(bytes(nuget_file.read()))
  File "C:\Python38\lib\http\client.py", line 471, in read
    s = self._safe_read(self.length)
  File "C:\Python38\lib\http\client.py", line 614, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(5455411 bytes read, 1122349 more expe
cted)
[INFO] 20/Aug/2020 16:46:12 -
  __  __       _    ____  _____       _____  _
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / |
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \ | |
 | |  | | (_) | |_) |__) |  _|  \ V / ___) || |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)_|

[INFO] 20/Aug/2020 16:46:12 - Mobile Security Framework v3.1.2 Beta
REST API Key: fbe3ed5e322e76db5992bd142af0c469124bbefe07bc1d488bede4ae2408cfb1
[INFO] 20/Aug/2020 16:46:12 - OS: Windows
[INFO] 20/Aug/2020 16:46:12 - Platform: Windows-2012ServerR2-6.3.9600-SP0
[INFO] 20/Aug/2020 16:46:12 - Dist:
[INFO] 20/Aug/2020 16:46:12 - MobSF Basic Environment Check

**Comment by superpoussin22** [comment]
1) use python 3.7
2) reduce path like e:\MobSF\
3) check your internet connectivity
4) use slack channel to discuss installation issue
