### ISSUE TITLE
Getting Manifest file some errors 

### ISSUE THREAD

**Issue by Cr-cm** [MobSF/Mobile-Security-Framework-MobSF#1520]
Error
Raised when run() is called with check=True and the process returns a non-zero exit status. Attributes: cmd, returncode, stdout, stderr, output

Command '['C:\\Program Files\\Java\\jdk1.8.0_261\\bin\\java.exe', '-jar', 'E:/MOBSF/StaticAnalyzer/tools\\baksmali-2.4.0.jar', 'list', 'classes', 'E:/MOBSF/uploads/23d01b8102ba1d52cbbdcc52c017ee28\\classes.dex']' returned non-zero exit status 1.

[ERROR] 20/Aug/2020 19:27:19 - Getting Manifest file
Traceback (most recent call last):
  File "E:\MOBSF\StaticAnalyzer\views\android\manifest_analysis.py", line 901, i
n get_manifest_file
    subprocess.check_output(args)
  File "C:\Python37\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "C:\Python37\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Program Files\\Java\\jdk1.8.0_261\
\bin\\java.exe', '-jar', 'E:/MOBSF/StaticAnalyzer/tools\\apktool_2.4.1.jar', '--
match-original', '--frame-path', 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\3',
 '-f', '-s', 'd', 'E:/MOBSF/uploads/23d01b8102ba1d52cbbdcc52c017ee28/23d01b8102b
a1d52cbbdcc52c017ee28.apk', '-o', 'E:/MOBSF/uploads/23d01b8102ba1d52cbbdcc52c017
ee28/apktool_out']' returned non-zero exit status 1.
[ERROR] 20/Aug/2020 19:27:19 - Reading Manifest file
Traceback (most recent call last):
  File "E:\MOBSF\StaticAnalyzer\views\android\manifest_analysis.py", line 847, i
n read_manifest
    if is_file_exists(manifest):
  File "E:\MOBSF\MobSF\utils.py", line 294, in is_file_exists
    if os.path.isfile(file_path):
  File "C:\Python37\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneT
ype
[INFO] 20/Aug/2020 19:27:19 - Parsing AndroidManifest.xml
[ERROR] 20/Aug/2020 19:27:19 - apktool failed to extract AndroidManifest.xml or
parsing failed
Traceback (most recent call last):
  File "E:\MOBSF\StaticAnalyzer\views\android\manifest_analysis.py", line 41, in
 get_manifest
    manifest = minidom.parseString(dat)
  File "C:\Python37\lib\xml\dom\minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "C:\Python37\lib\xml\dom\expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "C:\Python37\lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
TypeError: a bytes-like object is required, not 'NoneType'
[WARNING] 20/Aug/2020 19:27:19 - Using Fake XML to continue the Analysis
WARNING:androguard.axml:invalid decoded string length

[ERROR] 20/Aug/2020 19:28:01 - [ERROR] Trackers DB Update
Traceback (most recent call last):
  File "e:\mobsf\venv\lib\site-packages\urllib3\response.py", line 436, in _erro
r_catcher
    yield
  File "e:\mobsf\venv\lib\site-packages\urllib3\response.py", line 766, in read_
chunked
    chunk = self._handle_chunk(amt)
  File "e:\mobsf\venv\lib\site-packages\urllib3\response.py", line 710, in _hand
le_chunk
    value = self._fp._safe_read(amt)
  File "C:\Python37\lib\http\client.py", line 620, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "C:\Python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Python37\lib\ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Python37\lib\ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\mobsf\venv\lib\site-packages\requests\models.py", line 751, in genera
te
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "e:\mobsf\venv\lib\site-packages\urllib3\response.py", line 571, in strea
m
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "e:\mobsf\venv\lib\site-packages\urllib3\response.py", line 792, in read_
chunked
    self._original_response.close()
  File "C:\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "e:\mobsf\venv\lib\site-packages\urllib3\response.py", line 441, in _erro
r_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='reports.exodus-pr
ivacy.eu.org', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\MOBSF\MobSF\utils.py", line 419, in update_local_db
    verify=verify)
  File "e:\mobsf\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "e:\mobsf\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "e:\mobsf\venv\lib\site-packages\requests\sessions.py", line 530, in requ
est
    resp = self.send(prep, **send_kwargs)
  File "e:\mobsf\venv\lib\site-packages\requests\sessions.py", line 685, in send

    r.content
  File "e:\mobsf\venv\lib\site-packages\requests\models.py", line 829, in conten
t
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "e:\mobsf\venv\lib\site-packages\requests\models.py", line 758, in genera
te
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='reports.exodus-pr
ivacy.eu.org', port=443): Read timed out.
[INFO] 20/Aug/2020 19:28:02 - Detecting Trackers
[ERROR] 20/Aug/2020 19:28:03 - Error Performing Static Analysis
Traceback (most recent call last):
  File "E:\MOBSF\StaticAnalyzer\views\android\static_analyzer.py", line 188, in
static_analyzer
    tracker_res = tracker.get_trackers()
  File "E:\MOBSF\MalwareAnalyzer\views\Trackers.py", line 175, in get_trackers
    trackers = self.detect_trackers()
  File "E:\MOBSF\MalwareAnalyzer\views\Trackers.py", line 167, in detect_tracker
s
    eclasses = self.get_embedded_classes()
  File "E:\MOBSF\MalwareAnalyzer\views\Trackers.py", line 124, in get_embedded_c
lasses
    args, universal_newlines=True).splitlines()
  File "C:\Python37\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "C:\Python37\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Program Files\\Java\\jdk1.8.0_261\
\bin\\java.exe', '-jar', 'E:/MOBSF/StaticAnalyzer/tools\\baksmali-2.4.0.jar', 'l
ist', 'classes', 'E:/MOBSF/uploads/23d01b8102ba1d52cbbdcc52c017ee28\\classes.dex
']' returned non-zero exit status 1.
[ERROR] 20/Aug/2020 19:28:03 - Command '['C:\\Program Files\\Java\\jdk1.8.0_261\
\bin\\java.exe', '-jar', 'E:/MOBSF/StaticAnalyzer/tools\\baksmali-2.4.0.jar', 'l
ist', 'classes', 'E:/MOBSF/uploads/23d01b8102ba1d52cbbdcc52c017ee28\\classes.dex
']' returned non-zero exit status 1.
[ERROR] 20/Aug/2020 19:28:03 - Internal Server Error: /StaticAnalyzer/
ERROR:django.request:Internal Server Error: /StaticAnalyzer/

**Comment by Cr-cm** [comment]
Error
Raised when run() is called with check=True and the process returns a non-zero exit status. Attributes: cmd, returncode, stdout, stderr, output

Command '['C:\Program Files\Java\jdk1.8.0_261\bin\java.exe', '-jar', 'E:/MOBSF/StaticAnalyzer/tools\baksmali-2.4.0.jar', 'list', 'classes', 'E:/MOBSF/uploads/23d01b8102ba1d52cbbdcc52c017ee28\classes.dex']' returned non-zero exit status 1.

detail errors see above

**Comment by ajinabraham** [comment]
Looks to me like you have issues with your host OS.
Can you share the APK?  Also it might be possible that apktool we use internally doesnot support the APK.

I would recommend you to try the docker image once.

**Comment by Cr-cm** [comment]
in docker works fine but in window 2012 R2 it not work！

**Comment by ajinabraham** [comment]
I guess it is due to setup issues. Closing this here. Feel free to join our slack channel for support/queries.
