### ISSUE TITLE
setup.bat fails with ERROR: Failed building wheel for lief

### ISSUE THREAD

**Issue by doug-precocity** [MobSF/Mobile-Security-Framework-MobSF#1586]
After installing prerequisites according to https://mobsf.github.io/docs/#/requirements,
running setup.bat fails with the following error:

 ```
ERROR: Command errored out with exit status 1:
     command: 'd:\mobsf\mobile-security-framework-mobsf\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\doug\\AppData\\Local\\Temp\\pip-install-t5rja70n\\lief\\setup.py'"'"'; __file__='"'"'C:\\Users\\doug\\AppData\\Local\\Temp\\pip-install-t5rja70n\\lief\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\doug\AppData\Local\Temp\pip-record-m8wauamr\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\mobsf\mobile-security-framework-mobsf\venv\include\site\python3.8\lief'
         cwd: C:\Users\doug\AppData\Local\Temp\pip-install-t5rja70n\lief\
    Complete output (58 lines):
    0.10.1
    running install
    running build
    running build_ext
    cmake C:\Users\doug\AppData\Local\Temp\pip-install-t5rja70n\lief -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\doug\AppData\Local\Temp\pip-install-t5rja70n\lief\build\temp.win-amd64-3.8 -DPYTHON_EXECUTABLE=d:\mobsf\mobile-security-framework-mobsf\venv\scripts\python.exe -DLIEF_PYTHON_API=on -DCMAKE_BUILD_TYPE=Release -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\doug\AppData\Local\Temp\pip-install-t5rja70n\lief\build\temp.win-amd64-3.8 -DLIEF_USE_CRT_RELEASE=MT -A x64
    -- Building for: Visual Studio 16 2019
    -- LIEF_CRT: /MT
    -- Using Release VC++ CRT: MT
    -- Could NOT find cppcheck (missing: CPPCHECK_EXECUTABLE CPPCHECK_POSSIBLEERROR_ARG CPPCHECK_UNUSEDFUNC_ARG CPPCHECK_STYLE_ARG CPPCHECK_INCLUDEPATH_ARG CPPCHECK_QUIET_ARG)
    -- Selecting Windows SDK version 8.1 to target Windows 6.3.9600.
    -- The C compiler identification is unknown
    -- The CXX compiler identification is unknown
    CMake Error at CMakeLists.txt:30 (project):
      No CMAKE_C_COMPILER could be found.



    CMake Error at CMakeLists.txt:30 (project):
      No CMAKE_CXX_COMPILER could be found.



    -- Configuring incomplete, errors occurred!
    See also "C:/Users/doug/AppData/Local/Temp/pip-install-t5rja70n/lief/build/temp.win-amd64-3.8/Release/CMakeFiles/CMakeOutput.log".
    See also "C:/Users/doug/AppData/Local/Temp/pip-install-t5rja70n/lief/build/temp.win-amd64-3.8/Release/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\doug\AppData\Local\Temp\pip-install-t5rja70n\lief\setup.py", line 363, in <module>
        setup(
      File "d:\mobsf\mobile-security-framework-mobsf\venv\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\doug\AppData\Local\Programs\Python\Python38\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\doug\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\doug\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "d:\mobsf\mobile-security-framework-mobsf\venv\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\doug\AppData\Local\Programs\Python\Python38\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\doug\AppData\Local\Programs\Python\Python38\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\doug\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\doug\AppData\Local\Programs\Python\Python38\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\doug\AppData\Local\Programs\Python\Python38\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\doug\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\doug\AppData\Local\Temp\pip-install-t5rja70n\lief\setup.py", line 78, in run
        self.build_extension(ext)
      File "C:\Users\doug\AppData\Local\Temp\pip-install-t5rja70n\lief\setup.py", line 202, in build_extension
        subprocess.check_call(configure_cmd, cwd=self.build_temp, env=env)
      File "C:\Users\doug\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\doug\\AppData\\Local\\Temp\\pip-install-t5rja70n\\lief', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\doug\\AppData\\Local\\Temp\\pip-install-t5rja70n\\lief\\build\\temp.win-amd64-3.8', '-DPYTHON_EXECUTABLE=d:\\\mobsf\\mobile-security-framework-mobsf\\venv\\scripts\\python.exe', '-DLIEF_PYTHON_API=on', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\doug\\AppData\\Local\\Temp\\pip-install-t5rja70n\\lief\\build\\temp.win-amd64-3.8', '-DLIEF_USE_CRT_RELEASE=MT', '-A', 'x64']' returned non-zero exit status 1.
```

It looks like this is due to a known issue in lief: https://github.com/lief-project/LIEF/issues/471
That issue seems to be fixed in lief nightlies.  Is there a way to specify a different version of lief in the MobSF setup?

**Comment by ajinabraham** [comment]
Please use Python 3.7 as mentioned in docs

**Comment by ttimasdf** [comment]
We could manually install lief nightly build. Make the following change and re-run `setup.bat`. Tested on Windows 10 + Python 
3.8.3.

```diff
diff --git a/requirements.txt b/requirements.txt
index 0ce466e9..f6893e53 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -19,7 +19,7 @@ asn1crypto==1.4.0
 oscrypto==1.2.1
 distro==1.5.0
 IP2Location==8.5.1
-lief==0.10.1
+lief>=0.10.1
 http-tools==2.0.0
 libsast==1.3.6
 # Do not update the following
diff --git a/setup.bat b/setup.bat
index 1f6919b0..e0cfe47e 100644
--- a/setup.bat
+++ b/setup.bat
@@ -56,6 +56,7 @@ where python >nul 2>&1 && (
   )

   echo [INSTALL] Installing Requirements
+  pip install --index-url https://lief.quarkslab.com/packages lief==0.11.0.dev0
   pip install --no-cache-dir -r requirements.txt

   echo [INSTALL] Clean Up
```
