### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by yeraldinm** [MobSF/Mobile-Security-Framework-MobSF#1592]
## ENVIRONMENT

```
OS and Version:Windows 10
Python Version:python38
MobSF Version:opensecurity/mobile-security-framework-mobsf
```

## EXPLANATION OF THE ISSUE

```
running docker image fails throwing a type error.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step
docker pull opensecurity/mobile-security-framework-mobsf
2. This is the second step
docker run -it --rm -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest

```

## LOG FILE

Creating MobSF Home Directory

Traceback (most recent call last):

File "/root/Mobile-Security-Framework-MobSF/MobSF/init.py", line 122, in get_mobsf_home

shutil.copytree(src, sig_dir)

File "/usr/lib/python3.8/shutil.py", line 554, in copytree

return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,

File "/usr/lib/python3.8/shutil.py", line 455, in _copytree

os.makedirs(dst, exist_ok=dirs_exist_ok)

File "/usr/lib/python3.8/os.py", line 223, in makedirs

mkdir(name, mode)

FileExistsError: [Errno 17] File exists: '/root/.MobSF/signatures/'

Traceback (most recent call last):

File "/root/Mobile-Security-Framework-MobSF/manage.py", line 18, in <module>

execute_from_command_line(sys.argv)

File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line

utility.execute()

File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 345, in execute

settings.INSTALLED_APPS

File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 83, in __getattr__

self._setup(name)

File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 70, in _setup

self._wrapped = Settings(settings_module)

File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 177, in __init__

mod = importlib.import_module(self.SETTINGS_MODULE)

File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module

return _bootstrap._gcd_import(name[level:], package, level)

File "<frozen importlib._bootstrap>", line 1014, in _gcd_import

File "<frozen importlib._bootstrap>", line 991, in _find_and_load

File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

File "<frozen importlib._bootstrap_external>", line 783, in exec_module

File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

File "/root/Mobile-Security-Framework-MobSF/MobSF/settings.py", line 46, in <module>

LOG_DIR = os.path.join(MobSF_HOME, 'logs/')

File "/usr/lib/python3.8/posixpath.py", line 76, in join

a = os.fspath(a)

TypeError: expected str, bytes or os.PathLike object, not NoneType

Creating MobSF Home Directory

Traceback (most recent call last):

File "/root/Mobile-Security-Framework-MobSF/MobSF/init.py", line 122, in get_mobsf_home

shutil.copytree(src, sig_dir)

File "/usr/lib/python3.8/shutil.py", line 554, in copytree

return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,

File "/usr/lib/python3.8/shutil.py", line 455, in _copytree

os.makedirs(dst, exist_ok=dirs_exist_ok)

File "/usr/lib/python3.8/os.py", line 223, in makedirs

mkdir(name, mode)

FileExistsError: [Errno 17] File exists: '/root/.MobSF/signatures/'

Traceback (most recent call last):

File "/root/Mobile-Security-Framework-MobSF/manage.py", line 18, in <module>

execute_from_command_line(sys.argv)

File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line

utility.execute()

File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 345, in execute

settings.INSTALLED_APPS

File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 83, in __getattr__

self._setup(name)

File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 70, in _setup

self._wrapped = Settings(settings_module)

File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 177, in __init__

mod = importlib.import_module(self.SETTINGS_MODULE)

File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module

return _bootstrap._gcd_import(name[level:], package, level)

File "<frozen importlib._bootstrap>", line 1014, in _gcd_import

File "<frozen importlib._bootstrap>", line 991, in _find_and_load

File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

File "<frozen importlib._bootstrap_external>", line 783, in exec_module

File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

File "/root/Mobile-Security-Framework-MobSF/MobSF/settings.py", line 46, in <module>

LOG_DIR = os.path.join(MobSF_HOME, 'logs/')

File "/usr/lib/python3.8/posixpath.py", line 76, in join

a = os.fspath(a)

TypeError: expected str, bytes or os.PathLike object, not NoneType

Creating MobSF Home Directory

Traceback (most recent call last):

File "/root/Mobile-Security-Framework-MobSF/MobSF/init.py", line 122, in get_mobsf_home

shutil.copytree(src, sig_dir)

File "/usr/lib/python3.8/shutil.py", line 554, in copytree

return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,

File "/usr/lib/python3.8/shutil.py", line 455, in _copytree

os.makedirs(dst, exist_ok=dirs_exist_ok)

File "/usr/lib/python3.8/os.py", line 223, in makedirs

mkdir(name, mode)

FileExistsError: [Errno 17] File exists: '/root/.MobSF/signatures/'

Traceback (most recent call last):

File "/root/Mobile-Security-Framework-MobSF/manage.py", line 18, in <module>

execute_from_command_line(sys.argv)

File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line

utility.execute()

File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 345, in execute

settings.INSTALLED_APPS

File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 83, in __getattr__

self._setup(name)

File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 70, in _setup

self._wrapped = Settings(settings_module)

File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 177, in __init__

mod = importlib.import_module(self.SETTINGS_MODULE)

File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module

return _bootstrap._gcd_import(name[level:], package, level)

File "<frozen importlib._bootstrap>", line 1014, in _gcd_import

File "<frozen importlib._bootstrap>", line 991, in _find_and_load

File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

File "<frozen importlib._bootstrap_external>", line 783, in exec_module

File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

File "/root/Mobile-Security-Framework-MobSF/MobSF/settings.py", line 46, in <module>

LOG_DIR = os.path.join(MobSF_HOME, 'logs/')

File "/usr/lib/python3.8/posixpath.py", line 76, in join

a = os.fspath(a)

TypeError: expected str, bytes or os.PathLike object, not NoneType

Creating MobSF Home Directory

Traceback (most recent call last):

File "/root/Mobile-Security-Framework-MobSF/MobSF/init.py", line 122, in get_mobsf_home

shutil.copytree(src, sig_dir)

File "/usr/lib/python3.8/shutil.py", line 554, in copytree

return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,

File "/usr/lib/python3.8/shutil.py", line 455, in _copytree

os.makedirs(dst, exist_ok=dirs_exist_ok)

File "/usr/lib/python3.8/os.py", line 223, in makedirs

mkdir(name, mode)

FileExistsError: [Errno 17] File exists: '/root/.MobSF/signatures/'

Traceback (most recent call last):

File "/root/Mobile-Security-Framework-MobSF/manage.py", line 18, in <module>

execute_from_command_line(sys.argv)

File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line

utility.execute()

File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 345, in execute

settings.INSTALLED_APPS

File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 83, in __getattr__

self._setup(name)

File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 70, in _setup

self._wrapped = Settings(settings_module)

File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 177, in __init__

mod = importlib.import_module(self.SETTINGS_MODULE)

File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module

return _bootstrap._gcd_import(name[level:], package, level)

File "<frozen importlib._bootstrap>", line 1014, in _gcd_import

File "<frozen importlib._bootstrap>", line 991, in _find_and_load

File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

File "<frozen importlib._bootstrap_external>", line 783, in exec_module

File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

File "/root/Mobile-Security-Framework-MobSF/MobSF/settings.py", line 46, in <module>

LOG_DIR = os.path.join(MobSF_HOME, 'logs/')

File "/usr/lib/python3.8/posixpath.py", line 76, in join

a = os.fspath(a)

TypeError: expected str, bytes or os.PathLike object, not NoneType

[INFO] 16/Nov/2020 01:46:22 -

__ __ _ ____ _____ _____ _

| \/ | ___ | |__/ ___|| ___|_ _|___ / / |

| |\/| |/ _ \| '_ \___ \| |_ \ \ / / |_ \ | |

| | | | (_) | |_) |__) | _| \ V / ___) || |

|_| |_|\___/|_.__/____/|_| \_/ |____(_)_|

[INFO] 16/Nov/2020 01:46:22 - Mobile Security Framework v3.1.9 Beta

REST API Key: e8e3765a26fd4ba7ddf00fca1222bf37d01f753b9f89f718cc39750065d2f301

[INFO] 16/Nov/2020 01:46:22 - OS: Linux

[INFO] 16/Nov/2020 01:46:22 - Platform: Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.29

[INFO] 16/Nov/2020 01:46:22 - Dist: ubuntu 20.04 focal

[INFO] 16/Nov/2020 01:46:22 - MobSF Basic Environment Check

[INFO] 16/Nov/2020 01:46:22 - Checking for Update.

No changes detected

[INFO] 16/Nov/2020 01:46:22 - No updates available.

Creating MobSF Home Directory

Traceback (most recent call last):

File "/root/Mobile-Security-Framework-MobSF/MobSF/init.py", line 122, in get_mobsf_home

shutil.copytree(src, sig_dir)

File "/usr/lib/python3.8/shutil.py", line 554, in copytree

return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,

File "/usr/lib/python3.8/shutil.py", line 455, in _copytree

os.makedirs(dst, exist_ok=dirs_exist_ok)

File "/usr/lib/python3.8/os.py", line 223, in makedirs

mkdir(name, mode)

FileExistsError: [Errno 17] File exists: '/root/.MobSF/signatures/'

Traceback (most recent call last):

File "manage.py", line 18, in <module>

execute_from_command_line(sys.argv)

File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line

utility.execute()

File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 345, in execute

settings.INSTALLED_APPS

File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 83, in __getattr__

self._setup(name)

File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 70, in _setup

self._wrapped = Settings(settings_module)

File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 177, in __init__

mod = importlib.import_module(self.SETTINGS_MODULE)

File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module

return _bootstrap._gcd_import(name[level:], package, level)

File "<frozen importlib._bootstrap>", line 1014, in _gcd_import

File "<frozen importlib._bootstrap>", line 991, in _find_and_load

File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

File "<frozen importlib._bootstrap_external>", line 783, in exec_module

File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

File "/root/Mobile-Security-Framework-MobSF/MobSF/settings.py", line 46, in <module>

LOG_DIR = os.path.join(MobSF_HOME, 'logs/')

File "/usr/lib/python3.8/posixpath.py", line 76, in join

a = os.fspath(a)

TypeError: expected str, bytes or os.PathLike object, not NoneType

[2020-11-16 01:46:22 +0000] [18] [INFO] Starting gunicorn 20.0.4

[2020-11-16 01:46:22 +0000] [18] [INFO] Listening at: http://0.0.0.0:8000 (18)

[2020-11-16 01:46:22 +0000] [18] [INFO] Using worker: threads

[2020-11-16 01:46:22 +0000] [20] [INFO] Booting worker with pid: 20

Creating MobSF Home Directory

Traceback (most recent call last):

File "/root/Mobile-Security-Framework-MobSF/MobSF/init.py", line 122, in get_mobsf_home

shutil.copytree(src, sig_dir)

File "/usr/lib/python3.8/shutil.py", line 554, in copytree

return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,

File "/usr/lib/python3.8/shutil.py", line 455, in _copytree

os.makedirs(dst, exist_ok=dirs_exist_ok)

File "/usr/lib/python3.8/os.py", line 223, in makedirs

mkdir(name, mode)

FileExistsError: [Errno 17] File exists: '/root/.MobSF/signatures/'

[2020-11-16 01:46:22 +0000] [20] [ERROR] Exception in worker process

Traceback (most recent call last):

File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker

worker.init_process()

File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/gthread.py", line 92, in init_process

super().init_process()

File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 119, in init_process

self.load_wsgi()

File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 144, in load_wsgi

self.wsgi = self.app.wsgi()

File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi

self.callable = self.load()

File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load

return self.load_wsgiapp()

File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp

return util.import_app(self.app_uri)

File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 358, in import_app

mod = importlib.import_module(module)

File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module

return _bootstrap._gcd_import(name[level:], package, level)

File "<frozen importlib._bootstrap>", line 1014, in _gcd_import

File "<frozen importlib._bootstrap>", line 991, in _find_and_load

File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

File "<frozen importlib._bootstrap_external>", line 783, in exec_module

File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

File "/root/Mobile-Security-Framework-MobSF/MobSF/wsgi.py", line 20, in <module>

application = WhiteNoise(get_wsgi_application(),

File "/usr/local/lib/python3.8/dist-packages/django/core/wsgi.py", line 12, in get_wsgi_application

django.setup(set_prefix=False)

File "/usr/local/lib/python3.8/dist-packages/django/__init__.py", line 19, in setup

configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)

File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 83, in __getattr__

self._setup(name)

File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 70, in _setup

self._wrapped = Settings(settings_module)

File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 177, in __init__

mod = importlib.import_module(self.SETTINGS_MODULE)

File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module

return _bootstrap._gcd_import(name[level:], package, level)

File "<frozen importlib._bootstrap>", line 1014, in _gcd_import

File "<frozen importlib._bootstrap>", line 991, in _find_and_load

File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

File "<frozen importlib._bootstrap_external>", line 783, in exec_module

File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

File "/root/Mobile-Security-Framework-MobSF/MobSF/settings.py", line 46, in <module>

LOG_DIR = os.path.join(MobSF_HOME, 'logs/')

File "/usr/lib/python3.8/posixpath.py", line 76, in join

a = os.fspath(a)

TypeError: expected str, bytes or os.PathLike object, not NoneType

[2020-11-16 01:46:22 +0000] [20] [INFO] Worker exiting (pid: 20)

[2020-11-16 01:46:22 +0000] [18] [INFO] Shutting down: Master

[2020-11-16 01:46:22 +0000] [18] [INFO] Reason: Worker failed to boot.
![Capture](https://user-images.githubusercontent.com/23369125/99204836-db19ce80-2784-11eb-875f-af1eb345753f.PNG)

**Comment by superpoussin22** [comment]
can you try last version ?

**Comment by ajinabraham** [comment]
Fixed in latest master and docker image
