### ISSUE TITLE
Still Assert require SQLite 3.8.3 or higher after upgraded to sqlite3.33.0

### ISSUE THREAD

**Issue by weamylady2** [MobSF/Mobile-Security-Framework-MobSF#1594]
`[ERROR]` 16/Nov/2020 07:20:37 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/data/Mobile-Security-Framework-MobSF-master/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/data/Mobile-Security-Framework-MobSF-master/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/data/Mobile-Security-Framework-MobSF-master/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/data/Mobile-Security-Framework-MobSF-master/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/data/Mobile-Security-Framework-MobSF-master/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 215, in get_new_connection
    create_deterministic_function('django_date_extract', 2, _sqlite_datetime_extract)
sqlite3.NotSupportedError: deterministic=True requires SQLite 3.8.3 or higher

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/android/static_analyzer.py", line 105, in static_analyzer
    if db_entry.exists() and rescan == '0':
  File "/data/Mobile-Security-Framework-MobSF-master/venv/lib/python3.8/site-packages/django/db/models/query.py", line 809, in exists
    return self.query.has_results(using=self.db)
  File "/data/Mobile-Security-Framework-MobSF-master/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 535, in has_results
    return compiler.has_results()
  File "/data/Mobile-Security-Framework-MobSF-master/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1126, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/data/Mobile-Security-Framework-MobSF-master/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
    cursor = self.connection.cursor()
  File "/data/Mobile-Security-Framework-MobSF-master/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/data/Mobile-Security-Framework-MobSF-master/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/data/Mobile-Security-Framework-MobSF-master/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/data/Mobile-Security-Framework-MobSF-master/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/data/Mobile-Security-Framework-MobSF-master/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/data/Mobile-Security-Framework-MobSF-master/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/data/Mobile-Security-Framework-MobSF-master/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/data/Mobile-Security-Framework-MobSF-master/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/data/Mobile-Security-Framework-MobSF-master/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/data/Mobile-Security-Framework-MobSF-master/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/data/Mobile-Security-Framework-MobSF-master/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 215, in get_new_connection
    create_deterministic_function('django_date_extract', 2, _sqlite_datetime_extract)
django.db.utils.NotSupportedError: deterministic=True requires SQLite 3.8.3 or higher
[ERROR] 16/Nov/2020 07:20:37 - deterministic=True requires SQLite 3.8.3 or higher
[ERROR] 16/Nov/2020 07:20:37 - Internal Server Error: /StaticAnalyzer/`

python version: 3.8.3
OS: Red Hat 4.8.5-39

I upgraded sqlite3 to 3.33.0 and it shows the right version in python command 'sqlite3.sqlite_version' as '3.33.0'
I run 'run.sh' and it start successfully. When I open the website and upload an apk to analyze, the console print this error and the website prompt 'deterministic=True requires SQLite 3.8.3 or higher'.
I have tried reboot the OS, reinstall MobsF, reinstall Python3, and it won't work.

**Comment by ajinabraham** [comment]
Please use slack channel for support.

**Comment by liuyoyi** [comment]
how to resolve?
@weamylady2
