### ISSUE TITLE
MobSFying Android Runtime Connection failed

### ISSUE THREAD

**Issue by abhishobhit** [MobSF/Mobile-Security-Framework-MobSF#1604]
## ENVIRONMENT

```
OS and Version:Windows 10
Python Version:3.7.9
MobSF Version:3.1.9
```

## EXPLANATION OF THE ISSUE

```
I know this issue has asked many times but after going through all this i'm unable to solve it. I'm trying to do dynamic analysis using genymotion google pixel (9.0-API 28) in windows 10 machine when trying to run it gives me following error.

MobSFying Android Runtime
Connection failed

IP Port and Identifier
192.168.104.101:5555 
```

## LOG FILE

```
[INFO] 25/Nov/2020 11:11:04 - Mobile Security Framework v3.1.9 Beta
REST API Key: 0eb76d4d52d6cbab1ce1ccb07ced63a9eb4fabdbd61ab8ad1063fb7c089ff3d9
[INFO] 25/Nov/2020 11:11:04 - OS: Windows
[INFO] 25/Nov/2020 11:11:04 - Platform: Windows-10-10.0.18362-SP0
[INFO] 25/Nov/2020 11:11:04 - Dist:
[INFO] 25/Nov/2020 11:11:04 - MobSF Basic Environment Check
[INFO] 25/Nov/2020 11:11:04 - Checking for Update.
[INFO] 25/Nov/2020 11:11:04 - No updates available.
[INFO] 25/Nov/2020 11:11:29 - MobSFying Android instance
[INFO] 25/Nov/2020 11:11:34 - ADB Restarted
[INFO] 25/Nov/2020 11:11:34 - Waiting for 2 seconds...
[INFO] 25/Nov/2020 11:11:36 - Connecting to Android 192.168.104.101:5555
[INFO] 25/Nov/2020 11:11:36 - Waiting for 2 seconds...
[INFO] 25/Nov/2020 11:11:38 - Restarting ADB Daemon as root
[INFO] 25/Nov/2020 11:11:38 - Waiting for 2 seconds...
[INFO] 25/Nov/2020 11:11:40 - Reconnecting to Android Device
[INFO] 25/Nov/2020 11:11:40 - Waiting for 2 seconds...
[INFO] 25/Nov/2020 11:11:43 - Found Genymotion x86 Android VM
[INFO] 25/Nov/2020 11:11:43 - Remounting
[INFO] 25/Nov/2020 11:11:43 - Performing System check
[INFO] 25/Nov/2020 11:11:43 - Android API Level identified as 28
[INFO] 25/Nov/2020 11:11:43 - Android Version identified as 9.0
[INFO] 25/Nov/2020 11:11:43 - Android OS architecture identified as x86
[INFO] 25/Nov/2020 11:11:43 - Copying frida server for x86
[ERROR] 25/Nov/2020 13:15:13 - Failed to MobSFy Android Instance
Traceback (most recent call last):
  File "C:\Users\windows-PC\Mobile-Security-Framework-MobSF\DynamicAnalyzer\views\android\environment.py", line 473, in mobsfy_init
    self.mobsf_agents_setup('frida')
  File "C:\Users\windows-PC\Mobile-Security-Framework-MobSF\DynamicAnalyzer\views\android\environment.py", line 483, in mobsf_agents_setup
    self.install_mobsf_ca('install')
  File "C:\Users\windows-PC\Mobile-Security-Framework-MobSF\DynamicAnalyzer\views\android\environment.py", line 178, in install_mobsf_ca
    mobsf_ca = get_ca_file()
  File "C:\Users\windows-PC\Mobile-Security-Framework-MobSF\DynamicAnalyzer\tools\webproxy.py", line 67, in get_ca_file
    from mitmproxy import ctx
  File "c:\users\windows-pc\mobile-security-framework-mobsf\venv\lib\site-packages\mitmproxy\ctx.py", line 2, in <module>
    import mitmproxy.master
  File "c:\users\windows-pc\mobile-security-framework-mobsf\venv\lib\site-packages\mitmproxy\master.py", line 7, in <module>
    from mitmproxy import addonmanager
  File "c:\users\windows-pc\mobile-security-framework-mobsf\venv\lib\site-packages\mitmproxy\addonmanager.py", line 8, in <module>
    from mitmproxy import eventsequence
  File "c:\users\windows-pc\mobile-security-framework-mobsf\venv\lib\site-packages\mitmproxy\eventsequence.py", line 5, in <module>
    from mitmproxy import http
  File "c:\users\windows-pc\mobile-security-framework-mobsf\venv\lib\site-packages\mitmproxy\http.py", line 7, in <module>
    from mitmproxy.net import http
  File "c:\users\windows-pc\mobile-security-framework-mobsf\venv\lib\site-packages\mitmproxy\net\http\__init__.py", line 1, in <module>
    from mitmproxy.net.http.request import Request
  File "c:\users\windows-pc\mobile-security-framework-mobsf\venv\lib\site-packages\mitmproxy\net\http\request.py", line 9, in <module>
    from mitmproxy.net.http import message
  File "c:\users\windows-pc\mobile-security-framework-mobsf\venv\lib\site-packages\mitmproxy\net\http\message.py", line 6, in <module>
    from mitmproxy.net.http import encoding
  File "c:\users\windows-pc\mobile-security-framework-mobsf\venv\lib\site-packages\mitmproxy\net\http\encoding.py", line 11, in <module>
    import brotli
  File "c:\users\windows-pc\mobile-security-framework-mobsf\venv\lib\site-packages\brotli.py", line 8, in <module>
    import _brotli
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by ajinabraham** [comment]
The module is not installed properly, Please use slack for support
