### ISSUE TITLE
issues installing MobSF - breaks on lief and apkid

### ISSUE THREAD

**Issue by bensh** [MobSF/Mobile-Security-Framework-MobSF#1612]
## ENVIRONMENT

```
OS and Version: macOS 10.14.6
Python Version: 3.9.0

$ . venv/bin/activate
(venv) $ python --version
Python 3.9.0

MobSF Version: latest 
```

## EXPLANATION OF THE ISSUE

```
run ./setup.sh
runs fine until setup of lief

Running setup.py install for lief ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/ben/Documents/ios/iosation/tools/Mobile-Security-Framework-MobSF/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/w8/bgzlm3zd5_b7jk2mzv6500zc0000gn/T/pip-install-18j5ifja/lief_6f81ab72cf254557b662b931db819fde/setup.py'"'"'; __file__='"'"'/private/var/folders/w8/bgzlm3zd5_b7jk2mzv6500zc0000gn/T/pip-install-18j5ifja/lief_6f81ab72cf254557b662b931db819fde/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/w8/bgzlm3zd5_b7jk2mzv6500zc0000gn/T/pip-record-gd00u7ks/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ben/Documents/ios/iosation/tools/Mobile-Security-Framework-MobSF/venv/include/site/python3.9/lief
         cwd: /private/var/folders/w8/bgzlm3zd5_b7jk2mzv6500zc0000gn/T/pip-install-18j5ifja/lief_6f81ab72cf254557b662b931db819fde/
    Complete output (128 lines):
    0.10.1
    running install
    running build
    running build_ext
    cmake /private/var/folders/w8/bgzlm3zd5_b7jk2mzv6500zc0000gn/T/pip-install-18j5ifja/lief_6f81ab72cf254557b662b931db819fde -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/w8/bgzlm3zd5_b7jk2mzv6500zc0000gn/T/pip-install-18j5ifja/lief_6f81ab72cf254557b662b931db819fde/build -DPYTHON_EXECUTABLE=/Users/ben/Documents/ios/iosation/tools/Mobile-Security-Framework-MobSF/venv/bin/python3 -DLIEF_PYTHON_API=on -DCMAKE_BUILD_TYPE=Release
    -- Could NOT find cppcheck (missing: CPPCHECK_EXECUTABLE CPPCHECK_POSSIBLEERROR_ARG CPPCHECK_UNUSEDFUNC_ARG CPPCHECK_STYLE_ARG CPPCHECK_INCLUDEPATH_ARG CPPCHECK_QUIET_ARG)
    -- The C compiler identification is AppleClang 11.0.0.11000033
    -- The CXX compiler identification is AppleClang 11.0.0.11000033
    -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
    -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
    -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- LIEF 0.10.0
    -- ccache: ON
    -- Enable JSON support
    -- Enable Frozen (C++14 support)
    -- Performing Test C_SUPPORTS_WALL
    -- Performing Test C_SUPPORTS_WALL - Success
    -- Performing Test CXX_SUPPORTS_WALL
    -- Performing Test CXX_SUPPORTS_WALL - Success
    -- Performing Test C_SUPPORTS_WEXTRA
    -- Performing Test C_SUPPORTS_WEXTRA - Success
    -- Performing Test CXX_SUPPORTS_WEXTRA
    -- Performing Test CXX_SUPPORTS_WEXTRA - Success
    -- Performing Test C_SUPPORTS_WPEDANTIC
    -- Performing Test C_SUPPORTS_WPEDANTIC - Success
    -- Performing Test CXX_SUPPORTS_WPEDANTIC
    -- Performing Test CXX_SUPPORTS_WPEDANTIC - Success
    -- Performing Test C_SUPPORTS_NO_STACK_PROTECTOR
    -- Performing Test C_SUPPORTS_NO_STACK_PROTECTOR - Success
    -- Performing Test CXX_SUPPORTS_NO_STACK_PROTECTOR
    -- Performing Test CXX_SUPPORTS_NO_STACK_PROTECTOR - Success
    -- Performing Test C_SUPPORTS_OMIT_FRAME_POINTER
    -- Performing Test C_SUPPORTS_OMIT_FRAME_POINTER - Success
    -- Performing Test CXX_SUPPORTS_OMIT_FRAME_POINTER
    -- Performing Test CXX_SUPPORTS_OMIT_FRAME_POINTER - Success
    -- Performing Test C_SUPPORTS_NO_STRICT_ALIASING
    -- Performing Test C_SUPPORTS_NO_STRICT_ALIASING - Success
    -- Performing Test CXX_SUPPORTS_NO_STRICT_ALIASING
    -- Performing Test CXX_SUPPORTS_NO_STRICT_ALIASING - Success
    -- Performing Test C_SUPPORTS_EXCEPTION
    -- Performing Test C_SUPPORTS_EXCEPTION - Success
    -- Performing Test CXX_SUPPORTS_EXCEPTION
    -- Performing Test CXX_SUPPORTS_EXCEPTION - Success
    -- Performing Test C_SUPPORTS_VISIBILITY
    -- Performing Test C_SUPPORTS_VISIBILITY - Success
    -- Performing Test CXX_SUPPORTS_VISIBILITY
    -- Performing Test CXX_SUPPORTS_VISIBILITY - Success
    -- Performing Test C_SUPPORTS_NO_EXPANSION_TO_DEFINED
    -- Performing Test C_SUPPORTS_NO_EXPANSION_TO_DEFINED - Success
    -- Performing Test CXX_SUPPORTS_NO_EXPANSION_TO_DEFINED
    -- Performing Test CXX_SUPPORTS_NO_EXPANSION_TO_DEFINED - Success
    -- Performing Test C_SUPPORTS_DIAGNOSTICS_COLOR
    -- Performing Test C_SUPPORTS_DIAGNOSTICS_COLOR - Success
    -- Performing Test CXX_SUPPORTS_DIAGNOSTICS_COLOR
    -- Performing Test CXX_SUPPORTS_DIAGNOSTICS_COLOR - Success
    -- Performing Test C_SUPPORTS_COLOR_DIAGNOSTICS
    -- Performing Test C_SUPPORTS_COLOR_DIAGNOSTICS - Success
    -- Performing Test CXX_SUPPORTS_COLOR_DIAGNOSTICS
    -- Performing Test CXX_SUPPORTS_COLOR_DIAGNOSTICS - Success
    -- Could NOT find cppcheck (missing: CPPCHECK_EXECUTABLE CPPCHECK_POSSIBLEERROR_ARG CPPCHECK_UNUSEDFUNC_ARG CPPCHECK_STYLE_ARG CPPCHECK_INCLUDEPATH_ARG CPPCHECK_QUIET_ARG)
    -- Configuration Types:
    -- Build Types: Release
    -- Found PythonInterp: /Users/ben/Documents/ios/iosation/tools/Mobile-Security-Framework-MobSF/venv/bin/python3 (found suitable version "3.9", minimum required is "3.5")
    -- Found PythonLibs: /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib
    -- Python version: 3.5
    -- Python lib:     /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib
    -- Python include: /usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/include/python3.9
    -- Python interpreter: /Users/ben/Documents/ios/iosation/tools/Mobile-Security-Framework-MobSF/venv/bin/python3
    -- Performing Test C_SUPPORTS_NO_MACRO_REDEFINED
    -- Performing Test C_SUPPORTS_NO_MACRO_REDEFINED - Success
    -- Performing Test CXX_SUPPORTS_NO_MACRO_REDEFINED
    -- Performing Test CXX_SUPPORTS_NO_MACRO_REDEFINED - Success
    -- Performing Test C_SUPPORTS_NO_DEPRECATED_DECLARATIONS
    -- Performing Test C_SUPPORTS_NO_DEPRECATED_DECLARATIONS - Success
    -- Performing Test CXX_SUPPORTS_NO_DEPRECATED_DECLARATIONS
    -- Performing Test CXX_SUPPORTS_NO_DEPRECATED_DECLARATIONS - Success
    -- Performing Test HAS_ANSI
    -- Performing Test HAS_ANSI - Success
    CMake Error at CMakeLists.txt:541 (add_subdirectory):
      add_subdirectory given source
      "/private/var/folders/w8/bgzlm3zd5_b7jk2mzv6500zc0000gn/T/pip-install-18j5ifja/lief_6f81ab72cf254557b662b931db819fde/package"
      which is not an existing directory.
    
    
    -- Configuring incomplete, errors occurred!
    See also "/private/var/folders/w8/bgzlm3zd5_b7jk2mzv6500zc0000gn/T/pip-install-18j5ifja/lief_6f81ab72cf254557b662b931db819fde/build/temp.macosx-10.14-x86_64-3.9/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/w8/bgzlm3zd5_b7jk2mzv6500zc0000gn/T/pip-install-18j5ifja/lief_6f81ab72cf254557b662b931db819fde/setup.py", line 363, in <module>
        setup(
      File "/Users/ben/Documents/ios/iosation/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.9/site-packages/setuptools/__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/ben/Documents/ios/iosation/tools/Mobile-Security-Framework-MobSF/venv/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/install.py", line 546, in run
        self.run_command('build')
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/w8/bgzlm3zd5_b7jk2mzv6500zc0000gn/T/pip-install-18j5ifja/lief_6f81ab72cf254557b662b931db819fde/setup.py", line 78, in run
        self.build_extension(ext)
      File "/private/var/folders/w8/bgzlm3zd5_b7jk2mzv6500zc0000gn/T/pip-install-18j5ifja/lief_6f81ab72cf254557b662b931db819fde/setup.py", line 202, in build_extension
        subprocess.check_call(configure_cmd, cwd=self.build_temp, env=env)
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/w8/bgzlm3zd5_b7jk2mzv6500zc0000gn/T/pip-install-18j5ifja/lief_6f81ab72cf254557b662b931db819fde', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/w8/bgzlm3zd5_b7jk2mzv6500zc0000gn/T/pip-install-18j5ifja/lief_6f81ab72cf254557b662b931db819fde/build', '-DPYTHON_EXECUTABLE=/Users/ben/Documents/ios/iosation/tools/Mobile-Security-Framework-MobSF/venv/bin/python3', '-DLIEF_PYTHON_API=on', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/ben/Documents/ios/iosation/tools/Mobile-Security-Framework-MobSF/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/w8/bgzlm3zd5_b7jk2mzv6500zc0000gn/T/pip-install-18j5ifja/lief_6f81ab72cf254557b662b931db819fde/setup.py'"'"'; __file__='"'"'/private/var/folders/w8/bgzlm3zd5_b7jk2mzv6500zc0000gn/T/pip-install-18j5ifja/lief_6f81ab72cf254557b662b931db819fde/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/w8/bgzlm3zd5_b7jk2mzv6500zc0000gn/T/pip-record-gd00u7ks/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ben/Documents/ios/iosation/tools/Mobile-Security-Framework-MobSF/venv/include/site/python3.9/lief Check the logs for full command output.
[INSTALL] Clean Up

```

**Comment by ajinabraham** [comment]
Python 3.9 is not supported

**Comment by bensh** [comment]
bit more info please? is there a workaround

**Comment by superpoussin22** [comment]
use python 3.7.X or Python 3.8.X  :) please use slack for such issue

**Comment by ajinabraham** [comment]
We have docs that clearly mention the requirements. Python 3.9 is not supported out of the box by some of the dependencies.The work around would be to troubleshoot and fix LIEF setup failure. Also github issues are not for support.
