### ISSUE TITLE
Error installing Mobsf in kali 2020

### ISSUE THREAD

**Issue by Subho-n5** [MobSF/Mobile-Security-Framework-MobSF#1622]
While checking the requirements using "pip install  -r requirements.txt" the following error was encountered:

Building wheel for lief (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-g062nrz6/lief_32b2cd673cc54408a59be7decfa196ab/setup.py'"'"'; __file__='"'"'/tmp/pip-install-g062nrz6/lief_32b2cd673cc54408a59be7decfa196ab/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-o06inprf                                                                       
       cwd: /tmp/pip-install-g062nrz6/lief_32b2cd673cc54408a59be7decfa196ab/                              
  Complete output (46 lines):                                                                             
  0.10.1                                                                                                  
  running bdist_wheel                                                                                     
  running build                                                                                           
  running build_ext                                                                                       
  Traceback (most recent call last):                                                                      
    File "/tmp/pip-install-g062nrz6/lief_32b2cd673cc54408a59be7decfa196ab/setup.py", line 72, in run      
      subprocess.check_output(['cmake', '--version'])                                                     
    File "/usr/lib/python3.9/subprocess.py", line 420, in check_output                                    
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,                                    
    File "/usr/lib/python3.9/subprocess.py", line 501, in run                                             
      with Popen(*popenargs, **kwargs) as process:                                                        
    File "/usr/lib/python3.9/subprocess.py", line 947, in __init__                                        
      self._execute_child(args, executable, preexec_fn, close_fds,                                        
    File "/usr/lib/python3.9/subprocess.py", line 1819, in _execute_child                                 
      raise child_exception_type(errno_num, err_msg, err_filename)                                        
  FileNotFoundError: [Errno 2] No such file or directory: 'cmake'                                         
                                                                                                          
  During handling of the above exception, another exception occurred:                                     
                                                                                                          
  Traceback (most recent call last):                                                                      
    File "<string>", line 1, in <module>                                                                  
    File "/tmp/pip-install-g062nrz6/lief_32b2cd673cc54408a59be7decfa196ab/setup.py", line 363, in <module>
      setup(                                                                                              
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup                      
      return distutils.core.setup(**attrs)                                                                
    File "/usr/lib/python3.9/distutils/core.py", line 148, in setup                                       
      dist.run_commands()                                                                                 
    File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands                                
      self.run_command(cmd)                                                                               
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command                                 
      cmd_obj.run()                                                                                       
    File "/usr/local/lib/python3.9/dist-packages/wheel/bdist_wheel.py", line 299, in run                  
      self.run_command('build')                                                                           
    File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command                                  
      self.distribution.run_command(command)                                                              
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command                                 
      cmd_obj.run()                                                                                       
    File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run                                
      self.run_command(cmd_name)                                                                          
    File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command                                  
      self.distribution.run_command(command)                                                              
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command                                 
      cmd_obj.run()                                                                                       
    File "/tmp/pip-install-g062nrz6/lief_32b2cd673cc54408a59be7decfa196ab/setup.py", line 74, in run      
      raise RuntimeError("CMake must be installed to build the following extensions: " +                  
  RuntimeError: CMake must be installed to build the following extensions: lief                           
  ----------------------------------------                                                                
  ERROR: Failed building wheel for lief

**Comment by superpoussin22** [comment]
python 3.9 is not supported

Please use slack channel for installation issue
