### ISSUE TITLE
cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by ETOCheney** [MobSF/Mobile-Security-Framework-MobSF#1646]
[INFO] 16/Jan/2021 09:36:59 - MIME Type: application/vnd.android.package-archive FILE: XXXX.apk
[INFO] 16/Jan/2021 09:36:59 - Performing Static Analysis of Android APK
[INFO] 16/Jan/2021 09:36:59 - Starting Analysis on : XXXX.apk
[INFO] 16/Jan/2021 09:36:59 - Generating Hashes
[INFO] 16/Jan/2021 09:36:59 - Unzipping
[INFO] 16/Jan/2021 09:37:01 - APK Extracted
[INFO] 16/Jan/2021 09:37:01 - Getting Hardcoded Certificates/Keystores
[INFO] 16/Jan/2021 09:37:01 - Getting AndroidManifest.xml from APK
[INFO] 16/Jan/2021 09:37:01 - Converting AXML to XML
Exception in thread "main" brut.androlib.AndrolibException: unsupported res type name for bags. Found: c
        at brut.androlib.res.data.value.ResValueFactory.bagFactory(ResValueFactory.java:118)
        at brut.androlib.res.decoder.ARSCDecoder.readComplexEntry(ARSCDecoder.java:350)
        at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:276)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:252)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:175)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:131)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:790)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
        at brut.androlib.Androlib.getResTable(Androlib.java:66)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:236)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
        at brut.apktool.Main.cmdDecode(Main.java:179)
        at brut.apktool.Main.main(Main.java:82)
[ERROR] 16/Jan/2021 09:37:02 - Getting Manifest file
Traceback (most recent call last):                                                                         
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/manifest_analysis.py", line 896, in get_manifest_apk                                                                                       
    subprocess.check_output(args)                                                                          
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output                                       
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,                                       
  File "/usr/lib/python3.8/subprocess.py", line 512, in run                                                
    raise CalledProcessError(retcode, process.args,                                                        
subprocess.CalledProcessError: Command '['/jdk-12/bin/java', '-jar', '/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/apktool_2.5.0.jar', '--match-original', '--frame-path', '/tmp', '-f', '-s', 'd', '/root/.MobSF/uploads/f74a06b2cae0321d10e582736e339573/f74a06b2cae0321d10e582736e339573.apk', '-o', '/root/.MobSF/uploads/f74a06b2cae0321d10e582736e339573/apktool_out']' returned non-zero exit status 1.                
[ERROR] 16/Jan/2021 09:37:02 - Parsing Manifest file
Traceback (most recent call last):                                                                         
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/manifest_analysis.py", line 42, in get_manifest                                                                                            
    mfile = Path(manifest_file)                                                                            
  File "/usr/lib/python3.8/pathlib.py", line 1038, in __new__                                              
    self = cls._from_parts(args, init=False)                                                               
  File "/usr/lib/python3.8/pathlib.py", line 679, in _from_parts                                           
    drv, root, parts = self._parse_args(args)                                                              
  File "/usr/lib/python3.8/pathlib.py", line 663, in _parse_args                                           
    a = os.fspath(a)                                                                                       
TypeError: expected str, bytes or os.PathLike object, not NoneType                                         
[ERROR] 16/Jan/2021 09:37:02 - Error Performing Static Analysis
Traceback (most recent call last):                                                                         
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/static_analyzer.py", line 132, in static_analyzer                                                                                          
    mani_file, mani_xml = get_manifest(                                                                    
TypeError: cannot unpack non-iterable NoneType object                                                      
[ERROR] 16/Jan/2021 09:37:02 - cannot unpack non-iterable NoneType object
[ERROR] 16/Jan/2021 09:37:02 - Internal Server Error: /static_analyzer/

**Comment by ajinabraham** [comment]
Please share the APK to debug this further.

**Comment by safebaseline** [comment]
I have a same problem,so i want update v3.2.8

**Comment by ajinabraham** [comment]
Please share the APK over slack channel for troubleshooting.

**Comment by ajinabraham** [comment]
10 days response time is over

**Comment by nilkashid** [comment]
I am also facing similar issue:

**Comment by nilkashid** [comment]
Similar kind of issue: 

```
Exception in thread "main" brut.androlib.AndrolibException: Invalid chunk type: expected=0x00000200, got=0x00000203
	at brut.androlib.res.decoder.ARSCDecoder.checkChunkType(ARSCDecoder.java:544)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:88)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:790)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
	at brut.androlib.Androlib.getResTable(Androlib.java:66)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:236)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
	at brut.apktool.Main.cmdDecode(Main.java:179)
	at brut.apktool.Main.main(Main.java:82)
[ERROR] 24/May/2021 03:42:15 - Getting Manifest file
Traceback (most recent call last):
  File "/Users/dummy/Documents/mobsf_git/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/manifest_analysis.py", line 905, in get_manifest_apk
    subprocess.check_output(args)  # lgtm [py/command-line-injection] md5 hash
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['java', '-jar', '/Users/dummy/Documents/mobsf_git/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/tools/apktool_2.5.0.jar', '--match-original', '--frame-path', '/var/folders/m8/_t4md2hs705d_75crlfxc0lmj1b8kj/T', '-f', '-s', 'd', '/Users/dummy/.MobSF/uploads/903450346e90fabdc6f22be544b2f415/903450346e90fabdc6f22be544b2f415.apk', '-o', '/Users/dummy/.MobSF/uploads/903450346e90fabdc6f22be544b2f415/apktool_out']' returned non-zero exit status 1.
[ERROR] 24/May/2021 03:42:15 - Parsing Manifest file
Traceback (most recent call last):
  File "/Users/dummy/Documents/mobsf_git/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/manifest_analysis.py", line 41, in get_manifest
    mfile = Path(manifest_file)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1041, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pathlib.py", line 682, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pathlib.py", line 666, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[ERROR] 24/May/2021 03:42:15 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/Users/dummy/Documents/mobsf_git/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 158, in static_analyzer
    mani_file, mani_xml = get_manifest(
TypeError: cannot unpack non-iterable NoneType object
[ERROR] 24/May/2021 03:42:15 - cannot unpack non-iterable NoneType object
[ERROR] 24/May/2021 03:42:15 - Internal Server Error: /static_analyzer/

```

Using V3.4.4Beta. For simple APK's it is working fine. But for other complex projects and APK's it is giving the above issue.

**Comment by idrees1991** [comment]
I am getting this error. can anyone help me?

Error
Inappropriate argument type.

cannot unpack non-iterable NoneType object

**Comment by renitto** [comment]
Same Issue - Error, Inappropriate argument type. cannot unpack non-iterable NoneType object

[ERROR] 21/Feb/2022 15:55:30 - Getting Manifest file
Traceback (most recent call last):
  File "/Users/renittojose/Desktop/ProEchoes/Security/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/manifest_analysis.py", line 905, in get_manifest_apk
    subprocess.check_output(args)  # lgtm [py/command-line-injection] md5 hash
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['java', '-jar', '/Users/renittojose/Desktop/ProEchoes/Security/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/tools/apktool_2.6.0.jar', '--match-original', '--frame-path', '/var/folders/36/j3jgg4111cgf_c1p4p0zpn4h0000gn/T', '-f', '-s', 'd', '/Users/renittojose/.MobSF/uploads/dd9e90f29a2ceb47634ab6763e61d692/dd9e90f29a2ceb47634ab6763e61d692.apk', '-o', '/Users/renittojose/.MobSF/uploads/dd9e90f29a2ceb47634ab6763e61d692/apktool_out']' returned non-zero exit status 1.
[ERROR] 21/Feb/2022 15:55:30 - Parsing Manifest file
Traceback (most recent call last):
  File "/Users/renittojose/Desktop/ProEchoes/Security/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/manifest_analysis.py", line 41, in get_manifest
    mfile = Path(manifest_file)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1041, in __new__
    self = cls._from_parts(args, init=False)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/pathlib.py", line 682, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/pathlib.py", line 666, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[ERROR] 21/Feb/2022 15:55:30 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/Users/renittojose/Desktop/ProEchoes/Security/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 163, in static_analyzer
    mani_file, mani_xml = get_manifest(
TypeError: cannot unpack non-iterable NoneType object
[ERROR] 21/Feb/2022 15:55:30 - cannot unpack non-iterable NoneType object
[ERROR] 21/Feb/2022 15:55:30 - Internal Server Error: /static_analyzer/

**Comment by safebaseline** [comment]
已收到

**Comment by rive-n** [comment]
Same error over here.
