### ISSUE TITLE
sqlite3.OperationalError: no such table: StaticAnalyzer_recentscansdb

### ISSUE THREAD

**Issue by blshkv** [MobSF/Mobile-Security-Framework-MobSF#1649]
I have just installed a fresh mobsf 3.2.6, configured USE_HOME and tried to upload a random APK file. The execution failed with the following error:

```
[INFO] 18/Jan/2021 07:05:52 - MIME Type: application/vnd.android.package-archive FILE: hi_3.3_14May.apk
[ERROR] 18/Jan/2021 07:05:53 - Adding Scan URL to Database
Traceback (most recent call last):                                                                                          
  File "/usr/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute                                 
    return self.cursor.execute(sql, params)                                                                                 
  File "/usr/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute                          
    return Database.Cursor.execute(self, query, params)                                                                     
sqlite3.OperationalError: no such table: StaticAnalyzer_recentscansdb                                                       

The above exception was the direct cause of the following exception:                                                        

Traceback (most recent call last):                                                                                          
  File "/usr/lib/python3.8/site-packages/mobsf/MobSF/views/scanning.py", line 18, in add_to_recent_scan                     
    if not db_obj.exists():                                                                                                 
  File "/usr/lib/python3.8/site-packages/django/db/models/query.py", line 809, in exists                                    
    return self.query.has_results(using=self.db)                                                                            
  File "/usr/lib/python3.8/site-packages/django/db/models/sql/query.py", line 535, in has_results                           
    return compiler.has_results()                                                                                           
  File "/usr/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1126, in has_results                       
    return bool(self.execute_sql(SINGLE))                                                                                   
  File "/usr/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql                       
    cursor.execute(sql, params)                                                                                             
  File "/usr/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute                                  
    return super().execute(sql, params)                                                                                     
  File "/usr/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute                                  
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)                                     
  File "/usr/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers                   
    return executor(sql, params, many, context)                                                                             
  File "/usr/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute                                 
    return self.cursor.execute(sql, params)                                                                                 
  File "/usr/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__                                          
    raise dj_exc_value.with_traceback(traceback) from exc_value                                                             
  File "/usr/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute                                 
    return self.cursor.execute(sql, params)                                                                                 
  File "/usr/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute                          
    return Database.Cursor.execute(self, query, params)                                                                     
django.db.utils.OperationalError: no such table: StaticAnalyzer_recentscansdb                                               
[INFO] 18/Jan/2021 07:05:53 - Performing Static Analysis of Android APK
[INFO] 18/Jan/2021 07:05:53 - Starting Analysis on : hi_3.3_14May.apk
[ERROR] 18/Jan/2021 07:05:53 - Error Performing Static Analysis
Traceback (most recent call last):                                                                                          
  File "/usr/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: StaticAnalyzer_staticanalyzerandroid

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 120, in static_analyzer
    if db_entry.exists() and rescan == '0':
  File "/usr/lib/python3.8/site-packages/django/db/models/query.py", line 809, in exists
    return self.query.has_results(using=self.db)
  File "/usr/lib/python3.8/site-packages/django/db/models/sql/query.py", line 535, in has_results
    return compiler.has_results()
  File "/usr/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1126, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/usr/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: StaticAnalyzer_staticanalyzerandroid
[ERROR] 18/Jan/2021 07:05:53 - no such table: StaticAnalyzer_staticanalyzerandroid
[ERROR] 18/Jan/2021 07:05:53 - Internal Server Error: /static_analyzer/

```

Any idea what's going on?

**Comment by blshkv** [comment]
I removed .MobSF directory and tried again. The directory was re-created and I got db.sqlite3 file with size 0.
It looks like mobsf has failed to create the DB properly

**Comment by ajinabraham** [comment]
```
sqlite3.OperationalError: no such table: StaticAnalyzer_recentscansdb
```
The database migration is not done.
```
python manage.py makemigrations
python manage.py makemigrations StaticAnalyzer
python manage.py migrate
```
This will create db.sqlite3 with necessary schema.

**Comment by blshkv** [comment]
can it execute all unnecessary steps automatically? The database does not exist, so it is logical to create it with a proper structure

**Comment by ajinabraham** [comment]
Well the setup.sh does that automatically.

**Comment by blshkv** [comment]
ok, I ran it during setup stage, generated files and it started to work as expected. Great, thanks!
