### ISSUE TITLE
The Home Views search func query the RecentScansDB by URL, but the models didn't declare it

### ISSUE THREAD

**Issue by Antique811** [MobSF/Mobile-Security-Framework-MobSF#1666]
## ENVIRONMENT

```
OS and Version:Windows 10 
Python Version:3.8
MobSF Version:3.3 beta
```

## EXPLANATION OF THE ISSUE

```
MOBSF v3.3 beta
When user use the home page's search form , the home view's search func query the RecentScansDB by the attr URL.
but the models did't declare the URL portery
```

## STEPS TO REPRODUCE THE ISSUE

```
1. upload a apk and start the Static Scan
2. go back to the home page and search the MD5
3. the RecentScanDB table didn't have URL attr
```

![image](https://user-images.githubusercontent.com/19317774/106939886-d1887d00-675b-11eb-8d23-fd0d61727927.png)
![image](https://user-images.githubusercontent.com/19317774/106940034-fd0b6780-675b-11eb-9fb1-2734f85d3403.png)

## LOG FILE

```
[ERROR] 05/Feb/2021 02:43:41 - Internal Server Error: /search
Traceback (most recent call last):
  File "\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "\mobsf\MobSF\views\home.py", line 227, in search
    return HttpResponseRedirect('/' + db_obj[0].URL)
AttributeError: 'RecentScansDB' object has no attribute 'URL'
[ERROR] 05/Feb/2021 02:43:41 - "GET /search?md5=<the file md5> HTTP/1.1" 500 80105
```

**Comment by ajinabraham** [comment]
Thanks for reporting this.
