### ISSUE TITLE
cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by benking001** [MobSF/Mobile-Security-Framework-MobSF#1677]
## ENVIRONMENT

```
OS and Version:win10
Python Version:3.8.8
MobSF Version:3.3.1
```

## EXPLANATION OF THE ISSUE

```
cannot unpack non-iterable NoneType object
```

## LOG FILE

```
[INFO] 19/Feb/2021 12:37:04 - MIME Type: application/vnd.android.package-archive FILE: xxxx-app-1.9.56.7-SNAPSHOT-6496-dev.apk
[INFO] 19/Feb/2021 12:37:04 - Performing Static Analysis of Android APK
[INFO] 19/Feb/2021 12:37:04 - Starting Analysis on : xxxx-app-1.9.56.7-SNAPSHOT-6496-dev.apk
[INFO] 19/Feb/2021 12:37:04 - Generating Hashes
[INFO] 19/Feb/2021 12:37:04 - Unzipping
[INFO] 19/Feb/2021 12:37:07 - APK Extracted
[INFO] 19/Feb/2021 12:37:07 - Getting Hardcoded Certificates/Keystores
[INFO] 19/Feb/2021 12:37:07 - Getting AndroidManifest.xml from APK
[INFO] 19/Feb/2021 12:37:07 - Converting AXML to XML
[ERROR] 19/Feb/2021 12:37:08 - Getting Manifest file
Traceback (most recent call last):
  File "D:\MobSF\mobsf-setup\mobsf\StaticAnalyzer\views\android\manifest_analysis.py", line 899, in get_manifest_apk
    subprocess.check_output(args)
  File "D:\MobSF\python\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "D:\MobSF\python\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['D:\\jdk-15.0.1\\bin\\java.exe', '-jar', 'D:/MobSF/mobsf-setup/mobsf/StaticAnalyzer/tools\\apktool_2.5.0.jar', '--match-original', '--frame-path', 'C:\\Users\\12439\\AppData\\Local\\Temp', '-f', '-s', 'd', 'D:/MobSF/mobsf-setup/mobsf/uploads/373ad59c349d709d439f5902d13c9549/373ad59c349d709d439f5902d13c9549.apk', '-o', 'D:/MobSF/mobsf-setup/mobsf/uploads/373ad59c349d709d439f5902d13c9549/apktool_out']' returned non-zero exit status 1.
[ERROR] 19/Feb/2021 12:37:08 - Parsing Manifest file
Traceback (most recent call last):
  File "D:\MobSF\mobsf-setup\mobsf\StaticAnalyzer\views\android\manifest_analysis.py", line 41, in get_manifest
    mfile = Path(manifest_file)
  File "D:\MobSF\python\lib\pathlib.py", line 1041, in __new__
    self = cls._from_parts(args, init=False)
  File "D:\MobSF\python\lib\pathlib.py", line 682, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "D:\MobSF\python\lib\pathlib.py", line 666, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[ERROR] 19/Feb/2021 12:37:08 - Error Performing Static Analysis
Traceback (most recent call last):
  File "D:\MobSF\mobsf-setup\mobsf\StaticAnalyzer\views\android\static_analyzer.py", line 147, in static_analyzer
    mani_file, mani_xml = get_manifest(
TypeError: cannot unpack non-iterable NoneType object
[ERROR] 19/Feb/2021 12:37:08 - cannot unpack non-iterable NoneType object
[ERROR] 19/Feb/2021 12:37:08 - Internal Server Error: /static_analyzer/
```

**Comment by bkinig** [comment]
i can't find the answer

**Comment by ajinabraham** [comment]
Please join slack channel for support

**Comment by benking001** [comment]
OK,thanks
