### ISSUE TITLE
OperationalError at /recent_scans/

### ISSUE THREAD

**Issue by Cr-cm** [MobSF/Mobile-Security-Framework-MobSF#1689]
OperationalError at /recent_scans/
no such column: StaticAnalyzer_staticanalyzerandroid.NIAP_ANALYSIS

Request Method: | GET
-- | --
http://10.10.2.55:8000/recent_scans/
3.1.5
OperationalError
no such column: StaticAnalyzer_staticanalyzerandroid.NIAP_ANALYSIS
/usr/local/lib/python3.8/dist-packages/django/db/backends/sqlite3/base.py, line 413, in execute
/usr/bin/python3
3.8.5
['/root/Mobile-Security-Framework-MobSF',  '/usr/local/bin',  '/usr/lib/python38.zip',  '/usr/lib/python3.8',  '/usr/lib/python3.8/lib-dynload',  '/usr/local/lib/python3.8/dist-packages',  '/usr/lib/python3/dist-packages']

Environment:

Request Method: GET
Request URL: http://10.10.2.55:8000/recent_scans/

Django Version: 3.1.5
Python Version: 3.8.5
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'mobsf.StaticAnalyzer',
 'mobsf.DynamicAnalyzer',
 'mobsf.MobSF',
 'mobsf.MalwareAnalyzer')
Installed Middleware:
('mobsf.MobSF.views.api.api_middleware.RestApiAuthMiddleware',)

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)

The above exception (no such column: StaticAnalyzer_staticanalyzerandroid.NIAP_ANALYSIS) was the direct cause of the following exception:
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/Mobile-Security-Framework-MobSF/mobsf/MobSF/views/home.py", line 204, in recent_scans
    for item in android:
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 287, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)

Exception Type: OperationalError at /recent_scans/
Exception Value: no such column: StaticAnalyzer_staticanalyzerandroid.NIAP_ANALYSIS

**Comment by ajinabraham** [comment]
This is due to missing DB migration. See FAQ in docs or use slack for support.

**Comment by Cr-cm** [comment]
> This is due to missing DB migration. See FAQ in docs or use slack for support.

where is updating.md？i can't find this file

**Comment by ajinabraham** [comment]
See
https://mobsf.github.io/docs/#/updating
https://mobsf.github.io/docs/#/faq

**Comment by Cr-cm** [comment]
> See
> https://mobsf.github.io/docs/#/updating
> https://mobsf.github.io/docs/#/faq

I have installed it in docker,i should do this?DB migration
