### ISSUE TITLE
I tested 4-5 apks but one app giving me error, looks unable to unzip

### ISSUE THREAD

**Issue by jaykumarjp** [MobSF/Mobile-Security-Framework-MobSF#1696]
## Logs

```
[ERROR] 12/Mar/2021 05:57:48 - Unzipping Error
Traceback (most recent call last):                                                                                                                  
  File "/root/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/shared_func.py", line 90, in unzip                                         
    zipptr.extract(filename, ext_path)                                                                                                              
  File "/usr/lib/python3.9/zipfile.py", line 1616, in extract                                                                                       
    return self._extract_member(member, path, pwd)                                                                                                  
  File "/usr/lib/python3.9/zipfile.py", line 1687, in _extract_member                                                                               
    open(targetpath, "wb") as target:                                                                                                               
OSError: [Errno 36] File name too long: '/root/Mobile-Security-Framework-MobSF/mobsf/uploads/8d73fcd155a1c1cce58c0ab251a8c00a/META-INF/services/o0ooo0O0o0Oo0OOoO000o0oOO0O000O0OOOo.OooOoO0O0oooooo0OO0ooOOooooo00O00OO0.O0000Oo0oOOO0oooooooo0OO00o0OoO0oOOO.oOoo00OOOoOOOo00O0oO00o0ooOOoooooooO.oOoooOo0OOOoOOOo000O0oo0OO0OOo0OOO0o.oo0O0oOoOOoOoOoOOo0o0o0OOOoo000oOOo0.oOoo00OOOoOOOo00O0oO00o0ooOOoooooooO'                                         
[INFO] 12/Mar/2021 05:57:48 - Using the Default OS Unzip Utility.
error:  cannot create /root/Mobile-Security-Framework-MobSF/mobsf/uploads/8d73fcd155a1c1cce58c0ab251a8c00a/META-INF/services/o0ooo0O0o0Oo0OOoO000o0oOO0O000O0OOOo.OooOoO0O0oooooo0OO0ooOOooooo00O00OO0.O0000Oo0oOOO0oooooooo0OO00o0OoO0oOOO.oOoo00OOOoOOOo00O0oO00o0ooOOoooooooO.oOoooOo0OOOoOOOo000O0oo0OO0OOo0OOO0o.oo0O0oOoOOoOoOoOOo0o0o0OOOoo000oOOo0.oOoo00OOOoOOOo00O0oO00o0ooOOoooooooO
        File name too long
error:  cannot create /root/Mobile-Security-Framework-MobSF/mobsf/uploads/8d73fcd155a1c1cce58c0ab251a8c00a/META-INF/services/o0ooo0O0o0Oo0OOoO000o0oOO0O000O0OOOo.OooOoO0O0oooooo0OO0ooOOooooo00O00OO0.O0000Oo0oOOO0oooooooo0OO00o0OoO0oOOO.oOoo00OOOoOOOo00O0oO00o0ooOOoooooooO.oOoooOo0OOOoOOOo000O0oo0OO0OOo0OOO0o.ooo0oo0ooO0o00o0OoOO00oOo00oO0ooo000.o00O0Oo000o00Oo0OoO00oO00OOOOOo0oo0O
        File name too long
[INFO] 12/Mar/2021 05:57:48 - APK Extracted
[INFO] 12/Mar/2021 05:57:48 - Getting Hardcoded Certificates/Keystores
[INFO] 12/Mar/2021 05:57:48 - Getting AndroidManifest.xml from APK
[INFO] 12/Mar/2021 05:57:48 - Converting AXML to XML
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: META-INF
        at brut.androlib.Androlib.writeOriginalFiles(Androlib.java:245)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:183)
        at brut.apktool.Main.cmdDecode(Main.java:179)
        at brut.apktool.Main.main(Main.java:82)
Caused by: brut.directory.DirectoryException: Error copying file: META-INF
        at brut.directory.DirUtil.copyToDir(DirUtil.java:94)
        at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:208)
        at brut.androlib.Androlib.writeOriginalFiles(Androlib.java:234)
        ... 3 more
Caused by: brut.directory.DirectoryException: Error copying file: services/o0ooo0O0o0Oo0OOoO000o0oOO0O000O0OOOo.OooOoO0O0oooooo0OO0ooOOooooo00O00OO0.O0000Oo0oOOO0oooooooo0OO00o0OoO0oOOO.oOoo00OOOoOOOo00O0oO00o0ooOOoooooooO.oOoooOo0OOOoOOOo000O0oo0OO0OOo0OOO0o.oo0O0oOoOOoOoOoOOo0o0o0OOOoo000oOOo0.oOoo00OOOoOOOo00O0oO00o0ooOOoooooooO
        at brut.directory.DirUtil.copyToDir(DirUtil.java:91)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:63)
        at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:198)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:79)
        ... 5 more
Caused by: java.io.FileNotFoundException: /root/Mobile-Security-Framework-MobSF/mobsf/uploads/8d73fcd155a1c1cce58c0ab251a8c00a/apktool_out/original/META-INF/services/o0ooo0O0o0Oo0OOoO000o0oOO0O000O0OOOo.OooOoO0O0oooooo0OO0ooOOooooo00O00OO0.O0000Oo0oOOO0oooooooo0OO00o0OoO0oOOO.oOoo00OOOoOOOo00O0oO00o0ooOOoooooooO.oOoooOo0OOOoOOOo000O0oo0OO0OOo0OOO0o.oo0O0oOoOOoOoOoOOo0o0o0OOOoo000oOOo0.oOoo00OOOoOOOo00O0oO00o0ooOOoooooooO (File name too long)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:87)
        ... 8 more
[ERROR] 12/Mar/2021 05:57:58 - Getting Manifest file
Traceback (most recent call last):                                                                                                                  
  File "/root/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/manifest_analysis.py", line 899, in get_manifest_apk               
    subprocess.check_output(args)                                                                                                                   
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output                                                                                
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,                                                                                
  File "/usr/lib/python3.9/subprocess.py", line 528, in run                                                                                         
    raise CalledProcessError(retcode, process.args,                                                                                                 
subprocess.CalledProcessError: Command '['java', '-jar', '/root/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/tools/apktool_2.5.0.jar', '--match-original', '--frame-path', '/tmp', '-f', '-s', 'd', '/root/Mobile-Security-Framework-MobSF/mobsf/uploads/8d73fcd155a1c1cce58c0ab251a8c00a/8d73fcd155a1c1cce58c0ab251a8c00a.apk', '-o', '/root/Mobile-Security-Framework-MobSF/mobsf/uploads/8d73fcd155a1c1cce58c0ab251a8c00a/apktool_out']' returned non-zero exit status 1.                                                                                                                            
[ERROR] 12/Mar/2021 05:57:58 - Parsing Manifest file
Traceback (most recent call last):                                                                                                                  
  File "/root/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/manifest_analysis.py", line 41, in get_manifest                    
    mfile = Path(manifest_file)                                                                                                                     
  File "/usr/lib/python3.9/pathlib.py", line 1071, in __new__                                                                                       
    self = cls._from_parts(args, init=False)                                                                                                        
  File "/usr/lib/python3.9/pathlib.py", line 696, in _from_parts                                                                                    
    drv, root, parts = self._parse_args(args)                                                                                                       
  File "/usr/lib/python3.9/pathlib.py", line 680, in _parse_args                                                                                    
    a = os.fspath(a)                                                                                                                                
TypeError: expected str, bytes or os.PathLike object, not NoneType                                                                                  
[ERROR] 12/Mar/2021 05:57:58 - Error Performing Static Analysis
Traceback (most recent call last):                                                                                                                  
  File "/root/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 147, in static_analyzer                  
    mani_file, mani_xml = get_manifest(                                                                                                             
TypeError: cannot unpack non-iterable NoneType object                                                                                               
[ERROR] 12/Mar/2021 05:57:58 - cannot unpack non-iterable NoneType object
[ERROR] 12/Mar/2021 05:57:58 - Internal Server Error: /static_analyzer/


```

You can download APK from https://webapp.diawi.com/install/Rxxpye

**Comment by ajinabraham** [comment]
This APK has anti reversing characteristics and the long filename will prevent most tools from analyzing the apk. I will see if anything can be done to support this.

**Comment by ajinabraham** [comment]
Also I don't think we can fully support it as we don't control how third party tools we use will deal with it.

**Comment by ajinabraham** [comment]
You might want to report this to apktool project. https://github.com/iBotPeaches/Apktool

It fails with apktool and we cannot fix things that happens in thirdparty tools.

```
[INFO] 12/Mar/2021 05:57:48 - Converting AXML to XML
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: META-INF
        at brut.androlib.Androlib.writeOriginalFiles(Androlib.java:245)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:183)
        at brut.apktool.Main.cmdDecode(Main.java:179)
        at brut.apktool.Main.main(Main.java:82)
Caused by: brut.directory.DirectoryException: Error copying file: META-INF
        at brut.directory.DirUtil.copyToDir(DirUtil.java:94)
        at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:208)
        at brut.androlib.Androlib.writeOriginalFiles(Androlib.java:234)
        ... 3 more
Caused by: brut.directory.DirectoryException: Error copying file: services/o0ooo0O0o0Oo0OOoO000o0oOO0O000O0OOOo.OooOoO0O0oooooo0OO0ooOOooooo00O00OO0.O0000Oo0oOOO0oooooooo0OO00o0OoO0oOOO.oOoo00OOOoOOOo00O0oO00o0ooOOoooooooO.oOoooOo0OOOoOOOo000O0oo0OO0OOo0OOO0o.oo0O0oOoOOoOoOoOOo0o0o0OOOoo000oOOo0.oOoo00OOOoOOOo00O0oO00o0ooOOoooooooO
        at brut.directory.DirUtil.copyToDir(DirUtil.java:91)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:63)
        at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:198)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:79)
        ... 5 more
Caused by: java.io.FileNotFoundException: /root/Mobile-Security-Framework-MobSF/mobsf/uploads/8d73fcd155a1c1cce58c0ab251a8c00a/apktool_out/original/META-INF/services/o0ooo0O0o0Oo0OOoO000o0oOO0O000O0OOOo.OooOoO0O0oooooo0OO0ooOOooooo00O00OO0.O0000Oo0oOOO0oooooooo0OO00o0OoO0oOOO.oOoo00OOOoOOOo00O0oO00o0ooOOoooooooO.oOoooOo0OOOoOOOo000O0oo0OO0OOo0OOO0o.oo0O0oOoOOoOoOoOOo0o0o0OOOoo000oOOo0.oOoo00OOOoOOOo00O0oO00o0ooOOoooooooO (File name too long)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:87)
        ... 8 more
```

**Comment by abualialfatih23** [comment]
any update for this issue
