### ISSUE TITLE
IPA analysis error: AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by 7a** [MobSF/Mobile-Security-Framework-MobSF#1703]
## ENVIRONMENT

```
OS and Version: Linux-5.4.0-kali4-amd64-x86_64-with-glibc2.29
Python Version: the one from docker - docker run -it --name mobsf -p 8000:8000 -v /root/.MobSF:/root/.MobSF opensecurity/mobile-security-framework-mobsf:latest
MobSF Version: Mobile Security Framework v3.3.5 Beta
```

## EXPLANATION OF THE ISSUE

I upload an IPA to MobSF, expect the report, get an immediate crash due to the following bug:
```
[INFO] 23/Mar/2021 11:55:02 - Extracting IPA
[INFO] 23/Mar/2021 11:55:02 - Unzipping
[INFO] 23/Mar/2021 11:55:02 - Get Files, BIN Plist -> XML, and Normalize
[INFO] 23/Mar/2021 11:55:02 - iOS Info.plist Analysis Started
[INFO] 23/Mar/2021 11:55:02 - Finding Info.plist in iOS Binary
[INFO] 23/Mar/2021 11:55:02 - Checking Permissions
[INFO] 23/Mar/2021 11:55:02 - Checking for Insecure Connections
[ERROR] 23/Mar/2021 11:55:02 - Reading from Info.plist
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/ios/plist_analysis.py", line 122, in plist_analysis
    plist_info['inseccon'] += check_transport_security(plist_obj_)
  File "/root/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/ios/app_transport_security.py", line 12, in check_transport_security
    if ats_dict.get('NSAllowsArbitraryLoads'):
AttributeError: 'str' object has no attribute 'get'
[ERROR] 23/Mar/2021 11:55:02 - Error Perfroming Static Analysis
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/ios/static_analyzer.py", line 116, in static_analyzer_ios
    app_dict['appstore'] = app_search(infoplist_dict.get('id'))
AttributeError: 'NoneType' object has no attribute 'get'
[ERROR] 23/Mar/2021 11:55:02 - 'NoneType' object has no attribute 'get'
[ERROR] 23/Mar/2021 11:55:02 - Internal Server Error: /static_analyzer_ios/
```

## STEPS TO REPRODUCE THE ISSUE

```
1. Start latest MobSF from docker - docker run -it --name mobsf -p 8000:8000 -v /root/.MobSF:/root/.MobSF 
2. Upload IPA
3. Observe the crash in the terminal
```

## LOG FILE

see stack trace above, the contents of debug.log are identical

**Comment by ajinabraham** [comment]
Can you share the IPA or Info.plist file? it looks like the plist file lacks some fields, MobSF is expecting for ATS checks.

**Comment by ajinabraham** [comment]
Fixed in latest master
