### ISSUE TITLE
Error: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by 0x1bitcrack3r** [MobSF/Mobile-Security-Framework-MobSF#1717]
## ENVIRONMENT

```
OS and Version: Big Sur 11.2.3
Python Version: 3.9
MobSF Version: using mobsf from docker `opensecurity/mobile-security-framework-mobsf`
```

## EXPLANATION OF THE ISSUE

```
getting `cannot unpack non-iterable NoneType object` error after uploading apk file
```

## STEPS TO REPRODUCE THE ISSUE

```
1. Choose file to upload
2. After uploading getting `cannot unpack non-iterable NoneType object` error
```

## LOG FILE

```
[INFO] 14/Apr/2021 09:40:51 - OS: Linux
[INFO] 14/Apr/2021 09:40:51 - Platform: Linux-4.19.104-linuxkit-x86_64-with-glibc2.29
[INFO] 14/Apr/2021 09:40:51 - Dist: ubuntu 20.04 focal
[INFO] 14/Apr/2021 09:40:51 - MobSF Basic Environment Check
[INFO] 14/Apr/2021 09:40:53 - Checking for Update.
[INFO] 14/Apr/2021 09:40:54 - No updates available.
[INFO] 14/Apr/2021 09:41:02 - MIME Type: application/octet-stream FILE: tousanticovid_2.4.0.apk
[INFO] 14/Apr/2021 09:41:02 - Performing Static Analysis of Android APK
[INFO] 14/Apr/2021 09:41:02 - Starting Analysis on : tousanticovid_2.4.0.apk
[INFO] 14/Apr/2021 09:41:02 - Generating Hashes
[INFO] 14/Apr/2021 09:41:03 - Unzipping
[INFO] 14/Apr/2021 09:41:04 - APK Extracted
[INFO] 14/Apr/2021 09:41:04 - Getting Hardcoded Certificates/Keystores
[INFO] 14/Apr/2021 09:41:04 - Getting AndroidManifest.xml from APK
[INFO] 14/Apr/2021 09:41:04 - Converting AXML to XML
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[ERROR] 14/Apr/2021 09:41:06 - Getting Manifest file
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/manifest_analysis.py", line 905, in get_manifest_apk
    subprocess.check_output(args)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/jdk-12/bin/java', '-jar', '/root/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/tools/apktool_2.5.0.jar', '--match-original', '--frame-path', '/tmp', '-f', '-s', 'd', '/root/.MobSF/uploads/438577bf66681c684e9b1e3ce4798801/438577bf66681c684e9b1e3ce4798801.apk', '-o', '/root/.MobSF/uploads/438577bf66681c684e9b1e3ce4798801/apktool_out']' died with <Signals.SIGSEGV: 11>.
[ERROR] 14/Apr/2021 09:41:06 - Parsing Manifest file
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/manifest_analysis.py", line 41, in get_manifest
    mfile = Path(manifest_file)
  File "/usr/lib/python3.8/pathlib.py", line 1038, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.8/pathlib.py", line 679, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.8/pathlib.py", line 663, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[ERROR] 14/Apr/2021 09:41:06 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 150, in static_analyzer
    mani_file, mani_xml = get_manifest(
TypeError: cannot unpack non-iterable NoneType object
[ERROR] 14/Apr/2021 09:41:06 - cannot unpack non-iterable NoneType object
[ERROR] 14/Apr/2021 09:41:06 - Internal Server Error: /static_analyzer/
```

## APK FILE THAT I HAVE USED
[Download from here](https://easyupload.io/ffrh4e)

**Comment by ajinabraham** [comment]
Closing as this APK works for me. Replied over slack.
