### ISSUE TITLE
pip's legacy dependency resolver does not consider dependency conflicts

### ISSUE THREAD

**Issue by elig0n** [MobSF/Mobile-Security-Framework-MobSF#1722]
## ENVIRONMENT

```
OS and Version: Windows 10
Python Version: 3.9.4
MobSF Version: Git
```

## EXPLANATION OF THE ISSUE

Running setup.bat fails (pip legacy resolver):

```
ERROR: pip's legacy dependency resolver does not consider dependency conflicts when selecting packages. This behaviour is the source of the following dependency conflicts.
mitmproxy 6.0.2 requires ruamel.yaml<0.17,>=0.16, but you'll have ruamel-yaml 0.17.4 which is incompatible.
networkx 2.5.1 requires decorator<5,>=4.3, but you'll have decorator 5.0.7 which is incompatible.
Successfully installed Brotli-1.0.9 Django-3.2 IP2Location-8.5.1 Jinja2-2.11.3 MarkupSafe-1.1.1 Werkzeug-1.0.1 altgraph-0.17 androguard-3.3.5 apkid-2.1.2 asgiref-3.3.4 asn1crypto-1.4.0 backcall-0.2.0 beautifulsoup4-4.9.3 biplist-1.0.3 blinker-1.4 bs4-0.0.1 certifi-2020.12.5 cffi-1.14.5 chardet-4.0.0 click-7.1.2 colorama-0.4.4 colorlog-5.0.1 cryptography-3.3.2 cycler-0.10.0 decorator-5.0.7 distro-1.5.0 flask-1.1.2 frida-14.2.14 future-0.18.2 google-play-scraper-0.2.1 h11-0.12.0 h2-4.0.0 hpack-4.0.0 http-tools-2.1.0 hyperframe-6.0.1 idna-2.10 ipython-7.22.0 ipython-genutils-0.2.0 itsdangerous-1.1.0 jedi-0.18.0 kaitaistruct-0.9 kiwisolver-1.3.1 ldap3-2.8.1 libsast-1.4.1 lief-0.11.4 lxml-4.6.3 macholib-1.14 matplotlib-3.4.1 mitmproxy-6.0.2 msgpack-1.0.2 networkx-2.5.1 numpy-1.20.2 oscrypto-1.2.1 parso-0.8.2 passlib-1.7.4 pdfkit-0.6.1 pickleshare-0.7.5 pillow-8.2.0 prompt-toolkit-3.0.18 protobuf-3.14.0 psutil-5.8.0 publicsuffix2-2.20191221 pyOpenSSL-20.0.1 pyasn1-0.4.8 pycparser-2.20 pydivert-2.1.0 pydot-1.4.2 pygments-2.8.1 pyparsing-2.4.7 pyperclip-1.8.2 python-dateutil-2.8.1 pytz-2021.1 pyyaml-5.4.1 requests-2.25.1 rsa-4.7.2 ruamel.yaml-0.17.4 ruamel.yaml.clib-0.2.2 shelljob-0.6.3 six-1.15.0 sortedcontainers-2.3.0 soupsieve-2.2.1 sqlparse-0.4.1 tornado-6.1 traitlets-5.0.5 urllib3-1.26.4 urwid-2.1.2 waitress-2.0.0 wcwidth-0.2.5 whitenoise-5.2.0 wsproto-1.0.0 yara-python-dex-1.0.0 zstandard-0.14.1
[INSTALL] Clean Up
=======================MobSF Clean Script for Windows=======================
..................
[INSTALL] Migrating Database
Traceback (most recent call last):
  File "d:\MobSF2\venv\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "d:\MobSF2\venv\lib\site-packages\django\core\management\base.py", line 393, in execute
    self.check()
  File "d:\MobSF2\venv\lib\site-packages\django\core\management\base.py", line 419, in check
    all_issues = checks.run_checks(
  File "d:\MobSF2\venv\lib\site-packages\django\core\checks\registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "d:\MobSF2\venv\lib\site-packages\django\core\checks\translation.py", line 60, in check_language_settings_consistent
    get_supported_language_variant(settings.LANGUAGE_CODE)
  File "d:\MobSF2\venv\lib\site-packages\django\conf\__init__.py", line 82, in __getattr__
    self._setup(name)
  File "d:\MobSF2\venv\lib\site-packages\django\conf\__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "d:\MobSF2\venv\lib\site-packages\django\conf\__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mobsf'
```

ModuleNotFoundError error repeats several times

**Comment by ajinabraham** [comment]
This is due to an incomplete setup. Please use the slack channel for support.

**Comment by ajinabraham** [comment]
Quick heads up. I did some QA to windows setup and run scripts few minutes back. Try pulling the latest master and run setup again.

**Comment by elig0n** [comment]
It seems to work now.

**Comment by fadeevab** [comment]
Whoever faces with this issue:
1. Remove MobSF folder completely.
2. Clone the repo.
3. `./setup.sh` or `./setup.bat`.

For the record: removing `venv` alone doesn't help.
