### ISSUE TITLE
pip's legacy dependency conflict (Flask, mitmproxy, networkx) + Frida SSL Pinning Bypass error + httptools Web UI error

### ISSUE THREAD

**Issue by RussellMurad** [MobSF/Mobile-Security-Framework-MobSF#1747]
## ENVIRONMENT

```
OS and Version: Windows 10, Home Edition
Python Version: 3.8.0
MobSF Version: V3.4.3 beta
Pip Version: 21.1.2
Openjdk version: 1.8.0_292
Genymotion version: 3.2.1
Device VM: Google Pixel 3 (9.0-API 28) 
```

## EXPLANATION OF THE ISSUE

**Problem 1**: While installing with "setup.bat", it gives me some dependency conflict error:

```
ERROR: pip's legacy dependency resolver does not consider dependency conflicts when selecting packages.
This behaviour is the source of the following dependency conflicts.
flask 1.1.4 requires click<8.0,>=5.1, but you'll have click 8.0.1 which is incompatible.
mitmproxy 6.0.2 requires click<8,>=7.0, but you'll have click 8.0.1 which is incompatible.
mitmproxy 6.0.2 requires ruamel.yaml<0.17,>=0.16, but you'll have ruamel-yaml 0.17.9 which is incompatible.
networkx 2.5.1 requires decorator<5,>=4.3, but you'll have decorator 5.0.9 which is incompatible. 
```

Rest of installation goes fine.

**Problem 2**: After Mobsyfied my android emulator, I've tried to run dynamic analyzer on Wikipedia app. 
The app won't have any internet connection says, "Content cannot be loaded when offline" (Screenshot Attached).
Not even android browser have any internet connection. But after HTTP Proxy turned off, reboot, app seems working fine.
Here's mobsf frida script log - 
```

[DEBUG] 14/Jun/2021 23:57:43 - [Frida] Loaded Frida Script - api_monitor
[DEBUG] 14/Jun/2021 23:57:43 - [Frida] Loaded Frida Script - debugger_check_bypass
[DEBUG] 14/Jun/2021 23:57:43 - [Frida] Loaded Frida Script - root_bypass
[DEBUG] 14/Jun/2021 23:57:43 - [Frida] Loaded Frida Script - ssl_pinning_bypass
[DEBUG] 14/Jun/2021 23:57:55 - [Frida] [API Monitor] Cannot find org.apache.http.impl.client.AbstractHttpClient.execute
[DEBUG] 14/Jun/2021 23:57:55 - [Frida] [API Monitor] Cannot find com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream
[DEBUG] 14/Jun/2021 23:57:55 - [Frida] [SSL Pinning Bypass] okhttp CertificatePinner not found
[DEBUG] 14/Jun/2021 23:57:55 - [Frida] [SSL Pinning Bypass] DataTheorem trustkit not found
[DEBUG] 14/Jun/2021 23:57:55 - [Frida] [SSL Pinning Bypass] Appcelerator PinningTrustManager not found
[DEBUG] 14/Jun/2021 23:57:55 - [Frida] [SSL Pinning Bypass] Apache Cordova SSLCertificateChecker not found
[DEBUG] 14/Jun/2021 23:57:55 - [Frida] [SSL Pinning Bypass] Wultra CertStore.validateFingerprint not found
[DEBUG] 14/Jun/2021 23:57:55 - [Frida] [SSL Pinning Bypass] Xutils not found
[DEBUG] 14/Jun/2021 23:57:55 - [Frida] [SSL Pinning Bypass] httpclientandroidlib not found
[DEBUG] 14/Jun/2021 23:57:55 - [Frida] [SSL Pinning Bypass] Cronet not found
[ERROR] 14/Jun/2021 23:57:55 - [Frida] {'type': 'error', 'description': 'Error: java.lang.ClassNotFoundException: Didn\'t find class "com.babylon.certificatetransparency.CTInterceptorBuilder" on path: DexPathList[[dex file "/data/data/org.wikipedia/cache/frida5543855568598672617.dex"],nativeLibraryDirectories=[/system/lib, /system/vendor/lib]]', 'stack': 'Error: java.lang.ClassNotFoundException: Didn\'t find class "com.babylon.certificatetransparency.CTInterceptorBuilder" on path: DexPathList[[dex file "/data/data/org.wikipedia/cache/frida5543855568598672617.dex"],nativeLibraryDirectories=[/system/lib, /system/vendor/lib]]\n    at <anonymous> (frida/node_modules/frida-java-bridge/lib/env.js:124)\n    at <anonymous> (frida/node_modules/frida-java-bridge/lib/class-factory.js:443)\n    at value (frida/node_modules/frida-java-bridge/lib/class-factory.js:812)\n    at _make (frida/node_modules/frida-java-bridge/lib/class-factory.js:112)\n    at use (frida/node_modules/frida-java-bridge/lib/class-factory.js:63)\n    at use (frida/node_modules/frida-java-bridge/index.js:246)\n    at <anonymous> (/script1.js:1098)\n    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:11)\n    at perform (frida/node_modules/frida-java-bridge/index.js:193)\n    at <anonymous> (/script1.js:1102)\n    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:11)\n    at perform (frida/node_modules/frida-java-bridge/index.js:193)\n    at <anonymous> (/script1.js:1107)\n    at apply (native)\n    at <anonymous> (frida/runtime/core.js:45)', 'fileName': 'frida/node_modules/frida-java-bridge/lib/env.js', 'lineNumber': 124, 'columnNumber': 1}  
[DEBUG] 14/Jun/2021 23:57:57 - [Frida] [SSL Pinning Bypass] verifyCertificateChain() bypassed 

```

**Problem 3**:  After generating report and clicking "Start HTTP Tools", it's open a new tab and says, "Can't reach the page" (Screenshot Attached Below) and in cmd, some Traceback generates, like this - 

```

Traceback (most recent call last):
File "D:\Software\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\pkg_resources\__init__.py", line 583, in _build_master
ws.require(__requires__)
File "D:\Software\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\pkg_resources\__init__.py", line 900, in require
needed = self.resolve(parse_requirements(requirements))
File "D:\Software\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\pkg_resources\__init__.py", line 791, in resolve
raise VersionConflict(dist, req).with_context(dependent_req) 
pkg_resources.ContextualVersionConflict: (click 8.0.1 (d:\software\mobile-security-framework-mobsf-master\venv\lib\site-packages), Requirement.parse('click<8,>=7.0'), {'mitmproxy'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last): 
File "D:\Software\Mobile-Security-Framework-MobSF-master\venv\Scripts\httptools-script.py", line 6, in <module>
from pkg_resources import load_entry_point
File "D:\Software\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\pkg_resources\__init__.py", line 3251, in <module>
def _initialize_master_working_set():
File "D:\Software\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\pkg_resources\__init__.py", line 3234, in _call_aside
f(*args, **kwargs) 
File "D:\Software\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\pkg_resources\__init__.py", line 3263, in _initialize_master_working_set
working_set = WorkingSet._build_master()
File "D:\Software\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\pkg_resources\__init__.py", line 585, in _build_master
return cls._build_from_requirements(__requires__)
File "D:\Software\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\pkg_resources\__init__.py", line 598, in _build_from_requirements
dists = ws.resolve(reqs, Environment())
File "D:\Software\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\pkg_resources\__init__.py", line 786, in resolve
raise DistributionNotFound(req, requires)
pkg_resources.DistributionNotFound: The 'click<8,>=7.0' distribution was not found and is required by mitmproxy
```

![image](https://user-images.githubusercontent.com/6575563/121938734-ffb34480-cd6d-11eb-9627-31cbe24e86d1.png)
![image](https://user-images.githubusercontent.com/6575563/121938778-0e016080-cd6e-11eb-85d2-f067fa08278c.png)
![image](https://user-images.githubusercontent.com/6575563/121938824-1c4f7c80-cd6e-11eb-9776-5d6d94d0083e.png)
![image](https://user-images.githubusercontent.com/6575563/121938929-3721f100-cd6e-11eb-8ed4-76ad59b9e152.png)
![image](https://user-images.githubusercontent.com/6575563/121942154-fc21bc80-cd71-11eb-8ba7-8439da5c625c.png)

**Comment by ajinabraham** [comment]
Addressed in slack.
