### ISSUE TITLE
quark apk analysis error

### ISSUE THREAD

**Issue by firmianay** [MobSF/Mobile-Security-Framework-MobSF#1774]
## ENVIRONMENT

```
OS and Version: Linux kali 5.10.0-kali9-amd64 #1 SMP Debian 5.10.46-1kali1 (2021-06-25) x86_64 GNU/Linux
Python Version: Python 3.9.2
MobSF Version: v3.4.5 Beta
```

## EXPLANATION OF THE ISSUE

```
[ERROR] 30/Jul/2021 13:21:40 - Quark APK Analysis
Traceback (most recent call last):                                                                                                                           
  File "/home/seclab/Mobile-Security-Framework-MobSF/mobsf/MalwareAnalyzer/views/quark.py", line 48, in quark_analysis                                       
    data.run(rule_checker)                                                                                                                                   
  File "/home/seclab/Mobile-Security-Framework-MobSF/venv/lib/python3.9/site-packages/quark/Objects/quark.py", line 317, in run                              
    if self.check_parameter(parent_function, first_wrapper, second_wrapper):                                                                                 
  File "/home/seclab/Mobile-Security-Framework-MobSF/venv/lib/python3.9/site-packages/quark/Objects/quark.py", line 190, in check_parameter                  
    pyeval.eval[instruction[0]](instruction)                                                                                                                 
  File "/home/seclab/Mobile-Security-Framework-MobSF/venv/lib/python3.9/site-packages/quark/Evaluator/pyeval.py", line 31, in warp                           
    func(*args, **kwargs)                                                                                                                                    
  File "/home/seclab/Mobile-Security-Framework-MobSF/venv/lib/python3.9/site-packages/quark/Evaluator/pyeval.py", line 336, in AGET_OBJECT                   
    array_obj = self.table_obj.get_obj_list(                                                                                                                 
AttributeError: 'NoneType' object has no attribute 'pop'                                                                                                     
[ERROR] 30/Jul/2021 13:21:40 - Error Performing Static Analysis
Traceback (most recent call last):                                                                                                                           
  File "/home/seclab/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 227, in static_analyzer                    
    quark_results = quark_analysis(                                                                                                                          
  File "/home/seclab/Mobile-Security-Framework-MobSF/mobsf/MalwareAnalyzer/views/quark.py", line 63, in quark_analysis                                       
    return _convert_report(json_report['crimes'], app_dir)                                                                                                   
UnboundLocalError: local variable 'json_report' referenced before assignment                                                                                 
[ERROR] 30/Jul/2021 13:21:40 - local variable 'json_report' referenced before assignment
[ERROR] 30/Jul/2021 13:21:40 - Internal Server Error: /static_analyzer/

```

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step
2. This is the second step
3. Further steps, etc.
```

## LOG FILE

```
Paste the contents of ~/.MobSF/debug.log here or attach the log file.
```

**Comment by superpoussin22** [comment]
this is under investigation

**Comment by ajinabraham** [comment]
Fixed in master

**Comment by ajinabraham** [comment]
@firmianay Do you have a sample APK to replicate this issue. Quark team would like to troubleshoot this and fix it in the tool.
