### ISSUE TITLE
OperationalError at /recent_scans/

### ISSUE THREAD

**Issue by Kaaveh** [MobSF/Mobile-Security-Framework-MobSF#1775]
## ENVIRONMENT

```
OS and Version: Windows 10 Enterprise - version 20H2
Python Version:  3.9.5
MobSF Version: 3.4.5 Beta
```

## EXPLANATION OF THE ISSUE

```
After updating MobSF from 3.4.4 Beta to the last version(3.4.5 Beta), I can't access the recent scans section.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. Lanch Home screen
2. Click on Recent scan
```

## LOG FILE

```
OperationalError    at /recent_scans/
no such column: StaticAnalyzer_staticanalyzerandroid.QUARK
  
Request Method:  GET
Request URL: http://127.0.0.1:8000/recent_scans/
Django Version: 3.2.3
Exception Type: OperationalError
Exception Value: no such column: StaticAnalyzer_staticanalyzerandroid.QUARK
Exception Location: c:\pentest\mobile-security-framework-mobsf\venv\lib\site-packages\django\db\backends\sqlite3\base.py, line 423, in execute
Python Executable: c:\pentest\mobile-security-framework-mobsf\venv\scripts\python.exe
Python Version: 3.9.5
Python Path: ['C:\\Pentest\\Mobile-Security-Framework-MobSF\\venv\\Scripts\\waitress-serve.exe',  'C:\\Program Files\\Python39\\python39.zip',  'C:\\Program Files\\Python39\\DLLs',  'C:\\Program Files\\Python39\\lib',  'C:\\Program Files\\Python39',  'c:\\pentest\\mobile-security-framework-mobsf\\venv',  'c:\\pentest\\mobile-security-framework-mobsf\\venv\\lib\\site-packages',  'C:\\Pentest\\Mobile-Security-Framework-MobSF']
Server time: Mon, 02 Aug 2021 05:36:15 +0000











Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/recent_scans/

Django Version: 3.2.3
Python Version: 3.9.5
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'mobsf.StaticAnalyzer',
 'mobsf.DynamicAnalyzer',
 'mobsf.MobSF',
 'mobsf.MalwareAnalyzer')
Installed Middleware:
('mobsf.MobSF.views.api.api_middleware.RestApiAuthMiddleware',)



Traceback (most recent call last):
  File "c:\pentest\mobile-security-framework-mobsf\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "c:\pentest\mobile-security-framework-mobsf\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)

The above exception (no such column: StaticAnalyzer_staticanalyzerandroid.QUARK) was the direct cause of the following exception:
  File "c:\pentest\mobile-security-framework-mobsf\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "c:\pentest\mobile-security-framework-mobsf\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Pentest\Mobile-Security-Framework-MobSF\mobsf\MobSF\views\home.py", line 208, in recent_scans
    for item in android:
  File "c:\pentest\mobile-security-framework-mobsf\venv\lib\site-packages\django\db\models\query.py", line 280, in __iter__
    self._fetch_all()
  File "c:\pentest\mobile-security-framework-mobsf\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "c:\pentest\mobile-security-framework-mobsf\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "c:\pentest\mobile-security-framework-mobsf\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "c:\pentest\mobile-security-framework-mobsf\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "c:\pentest\mobile-security-framework-mobsf\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "c:\pentest\mobile-security-framework-mobsf\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "c:\pentest\mobile-security-framework-mobsf\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "c:\pentest\mobile-security-framework-mobsf\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "c:\pentest\mobile-security-framework-mobsf\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "c:\pentest\mobile-security-framework-mobsf\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)

Exception Type: OperationalError at /recent_scans/
Exception Value: no such column: StaticAnalyzer_staticanalyzerandroid.QUARK

```

**Comment by superpoussin22** [comment]
see the upgrade procedure in the documentation

**Comment by Kaaveh** [comment]
Thanks, it works.
