### ISSUE TITLE
RecentScansDB is empty while trying to retrieve past scan results and generate PDF report

### ISSUE THREAD

**Issue by ychen96** [MobSF/Mobile-Security-Framework-MobSF#1778]
## ENVIRONMENT

```
OS and Version: mac OS Big Sur ver. 11.4
Python Version: 3.9.6
MobSF Version: 3.4
```

## EXPLANATION OF THE ISSUE

```
While I was uploading an IPA file for waiting for scanning results, everything was ok and the logs says the results was saved to Database, here I suppose the "Database" means StaticAnalyzerIOS and RecentScansDB both.

However, when I want to retrieve the pdf report, I have to fetch the data from RecentScansDB and it turns out RecentScansDB is totally empty, thus throws out the error.
```

## STEPS TO REPRODUCE THE ISSUE

```
./setup.sh    #setup the environment
./run.sh 127.0.0.1:9527     #running the service and upload an IPA file, waiting for results
```
click the "PDF Report" button on the left side bar and you will see the error.

## LOG FILE

```
...
[INFO] 05/Aug/2021 02:55:22 - OS: Darwin
[INFO] 05/Aug/2021 02:55:22 - Platform: macOS-11.4-x86_64-i386-64bit
[INFO] 05/Aug/2021 02:55:22 - Dist: darwin 20.5.0
[INFO] 05/Aug/2021 02:55:22 - MobSF Basic Environment Check
[WARNING] 05/Aug/2021 02:55:22 - Dynamic Analysis related functions will not work.
Make sure a Genymotion Android VM/Android Studio Emulator is running before performing Dynamic Analysis.
[INFO] 05/Aug/2021 02:55:22 - iOS Static Analysis Started
[INFO] 05/Aug/2021 02:55:22 - iOS Binary (IPA) Analysis Started
[INFO] 05/Aug/2021 02:55:22 - Generating Hashes
[INFO] 05/Aug/2021 02:55:22 - Extracting IPA
[INFO] 05/Aug/2021 02:55:22 - Unzipping
[INFO] 05/Aug/2021 02:55:23 - Get Files, BIN Plist -> XML, and Normalize
[INFO] 05/Aug/2021 02:55:23 - iOS Info.plist Analysis Started
[INFO] 05/Aug/2021 02:55:23 - Finding Info.plist in iOS Binary
[INFO] 05/Aug/2021 02:55:23 - Checking Permissions
[INFO] 05/Aug/2021 02:55:23 - Checking for Insecure Connections
[INFO] 05/Aug/2021 02:55:23 - Starting Binary Analysis
[INFO] 05/Aug/2021 02:55:23 - Running MachO Analysis on Beckon
[INFO] 05/Aug/2021 02:55:24 - Getting Binary Information
[INFO] 05/Aug/2021 02:55:24 - Dumping classes
[INFO] 05/Aug/2021 02:55:24 - Running class-dump-swift against binary
[INFO] 05/Aug/2021 02:55:25 - Running strings against the Binary
[INFO] 05/Aug/2021 02:55:25 - Fetching icon path
[INFO] 05/Aug/2021 03:03:32 - Finished URL and Email Extraction
[INFO] 05/Aug/2021 03:03:32 - Detecting Firebase URL(s)
[INFO] 05/Aug/2021 03:03:32 - Connecting to DB
[INFO] 05/Aug/2021 03:03:32 - Saving to Database
[INFO] 05/Aug/2021 03:03:51 - Fetching data from DB for PDF Report Generation (IOS)
[INFO] 05/Aug/2021 03:03:51 - Analysis is already Done. Fetching data from the DB...
[INFO] 05/Aug/2021 03:03:51 - Generating PDF report for IOS ipa
[ERROR] 05/Aug/2021 03:03:51 - Error Generating PDF Report
Traceback (most recent call last):
  File "/Users/cyc/Projects/Mobile-Security-Framework-MobSF-master/Mobile-Security-Framework-MobSF-master/mobsf/StaticAnalyzer/views/shared_func.py", line 166, in pdf
    context['timestamp'] = RecentScansDB.objects.get(
  File "/Users/cyc/Projects/Mobile-Security-Framework-MobSF-master/Mobile-Security-Framework-MobSF-master/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/cyc/Projects/Mobile-Security-Framework-MobSF-master/Mobile-Security-Framework-MobSF-master/venv/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
mobsf.StaticAnalyzer.models.RecentScansDB.DoesNotExist: RecentScansDB matching query does not exist.
[ERROR] 05/Aug/2021 03:03:51 - RecentScansDB matching query does not exist.
[ERROR] 05/Aug/2021 03:03:51 - Internal Server Error: /pdf/
```

**Comment by ychen96** [comment]
Figure out why, it's not really a bug. Just close it and sorry to bother.
