### ISSUE TITLE
Mac Apple silicon M1, and APK errors

### ISSUE THREAD

**Issue by droidandy** [MobSF/Mobile-Security-Framework-MobSF#1785]
## ENVIRONMENT

```
OS and Version: MacOS 11.4
Python Version: 3.8
MobSF Version: 3.4
```

## EXPLANATION OF THE ISSUE

```
What happens, under which versions, under what conditions, when, and what were you expecting instead.
```

Running an analysis on a universal APK, generated from android app bundle. I get errors, MobSF seems to loop and not progress. 

## LOG FILE

```
[INFO] 10/Aug/2021 11:20:42 -
  __  __       _    ____  _____         _____ _  _
 |  \/  | ___ | |__/ ___||  ___| __   _|___ /| || |
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / |_ \| || |_
 | |  | | (_) | |_) |__) |  _|    \ V / ___) |__   _|
 |_|  |_|\___/|_.__/____/|_|       \_/ |____(_) |_|

[INFO] 10/Aug/2021 11:20:42 - Mobile Security Framework v3.4.5 Beta
REST API Key: [HIDDEN]
[INFO] 10/Aug/2021 11:20:42 - OS: Linux
[INFO] 10/Aug/2021 11:20:42 - Platform: Linux-5.10.25-linuxkit-aarch64-with-glibc2.29
[INFO] 10/Aug/2021 11:20:42 - Dist: ubuntu 20.04 focal
[INFO] 10/Aug/2021 11:20:42 - MobSF Basic Environment Check
[INFO] 10/Aug/2021 11:20:42 - Starting Analysis on: universal.apk
[INFO] 10/Aug/2021 11:20:42 - Generating Hashes
[INFO] 10/Aug/2021 11:20:42 - Checking for Update.
[INFO] 10/Aug/2021 11:20:42 - No updates available.
[INFO] 10/Aug/2021 11:20:43 - Unzipping
[INFO] 10/Aug/2021 11:20:55 - APK Extracted
[INFO] 10/Aug/2021 11:20:55 - Getting Hardcoded Certificates/Keystores
[INFO] 10/Aug/2021 11:20:55 - Getting AndroidManifest.xml from APK
[INFO] 10/Aug/2021 11:20:55 - Parsing AndroidManifest.xml
Requested API level 30 is larger than maximum we have, returning API level 28 instead.
[INFO] 10/Aug/2021 11:20:55 - Fetching icon path
Requested API level 30 is larger than maximum we have, returning API level 28 instead.
[INFO] 10/Aug/2021 11:20:55 - Extracting Manifest Data
[INFO] 10/Aug/2021 11:20:55 - Fetching Details from Play Store: com.HIDDEN
[INFO] 10/Aug/2021 11:20:55 - Manifest Analysis Started
[INFO] 10/Aug/2021 11:20:55 - Binary Analysis Started
[INFO] 10/Aug/2021 11:20:55 - Analyzing lib/arm64-v8a/libapp.so
[INFO] 10/Aug/2021 11:20:56 - Analyzing lib/arm64-v8a/libbarhopper_v2.so
[INFO] 10/Aug/2021 11:20:56 - Analyzing lib/arm64-v8a/libface_detector_v2_jni.so
[INFO] 10/Aug/2021 11:20:56 - Analyzing lib/arm64-v8a/libflutter.so
[INFO] 10/Aug/2021 11:20:56 - Analyzing lib/arm64-v8a/liblanguage_id_jni.so
[INFO] 10/Aug/2021 11:20:56 - Analyzing lib/arm64-v8a/libmlkitcommonpipeline.so
[INFO] 10/Aug/2021 11:20:56 - Analyzing lib/armeabi-v7a/libapp.so
[INFO] 10/Aug/2021 11:20:57 - Analyzing lib/armeabi-v7a/libbarhopper_v2.so
[INFO] 10/Aug/2021 11:20:57 - Analyzing lib/armeabi-v7a/libface_detector_v2_jni.so
[INFO] 10/Aug/2021 11:20:57 - Analyzing lib/armeabi-v7a/libflutter.so
[INFO] 10/Aug/2021 11:20:57 - Analyzing lib/armeabi-v7a/liblanguage_id_jni.so
[INFO] 10/Aug/2021 11:20:57 - Analyzing lib/armeabi-v7a/libmlkitcommonpipeline.so
[INFO] 10/Aug/2021 11:20:57 - Analyzing lib/x86/libbarhopper_v2.so
[INFO] 10/Aug/2021 11:20:58 - Analyzing lib/x86/libface_detector_v2_jni.so
[INFO] 10/Aug/2021 11:20:58 - Analyzing lib/x86/liblanguage_id_jni.so
[INFO] 10/Aug/2021 11:20:58 - Analyzing lib/x86/libmlkitcommonpipeline.so
[INFO] 10/Aug/2021 11:20:58 - Analyzing lib/x86_64/libapp.so
[INFO] 10/Aug/2021 11:20:59 - Analyzing lib/x86_64/libbarhopper_v2.so
[INFO] 10/Aug/2021 11:20:59 - Analyzing lib/x86_64/libface_detector_v2_jni.so
[INFO] 10/Aug/2021 11:20:59 - Analyzing lib/x86_64/libflutter.so
[INFO] 10/Aug/2021 11:20:59 - Analyzing lib/x86_64/liblanguage_id_jni.so
[INFO] 10/Aug/2021 11:20:59 - Analyzing lib/x86_64/libmlkitcommonpipeline.so
[INFO] 10/Aug/2021 11:20:59 - Reading Code Signing Certificate
Requested API level 30 is larger than maximum we have, returning API level 28 instead.
[INFO] 10/Aug/2021 11:21:00 - Running APKiD 2.1.2
[INFO] 10/Aug/2021 11:21:04 - Trackers Database is up-to-date
[INFO] 10/Aug/2021 11:21:04 - Detecting Trackers
[INFO] 10/Aug/2021 11:21:05 - APK -> JAVA
[INFO] 10/Aug/2021 11:21:05 - Decompiling to Java with jadx
[INFO] 10/Aug/2021 11:21:57 - DEX -> SMALI
[INFO] 10/Aug/2021 11:21:57 - Converting classes.dex to Smali Code
[INFO] 10/Aug/2021 11:21:57 - Converting classes2.dex to Smali Code
[INFO] 10/Aug/2021 11:21:57 - Code Analysis Started on - java_source
					[INFO] 10/Aug/2021 11:23:39 - Running NIAP Analyzer
							[INFO] 10/Aug/2021 11:26:02 - Starting Analysis on: universal.apk
[INFO] 10/Aug/2021 11:26:02 - Generating Hashes
[INFO] 10/Aug/2021 11:26:07 - Unzipping
[INFO] 10/Aug/2021 12:04:48 - APK Extracted
[INFO] 10/Aug/2021 12:04:48 - Getting Hardcoded Certificates/Keystores
[INFO] 10/Aug/2021 12:04:48 - Getting AndroidManifest.xml from APK
[INFO] 10/Aug/2021 12:04:48 - Parsing AndroidManifest.xml
Requested API level 30 is larger than maximum we have, returning API level 28 instead.
[INFO] 10/Aug/2021 12:04:49 - Fetching icon path
Requested API level 30 is larger than maximum we have, returning API level 28 instead.
[INFO] 10/Aug/2021 12:04:49 - Extracting Manifest Data
[INFO] 10/Aug/2021 12:04:49 - Fetching Details from Play Store: com.HIDDEN
[INFO] 10/Aug/2021 12:04:49 - Manifest Analysis Started
[INFO] 10/Aug/2021 12:04:49 - Binary Analysis Started
[INFO] 10/Aug/2021 12:04:49 - Analyzing lib/arm64-v8a/libapp.so
[INFO] 10/Aug/2021 12:04:50 - Analyzing lib/arm64-v8a/libbarhopper_v2.so
[INFO] 10/Aug/2021 12:04:50 - Analyzing lib/arm64-v8a/libface_detector_v2_jni.so
[INFO] 10/Aug/2021 12:04:51 - Analyzing lib/arm64-v8a/libflutter.so
[INFO] 10/Aug/2021 12:04:52 - Analyzing lib/arm64-v8a/liblanguage_id_jni.so
[INFO] 10/Aug/2021 12:04:52 - Analyzing lib/arm64-v8a/libmlkitcommonpipeline.so
[INFO] 10/Aug/2021 12:04:52 - Analyzing lib/armeabi-v7a/libapp.so
[INFO] 10/Aug/2021 12:04:53 - Analyzing lib/armeabi-v7a/libbarhopper_v2.so
[INFO] 10/Aug/2021 12:04:53 - Analyzing lib/armeabi-v7a/libface_detector_v2_jni.so
[INFO] 10/Aug/2021 12:04:53 - Analyzing lib/armeabi-v7a/libflutter.so
[INFO] 10/Aug/2021 12:04:53 - Analyzing lib/armeabi-v7a/liblanguage_id_jni.so
[INFO] 10/Aug/2021 12:04:53 - Analyzing lib/armeabi-v7a/libmlkitcommonpipeline.so
[INFO] 10/Aug/2021 12:04:54 - Analyzing lib/x86/libbarhopper_v2.so
[INFO] 10/Aug/2021 12:04:54 - Analyzing lib/x86/libface_detector_v2_jni.so
[INFO] 10/Aug/2021 12:04:54 - Analyzing lib/x86/liblanguage_id_jni.so
[INFO] 10/Aug/2021 12:04:54 - Analyzing lib/x86/libmlkitcommonpipeline.so
[INFO] 10/Aug/2021 12:04:54 - Analyzing lib/x86_64/libapp.so
[INFO] 10/Aug/2021 12:04:55 - Analyzing lib/x86_64/libbarhopper_v2.so
[INFO] 10/Aug/2021 12:04:55 - Analyzing lib/x86_64/libface_detector_v2_jni.so
[INFO] 10/Aug/2021 12:04:55 - Analyzing lib/x86_64/libflutter.so
[INFO] 10/Aug/2021 12:04:55 - Analyzing lib/x86_64/liblanguage_id_jni.so
[INFO] 10/Aug/2021 12:04:55 - Analyzing lib/x86_64/libmlkitcommonpipeline.so
[INFO] 10/Aug/2021 12:04:56 - Reading Code Signing Certificate
Requested API level 30 is larger than maximum we have, returning API level 28 instead.
[INFO] 10/Aug/2021 12:04:56 - Running APKiD 2.1.2
[INFO] 10/Aug/2021 12:05:03 - Trackers Database is up-to-date
[INFO] 10/Aug/2021 12:05:03 - Detecting Trackers
[INFO] 10/Aug/2021 12:05:04 - APK -> JAVA
[INFO] 10/Aug/2021 12:05:04 - Decompiling to Java with jadx
[ERROR] 10/Aug/2021 12:05:04 - NIAP scan
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/libsast/core_matcher/choice_matcher.py", line 76, in choice_matcher
    if sfile.stat().st_size / 1000 / 1000 > 5:
  File "/usr/lib/python3.8/pathlib.py", line 1198, in stat
    return self._accessor.stat(self)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.MobSF/uploads/9cbec5e94d47d39cafe0ea1da0dca309/java_source/c/b/o/j/p.java'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/sast_engine.py", line 39, in niap_scan
    res = scanner.scan()
  File "/usr/local/lib/python3.8/dist-packages/libsast/scanner.py", line 61, in scan
    results['choice_matcher'] = ChoiceMatcher(
  File "/usr/local/lib/python3.8/dist-packages/libsast/core_matcher/choice_matcher.py", line 42, in scan
    self.choice_matcher(scan_paths, rule)
  File "/usr/local/lib/python3.8/dist-packages/libsast/core_matcher/choice_matcher.py", line 94, in choice_matcher
    raise exceptions.RuleProcessingException('Rule processing error.')
libsast.exceptions.RuleProcessingException: Rule processing error.
[ERROR] 10/Aug/2021 12:05:04 - Performing Code Analysis
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/code_analysis.py", line 67, in code_analysis
    for pfile in Path(src).rglob('*'):
  File "/usr/lib/python3.8/pathlib.py", line 1152, in rglob
    for p in selector.select_from(self):
  File "/usr/lib/python3.8/pathlib.py", line 586, in _select_from
    for starting_point in self._iterate_directories(parent_path, is_dir, scandir):
  File "/usr/lib/python3.8/pathlib.py", line 576, in _iterate_directories
    for p in self._iterate_directories(path, is_dir, scandir):
  File "/usr/lib/python3.8/pathlib.py", line 576, in _iterate_directories
    for p in self._iterate_directories(path, is_dir, scandir):
  File "/usr/lib/python3.8/pathlib.py", line 576, in _iterate_directories
    for p in self._iterate_directories(path, is_dir, scandir):
  File "/usr/lib/python3.8/pathlib.py", line 565, in _iterate_directories
    with scandir(parent_path) as scandir_it:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.MobSF/uploads/9cbec5e94d47d39cafe0ea1da0dca309/java_source/c/b/p'
[INFO] 10/Aug/2021 12:05:05 - Running Quark 21.6.3
[+] DONE: Complete downloading the latest quark-rules
Requested API level 30 is larger than maximum we have, returning API level 28 instead.
[INFO] 10/Aug/2021 12:05:37 - Extracting Strings from APK
Requested API level 30 is larger than maximum we have, returning API level 28 instead.
[ERROR] 10/Aug/2021 12:05:38 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 239, in static_analyzer
    code_an_dic['urls_list'].extend(
TypeError: 'NoneType' object is not subscriptable
[ERROR] 10/Aug/2021 12:05:38 - 'NoneType' object is not subscriptable
[ERROR] 10/Aug/2021 12:05:38 - Internal Server Error: /static_analyzer/
[2021-08-10 12:05:56 +0000] [29] [WARNING] Worker with pid 419 was terminated due to signal 9
[2021-08-10 12:05:56 +0000] [679] [INFO] Booting worker with pid: 679
```

**Comment by ajinabraham** [comment]
You need to use arm image on M1 mac.
https://hub.docker.com/r/opensecurity/mobile-security-framework-mobsf/tags
