### ISSUE TITLE
运行 ./setup.sh报错

### ISSUE THREAD

**Issue by MoShenGuo** [MobSF/Mobile-Security-Framework-MobSF#1790]
## ENVIRONMENT

```
OS and Version:macOS Big Sur
Python Version:3.8
MobSF Version:最新下载master分支代码
```

## EXPLANATION OF THE ISSUE

报错:
[ERROR] Installation Failed!
Please ensure that all the requirements mentioned in documentation are installed before you run setup script.
Scroll up to see any installtion errors.

The 'decorator==4.4.2' distribution was not found and is required by the application
![image](https://user-images.githubusercontent.com/21171688/130026779-f5485446-bd62-476b-baed-f5d61d3fa434.png)
![image](https://user-images.githubusercontent.com/21171688/130026805-ac92768f-2648-436a-a464-cd02e2afa1d8.png)
![image](https://user-images.githubusercontent.com/21171688/130026850-db79d98e-7923-4208-bc2b-932017bed722.png)

![image](https://user-images.githubusercontent.com/21171688/130026672-6c952b53-2fbb-411b-adca-7ace9c002d63.png)

**Comment by ajinabraham** [comment]
Please use slack channel for support

**Comment by MoShenGuo** [comment]
Last login: Thu Aug 19 16:37:09 on ttys001
bodadmin@bodadmindeMac-mini ~ % cd /Users/bodadmin/Desktop/MobSF/Mobile-Security-Framework-MobSF
bodadmin@bodadmindeMac-mini Mobile-Security-Framework-MobSF % sudo ./setup.sh
Password:
[INSTALL] Found Python 3.8.2
pip 21.2.4 from /Library/Python/3.8/site-packages/pip (python 3.8)
[INSTALL] Found pip
Requirement already satisfied: pip in /Library/Python/3.8/site-packages (21.2.4)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
xcode-select version 2384.
[INSTALL] Found Xcode
[INSTALL] Using python virtualenv
[INSTALL] Activating virtualenv
WARNING: The directory '/Users/bodadmin/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/Users/bodadmin/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pip
  Downloading https://files.pythonhosted.org/packages/ca/31/b88ef447d595963c01060998cb329251648acf4a067721b0452c45527eb8/pip-21.2.4-py3-none-any.whl (1.6MB)
     |████████████████████████████████| 1.6MB 25kB/s 
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-21.2.4
[INSTALL] Installing Requirements
Ignoring waitress: markers 'platform_system == "Windows"' don't match your environment
Collecting Django>=3.1.5
  Downloading Django-3.2.6-py3-none-any.whl (7.9 MB)
     |████████████▋                   | 3.1 MB 16 kB/s eta 0:04:47ERROR: Exception:
Traceback (most recent call last):
  File "/Users/bodadmin/Desktop/MobSF/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/Users/bodadmin/Desktop/MobSF/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 458, in read
    n = self.readinto(b)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bodadmin/Desktop/MobSF/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/Users/bodadmin/Desktop/MobSF/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/Users/bodadmin/Desktop/MobSF/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 315, in run
    requirement_set = resolver.resolve(
  File "/Users/bodadmin/Desktop/MobSF/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 172, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/Users/bodadmin/Desktop/MobSF/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 370, in _resolve_one
    dist = self._get_dist_for(req_to_install)
  File "/Users/bodadmin/Desktop/MobSF/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 323, in _get_dist_for
    dist = self.preparer.prepare_linked_requirement(req)
  File "/Users/bodadmin/Desktop/MobSF/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/Users/bodadmin/Desktop/MobSF/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 550, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/Users/bodadmin/Desktop/MobSF/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 239, in unpack_url
    file = get_http_url(
  File "/Users/bodadmin/Desktop/MobSF/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 102, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/Users/bodadmin/Desktop/MobSF/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/pip/_internal/network/download.py", line 145, in __call__
    for chunk in chunks:
  File "/Users/bodadmin/Desktop/MobSF/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/pip/_internal/cli/progress_bars.py", line 144, in iter
    for x in it:
  File "/Users/bodadmin/Desktop/MobSF/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "/Users/bodadmin/Desktop/MobSF/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Users/bodadmin/Desktop/MobSF/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/bodadmin/Desktop/MobSF/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
[INSTALL] Clean Up

=======================MobSF Clean Script for Unix=======================
Running this script will delete the Scan database, all files uploaded and generated.

Deleting all Uploads
Deleting all Downloads
Deleting Static Analyzer Migrations
Deleting Dynamic Analyzer Migrations
Deleting MobSF Migrations
Deleting python byte code files
Deleting temp and log files
Deleting DB
Deleting Secret File
Done
[INSTALL] Migrating Database
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
./setup.sh: line 71: wkhtmltopdf: command not found
Download and Install wkhtmltopdf for PDF Report Generation - https://wkhtmltopdf.org/downloads.html
[INSTALL] Installation Complete
[ERROR] Installation Failed!
Please ensure that all the requirements mentioned in documentation are installed before you run setup script.
Scroll up to see any installtion errors.

The 'decorator==4.4.2' distribution was not found and is required by the application
bodadmin@bodadmindeMac-mini Mobile-Security-Framework-MobSF %

**Comment by jianjiaoxia** [comment]
解决了吗找不到django
