### ISSUE TITLE
manifile.read() utf-8 error

### ISSUE THREAD

**Issue by firmianay** [MobSF/Mobile-Security-Framework-MobSF#1792]
## ENVIRONMENT

```
OS and Version:Linux firmy-vm 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Python Version:Python 3.8.10
MobSF Version:v3.4.5 Beta
```

```
[INFO] 19/Aug/2021 13:55:33 - Reading Code Signing Certificate
[ERROR] 19/Aug/2021 13:55:33 - Reading Code Signing Certificate
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/cert_analysis.py", line 114, in cert_info
    manidat = manifile.read()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 18104-18105: invalid continuation byte
```

**Comment by superpoussin22** [comment]
can you share the apk ?

**Comment by ajinabraham** [comment]
No response. Closing.
