### ISSUE TITLE
MobSF fails on generate report 

### ISSUE THREAD

**Issue by mastercho** [MobSF/Mobile-Security-Framework-MobSF#1813]
## ENVIRONMENT

```
OS and Version: Windows 10 Pro- version 20H2
Python Version:  3.9.5
MobSF Version: 3.4.3 
```

## EXPLANATION OF THE ISSUE

```
I did dynamic analysis on com.dave package all good then when i click generate reports got error 
```

```
[ERROR] 22/Sep/2021 07:03:03 - Dynamic Analysis Report Generation
Traceback (most recent call last):
  File "C:\Users\Mastercho\Desktop\Mobile-Security-Framework-MobSF-3.4.3\mobsf\DynamicAnalyzer\views\android\report.py", line 75, in view_report
    analysis_result = run_analysis(app_dir, checksum, package)
  File "C:\Users\Mastercho\Desktop\Mobile-Security-Framework-MobSF-3.4.3\mobsf\DynamicAnalyzer\views\android\analysis.py", line 47, in run_analysis
    urls = re.findall(url_pattern, datas['traffic'].lower())
MemoryError
[ERROR] 22/Sep/2021 07:03:03 - Error Geneating Dynamic Analysis Report.
[ERROR] 22/Sep/2021 07:03:03 - Internal Server Error: /dynamic_report/430b90d87dccb83d611d840dc23b933b
ERROR:django.request:Internal Server Error: /dynamic_report/430b90d87dccb83d611d840dc23b933b
```
## STEPS TO REPRODUCE THE ISSUE

```
1. Run Dynamic analysis on com.dave package
2. Click generate report
3. Got error
```

## LOG FILE

```
[INFO] 22/Sep/2021 06:50:59 - Collecting Data and Cleaning Up
[INFO] 22/Sep/2021 06:50:59 - Downloading logcat logs
[INFO] 22/Sep/2021 06:50:59 - Downloading dumpsys logs
[INFO] 22/Sep/2021 06:51:02 - Stopping app
[INFO] 22/Sep/2021 06:51:02 - Removing Global Proxy for Android VM
[INFO] 22/Sep/2021 06:51:03 - Downloading app data
[INFO] 22/Sep/2021 06:51:12 - Archiving files created by app
[INFO] 22/Sep/2021 06:51:12 - Downloading Archive
[INFO] 22/Sep/2021 06:51:14 - Stopping ADB server
[INFO] 22/Sep/2021 06:51:14 - Dynamic Analysis Report Generation
[INFO] 22/Sep/2021 06:51:14 - Frida API Monitor Analysis
[INFO] 22/Sep/2021 06:51:14 - Dynamic File Analysis
[ERROR] 22/Sep/2021 06:51:15 - Dynamic Analysis Report Generation
Traceback (most recent call last):
  File "C:\Users\Mastercho\Desktop\Mobile-Security-Framework-MobSF-3.4.3\mobsf\DynamicAnalyzer\views\android\report.py", line 75, in view_report
    analysis_result = run_analysis(app_dir, checksum, package)
  File "C:\Users\Mastercho\Desktop\Mobile-Security-Framework-MobSF-3.4.3\mobsf\DynamicAnalyzer\views\android\analysis.py", line 47, in run_analysis
    urls = re.findall(url_pattern, datas['traffic'].lower())
MemoryError
[ERROR] 22/Sep/2021 06:51:15 - Error Geneating Dynamic Analysis Report. 
[ERROR] 22/Sep/2021 06:51:15 - Internal Server Error: /dynamic_report/430b90d87dccb83d611d840dc23b933b
```

**Comment by ajinabraham** [comment]
This is due to the resource constraints of your system. The APK is about 380MB in size.
