### ISSUE TITLE
[ERROR] 14/Oct/2021 08:09:01 - Performing Binary Analysis

### ISSUE THREAD

**Issue by lsq-connect** [MobSF/Mobile-Security-Framework-MobSF#1826]
After docker deployment or script deployment, the following error occurs when analyzing apK files：

Unknown format
[ERROR] 14/Oct/2021 08:09:01 - Performing Binary Analysis
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/binary_analysis.py", line 248, in elf_analysis
    elf_find = chk.checksec()
  File "/root/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/binary_analysis.py", line 19, in checksec
    is_nx = self.is_nx()
  File "/root/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/binary_analysis.py", line 174, in is_nx
    return self.elf.has_nx
AttributeError: 'NoneType' object has no attribute 'has_nx'

![image](https://user-images.githubusercontent.com/53843638/137277610-bd98d493-455c-4b7d-9352-126066821d0d.png)

**Comment by ajinabraham** [comment]
Please share the APK to debug this further (ajin25)[gmail.com]

**Comment by ajinabraham** [comment]
I am sorry, but for errors like this, we need the APK to troubleshoot. I am closing this for now. Maybe you can reach back when you are planning to publish the APK over GooglePlay store.
