### ISSUE TITLE
Corellium Frida Server Error

### ISSUE THREAD

**Issue by emrecangerede** [MobSF/Mobile-Security-Framework-MobSF#1828]
## ENVIRONMENT

```
OS and Version: Windows 10
Python Version: 3.8.8
MobSF Version: v3.8.5 Beta
```

## EXPLANATION OF THE ISSUE

```
After successfully finished the static analysis and going for the dynamic analysis its all good up-to the stage where we need to click the Start Instrumentation. Its showing Frida server is running and suddenly it falling into an error, which is Error Connecting to Frida.

```

## STEPS TO REPRODUCE THE ISSUE

```
1. Uploading APK and Completed the static Analysis
2. Moving to Dynamic analysis tab and completed the MobSFy Android Run time Successfully without any error
3.  Selecting an app for Dynamic analysis and clicking on the Start instrumentation
4.  log showing frida server is running 
5.  Next the error occurring Error Connecting To Frida

```

## LOG FILE

```
[INFO] 15/Oct/2021 15:26:38 - Creating Dynamic Analysis Environment for com.turkcell.bip
[INFO] 15/Oct/2021 15:26:40 - ADB Restarted
[INFO] 15/Oct/2021 15:26:40 - Waiting for 2 seconds...
[INFO] 15/Oct/2021 15:26:42 - Connecting to Android 10.11.1.4:5001
[INFO] 15/Oct/2021 15:26:42 - Waiting for 2 seconds...
[INFO] 15/Oct/2021 15:26:44 - Restarting ADB Daemon as root
[INFO] 15/Oct/2021 15:26:45 - Waiting for 2 seconds...
[INFO] 15/Oct/2021 15:26:47 - Reconnecting to Android Device
[INFO] 15/Oct/2021 15:26:47 - Waiting for 2 seconds...
[INFO] 15/Oct/2021 15:26:51 - Found Corellium ARM Android VM
[INFO] 15/Oct/2021 15:26:51 - Remounting
[INFO] 15/Oct/2021 15:26:52 - Performing System check
[INFO] 15/Oct/2021 15:26:52 - Android API Level identified as 25
[INFO] 15/Oct/2021 15:26:53 - Android Version identified as 7.1
[INFO] 15/Oct/2021 15:26:53 - Environment MobSFyed Check
[INFO] 15/Oct/2021 15:26:53 - Installing MobSF RootCA
[INFO] 15/Oct/2021 15:26:55 - Starting HTTPs Proxy on 1337
[INFO] 15/Oct/2021 15:26:55 - Killing httptools UI
[INFO] 15/Oct/2021 15:26:55 - Enabling ADB Reverse TCP on 1337
[INFO] 15/Oct/2021 15:26:55 - Setting Global Proxy for Android VM
[INFO] 15/Oct/2021 15:26:56 - Starting Clipboard Monitor
[INFO] 15/Oct/2021 15:26:57 - Getting screen resolution
[INFO] 15/Oct/2021 15:26:58 - Installing APK - com.turkcell.bip
[INFO] 15/Oct/2021 15:34:26 - Testing Environment is Ready!
[INFO] 15/Oct/2021 15:35:56 - Starting Instrumentation
[INFO] 15/Oct/2021 15:35:56 - Starting Frida Server
[INFO] 15/Oct/2021 15:35:56 - Waiting for 2 seconds...
[ERROR] 15/Oct/2021 15:35:59 - Error Connecting to Frida
Traceback (most recent call last):
  File "C:\Users\emrec\Mobile-Security-Framework-MobSF\mobsf\DynamicAnalyzer\views\android\frida_core.py", line 129, in connect
    pid = device.spawn([self.package])
  File "C:\Users\emrec\Mobile-Security-Framework-MobSF\venv\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\emrec\Mobile-Security-Framework-MobSF\venv\lib\site-packages\frida\core.py", line 149, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.NotSupportedError: need Gadget to attach on jailed Android; its default location is: C:\Users\emrec\AppData\Local\Microsoft\Windows\INetCache\frida\gadget-android-arm64.so

```

**Comment by mastercho** [comment]
i notice this happens if you have independently Frida installed in your PC, and MobSF throws this error. If you uninstall Frida then would be fine

**Comment by darkk9712** [comment]
I don't know how, but when I run dynamic analysis for android 8.1.0 version, I didn't get any error. Dynamic analysis for android version 7.1.2 creates problems in Corellium. Thanks
