### ISSUE TITLE
Old version just stop working 

### ISSUE THREAD

**Issue by mastercho** [MobSF/Mobile-Security-Framework-MobSF#1837]
## ENVIRONMENT

```
OS and Version: Windows 10 2021H
Python Version:Python38
MobSF Version: 3.4.3
```

## EXPLANATION OF THE ISSUE

```
It's was only good working version and its just stop working from nowhere and when I click run.bat I get error which is bellow
```

## STEPS TO REPRODUCE THE ISSUE

```
Double click on run.bat and got error bellow
```

## LOG FILE

```
Error processing line 1 of C:\Users\Mastercho\Desktop\Mobile-Security-Framework-MobSF-3.4.3\venv\lib\site-packages\protobuf-3.18.0-py3.8-nspkg.pth:

  Traceback (most recent call last):
    File "C:\Program Files (x86)\Python38-32\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 553, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
Error processing line 1 of C:\Users\Mastercho\Desktop\Mobile-Security-Framework-MobSF-3.4.3\venv\lib\site-packages\protobuf-3.18.0-py3.8-nspkg.pth:

  Traceback (most recent call last):
    File "C:\Program Files (x86)\Python38-32\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 553, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
```

**Comment by Heufiih** [comment]
Good

**Comment by Heufiih** [comment]
Uploading cv-304931b8_1635775075582_sc_w_v.mp4…

**Comment by superpoussin22** [comment]
use slack please

**Comment by mastercho** [comment]
For these which have same issue, i fix it by adding python site packages into PATH Env. in Windows
