### ISSUE TITLE
[Docker Persistence] Not enough privileges to write in volumes

### ISSUE THREAD

**Issue by roxax19** [MobSF/Mobile-Security-Framework-MobSF#1886]
## ENVIRONMENT

```
OS and Version: Ubuntu 20.04
Python Version: 3.8.10
MobSF Version: 3.4 beta
```

## EXPLANATION OF THE ISSUE

```
When I try to run a MobSF container with a volume, it fails. In the latests updates of the Dockerfile, MobSF starts using "mobsf" user instead of "root". It doesn't have the needed privileges for writing config and database files into "/home/mobsf/.MobSF/*" when sharing a volume.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. Using the Docs command: docker run -it --rm --name mobsf -p 8000:8000 -v <your_local_dir>:/home/mobsf/.MobSF opensecurity/mobile-security-framework-mobsf:latest

```

## LOG FILE

```
Cannot create config file
Traceback (most recent call last):
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/MobSF/init.py", line 64, in create_user_conf
    with open(config_path, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/home/mobsf/.MobSF/config.py'
Creating MobSF Home Directory
Traceback (most recent call last):
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/MobSF/init.py", line 118, in get_mobsf_home
    os.makedirs(dwd_dir)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/mobsf/.MobSF/downloads/'
Traceback (most recent call last):
  File "manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 369, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 84, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 71, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 179, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/MobSF/settings.py", line 32, in <module>
    DWD_DIR = os.path.join(MobSF_HOME, 'downloads/')
  File "/usr/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2022-01-20 11:52:18 +0000] [8] [INFO] Starting gunicorn 20.1.0
[2022-01-20 11:52:18 +0000] [8] [INFO] Listening at: http://0.0.0.0:8000 (8)
[2022-01-20 11:52:18 +0000] [8] [INFO] Using worker: gthread
[2022-01-20 11:52:18 +0000] [10] [INFO] Booting worker with pid: 10
Cannot create config file
Traceback (most recent call last):
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/MobSF/init.py", line 64, in create_user_conf
    with open(config_path, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/home/mobsf/.MobSF/config.py'
Creating MobSF Home Directory
Traceback (most recent call last):
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/MobSF/init.py", line 118, in get_mobsf_home
    os.makedirs(dwd_dir)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/mobsf/.MobSF/downloads/'
[2022-01-20 11:52:18 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/MobSF/wsgi.py", line 16, in <module>
    from . import settings
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/MobSF/settings.py", line 32, in <module>
    DWD_DIR = os.path.join(MobSF_HOME, 'downloads/')
  File "/usr/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2022-01-20 11:52:18 +0000] [10] [INFO] Worker exiting (pid: 10)
[2022-01-20 11:52:18 +0000] [8] [INFO] Shutting down: Master
[2022-01-20 11:52:18 +0000] [8] [INFO] Reason: Worker failed to boot.

```

**Comment by ajinabraham** [comment]
As you observed, we recently moved to [non-root container images](https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/33abc69b54689fb535c72c720b593dc7ed21a4cf/Dockerfile#L55-L56) and due to this, there is permission issues attempting to write to host mount. 

Here are some work around pointers:
https://stackoverflow.com/a/67021906
https://github.com/moby/moby/issues/2259
https://stackoverflow.com/a/39398511

**Comment by ajinabraham** [comment]
Also upon testing this on mac, it works fine at my end with docker desktop default install.

```
MobSF v3.4.6 Beta

docker version
Client:
 Cloud integration: v1.0.22
 Version:           20.10.11

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11

docker run -it --rm --name mobsf -p 8001:8000 -v /Users/***/Desktop/foo:/home/mobsf/.MobSF opensecurity/mobile-security-framework-mobsf:latest

# Did Static Analysis

 ls /Users/***/Desktop/foo
__pycache__ config.py   db.sqlite3  debug.log   downloads   secret      signatures  uploads
```

I think you have some other permission issue.

**Comment by ajinabraham** [comment]
If you are on linux, you might want to do this.

```
mkdir /Users/x/Desktop/foo
chown 9901:9901 /Users/x/Desktop/foo
docker run -it --rm --name mobsf -p 8001:8000 -v /Users/x/Desktop/foo:/home/mobsf/.MobSF opensecurity/mobile-security-framework-mobsf:latest
```
I will also update the docs.
