### ISSUE TITLE
PermissionError while executing a scan via Docker image

### ISSUE THREAD

**Issue by leinardi** [MobSF/Mobile-Security-Framework-MobSF#1890]
## ENVIRONMENT

```
Latest docker image from `opensecurity/mobile-security-framework-mobsf`
```

## EXPLANATION OF THE ISSUE
When I try to run a scan on an APK file via GitHub Actions, I get this permission error.
```
/usr/bin/docker run --name e18ec40738fe647c98963be178b53a067_031a64 --label 84217e --workdir /github/workspace --rm -e TERM -e JAVA_HOME -e GRADLE_BUILD_ACTION_CACHE_RESTORED -e INPUT_FILE_NAME -e SCAN_TYPE -e OUTPUT_FILE_NAME -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/Forlago/Forlago":"/github/workspace" 84217e:18ec40738fe647c98963be178b53a067
[2022-01-29 13:20:19 +0000] [12] [INFO] Starting gunicorn 20.1.0
[2022-01-29 13:20:19 +0000] [12] [INFO] Listening at: http://127.0.0.1:8000 (12)
[2022-01-29 13:20:19 +0000] [12] [INFO] Using worker: gthread
[2022-01-29 13:20:19 +0000] [15] [INFO] Booting worker with pid: 15
Creating MobSF Home Directory
Traceback (most recent call last):
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/MobSF/init.py", line 111, in get_mobsf_home
    os.makedirs(mobsf_home)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/github/home/.MobSF'
Error: 1-29 13:20:19 +0000] [15] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/MobSF/wsgi.py", line 16, in <module>
    from . import settings
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/MobSF/settings.py", line 32, in <module>
    DWD_DIR = os.path.join(MobSF_HOME, 'downloads/')
  File "/usr/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2022-01-29 13:20:19 +0000] [15] [INFO] Worker exiting (pid: 15)
[2022-01-29 13:20:19 +0000] [12] [INFO] Shutting down: Master
[2022-01-29 13:20:19 +0000] [12] [INFO] Reason: Worker failed to boot.
[/api/v1/upload] Upload the app to MobSF
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to localhost port 8000: Connection refused
```

## STEPS TO REPRODUCE THE ISSUE

```
Run this GitHub Action: https://github.com/leinardi/Forlago/runs/4991330190?check_suite_focus=true#step:11:21
```
I'm not 100% sure if it's an issue with the Docker image or with the GitHub Action so I opened an issue also on the Action's tracker: https://github.com/fundacaocerti/mobsf-action/issues/15

**Comment by ajinabraham** [comment]
The latest MobSF docker containers run as non root.
When using local mounts, you need to set appropriate permissions. The fix needs to be implemented in the action.

 https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1886#issuecomment-1022819570

**Comment by leinardi** [comment]
> When using local mounts, you need to set appropriate permissions. The fix needs to be implemented in the action.

Paging @inm-certi...
