### ISSUE TITLE
Mapping key not found. - 'good'

### ISSUE THREAD

**Issue by alonf1983** [MobSF/Mobile-Security-Framework-MobSF#1891]
installed the new version v3.5.0 Beta
from this point every apk return: Error - Mapping key not found. -'good'

[ERROR] 30/Jan/2022 15:18:52 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/Users/alonf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 307, in static_analyzer
    context['appsec'] = get_android_dashboard(context, True)
  File "/Users/alonf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/common/appsec.py", line 134, in get_android_dashboard
    findings[i[0]].append({
KeyError: 'good'
[ERROR] 30/Jan/2022 15:18:52 - 'good'
[ERROR] 30/Jan/2022 15:18:52 - Internal Server Error: /static_analyzer/
^[[A[2022-01-30 17:21:33 +0200] [20440] [INFO] Handling signal: winch
[2022-01-30 17:21:33 +0200] [20440] [INFO] Handling signal: winch

please help

**Comment by ajinabraham** [comment]
Please read release docs.

**Comment by alonf1983** [comment]
Thanks.
I did fresh installed (rm -rf and new git clone) and same issue.
I tried also after the new fresh install:
```
git pull origin master
. venv/bin/activate
pip install --no-cache-dir --use-deprecated=legacy-resolver -r requirements.txt
python manage.py makemigrations
python manage.py makemigrations StaticAnalyzer
python manage.py migrate
deactivate
```

however, getting the same error:

[ERROR] 31/Jan/2022 09:25:11 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/Users/alonf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 307, in static_analyzer
    context['appsec'] = get_android_dashboard(context, True)
  File "/Users/alonf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/common/appsec.py", line 134, in get_android_dashboard
    findings[i[0]].append({
KeyError: 'good'
[ERROR] 31/Jan/2022 09:25:11 - 'good'
[ERROR] 31/Jan/2022 09:25:11 - Internal Server Error: /static_analyzer/


could you help please?
