### ISSUE TITLE
SCRAM authentication requires libpq version 10 or above

### ISSUE THREAD

**Issue by t3chn0m4g3** [MobSF/Mobile-Security-Framework-MobSF#1898]
## ENVIRONMENT

```
Host OS and Version: Docker (macOS 12.2)
Container: Ubuntu 20.04
Python Version: 3.8
MobSF Version: 3.5.1 Beta
Architecture: Apple Silicon / ARM64
```

## EXPLANATION OF THE ISSUE

Running `docker-compose up` (on provided `Dockerfile`, `docker-compose.yml`) results in the following error with immediate `exit 1`. Using the DockerHub image [opensecurity/mobile-security-framework-mobsf:latest](https://hub.docker.com/r/opensecurity/mobile-security-framework-mobsf/tags) (arm64) works fine BTW.
```
mobile-security-framework-mobsf-mobsf-1     |   __  __       _    ____  _____       _____  ____
mobile-security-framework-mobsf-mobsf-1     |  |  \/  | ___ | |__/ ___||  ___|_   _|___ / | ___|
mobile-security-framework-mobsf-mobsf-1     |  | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \ |___ \
mobile-security-framework-mobsf-mobsf-1     |  | |  | | (_) | |_) |__) |  _|  \ V / ___) | ___) |
mobile-security-framework-mobsf-mobsf-1     |  |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)____/
mobile-security-framework-mobsf-mobsf-1     |
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:31 - Mobile Security Framework v3.5.1 Beta
mobile-security-framework-mobsf-mobsf-1     | REST API Key: d3b60459e14d512a11fa38ae5dd1d238a57d4e92ba5ba43da8cd53d617b3777a
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:31 - OS: Linux
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:31 - Platform: Linux-5.10.76-linuxkit-aarch64-with-glibc2.29
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:31 - Dist: ubuntu 20.04 focal
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:31 - MobSF Basic Environment Check
mobile-security-framework-mobsf-mobsf-1     | Traceback (most recent call last):
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 230, in ensure_connection
mobile-security-framework-mobsf-mobsf-1     |     self.connect()
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 25, in inner
mobile-security-framework-mobsf-mobsf-1     |     return func(*args, **kwargs)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 211, in connect
mobile-security-framework-mobsf-mobsf-1     |     self.connection = self.get_new_connection(conn_params)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 25, in inner
mobile-security-framework-mobsf-mobsf-1     |     return func(*args, **kwargs)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/postgresql/base.py", line 199, in get_new_connection
mobile-security-framework-mobsf-mobsf-1     |     connection = Database.connect(**conn_params)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/psycopg2/__init__.py", line 122, in connect
mobile-security-framework-mobsf-mobsf-1     |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
mobile-security-framework-mobsf-mobsf-1     | psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
mobile-security-framework-mobsf-mobsf-1     |
```

## STEPS TO REPRODUCE THE ISSUE

```
1. docker-compose build
2. docker-compose up
```

## LOG FILE

```
mobile-security-framework-mobsf-postgres-1  |
mobile-security-framework-mobsf-postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
mobile-security-framework-mobsf-postgres-1  |
mobile-security-framework-mobsf-postgres-1  | 2022-02-08 12:53:28.266 UTC [1] LOG:  starting PostgreSQL 14.1 (Debian 14.1-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
mobile-security-framework-mobsf-postgres-1  | 2022-02-08 12:53:28.266 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
mobile-security-framework-mobsf-postgres-1  | 2022-02-08 12:53:28.266 UTC [1] LOG:  listening on IPv6 address "::", port 5432
mobile-security-framework-mobsf-postgres-1  | 2022-02-08 12:53:28.268 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
mobile-security-framework-mobsf-postgres-1  | 2022-02-08 12:53:28.271 UTC [27] LOG:  database system was shut down at 2022-02-08 11:40:36 UTC
mobile-security-framework-mobsf-postgres-1  | 2022-02-08 12:53:28.279 UTC [1] LOG:  database system is ready to accept connections
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:29 -
mobile-security-framework-mobsf-mobsf-1     |   __  __       _    ____  _____       _____  ____
mobile-security-framework-mobsf-mobsf-1     |  |  \/  | ___ | |__/ ___||  ___|_   _|___ / | ___|
mobile-security-framework-mobsf-mobsf-1     |  | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \ |___ \
mobile-security-framework-mobsf-mobsf-1     |  | |  | | (_) | |_) |__) |  _|  \ V / ___) | ___) |
mobile-security-framework-mobsf-mobsf-1     |  |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)____/
mobile-security-framework-mobsf-mobsf-1     |
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:29 - Mobile Security Framework v3.5.1 Beta
mobile-security-framework-mobsf-mobsf-1     | REST API Key: d3b60459e14d512a11fa38ae5dd1d238a57d4e92ba5ba43da8cd53d617b3777a
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:29 - OS: Linux
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:29 - Platform: Linux-5.10.76-linuxkit-aarch64-with-glibc2.29
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:29 - Dist: ubuntu 20.04 focal
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:29 - MobSF Basic Environment Check
mobile-security-framework-mobsf-mobsf-1     | /usr/local/lib/python3.8/dist-packages/django/core/management/commands/makemigrations.py:105: RuntimeWarning: Got an error checking a consistent migration history performed for database connection 'default': SCRAM authentication requires libpq version 10 or above
mobile-security-framework-mobsf-mobsf-1     |
mobile-security-framework-mobsf-mobsf-1     |   warnings.warn(
mobile-security-framework-mobsf-mobsf-1     | No changes detected
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:29 - Checking for Update.
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:30 - No updates available.
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:30 -
mobile-security-framework-mobsf-mobsf-1     |   __  __       _    ____  _____       _____  ____
mobile-security-framework-mobsf-mobsf-1     |  |  \/  | ___ | |__/ ___||  ___|_   _|___ / | ___|
mobile-security-framework-mobsf-mobsf-1     |  | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \ |___ \
mobile-security-framework-mobsf-mobsf-1     |  | |  | | (_) | |_) |__) |  _|  \ V / ___) | ___) |
mobile-security-framework-mobsf-mobsf-1     |  |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)____/
mobile-security-framework-mobsf-mobsf-1     |
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:30 - Mobile Security Framework v3.5.1 Beta
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:30 - OS: Linux
mobile-security-framework-mobsf-mobsf-1     | REST API Key: d3b60459e14d512a11fa38ae5dd1d238a57d4e92ba5ba43da8cd53d617b3777a
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:30 - Platform: Linux-5.10.76-linuxkit-aarch64-with-glibc2.29
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:30 - Dist: ubuntu 20.04 focal
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:30 - MobSF Basic Environment Check
mobile-security-framework-mobsf-mobsf-1     | /usr/local/lib/python3.8/dist-packages/django/core/management/commands/makemigrations.py:105: RuntimeWarning: Got an error checking a consistent migration history performed for database connection 'default': SCRAM authentication requires libpq version 10 or above
mobile-security-framework-mobsf-mobsf-1     |
mobile-security-framework-mobsf-mobsf-1     |   warnings.warn(
mobile-security-framework-mobsf-mobsf-1     | Migrations for 'StaticAnalyzer':
mobile-security-framework-mobsf-mobsf-1     |   mobsf/StaticAnalyzer/migrations/0001_initial.py
mobile-security-framework-mobsf-mobsf-1     |     - Create model RecentScansDB
mobile-security-framework-mobsf-mobsf-1     |     - Create model StaticAnalyzerAndroid
mobile-security-framework-mobsf-mobsf-1     |     - Create model StaticAnalyzerIOS
mobile-security-framework-mobsf-mobsf-1     |     - Create model StaticAnalyzerWindows
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:30 - Checking for Update.
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:30 - No updates available.
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:31 -
mobile-security-framework-mobsf-mobsf-1     |   __  __       _    ____  _____       _____  ____
mobile-security-framework-mobsf-mobsf-1     |  |  \/  | ___ | |__/ ___||  ___|_   _|___ / | ___|
mobile-security-framework-mobsf-mobsf-1     |  | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \ |___ \
mobile-security-framework-mobsf-mobsf-1     |  | |  | | (_) | |_) |__) |  _|  \ V / ___) | ___) |
mobile-security-framework-mobsf-mobsf-1     |  |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)____/
mobile-security-framework-mobsf-mobsf-1     |
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:31 - Mobile Security Framework v3.5.1 Beta
mobile-security-framework-mobsf-mobsf-1     | REST API Key: d3b60459e14d512a11fa38ae5dd1d238a57d4e92ba5ba43da8cd53d617b3777a
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:31 - OS: Linux
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:31 - Platform: Linux-5.10.76-linuxkit-aarch64-with-glibc2.29
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:31 - Dist: ubuntu 20.04 focal
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:31 - MobSF Basic Environment Check
mobile-security-framework-mobsf-mobsf-1     | Traceback (most recent call last):
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 230, in ensure_connection
mobile-security-framework-mobsf-mobsf-1     |     self.connect()
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 25, in inner
mobile-security-framework-mobsf-mobsf-1     |     return func(*args, **kwargs)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 211, in connect
mobile-security-framework-mobsf-mobsf-1     |     self.connection = self.get_new_connection(conn_params)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 25, in inner
mobile-security-framework-mobsf-mobsf-1     |     return func(*args, **kwargs)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/postgresql/base.py", line 199, in get_new_connection
mobile-security-framework-mobsf-mobsf-1     |     connection = Database.connect(**conn_params)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/psycopg2/__init__.py", line 122, in connect
mobile-security-framework-mobsf-mobsf-1     |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
mobile-security-framework-mobsf-mobsf-1     | psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
mobile-security-framework-mobsf-mobsf-1     |
mobile-security-framework-mobsf-mobsf-1     |
mobile-security-framework-mobsf-mobsf-1     | The above exception was the direct cause of the following exception:
mobile-security-framework-mobsf-mobsf-1     |
mobile-security-framework-mobsf-mobsf-1     | Traceback (most recent call last):
mobile-security-framework-mobsf-mobsf-1     |   File "manage.py", line 18, in <module>
mobile-security-framework-mobsf-mobsf-1     |     execute_from_command_line(sys.argv)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
mobile-security-framework-mobsf-mobsf-1     |     utility.execute()
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 419, in execute
mobile-security-framework-mobsf-mobsf-1     |     self.fetch_command(subcommand).run_from_argv(self.argv)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 373, in run_from_argv
mobile-security-framework-mobsf-mobsf-1     |     self.execute(*args, **cmd_options)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 417, in execute
mobile-security-framework-mobsf-mobsf-1     |     output = self.handle(*args, **options)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 90, in wrapped
mobile-security-framework-mobsf-mobsf-1     |     res = handle_func(*args, **kwargs)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/migrate.py", line 75, in handle
mobile-security-framework-mobsf-mobsf-1     |     self.check(databases=[database])
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 438, in check
mobile-security-framework-mobsf-mobsf-1     |     all_issues = checks.run_checks(
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/core/checks/registry.py", line 77, in run_checks
mobile-security-framework-mobsf-mobsf-1     |     new_errors = check(app_configs=app_configs, databases=databases)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/core/checks/model_checks.py", line 34, in check_all_models
mobile-security-framework-mobsf-mobsf-1     |     errors.extend(model.check(**kwargs))
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 1307, in check
mobile-security-framework-mobsf-mobsf-1     |     *cls._check_indexes(databases),
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 1699, in _check_indexes
mobile-security-framework-mobsf-mobsf-1     |     connection.features.supports_covering_indexes or
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 48, in __get__
mobile-security-framework-mobsf-mobsf-1     |     res = instance.__dict__[self.name] = self.func(instance)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/postgresql/features.py", line 84, in is_postgresql_11
mobile-security-framework-mobsf-mobsf-1     |     return self.connection.pg_version >= 110000
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 48, in __get__
mobile-security-framework-mobsf-mobsf-1     |     res = instance.__dict__[self.name] = self.func(instance)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/postgresql/base.py", line 339, in pg_version
mobile-security-framework-mobsf-mobsf-1     |     with self.temporary_connection():
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
mobile-security-framework-mobsf-mobsf-1     |     return next(self.gen)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 614, in temporary_connection
mobile-security-framework-mobsf-mobsf-1     |     with self.cursor() as cursor:
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 25, in inner
mobile-security-framework-mobsf-mobsf-1     |     return func(*args, **kwargs)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 270, in cursor
mobile-security-framework-mobsf-mobsf-1     |     return self._cursor()
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 246, in _cursor
mobile-security-framework-mobsf-mobsf-1     |     self.ensure_connection()
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 25, in inner
mobile-security-framework-mobsf-mobsf-1     |     return func(*args, **kwargs)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 230, in ensure_connection
mobile-security-framework-mobsf-mobsf-1     |     self.connect()
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 90, in __exit__
mobile-security-framework-mobsf-mobsf-1     |     raise dj_exc_value.with_traceback(traceback) from exc_value
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 230, in ensure_connection
mobile-security-framework-mobsf-mobsf-1     |     self.connect()
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 25, in inner
mobile-security-framework-mobsf-mobsf-1     |     return func(*args, **kwargs)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 211, in connect
mobile-security-framework-mobsf-mobsf-1     |     self.connection = self.get_new_connection(conn_params)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 25, in inner
mobile-security-framework-mobsf-mobsf-1     |     return func(*args, **kwargs)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/postgresql/base.py", line 199, in get_new_connection
mobile-security-framework-mobsf-mobsf-1     |     connection = Database.connect(**conn_params)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/psycopg2/__init__.py", line 122, in connect
mobile-security-framework-mobsf-mobsf-1     |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
mobile-security-framework-mobsf-mobsf-1     | django.db.utils.OperationalError: SCRAM authentication requires libpq version 10 or above
mobile-security-framework-mobsf-mobsf-1     |
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:31 - Checking for Update.
mobile-security-framework-mobsf-mobsf-1     | [INFO] 08/Feb/2022 12:53:31 - No updates available.
```

**Comment by ajinabraham** [comment]
@superpoussin22  any thoughts?

**Comment by V1ctorW1ll1an** [comment]
> For those on M1-Based macs who are currently seeing this issue in docker - there appears to a bug upstream in libpg that's building against the wrong library version on ARM.
> 
> Until it's fixed, a workaround is to (at a performance hit) is to just [run it via rosetta](https://docs.docker.com/desktop/mac/apple-silicon/).
> 
> export DOCKER_DEFAULT_PLATFORM=linux/amd64, and re-build your images.
> 
> You'll get the latest version of libpq, and things should Just Work.
> 
> Ref: https://issueexplorer.com/issue/psycopg/psycopg2/1360
> 
> [Share](https://stackoverflow.com/a/70238851)
> 
> Full link of the discussion : https://stackoverflow.com/questions/62807717/how-can-i-solve-postgresql-scram-authentifcation-problem

awesome!!!

**Comment by nirradi** [comment]
This works perfectly. but slower. Any other way that doesn't require changing the target platform?

**Comment by V1ctorW1ll1an** [comment]
> This works perfectly. but slower. Any other way that doesn't require changing the target platform?

I changed my pip file with psycopg2-binary to psycopg2 and now I don't need to use rosetta, this worked on arm perfectly.

<img width="738" alt="Screenshot 2022-12-30 at 22 56 40" src="https://user-images.githubusercontent.com/47677499/210121708-e32f138a-9aad-47f2-aef5-5d088a19e76b.png">
