### ISSUE TITLE
Database broken due to commit 996a57cfe89d7fcfd993cef1cd648e30d8d90b92

### ISSUE THREAD

**Issue by dummys** [MobSF/Mobile-Security-Framework-MobSF#1902]
Hi,

In the commit: https://github.com/MobSF/Mobile-Security-Framework-MobSF/commit/996a57cfe89d7fcfd993cef1cd648e30d8d90b92

The description keyword is renamed to message but inside the code it is not message, but still description.
Ho and by the way, all the Django template are broken too, now.
you should revert the Hotfix, and fix all the problem before. The variable CWE goes to metadata and son on.
and the https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/mobsf/StaticAnalyzer/views/common/appsec.py too

**Comment by cryptax** [comment]
Not sure if this is related, but I indeed have a **database error** in MobSF now. There is a SQL error complaining there is no column named `QUARK`.
Because of this dynamic analysis is no longer possible.

```
[INFO] 15/Feb/2022 16:43:04 - Saving to Database
[ERROR] 15/Feb/2022 16:43:04 - Updating DB
Traceback (most recent call last):
  File "/home/axelle/softs/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/axelle/softs/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: table StaticAnalyzer_staticanalyzerandroid has no column named QUARK

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/axelle/softs/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/db_interaction.py", line 202, in save_or_update
    StaticAnalyzerAndroid.objects.create(**values)
  File "/home/axelle/softs/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/axelle/softs/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/axelle/softs/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/axelle/softs/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/home/axelle/softs/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/django/db/models/base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/axelle/softs/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/django/db/models/base.py", line 906, in _do_insert
    return manager._insert(
  File "/home/axelle/softs/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/axelle/softs/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/axelle/softs/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/home/axelle/softs/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/axelle/softs/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/axelle/softs/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/axelle/softs/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/axelle/softs/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/axelle/softs/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/axelle/softs/Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: table StaticAnalyzer_staticanalyzerandroid has no column named QUARK
```

**Comment by ajinabraham** [comment]
Hi @dummys The code is also reflected to update the change. If you had updated MobSF to latest, please also update the the dependencies to the latest as well especially libsast which has changes to accommodate the yaml changes of description to message.

**Comment by dummys** [comment]
> 

are you sure ? I don't see any template change. so the metadata.description is not existing anymore because it's metadata.message, as seen inside your rules change.

**Comment by cryptax** [comment]
> @cryptax `table StaticAnalyzer_staticanalyzerandroid has no column named QUARK` is due to an incomplete DB migration. Please see docs on updating MobSF.

@ajinabraham indeed - thanks. It solved my issue. Not related to @dummys then, sorry!

**Comment by ajinabraham** [comment]
@dummys No, it's handled in libsast
https://github.com/ajinabraham/libsast/blob/3f0a9edb5e7f883e91fcdac513c0840cd3637f54/libsast/core_matcher/pattern_matcher.py#L108

**Comment by dummys** [comment]
ok so I don't see why I get error then. Last version of git, removed .MobSF. same error, cd['metadata']['description'] Installed using mkvirtualenv and pip install -r requirements.txt

**Comment by superpoussin22** [comment]
> nstalled using mkvirtualenv and pip install -r requirements.txt

If I remember well mkvirtualenv did not work like venv .
 pip install is also not enough you must run command to migrate

**Comment by ajinabraham** [comment]
@dummys Please move this discussions to our support slack channel.
