### ISSUE TITLE
Error: could not open file "G:\Mobile-Security-Framework-MobSF-3.4.6\venv\Lib\site-packages\apkid\rules\rules.yarc"

### ISSUE THREAD

**Issue by seczzq** [MobSF/Mobile-Security-Framework-MobSF#1942]
[ERROR] 10/Apr/2022 22:36:15 - Performing Binary Analysis
Traceback (most recent call last):
  File "G:\2022年安服服务区\三、APP渗透测试\2-MobSF自动测试区\Mobile-Security-Framework-MobSF-3.4.6\mobsf\StaticAnalyzer\views\android\binary_analysis.py", line 254, in elf_analysis
    elf_find = chk.checksec()
  File "G:\2022年安服服务区\三、APP渗透测试\2-MobSF自动测试区\Mobile-Security-Framework-MobSF-3.4.6\mobsf\StaticAnalyzer\views\android\binary_analysis.py", line 64, in checksec
    relro = self.relro()
  File "G:\2022年安服服务区\三、APP渗透测试\2-MobSF自动测试区\Mobile-Security-Framework-MobSF-3.4.6\mobsf\StaticAnalyzer\views\android\binary_analysis.py", line 198, in relro
    if bind_now in self.elf.get(flags):
TypeError: argument of type 'NoneType' is not iterable
[INFO] 10/Apr/2022 22:36:15 - Reading Code Signing Certificate
[INFO] 10/Apr/2022 22:36:16 - Running APKiD 2.1.2
[ERROR] 10/Apr/2022 22:36:16 - Error Performing Static Analysis
Traceback (most recent call last):
  File "G:\2022年安服服务区\三、APP渗透测试\2-MobSF自动测试区\Mobile-Security-Framework-MobSF-3.4.6\mobsf\StaticAnalyzer\views\android\static_analyzer.py", line 212, in static_analyzer
    apkid_results = apkid_analysis(app_dic[
  File "G:\Mobile-Security-Framework-MobSF-3.4.6\mobsf\MalwareAnalyzer\views\apkid.py", line 41, in apkid_analysis
    rules = options.rules_manager.load()
  File "G:\Mobile-Security-Framework-MobSF-3.4.6\venv\lib\site-packages\apkid\rules.py", line 46, in load
    self.rules = yara.load(self.rules_path)
yara.Error: could not open file "G:\Mobile-Security-Framework-MobSF-3.4.6\venv\Lib\site-packages\apkid\rules\rules.yarc"
[ERROR] 10/Apr/2022 22:36:16 - could not open file "G:\Mobile-Security-Framework-MobSF-3.4.6\venv\Lib\site-packages\apkid\rules\rules.yarc"
[ERROR] 10/Apr/2022 22:36:16 - Internal Server Error: /static_analyzer/
ERROR:django.request:Internal Server Error: /static_analyzer/

**Comment by hanshanyike** [comment]
@seczzq 我也遇到了这个问题，请问你解决了吗

**Comment by dabai123456** [comment]
我也遇到这个问题了，有人解决了么

**Comment by YingYeNaiAi** [comment]
大佬解决了吗

**Comment by Nw2bigone** [comment]
Can you solve this problem ?
