### ISSUE TITLE
Cant access reports.exodus-privacy.eu.org

### ISSUE THREAD

**Issue by eskiesirius** [MobSF/Mobile-Security-Framework-MobSF#1960]
I have this error
```
[ERROR] 10/May/2022 23:17:46 - [ERROR] Trackers DB Update
Traceback (most recent call last):
  File "D:\Software Projects\Mobile-Security-Framework-MobSF\venv\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "D:\Software Projects\Mobile-Security-Framework-MobSF\venv\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "D:\Users\****\anaconda3\lib\socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software Projects\Mobile-Security-Framework-MobSF\venv\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\Software Projects\Mobile-Security-Framework-MobSF\venv\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "D:\Software Projects\Mobile-Security-Framework-MobSF\venv\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "D:\Software Projects\Mobile-Security-Framework-MobSF\venv\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "D:\Software Projects\Mobile-Security-Framework-MobSF\venv\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000020CD8EFD8E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software Projects\Mobile-Security-Framework-MobSF\venv\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "D:\Software Projects\Mobile-Security-Framework-MobSF\venv\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "D:\Software Projects\Mobile-Security-Framework-MobSF\venv\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='reports.exodus-privacy.eu.org', port=443): Max retries exceeded with url: /api/trackers (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020CD8EFD8E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software Projects\Mobile-Security-Framework-MobSF\mobsf\MobSF\utils.py", line 428, in update_local_db
    response = requests.get(url,
  File "D:\Software Projects\Mobile-Security-Framework-MobSF\venv\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "D:\Software Projects\Mobile-Security-Framework-MobSF\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Software Projects\Mobile-Security-Framework-MobSF\venv\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Software Projects\Mobile-Security-Framework-MobSF\venv\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "D:\Software Projects\Mobile-Security-Framework-MobSF\venv\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='reports.exodus-privacy.eu.org', port=443): Max retries exceeded with url: /api/trackers (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020CD8EFD8E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```

when i tried to access reports.exodus-privacy.eu.org directly it seems that the domain is not available

**Comment by eskiesirius** [comment]
I already fixed it.. i change my dns to 8.8.8.8
