### ISSUE TITLE
Error Inappropriate argument type.  cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by anand-s2022** [MobSF/Mobile-Security-Framework-MobSF#1963]
I get the following error message when I scan the apk. 

File "/Users/anands/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/manifest_analysis.py", line 41, in get_manifest
    mfile = Path(manifest_file)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1041, in __new__
    self = cls._from_parts(args, init=False)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/pathlib.py", line 682, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/pathlib.py", line 666, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[ERROR] 20/May/2022 18:28:42 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/Users/anands/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 163, in static_analyzer
    mani_file, mani_xml = get_manifest(
TypeError: cannot unpack non-iterable NoneType object
[ERROR] 20/May/2022 18:28:42 - cannot unpack non-iterable NoneType object
[ERROR] 20/May/2022 18:28:42 - Internal Server Error: /static_analyzer/

**Comment by ajinabraham** [comment]
Please share the APK for troubleshooting this.

**Comment by penguininthedesert** [comment]
Having the same issue

**Comment by ajinabraham** [comment]
The issues is closed due to lack of response from original author after 25 days.
Also this is a third party issue, you can track the progress here: https://github.com/iBotPeaches/Apktool/issues/2842
