### ISSUE TITLE
venv not working accordingly on Windows

### ISSUE THREAD

**Issue by ripp3rdoc** [MobSF/Mobile-Security-Framework-MobSF#1970]
## ENVIRONMENT

```
OS and Version: Windows 11
Python Version: 3.9
MobSF Version: 3.5
```

## EXPLANATION OF THE ISSUE

I was trying to setup MobSF on my Windows machine with `setup.bat` script. And I kept getting "packages not installed properly" when reaching the migration of DB step.

```
[INSTALL] Migrating Database
Traceback (most recent call last):
  File "D:\MobSF\Mobile-Security-Framework-MobSF\manage.py", line 11, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
Traceback (most recent call last):
  File "D:\MobSF\Mobile-Security-Framework-MobSF\manage.py", line 11, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
Traceback (most recent call last):
  File "D:\MobSF\Mobile-Security-Framework-MobSF\manage.py", line 11, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
Download and Install wkhtmltopdf for PDF Report Generation - https://wkhtmltopdf.org/downloads.html
[INSTALL] Installation Complete
'scripts' is not recognized as an internal or external command,
operable program or batch file.```

I fixed the issue on my machine by changing the variable names in the script from `%venv%` to `python`, and everything worked fine.

**Comment by Reelix** [comment]
To those going this route, you will need to `python -m pip install` a whole bunch of modules, including (But not limited to)

six, colorlog, shelljob, pyOpenSSL, frida-tools, requests, distro, psutil, tldexract, IP2Location, BeautifulSoup4, lief, androguard, oscrypto, libsast, google-play-scraper, biplist, macholib, openstep-parser, rsa, and more.

After you hit http-tools and that fails with weird Visual Studio errors, you might realize that simply going `docker pull opensecurity/mobile-security-framework-mobsf` followed by `docker run -it --rm -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest` then browsing to `http://localhost:8000/` might be far less of a hassle...
