### ISSUE TITLE
Client replay has crashed!

### ISSUE THREAD

**Issue by gearcapitan** [MobSF/Mobile-Security-Framework-MobSF#1996]
Client replay has crashed!

when I want to send a request to burpsuite I get the following error!

![WarMachine-Win-2022-07-19-12-33-32](https://user-images.githubusercontent.com/13740942/179814939-56de0891-9593-4aa6-8cdb-5b3667ee6e1f.png)

Client replay has crashed!
Traceback (most recent call last):
  File "C:\Users\WarwindowsMachine\Desktop\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\mitmproxy\addons\clientplayback.py", line 149, in playback
    h = ReplayHandler(self.inflight, self.options)
  File "C:\Users\WarwindowsMachine\Desktop\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\mitmproxy\addons\clientplayback.py", line 85, in __init__
    context.server.via = flow.server_conn.via = server_spec.parse_with_mode(
  File "C:\Users\WarwindowsMachine\Desktop\Mobile-Security-Framework-MobSF-master\venv\lib\site-packages\mitmproxy\connection.py", line 353, in __setattr__
    raise RuntimeError(f"Cannot change server.{name} on open connection.")
RuntimeError: Cannot change server.via on open connection.

![WarMachine-Win-2022-07-19-12-42-17](https://user-images.githubusercontent.com/13740942/179815064-7443f0fb-4fd3-41e4-b70b-a7f4cc109b99.png)

**Comment by ajinabraham** [comment]
Please join slack channel for support.
