### ISSUE TITLE
androidVersionText Error while analysing APK

### ISSUE THREAD

**Issue by lt3stus3el** [MobSF/Mobile-Security-Framework-MobSF#1999]
## ENVIRONMENT

```
OS and Version: Linux-5.4.0-122-generic-x86_64-with-glibc2.29 (Ubuntu 20.04)
Python Version: 3.8
MobSF Version: 3.5.2 Beta
```

## EXPLANATION OF THE ISSUE

When I upload an APK ([Subway Surf](https://play.google.com/store/apps/details?id=com.kiloo.subwaysurf)) to the MobSF, it raises an error in terminal and says:

```
[INFO] 23/Jul/2022 05:44:37 - Connecting to Database
[INFO] 23/Jul/2022 05:44:37 - Saving to Database
[DEBUG] 23/Jul/2022 05:44:37 - Exception while resolving variable 'androidVersionText' in template 'static_analysis/android_binary_analysis.html'.
Traceback (most recent call last):
  File "Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/django/template/base.py", line 875, in _resolve_lookup
    current = current[bit]
KeyError: 'androidVersionText'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'androidVersionText'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'androidVersionText'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Mobile-Security-Framework-MobSF/venv/lib/python3.8/site-packages/django/template/base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [androidVersionText] in {'title': 'Subway Surfers', 'description': 'DASH as fast as you can! \r\nDODGE the oncoming trains! \r\n\r\nHelp Jake, Tricky & Fresh escape from the grumpy Inspector and his dog. \r\n\r\n★ Grind trains with your cool crew! \r\n★ Colorful and vivid HD graphics! \r\n★ Hoverboard Surfing! \r\n★ Paint powered jetpack! \r\n★ Lightning fast swipe acrobatics! \r\n★ Challenge and help your friends! \r\n\r\nJoin the most daring chase! \r\n\r\nA Universal App with HD optimized graphics.\r\n\r\nBy Kiloo and Sybo.', 'summary': 'Help Jake, Tricky & Fresh escape from the grumpy Inspector and his dog!', 'installs': '1,000,000,000+', 'minInstalls': 1000000000, 'realInstalls': 1964534646, 'score': 4.5902867, 'ratings': 38890301, 'reviews': 1783774, 'histogram': [1860041, 580861, 1383667, 3983765, 31081950], 'price': 0, 'free': True, 'currency': 'USD', 'sale': False, 'saleTime': None, 'originalPrice': None, 'saleText': None, 'offersIAP': True, 'inAppProductPrice': '$0.99 - $99.99 per item', 'developer': 'SYBO Games', 'developerId': '7363891306616760846', 'developerEmail': 'subwaysurfers@sybo.zendesk.com', 'developerWebsite': 'https://sybogames.com/', 'developerAddress': 'Jorcks Passage 1A, 4. th.\n1162 Copenhagen\nDenmark', 'privacyPolicy': 'https://sybogames.com/privacy-policy/', 'genre': 'Arcade', 'genreId': 'GAME_ARCADE', 'icon': 'https://play-lh.googleusercontent.com/Nw6jAwTyWQ1gS696wJsRrjM6O3Jq1S0Gzfe5JVM3c6xOwyIc3unU1Y8tubNwLQdWcY0', 'headerImage': 'https://play-lh.googleusercontent.com/pyO-cNTO43lrCBPb66UxeaWDxFXg16Mv5dvsWZZMc3WmVZaV90zsJCCC1AoMztqBIDY', 'screenshots': ['https://play-lh.googleusercontent.com/T7wPml9ShwxDDQB2237XU4-LIn84O_UM3U3N90_xRRsOXy40kDpwQmL0QlZT5QeKZAk', 'https://play-lh.googleusercontent.com/_lZwSn_3O7X3B8vWqT_fbm2-BfGxBF7KtrbANm-VjomxVIDf6E9U_X051L9rg47fFA', 'https://play-lh.googleusercontent.com/whl6yNZdpr0jWYD4ZoSR01JNzLyB7ANDIEdNtWepuLuA3wh6ANfqENbhDHQ0K0sOa2w', 'https://play-lh.googleusercontent.com/5JGypLozMcrLF6gyl2jp2-aoDxaQ1Q04HYKTCaHEsRbh8UBDjU3k50GhYRwze_ix0Sk', 'https://play-lh.googleusercontent.com/NRGYdBVwJ78fWNf7mkVEaGVmrqTXUKf4DNvPYGeK7SkDv_izckSqMmaRl6hOiGDL7fQ', 'https://play-lh.googleusercontent.com/QXRR_5F94WC_3FTZPSWClOsA8OvmAhb1WxIumUaHwgVOBKO3joGOQmUdaNRKnxNgmw', 'https://play-lh.googleusercontent.com/t00ZGwO6MHgxizlsL_dbvziZ6E1Omth0szWdXKwF2UcOY0z9oG9PMy6fUIu8NLJH3A', 'https://play-lh.googleusercontent.com/qX-KoEYtvk8G4uNXbMktNtYqyiWn2XpfQspZNj_dYmwFk616fjXOSp8J5CVtAJmllg', 'https://play-lh.googleusercontent.com/_2YnFN7WZkgA6j10Fnc61U4hc_K7V5lcAa8SKvrGSCHaxQznorwbc_zZVh_eN7g8z_yt', 'https://play-lh.googleusercontent.com/YjMTy01Tm5yDJc-81DhiYuUSOiJTgSBUl0XaZyWSLNf4DlRhVu48c1g1ybEg09qGxOs', 'https://play-lh.googleusercontent.com/V-_UVgPrn91Rkt0JVSzPcBgJ4N41_o6iPknt7p3QdNRiQkUf4SLssjWB5EC-j2IX1w', 'https://play-lh.googleusercontent.com/3kIn8UMf0kWZMhHfcZq_oWBnnBaY0DzxHGtQqoD5F-S_RRekgB3Ri4gWbm3S8aLeXPlS', 'https://play-lh.googleusercontent.com/FB9QyPKvPOJxQjEJ7uy3Inhyg8yqXoPskzTtvMrAJweczhsOvYxo3UJVAvW6w6arY40', 'https://play-lh.googleusercontent.com/EKojYLPWj7MflasQafeBN2vA4P_oF8tEWnC8KiT4CRz9YISTIkZ1LOrk77ErL7syG3k', 'https://play-lh.googleusercontent.com/MWZBMpX0FfqtekJgwwkA_H8-TnfOq6qZCBrcBQz3z3vJLo_poQs7if-sIeY8iKHIa4NZ', 'https://play-lh.googleusercontent.com/F3jAsq6UAaQX3V2P5F6vyWsmlB6sNSa4OhSl3qX0zB0UIxdGOMCYqwRk9J0tc5yPMA', 'https://play-lh.googleusercontent.com/ReNUlmSOseKBzKDKYOSAdv5Wr-ubfekwahhyNE2y0Rb_4vP3pTWbM3XtAPLNQHANJZA', 'https://play-lh.googleusercontent.com/YWS_hMnMUgGeqfWxKYiL4nM_4RXnmWp15p3eSN0_X7MEp6hIoNPf-jqt1DmLPg5KUvFC', 'https://play-lh.googleusercontent.com/-_GdDWmBMs9TXC3m1HFIFZODa6OKE_YUaYcl9qbNcphZ45tdj-8QUpmMyGgFajCIQw', 'https://play-lh.googleusercontent.com/UTNrVDjT4mC_ZxaPTr6le_Ag_0-OWSB9rOLehrg-hcpQU9xo0JS9uPz7k43zGORJxg', 'https://play-lh.googleusercontent.com/VZ-q1MJ3MDTHH2dB1uhUGgGAGv7mKoMu9OAWZIZ4R8tw7hAoawohWAvKnrNiplh3Su4', 'https://play-lh.googleusercontent.com/sj_U0xpf9PzvJGxIKIrIooBI-Dg649X3C34y2Cw3HumaorkBd1UBEDvC_g3aTHk0Zzo', 'https://play-lh.googleusercontent.com/Y-MSkde0KMQrkTq9KhDd1lNxFXDzcHtR5KLqrg4TAU3mwAj--InKsk9Ks1r3iHvQYgmQ', 'https://play-lh.googleusercontent.com/YODXqNSVJH3Ug7b8KEIRe9mX2yOaZYWtqMsQepQs9lKb6xClJ2H_zByoH508F4skmxs'], 'video': 'https://www.youtube.com/embed/1pHSVWJQklc?ps=play&vq=large&rel=0&autohide=1&showinfo=0', 'videoImage': 'https://play-lh.googleusercontent.com/pyO-cNTO43lrCBPb66UxeaWDxFXg16Mv5dvsWZZMc3WmVZaV90zsJCCC1AoMztqBIDY', 'contentRating': 'Everyone 10+', 'contentRatingDescription': 'Fantasy Violence', 'adSupported': True, 'containsAds': True, 'released': 'Sep 20, 2012', 'updated': 1657869317, 'version': '2.37.0', 'recentChanges': None, 'recentChangesHTML': None, 'appId': 'com.kiloo.subwaysurf', 'url': 'https://play.google.com/store/apps/details?id=com.kiloo.subwaysurf&hl=en&gl=us', 'error': False}

```
It seems that this key **androidVersionText** is not text and django tries to parse it as int:
**ValueError: invalid literal for int() with base 10: 'androidVersionText'**

## STEPS TO REPRODUCE THE ISSUE

```
1. Upload APK to MobSF
2. It starts analysis of the uploaded file automatically.
3. This error happens at terminal and MobSF does not continue analysis.
```

**Comment by ajinabraham** [comment]
Thanks for the report. This should be hot fixed in latest master branch.
