### ISSUE TITLE
docker-compose up not working

### ISSUE THREAD

**Issue by hazcod** [MobSF/Mobile-Security-Framework-MobSF#2004]
## ENVIRONMENT

```
Docker for macOS (M1)
Command: `docker-compose up`
```

## LOG FILE

```
[+] Running 2/0
 ⠿ Container mobsf-postgres-1  Created                                                                                    0.0s
 ⠿ Container mobsf-mobsf-1     Created                                                                                    0.0s
Attaching to mobsf-mobsf-1, mobsf-postgres-1
mobsf-postgres-1  | 
mobsf-postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
mobsf-postgres-1  | 
mobsf-postgres-1  | 2022-07-27 08:29:10.161 UTC [1] LOG:  starting PostgreSQL 14.4 (Debian 14.4-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
mobsf-postgres-1  | 2022-07-27 08:29:10.161 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
mobsf-postgres-1  | 2022-07-27 08:29:10.161 UTC [1] LOG:  listening on IPv6 address "::", port 5432
mobsf-postgres-1  | 2022-07-27 08:29:10.163 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
mobsf-postgres-1  | 2022-07-27 08:29:10.166 UTC [26] LOG:  database system was shut down at 2022-07-27 08:23:09 UTC
mobsf-postgres-1  | 2022-07-27 08:29:10.169 UTC [1] LOG:  database system is ready to accept connections
mobsf-mobsf-1     | [INFO] 27/Jul/2022 08:29:10 - 
mobsf-mobsf-1     |   __  __       _    ____  _____       _____  ____  
mobsf-mobsf-1     |  |  \/  | ___ | |__/ ___||  ___|_   _|___ / | ___| 
mobsf-mobsf-1     |  | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \ |___ \ 
mobsf-mobsf-1     |  | |  | | (_) | |_) |__) |  _|  \ V / ___) | ___) |
mobsf-mobsf-1     |  |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)____/ 
mobsf-mobsf-1     | 
mobsf-mobsf-1     | [INFO] 27/Jul/2022 08:29:10 - Mobile Security Framework v3.5.2 Beta
mobsf-mobsf-1     | REST API Key: bd185e0356c61be9a3057b07717c8187d11d00dc44813a784660377a8d37046b
mobsf-mobsf-1     | [INFO] 27/Jul/2022 08:29:10 - OS: Linux
mobsf-mobsf-1     | [INFO] 27/Jul/2022 08:29:10 - Platform: Linux-5.10.104-linuxkit-aarch64-with-glibc2.29
mobsf-mobsf-1     | [INFO] 27/Jul/2022 08:29:10 - Dist: ubuntu 20.04 Focal Fossa
mobsf-mobsf-1     | [INFO] 27/Jul/2022 08:29:10 - MobSF Basic Environment Check
mobsf-mobsf-1     | /usr/local/lib/python3.8/dist-packages/django/core/management/commands/makemigrations.py:121: RuntimeWarning: Got an error checking a consistent migration history performed for database connection 'default': SCRAM authentication requires libpq version 10 or above
mobsf-mobsf-1     | 
mobsf-mobsf-1     |   warnings.warn(
mobsf-mobsf-1     | No changes detected
mobsf-mobsf-1     | [INFO] 27/Jul/2022 08:29:11 - Checking for Update.
mobsf-mobsf-1     | [INFO] 27/Jul/2022 08:29:11 - No updates available.
mobsf-mobsf-1     | [INFO] 27/Jul/2022 08:29:11 - 
mobsf-mobsf-1     |   __  __       _    ____  _____       _____  ____  
mobsf-mobsf-1     |  |  \/  | ___ | |__/ ___||  ___|_   _|___ / | ___| 
mobsf-mobsf-1     |  | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \ |___ \ 
mobsf-mobsf-1     |  | |  | | (_) | |_) |__) |  _|  \ V / ___) | ___) |
mobsf-mobsf-1     |  |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)____/ 
mobsf-mobsf-1     | 
mobsf-mobsf-1     | [INFO] 27/Jul/2022 08:29:11 - Mobile Security Framework v3.5.2 Beta
mobsf-mobsf-1     | REST API Key: bd185e0356c61be9a3057b07717c8187d11d00dc44813a784660377a8d37046b
mobsf-mobsf-1     | [INFO] 27/Jul/2022 08:29:11 - OS: Linux
mobsf-mobsf-1     | [INFO] 27/Jul/2022 08:29:11 - Platform: Linux-5.10.104-linuxkit-aarch64-with-glibc2.29
mobsf-mobsf-1     | [INFO] 27/Jul/2022 08:29:11 - Dist: ubuntu 20.04 Focal Fossa
mobsf-mobsf-1     | [INFO] 27/Jul/2022 08:29:11 - MobSF Basic Environment Check
mobsf-mobsf-1     | /usr/local/lib/python3.8/dist-packages/django/core/management/commands/makemigrations.py:121: RuntimeWarning: Got an error checking a consistent migration history performed for database connection 'default': SCRAM authentication requires libpq version 10 or above
mobsf-mobsf-1     | 
mobsf-mobsf-1     |   warnings.warn(
mobsf-mobsf-1     | No changes detected in app 'StaticAnalyzer'
mobsf-mobsf-1     | [INFO] 27/Jul/2022 08:29:12 - Checking for Update.
mobsf-mobsf-1     | [INFO] 27/Jul/2022 08:29:12 - No updates available.
mobsf-mobsf-1     | Traceback (most recent call last):
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 244, in ensure_connection
mobsf-mobsf-1     |     self.connect()
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 26, in inner
mobsf-mobsf-1     |     return func(*args, **kwargs)
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 225, in connect
mobsf-mobsf-1     |     self.connection = self.get_new_connection(conn_params)
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 26, in inner
mobsf-mobsf-1     |     return func(*args, **kwargs)
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/postgresql/base.py", line 203, in get_new_connection
mobsf-mobsf-1     |     connection = Database.connect(**conn_params)
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/psycopg2/__init__.py", line 122, in connect
mobsf-mobsf-1     |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
mobsf-mobsf-1     | psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
mobsf-mobsf-1     | 
mobsf-mobsf-1     | 
mobsf-mobsf-1     | The above exception was the direct cause of the following exception:
mobsf-mobsf-1     | 
mobsf-mobsf-1     | Traceback (most recent call last):
mobsf-mobsf-1     |   File "manage.py", line 18, in <module>
mobsf-mobsf-1     |     execute_from_command_line(sys.argv)
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
mobsf-mobsf-1     |     utility.execute()
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 440, in execute
mobsf-mobsf-1     |     self.fetch_command(subcommand).run_from_argv(self.argv)
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 414, in run_from_argv
mobsf-mobsf-1     |     self.execute(*args, **cmd_options)
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 460, in execute
mobsf-mobsf-1     |     output = self.handle(*args, **options)
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 98, in wrapped
mobsf-mobsf-1     |     res = handle_func(*args, **kwargs)
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/migrate.py", line 91, in handle
mobsf-mobsf-1     |     self.check(databases=[database])
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 487, in check
mobsf-mobsf-1     |     all_issues = checks.run_checks(
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/core/checks/registry.py", line 88, in run_checks
mobsf-mobsf-1     |     new_errors = check(app_configs=app_configs, databases=databases)
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/core/checks/model_checks.py", line 36, in check_all_models
mobsf-mobsf-1     |     errors.extend(model.check(**kwargs))
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 1461, in check
mobsf-mobsf-1     |     *cls._check_indexes(databases),
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 1864, in _check_indexes
mobsf-mobsf-1     |     connection.features.supports_covering_indexes
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 49, in __get__
mobsf-mobsf-1     |     res = instance.__dict__[self.name] = self.func(instance)
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/postgresql/features.py", line 84, in is_postgresql_11
mobsf-mobsf-1     |     return self.connection.pg_version >= 110000
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 49, in __get__
mobsf-mobsf-1     |     res = instance.__dict__[self.name] = self.func(instance)
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/postgresql/base.py", line 354, in pg_version
mobsf-mobsf-1     |     with self.temporary_connection():
mobsf-mobsf-1     |   File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
mobsf-mobsf-1     |     return next(self.gen)
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 639, in temporary_connection
mobsf-mobsf-1     |     with self.cursor() as cursor:
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 26, in inner
mobsf-mobsf-1     |     return func(*args, **kwargs)
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 284, in cursor
mobsf-mobsf-1     |     return self._cursor()
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 260, in _cursor
mobsf-mobsf-1     |     self.ensure_connection()
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 26, in inner
mobsf-mobsf-1     |     return func(*args, **kwargs)
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 244, in ensure_connection
mobsf-mobsf-1     |     self.connect()
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 91, in __exit__
mobsf-mobsf-1     |     raise dj_exc_value.with_traceback(traceback) from exc_value
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 244, in ensure_connection
mobsf-mobsf-1     |     self.connect()
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 26, in inner
mobsf-mobsf-1     |     return func(*args, **kwargs)
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 225, in connect
mobsf-mobsf-1     |     self.connection = self.get_new_connection(conn_params)
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 26, in inner
mobsf-mobsf-1     |     return func(*args, **kwargs)
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/postgresql/base.py", line 203, in get_new_connection
mobsf-mobsf-1     |     connection = Database.connect(**conn_params)
mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/psycopg2/__init__.py", line 122, in connect
mobsf-mobsf-1     |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
mobsf-mobsf-1     | django.db.utils.OperationalError: SCRAM authentication requires libpq version 10 or above
mobsf-mobsf-1     | 
mobsf-mobsf-1 exited with code 1
^[[A

```

**Comment by ajinabraham** [comment]
FYI @superpoussin22

**Comment by superpoussin22** [comment]
will have a look

**Comment by superpoussin22** [comment]
answer provided on slack

**Comment by hazcod** [comment]
@superpoussin22 sorry i'm not on slack, can you please reply here?
