### ISSUE TITLE
cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by hazcod** [MobSF/Mobile-Security-Framework-MobSF#2010]
## ENVIRONMENT

```
OS and Version: debian, docker (amd64 + arm64)
Python Version: 3.8
MobSF Version: 3.5.0
```

## EXPLANATION OF THE ISSUE

```
1. Upload .apk
```

## LOG FILE

```
[INFO] 05/Aug/2022 22:39:17 - Starting Analysis on: happify-1.80.2-f9370300f3fd57a-rework-kabinet-release.apk
[INFO] 05/Aug/2022 22:39:17 - Generating Hashes
[INFO] 05/Aug/2022 22:39:17 - Unzipping
[INFO] 05/Aug/2022 22:39:20 - APK Extracted
[INFO] 05/Aug/2022 22:39:20 - Getting Hardcoded Certificates/Keystores
[INFO] 05/Aug/2022 22:39:20 - Getting AndroidManifest.xml from APK
[INFO] 05/Aug/2022 22:39:20 - Converting AXML to XML
Exception in thread "main" java.lang.IllegalArgumentException: Chunk [ text-decoration: none] is not a valid entry
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:219)
	at com.google.common.base.Splitter$MapSplitter.split(Splitter.java:526)
	at brut.androlib.res.decoder.StringBlock$Tag.toString(StringBlock.java:167)
	at java.base/java.lang.String.valueOf(String.java:3365)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:169)
	at brut.androlib.res.decoder.StringBlock.processStyledString(StringBlock.java:260)
	at brut.androlib.res.decoder.StringBlock.getHTML(StringBlock.java:288)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:366)
	at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:285)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:261)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:184)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:135)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:84)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:50)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:783)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:64)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:56)
	at brut.androlib.Androlib.getResTable(Androlib.java:69)
	at brut.androlib.ApkDecoder.getResTable(ApkDecoder.java:247)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
	at brut.apktool.Main.cmdDecode(Main.java:175)
	at brut.apktool.Main.main(Main.java:78)
[ERROR] 05/Aug/2022 22:39:22 - Getting Manifest file
Traceback (most recent call last):
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/manifest_analysis.py", line 905, in get_manifest_apk
    subprocess.check_output(args)  # lgtm [py/command-line-injection] md5 hash
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/jdk-16.0.1/bin/java', '-jar', '/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/tools/apktool_2.6.0.jar', '--match-original', '--frame-path', '/tmp', '-f', '-s', 'd', '/home/mobsf/.MobSF/uploads/a19048ec00ecd0fb1d429f3d2a30700d/a19048ec00ecd0fb1d429f3d2a30700d.apk', '-o', '/home/mobsf/.MobSF/uploads/a19048ec00ecd0fb1d429f3d2a30700d/apktool_out']' returned non-zero exit status 1.
[ERROR] 05/Aug/2022 22:39:22 - Parsing Manifest file
Traceback (most recent call last):
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/manifest_analysis.py", line 41, in get_manifest
    mfile = Path(manifest_file)
  File "/usr/lib/python3.8/pathlib.py", line 1042, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.8/pathlib.py", line 683, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.8/pathlib.py", line 667, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[ERROR] 05/Aug/2022 22:39:22 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 163, in static_analyzer
    mani_file, mani_xml = get_manifest(
TypeError: cannot unpack non-iterable NoneType object
[ERROR] 05/Aug/2022 22:39:22 - cannot unpack non-iterable NoneType object
[ERROR] 05/Aug/2022 22:39:22 - Internal Server Error: /static_analyzer/
```

**Comment by ajinabraham** [comment]
```
Exception in thread "main" java.lang.IllegalArgumentException: Chunk [ text-decoration: none] is not a valid entry
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:219)
	at com.google.common.base.Splitter$MapSplitter.split(Splitter.java:526)
	at brut.androlib.res.decoder.StringBlock$Tag.toString(StringBlock.java:167)
	at java.base/java.lang.String.valueOf(String.java:3365)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:169)
	at brut.androlib.res.decoder.StringBlock.processStyledString(StringBlock.java:260)
	at brut.androlib.res.decoder.StringBlock.getHTML(StringBlock.java:288)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:366)
	at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:285)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:261)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:184)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:135)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:84)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:50)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:783)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:64)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:56)
	at brut.androlib.Androlib.getResTable(Androlib.java:69)
	at brut.androlib.ApkDecoder.getResTable(ApkDecoder.java:247)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
	at brut.apktool.Main.cmdDecode(Main.java:175)
	at brut.apktool.Main.main(Main.java:78)

```
The exception suggests that apktool failed. 
You need to raise a bug report here: https://github.com/iBotPeaches/Apktool
