### ISSUE TITLE
Error Inappropriate argument type.  'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by yztale** [MobSF/Mobile-Security-Framework-MobSF#2024]
ENVIRONMENT
```
OS and Version:Windows 10 (docker: 18.10.1)
Python Version:3.8.2 
MobSF Version:v3.0.9 Beta
```

upload ipa
```
root@seclab-ydjc:~# docker attach e3facfc387de
[2022-09-08 02:04:03 +0000] [1] [INFO] Handling signal: winch
[2022-09-08 02:04:03 +0000] [1] [INFO] Handling signal: winch
[INFO] 08/Sep/2022 02:05:19 - MIME Type: application/octet-stream FILE: ruhangzhixingpassenger.ipa
[INFO] 08/Sep/2022 02:05:19 - Performing Static Analysis of iOS IPA
[INFO] 08/Sep/2022 02:05:19 - iOS Static Analysis Started
[INFO] 08/Sep/2022 02:05:19 - iOS Binary (IPA) Analysis Started
[INFO] 08/Sep/2022 02:05:19 - Generating Hashes
[INFO] 08/Sep/2022 02:05:19 - Extracting IPA
[INFO] 08/Sep/2022 02:05:19 - Unzipping
[INFO] 08/Sep/2022 02:05:21 - Get Files, BIN Plist -> XML, and Normalize
[INFO] 08/Sep/2022 02:05:21 - iOS Info.plist Analysis Started
[INFO] 08/Sep/2022 02:05:21 - Finding Info.plist in iOS Binary
[INFO] 08/Sep/2022 02:05:21 - Checking Permissions
[INFO] 08/Sep/2022 02:05:21 - Checking for Insecure Connections
[INFO] 08/Sep/2022 02:05:21 - Fetching Details from App Store: com.gmcx.passenger
[WARNING] 08/Sep/2022 02:05:22 - Unable to get app details
[INFO] 08/Sep/2022 02:05:22 - Starting Binary Analysis
[INFO] 08/Sep/2022 02:05:22 - Getting Binary Information
[INFO] 08/Sep/2022 02:05:22 - Running Object analysis of binary: RuHangZhiXingPassenger
[ERROR] 08/Sep/2022 02:05:22 - Performing Object analysis of binary
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/otool_analysis.py", line 96, in otool_analysis
    otool_dict['libs'] = get_otool_out(
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/otool_analysis.py", line 33, in get_otool_out
    os.chmod(toolbin, stat.S_IEXEC)
FileNotFoundError: [Errno 2] No such file or directory: '/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/ios/jtool2.ELF64'
[INFO] 08/Sep/2022 02:05:22 - Dumping classes
[INFO] 08/Sep/2022 02:05:22 - Running jtool against the binary for dumping classes
[ERROR] 08/Sep/2022 02:05:22 - iOS Binary Analysis
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/binary_analysis.py", line 104, in binary_analysis
    object_data['bindata'] + cdump,
TypeError: can only concatenate str (not "bytes") to str
[INFO] 08/Sep/2022 02:05:22 - Fetching icon path
[WARNING] 08/Sep/2022 02:05:22 - Could not find app icon
[ERROR] 08/Sep/2022 02:05:22 - Error Perfroming Static Analysis
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/static_analyzer.py", line 115, in static_analyzer_ios
    bin_analysis_dict['strings'])
TypeError: 'NoneType' object is not subscriptable
[ERROR] 08/Sep/2022 02:05:22 - 'NoneType' object is not subscriptable
[ERROR] 08/Sep/2022 02:05:22 - Internal Server Error: /StaticAnalyzer_iOS/
[INFO] 08/Sep/2022 02:05:22 - iOS Static Analysis Started
[INFO] 08/Sep/2022 02:05:22 - iOS Binary (IPA) Analysis Started
[INFO] 08/Sep/2022 02:05:22 - Generating Hashes
[INFO] 08/Sep/2022 02:05:23 - Extracting IPA
[INFO] 08/Sep/2022 02:05:23 - Unzipping
[INFO] 08/Sep/2022 02:05:24 - Get Files, BIN Plist -> XML, and Normalize
[INFO] 08/Sep/2022 02:05:24 - iOS Info.plist Analysis Started
[INFO] 08/Sep/2022 02:05:24 - Finding Info.plist in iOS Binary
[INFO] 08/Sep/2022 02:05:24 - Checking Permissions
[INFO] 08/Sep/2022 02:05:24 - Checking for Insecure Connections
[INFO] 08/Sep/2022 02:05:24 - Fetching Details from App Store: com.gmcx.passenger
[WARNING] 08/Sep/2022 02:05:24 - Unable to get app details
[INFO] 08/Sep/2022 02:05:24 - Starting Binary Analysis
[INFO] 08/Sep/2022 02:05:24 - Getting Binary Information
[INFO] 08/Sep/2022 02:05:24 - Running Object analysis of binary: RuHangZhiXingPassenger
[ERROR] 08/Sep/2022 02:05:24 - Performing Object analysis of binary
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/otool_analysis.py", line 96, in otool_analysis
    otool_dict['libs'] = get_otool_out(
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/otool_analysis.py", line 33, in get_otool_out
    os.chmod(toolbin, stat.S_IEXEC)
FileNotFoundError: [Errno 2] No such file or directory: '/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/ios/jtool2.ELF64'
[INFO] 08/Sep/2022 02:05:24 - Dumping classes
[INFO] 08/Sep/2022 02:05:24 - Running jtool against the binary for dumping classes
[ERROR] 08/Sep/2022 02:05:24 - iOS Binary Analysis
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/binary_analysis.py", line 104, in binary_analysis
    object_data['bindata'] + cdump,
TypeError: can only concatenate str (not "bytes") to str
[INFO] 08/Sep/2022 02:05:24 - Fetching icon path
[WARNING] 08/Sep/2022 02:05:24 - Could not find app icon
[ERROR] 08/Sep/2022 02:05:24 - Error Perfroming Static Analysis
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/static_analyzer.py", line 115, in static_analyzer_ios
    bin_analysis_dict['strings'])
TypeError: 'NoneType' object is not subscriptable
[ERROR] 08/Sep/2022 02:05:24 - 'NoneType' object is not subscriptable
[ERROR] 08/Sep/2022 02:05:24 - Internal Server Error: /StaticAnalyzer_iOS/
```
<img width="499" alt="image" src="https://user-images.githubusercontent.com/45749015/189017761-c13e82e6-a259-4be4-8569-b4e38ea89b01.png">

**Comment by superpoussin22** [comment]
Please use slack channel
