### ISSUE TITLE
No able to run MobSF

### ISSUE THREAD

**Issue by shahfaisal21** [MobSF/Mobile-Security-Framework-MobSF#2028]
## ENVIRONMENT

```
OS and Version: Windows 10
Python Version: Python 3.9.2
MobSF Version: latest
```

## EXPLANATION OF THE ISSUE

```
What happens, under which versions, under what conditions, when, and what were you expecting instead.
```
I have followed the steps as per the installation guide. But when Iam running "setup.bat" Iam getting an error

Unable to create process using 'C:\Users\Shah Faisal Hussain\AppData\Local\Programs\Python\Python39\python.exe scripts/check_install.py'

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step
 When I run the command to setup MobSF, Iam getting an error
./setup.bat

[INSTALL] Checking for Python version 3.8+
[INSTALL] Found Python 3.9.2
[INSTALL] Found pip
Requirement already satisfied: pip in c:\users\shah faisal hussain\appdata\local\programs\python\python39\lib\site-packages (22.2.2)
[INSTALL] Found OpenSSL executable
[INSTALL] Found Visual Studio Build Tools
[INSTALL] Creating venv
Error: Command '['C:\\Users\\Shah Faisal Hussain\\Downloads\\Mobile-Security-Framework-MobSF\\venv\\Scripts\\python.exe', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 101.
Unable to create process using 'C:\Users\Shah Faisal Hussain\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip'
[INSTALL] Installing Requirements
Unable to create process using 'C:\Users\Shah Faisal Hussain\AppData\Local\Programs\Python\Python39\python.exe -m pip install --no-cache-dir wheel'
Unable to create process using 'C:\Users\Shah Faisal Hussain\AppData\Local\Programs\Python\Python39\python.exe -m pip install --no-cache-dir --use-deprecated=legacy-resolver -r requirements.txt'
[INSTALL] Clean Up
=======================MobSF Clean Script for Windows=======================
Running this script will delete the Scan database, all files uploaded and generated.
C:\Users\Shah Faisal Hussain\Downloads\Mobile-Security-Framework-MobSF\scripts
Deleting all Uploads
Deleting all Downloads
Deleting Static Analyzer Migrations
Deleting Dynamic Analyzer Migrations
Deleting MobSF Migrations
Deleting temp and log files
Deleting DB
Deleting Secret File
Deleting Previous Setup files
Done
[INSTALL] Migrating Database
Unable to create process using 'C:\Users\Shah Faisal Hussain\AppData\Local\Programs\Python\Python39\python.exe manage.py makemigrations'
Unable to create process using 'C:\Users\Shah Faisal Hussain\AppData\Local\Programs\Python\Python39\python.exe manage.py makemigrations StaticAnalyzer'
Unable to create process using 'C:\Users\Shah Faisal Hussain\AppData\Local\Programs\Python\Python39\python.exe manage.py migrate'
Download and Install wkhtmltopdf for PDF Report Generation - https://wkhtmltopdf.org/downloads.html
[INSTALL] Installation Complete
Unable to create process using 'C:\Users\Shah Faisal Hussain\AppData\Local\Programs\Python\Python39\python.exe scripts/check_install.py'


![MobSF error](https://user-images.githubusercontent.com/42960855/189909844-87a997c3-8152-4947-9392-516989014c7b.png)

**Comment by KimmAmy** [comment]
Please I need help here @ajinabraham 

┌──(root㉿kali)-[/home/kali/Downloads/Mobile-Security-Framework-MobSF-master]
└─# ./run.sh                      
[2025-01-23 14:10:28 -0500] [2202778] [INFO] Starting gunicorn 23.0.0
[2025-01-23 14:10:28 -0500] [2202778] [INFO] Listening at: http://[::]:8000 (2202778)
[2025-01-23 14:10:28 -0500] [2202778] [INFO] Using worker: gthread
[2025-01-23 14:10:28 -0500] [2202837] [INFO] Booting worker with pid: 2202837
Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/config.py", line 396, in resolve
    found = self.importer(used)
            ^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'colorlog'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/config.py", line 552, in configure
    formatters[name] = self.configure_formatter(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/config.py", line 664, in configure_formatter
    result = self.configure_custom(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/config.py", line 479, in configure_custom
    c = self.resolve(c)
        ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/config.py", line 407, in resolve
    raise v from e
ValueError: Cannot resolve 'colorlog.ColoredFormatter': No module named 'colorlog'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kali/Downloads/Mobile-Security-Framework-MobSF-master/mobsf/../manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/usr/lib/python3/dist-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/lib/python3/dist-packages/django/utils/log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python3.11/logging/config.py", line 823, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.11/logging/config.py", line 555, in configure
    raise ValueError('Unable to configure '
ValueError: Unable to configure formatter 'color'
Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/config.py", line 396, in resolve
    found = self.importer(used)
            ^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'colorlog'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/config.py", line 552, in configure
    formatters[name] = self.configure_formatter(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/config.py", line 664, in configure_formatter
    result = self.configure_custom(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/config.py", line 479, in configure_custom
    c = self.resolve(c)
        ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/config.py", line 407, in resolve
    raise v from e
ValueError: Cannot resolve 'colorlog.ColoredFormatter': No module named 'colorlog'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kali/Downloads/Mobile-Security-Framework-MobSF-master/mobsf/../manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/usr/lib/python3/dist-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/lib/python3/dist-packages/django/utils/log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python3.11/logging/config.py", line 823, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.11/logging/config.py", line 555, in configure
    raise ValueError('Unable to configure '
ValueError: Unable to configure formatter 'color'
Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/config.py", line 396, in resolve
    found = self.importer(used)
            ^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'colorlog'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/config.py", line 552, in configure
    formatters[name] = self.configure_formatter(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/config.py", line 664, in configure_formatter
    result = self.configure_custom(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/config.py", line 479, in configure_custom
    c = self.resolve(c)
        ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/config.py", line 407, in resolve
    raise v from e
ValueError: Cannot resolve 'colorlog.ColoredFormatter': No module named 'colorlog'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kali/Downloads/Mobile-Security-Framework-MobSF-master/mobsf/../manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/usr/lib/python3/dist-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/lib/python3/dist-packages/django/utils/log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python3.11/logging/config.py", line 823, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.11/logging/config.py", line 555, in configure
    raise ValueError('Unable to configure '
ValueError: Unable to configure formatter 'color'
Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/config.py", line 396, in resolve
    found = self.importer(used)
            ^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'colorlog'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/config.py", line 552, in configure
    formatters[name] = self.configure_formatter(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/config.py", line 664, in configure_formatter
    result = self.configure_custom(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/config.py", line 479, in configure_custom
    c = self.resolve(c)
        ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/config.py", line 407, in resolve
    raise v from e
ValueError: Cannot resolve 'colorlog.ColoredFormatter': No module named 'colorlog'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kali/Downloads/Mobile-Security-Framework-MobSF-master/mobsf/../manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/usr/lib/python3/dist-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/lib/python3/dist-packages/django/utils/log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python3.11/logging/config.py", line 823, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.11/logging/config.py", line 555, in configure
    raise ValueError('Unable to configure '
ValueError: Unable to configure formatter 'color'
Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/config.py", line 396, in resolve
    found = self.importer(used)
            ^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'colorlog'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/config.py", line 552, in configure
    formatters[name] = self.configure_formatter(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/config.py", line 664, in configure_formatter
    result = self.configure_custom(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/config.py", line 479, in configure_custom
    c = self.resolve(c)
        ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/config.py", line 407, in resolve
    raise v from e
ValueError: Cannot resolve 'colorlog.ColoredFormatter': No module named 'colorlog'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kali/Downloads/Mobile-Security-Framework-MobSF-master/mobsf/../manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/usr/lib/python3/dist-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/lib/python3/dist-packages/django/utils/log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python3.11/logging/config.py", line 823, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.11/logging/config.py", line 555, in configure
    raise ValueError('Unable to configure '
ValueError: Unable to configure formatter 'color'
[2025-01-23 19:10:48 +0000] [2202837] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/config.py", line 396, in resolve
    found = self.importer(used)
            ^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'colorlog'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/config.py", line 552, in configure
    formatters[name] = self.configure_formatter(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/config.py", line 664, in configure_formatter
    result = self.configure_custom(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/config.py", line 479, in configure_custom
    c = self.resolve(c)
        ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/config.py", line 407, in resolve
    raise v from e
ValueError: Cannot resolve 'colorlog.ColoredFormatter': No module named 'colorlog'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/gthread.py", line 94, in init_process
    super().init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 395, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kali/Downloads/Mobile-Security-Framework-MobSF-master/mobsf/MobSF/wsgi.py", line 23, in <module>
    application = WhiteNoise(get_wsgi_application(),
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/lib/python3/dist-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/lib/python3/dist-packages/django/utils/log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python3.11/logging/config.py", line 823, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.11/logging/config.py", line 555, in configure
    raise ValueError('Unable to configure '
ValueError: Unable to configure formatter 'color'
[2025-01-23 19:10:48 +0000] [2202837] [INFO] Worker exiting (pid: 2202837)
