### ISSUE TITLE
installation setup Issue

### ISSUE THREAD

**Issue by kamranbhutto** [MobSF/Mobile-Security-Framework-MobSF#2029]
## Operating System
```
kali linux 

``` 
## ENVIRONMENT

```
Python Version: python3 

```

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step : sudo ./run.sh 127.0.0.1:8000

```

## LOG FILE

```
[2022-09-18 12:18:01 -0400] [50644] [INFO] Starting gunicorn 20.1.0
[2022-09-18 12:18:01 -0400] [50644] [INFO] Listening at: http://127.0.0.1:8000 (50644)
[2022-09-18 12:18:01 -0400] [50644] [INFO] Using worker: threads
[2022-09-18 12:18:01 -0400] [50645] [INFO] Booting worker with pid: 50645
[2022-09-18 12:18:02 -0400] [50645] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kali/Desktop/Mobile-Security-Framework-MobSF/mobsf/MobSF/wsgi.py", line 14, in <module>
    from whitenoise import WhiteNoise
ModuleNotFoundError: No module named 'whitenoise'
[2022-09-18 12:18:02 -0400] [50645] [INFO] Worker exiting (pid: 50645)
[2022-09-18 12:18:02 -0400] [50644] [INFO] Shutting down: Master
[2022-09-18 12:18:02 -0400] [50644] [INFO] Reason: Worker failed to boot.

```

**Comment by superpoussin22** [comment]
hello
use slack channel please 
btw did you run setup.sh without issue

**Comment by dreyTee** [comment]
@kamranbhutto 
similar to my problem, did you address the issue already?
