### ISSUE TITLE
Converting AXML to XML  exception occurs

### ISSUE THREAD

**Issue by siberiah0h** [MobSF/Mobile-Security-Framework-MobSF#2045]
## ENVIRONMENT
```
OS and Version:
Linux version 3.10.0-1160.76.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Wed Aug 10 16:21:17 UTC 2022

Python Version:
root@9afbcacb7e19:~/Mobile-Security-Framework-MobSF-3.6.0/venv/bin# python3
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 

MobSF Version:
Mobile-Security-Framework-MobSF-3.6.0
```
## EXPLANATION OF THE ISSUE
```
What happens, under which versions, under what conditions, when, and what were you expecting instead.
```

`[INFO] 09/Oct/2022 04:10:10 - Converting AXML to XML
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:55)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:783)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:64)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:56)
	at brut.androlib.Androlib.getResTable(Androlib.java:70)
	at brut.androlib.ApkDecoder.getResTable(ApkDecoder.java:247)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
	at brut.apktool.Main.cmdDecode(Main.java:175)
	at brut.apktool.Main.main(Main.java:79)
Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000003
	at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:53)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:360)
	at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:285)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:261)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:184)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:135)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:84)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:50)
	... 8 more
[ERROR] 09/Oct/2022 04:10:11 - Getting Manifest file
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF-3.6.0/mobsf/StaticAnalyzer/views/android/manifest_analysis.py", line 909, in get_manifest_apk
    subprocess.check_output(args)  # lgtm [py/command-line-injection] md5 hash
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['java', '-jar', '/root/Mobile-Security-Framework-MobSF-3.6.0/mobsf/StaticAnalyzer/tools/apktool_2.6.1.jar', '--match-origin '/tmp', '-f', '-s', 'd', '/root/.MobSF/uploads/5b1ee7e42efdff2aedf675221a604ddb/5b1ee7e42efdff2aedf675221a604ddb.apk', '-o', '/root/.MobSF/uploads/5b1ee7e42efdff2atool_out']' returned non-zero exit status 1.
[ERROR] 09/Oct/2022 04:10:11 - Parsing Manifest file
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF-3.6.0/mobsf/StaticAnalyzer/views/android/manifest_analysis.py", line 41, in get_manifest
    mfile = Path(manifest_file)
  File "/usr/lib/python3.8/pathlib.py", line 1042, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.8/pathlib.py", line 683, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.8/pathlib.py", line 667, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[ERROR] 09/Oct/2022 04:10:11 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF-3.6.0/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 161, in static_analyzer
    mani_file, mani_xml = get_manifest(
TypeError: cannot unpack non-iterable NoneType object
[ERROR] 09/Oct/2022 04:10:11 - cannot unpack non-iterable NoneType object
[ERROR] 09/Oct/2022 04:10:11 - Internal Server Error: /static_analyzer/
[2022-10-09 12:10:33 +0800] [3055] [INFO] Handling signal: winch
`
## STEPS TO REPRODUCE THE ISSUE
```
An exception occurs after uploading the APK analysis and cannot be performed. How to solve the problem?
```

## LOG FILE

```
[debug.log](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/9740757/debug.log)
APK file download : https://bibmobilepro.bibvip929.com/app_download/android/bib_prod_1.0.072.apk
Paste the contents of ~/.MobSF/debug.log here or attach the log file.
```

**Comment by ohyeah521** [comment]
This bug should be submitted to apktool, because it is a bug of apktool

**Comment by siberiah0h** [comment]
thinks
