### ISSUE TITLE
Docker images broken starting with 3.5.x

### ISSUE THREAD

**Issue by t3chn0m4g3** [MobSF/Mobile-Security-Framework-MobSF#2055]
## ENVIRONMENT

```
OS and Version: Docker, macOS 12.6
Python Version: provided through docker image
MobSF Version: provided through docker image
```

## EXPLANATION OF THE ISSUE

```
MobSF stops running due to an error based on failed requirements for SCRAM authentication.
```

## STEPS TO REPRODUCE THE ISSUE

```
For every docker based version of MobSF 3.5+:
docker-compose build
docker-compose up
```

## LOG FILE

```
mobile-security-framework-mobsf-mobsf-1     |   __  __       _    ____  _____       _____  __
mobile-security-framework-mobsf-mobsf-1     |  |  \/  | ___ | |__/ ___||  ___|_   _|___ / / /_
mobile-security-framework-mobsf-mobsf-1     |  | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| '_ \
mobile-security-framework-mobsf-mobsf-1     |  | |  | | (_) | |_) |__) |  _|  \ V / ___) | (_) |
mobile-security-framework-mobsf-mobsf-1     |  |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/
mobile-security-framework-mobsf-mobsf-1     |
mobile-security-framework-mobsf-mobsf-1     | [INFO] 18/Oct/2022 12:49:22 - Mobile Security Framework v3.6.1 Beta
mobile-security-framework-mobsf-mobsf-1     | REST API Key: d117c7730ebd1d0eb90d9f72013746e4a2ae8465a0cdffb8463c1e04320b2815
mobile-security-framework-mobsf-mobsf-1     | [INFO] 18/Oct/2022 12:49:22 - OS: Linux
mobile-security-framework-mobsf-mobsf-1     | [INFO] 18/Oct/2022 12:49:22 - Platform: Linux-5.10.124-linuxkit-aarch64-with-glibc2.29
mobile-security-framework-mobsf-mobsf-1     | [INFO] 18/Oct/2022 12:49:22 - Dist: ubuntu 20.04 Focal Fossa
mobile-security-framework-mobsf-mobsf-1     | [INFO] 18/Oct/2022 12:49:22 - MobSF Basic Environment Check
mobile-security-framework-mobsf-mobsf-1     | Traceback (most recent call last):
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 282, in ensure_connection
mobile-security-framework-mobsf-mobsf-1     |     self.connect()
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 26, in inner
mobile-security-framework-mobsf-mobsf-1     |     return func(*args, **kwargs)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 263, in connect
mobile-security-framework-mobsf-mobsf-1     |     self.connection = self.get_new_connection(conn_params)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 26, in inner
mobile-security-framework-mobsf-mobsf-1     |     return func(*args, **kwargs)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
mobile-security-framework-mobsf-mobsf-1     |     connection = Database.connect(**conn_params)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/psycopg2/__init__.py", line 122, in connect
mobile-security-framework-mobsf-mobsf-1     |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
mobile-security-framework-mobsf-mobsf-1     | psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above
mobile-security-framework-mobsf-mobsf-1     |
mobile-security-framework-mobsf-mobsf-1     |
mobile-security-framework-mobsf-mobsf-1     | The above exception was the direct cause of the following exception:
mobile-security-framework-mobsf-mobsf-1     |
mobile-security-framework-mobsf-mobsf-1     | Traceback (most recent call last):
mobile-security-framework-mobsf-mobsf-1     |   File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/../manage.py", line 18, in <module>
mobile-security-framework-mobsf-mobsf-1     |     execute_from_command_line(sys.argv)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
mobile-security-framework-mobsf-mobsf-1     |     utility.execute()
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 440, in execute
mobile-security-framework-mobsf-mobsf-1     |     self.fetch_command(subcommand).run_from_argv(self.argv)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 402, in run_from_argv
mobile-security-framework-mobsf-mobsf-1     |     self.execute(*args, **cmd_options)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 448, in execute
mobile-security-framework-mobsf-mobsf-1     |     output = self.handle(*args, **options)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 96, in wrapped
mobile-security-framework-mobsf-mobsf-1     |     res = handle_func(*args, **kwargs)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/migrate.py", line 114, in handle
mobile-security-framework-mobsf-mobsf-1     |     executor = MigrationExecutor(connection, self.migration_progress_callback)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/executor.py", line 18, in __init__
mobile-security-framework-mobsf-mobsf-1     |     self.loader = MigrationLoader(self.connection)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/loader.py", line 58, in __init__
mobile-security-framework-mobsf-mobsf-1     |     self.build_graph()
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/loader.py", line 235, in build_graph
mobile-security-framework-mobsf-mobsf-1     |     self.applied_migrations = recorder.applied_migrations()
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
mobile-security-framework-mobsf-mobsf-1     |     if self.has_table():
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/recorder.py", line 57, in has_table
mobile-security-framework-mobsf-mobsf-1     |     with self.connection.cursor() as cursor:
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 26, in inner
mobile-security-framework-mobsf-mobsf-1     |     return func(*args, **kwargs)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 323, in cursor
mobile-security-framework-mobsf-mobsf-1     |     return self._cursor()
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 299, in _cursor
mobile-security-framework-mobsf-mobsf-1     |     self.ensure_connection()
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 26, in inner
mobile-security-framework-mobsf-mobsf-1     |     return func(*args, **kwargs)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 282, in ensure_connection
mobile-security-framework-mobsf-mobsf-1     |     self.connect()
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 91, in __exit__
mobile-security-framework-mobsf-mobsf-1     |     raise dj_exc_value.with_traceback(traceback) from exc_value
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 282, in ensure_connection
mobile-security-framework-mobsf-mobsf-1     |     self.connect()
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 26, in inner
mobile-security-framework-mobsf-mobsf-1     |     return func(*args, **kwargs)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 263, in connect
mobile-security-framework-mobsf-mobsf-1     |     self.connection = self.get_new_connection(conn_params)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 26, in inner
mobile-security-framework-mobsf-mobsf-1     |     return func(*args, **kwargs)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
mobile-security-framework-mobsf-mobsf-1     |     connection = Database.connect(**conn_params)
mobile-security-framework-mobsf-mobsf-1     |   File "/usr/local/lib/python3.8/dist-packages/psycopg2/__init__.py", line 122, in connect
mobile-security-framework-mobsf-mobsf-1     |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
mobile-security-framework-mobsf-mobsf-1     | django.db.utils.OperationalError: SCRAM authentication requires libpq version 10 or above
mobile-security-framework-mobsf-mobsf-1     |
mobile-security-framework-mobsf-mobsf-1     | [INFO] 18/Oct/2022 12:49:22 - Checking for Update.
mobile-security-framework-mobsf-mobsf-1     | [INFO] 18/Oct/2022 12:49:23 - No updates available.
mobile-security-framework-mobsf-mobsf-1     | [INFO] 18/Oct/2022 12:49:23 -
```

**Comment by t3chn0m4g3** [comment]
@superpoussin22 Thank you for the time to investigate this. I will leave this open and monitor if anything changes upstream.

**Comment by ajinabraham** [comment]
Closing this since the fix needs to come from psycopg.
