### ISSUE TITLE
[iOS] bug , 

### ISSUE THREAD

**Issue by jhay06** [MobSF/Mobile-Security-Framework-MobSF#2072]
Hello ,  
 will share my experience today , 

i have a problem in latest version . i have an old version before that is working (i don't know the actual version number)  and have no problem in ios 

but when i pull the latest and resetup it 
i try to scan one ios app 

and got below error 
```
Traceback (most recent call last):
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: StaticAnalyzer_suppressfindings

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/ios/db_interaction.py", line 79, in get_context_from_analysis
    code = process_suppression(
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/common/suppression.py", line 239, in process_suppression
    if not filters.exists():
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1225, in exists
    return self.query.has_results(using=self.db)
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 592, in has_results
    return compiler.has_results()
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1366, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: StaticAnalyzer_suppressfindings
[ERROR] 11/Nov/2022 02:47:38 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/ios/static_analyzer.py", line 185, in static_analyzer_ios
    context['virus_total'] = None
TypeError: 'NoneType' object does not support item assignment
[ERROR] 11/Nov/2022 02:47:38 - 'NoneType' object does not support item assignment
[ERROR] 11/Nov/2022 02:47:38 - Internal Server Error: /static_analyzer_ios/
[INFO] 11/Nov/2022 02:47:38 - iOS Static Analysis Started
[INFO] 11/Nov/2022 02:47:38 - Analysis is already Done. Fetching data from the DB...
[ERROR] 11/Nov/2022 02:47:38 - Fetching from DB
Traceback (most recent call last):
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: StaticAnalyzer_suppressfindings

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/ios/db_interaction.py", line 19, in get_context_from_db_entry
    code = process_suppression(
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/common/suppression.py", line 239, in process_suppression
    if not filters.exists():
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1225, in exists
    return self.query.has_results(using=self.db)
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 592, in has_results
    return compiler.has_results()
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1366, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: StaticAnalyzer_suppressfindings
[ERROR] 11/Nov/2022 02:47:38 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/home/jhay/test/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/ios/static_analyzer.py", line 185, in static_analyzer_ios
    context['virus_total'] = None
TypeError: 'NoneType' object does not support item assignment
[ERROR] 11/Nov/2022 02:47:38 - 'NoneType' object does not support item assignment
[ERROR] 11/Nov/2022 02:47:38 - Internal Server Error: /static_analyzer_ios/
```

i have ubuntu 22.04

**Comment by jhay06** [comment]
What i did to resolve but still no luck 

migrate staticanalyzer 
remove existing mobsf and clone the latest and run again the setup.sh 

but still the same error

**Comment by jhay06** [comment]
@ajinabraham  why you closed this ? it is not yet resolved

**Comment by ajinabraham** [comment]
Please use slack.

https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/2072#issuecomment-1311176970

**Comment by jhay06** [comment]
![image](https://user-images.githubusercontent.com/5191437/201269747-d8e0c081-61d4-4584-913f-1df93f639b08.png)

**Comment by jhay06** [comment]
can't join , i don't know why

**Comment by ajinabraham** [comment]
Might be a slack issue, just sent a slack invite to your email.

**Comment by jhay06** [comment]
> Might be a slack issue, just sent a slack invite to your email.


got the invitation thanks .

**Comment by Takaeda4413** [comment]
@ajinabraham can I also get an invite? the email is raandom.smiith@gmail.com Thank you.

**Comment by ajinabraham** [comment]
Looks like you are already in the Slack workspace
