### ISSUE TITLE
Download and Analyze function not working

### ISSUE THREAD

**Issue by ThetaEdra** [MobSF/Mobile-Security-Framework-MobSF#2087]
## ENVIRONMENT

```
OS and Version: Ubuntu 20.04.5 LTS x86_64
Python Version: Python 3.8.10
MobSF Version: v3.6 beta
```

## EXPLANATION OF THE ISSUE

```
When i use the download and scan by package name i get an error and the app crashes.
What should happen: The given app should be downloaded and analyzed
```

## STEPS TO REPRODUCE THE ISSUE

```
1. Install the listed Version under the listed os
2. Use the run.sh file and run the Framework
3. Use the download and analyze function and watch it crash
```

## LOG 

The App Shows in Browser:
```
Error
Operation doesn't work on directories.
[Errno 21] Is a directory: '/home/X/.MobSF/uploads/ebc35e89281ea16a4bd1273752429a43'
```
And in Console:
```
[ERROR] 11/Dec/2022 10:31:12 - Error Performing Static Analysis
Traceback (most recent call last):
  File "/home/X/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 182, in static_analyzer
    get_icon_apk(app_dic)
  File "/home/X/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/icon_analysis.py", line 216, in get_icon_apk
    copy2(src.as_posix(), out.as_posix())
  File "/usr/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
IsADirectoryError: [Errno 21] Is a directory: '/home/X/.MobSF/uploads/ebc35e89281ea16a4bd1273752429a43'
[ERROR] 11/Dec/2022 10:31:12 - [Errno 21] Is a directory: '/home/X/.MobSF/uploads/ebc35e89281ea16a4bd1273752429a43'
[ERROR] 11/Dec/2022 10:31:12 - Internal Server Error: /static_analyzer/
```

**Comment by ohyeah521** [comment]
maybe the apk file you analyzed was confused, so the icon copy crashed. Can you share your apk? Let me see for you

**Comment by ThetaEdra** [comment]
I just tried it with an older app and it worked. Maybe it is too new? I was interested to check de.asta_bochum.campus_app
