### ISSUE TITLE
[ERROR] Trackers DB Update

### ISSUE THREAD

**Issue by durianstudio** [MobSF/Mobile-Security-Framework-MobSF#2108]
## ENVIRONMENT

```
OS and Version: Windows 10 22H2
Python Version: 3.8.10
MobSF Version:  Mobile Security Framework v3.6.2 Beta
```

## EXPLANATION OF THE ISSUE

```
What happens, under which versions, under what conditions, when, and what were you expecting instead.
```

## STEPS TO REPRODUCE THE ISSUE

```
1. I was able to run the run.bat 127.0.0.1:8000
2. I wanted to try the static analysis and after few seconds : 
    Error
    File not found.

    [Errno 2] No such file or directory: 'C:\\Users\\kamote\\.MobSF\\signatures/exodus_trackers'
4. [ERROR] 03/Jan/2023 21:04:02 - [ERROR] Trackers DB Update
```

## LOG FILE

```
Paste the contents of ~/.MobSF/debug.log here or attach the log file.
```
[ERROR] 03/Jan/2023 21:04:07 - [ERROR] Trackers DB Update
Traceback (most recent call last):
  File "C:\Users\kamote\Mobile-Security-Framework-MobSF\venv\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\kamote\Mobile-Security-Framework-MobSF\venv\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\kamote\AppData\Local\Programs\Python\Python38\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kamote\Mobile-Security-Framework-MobSF\venv\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\kamote\Mobile-Security-Framework-MobSF\venv\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\kamote\Mobile-Security-Framework-MobSF\venv\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\kamote\Mobile-Security-Framework-MobSF\venv\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\kamote\Mobile-Security-Framework-MobSF\venv\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000022590360610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kamote\Mobile-Security-Framework-MobSF\venv\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\kamote\Mobile-Security-Framework-MobSF\venv\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\kamote\Mobile-Security-Framework-MobSF\venv\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='reports.exodus-privacy.eu.org', port=443): Max retries exceeded with url: /api/trackers (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022590360610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kamote\Mobile-Security-Framework-MobSF\mobsf\MobSF\utils.py", line 423, in update_local_db
    response = requests.get(url,
  File "C:\Users\kamote\Mobile-Security-Framework-MobSF\venv\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\kamote\Mobile-Security-Framework-MobSF\venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\kamote\Mobile-Security-Framework-MobSF\venv\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\kamote\Mobile-Security-Framework-MobSF\venv\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\kamote\Mobile-Security-Framework-MobSF\venv\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='reports.exodus-privacy.eu.org', port=443): Max retries exceeded with url: /api/trackers (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022590360610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[INFO] 03/Jan/2023 21:04:07 - Detecting Trackers
[ERROR] 03/Jan/2023 21:04:07 - Error Performing Static Analysis
Traceback (most recent call last):
  File "C:\Users\kamote\Mobile-Security-Framework-MobSF\mobsf\StaticAnalyzer\views\android\static_analyzer.py", line 205, in static_analyzer
    tracker_res = tracker.get_trackers()
  File "C:\Users\kamote\Mobile-Security-Framework-MobSF\mobsf\MalwareAnalyzer\views\Trackers.py", line 209, in get_trackers
    trackers = self.detect_trackers()
  File "C:\Users\kamote\Mobile-Security-Framework-MobSF\mobsf\MalwareAnalyzer\views\Trackers.py", line 184, in detect_trackers
    self.load_trackers_signatures()
  File "C:\Users\kamote\Mobile-Security-Framework-MobSF\mobsf\MalwareAnalyzer\views\Trackers.py", line 102, in load_trackers_signatures
    with io.open(self.tracker_db,
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\kamote\\.MobSF\\signatures/exodus_trackers'
[ERROR] 03/Jan/2023 21:04:07 - [Errno 2] No such file or directory: 'C:\\Users\\kamote\\.MobSF\\signatures/exodus_trackers'
[ERROR] 03/Jan/2023 21:04:07 - Internal Server Error: /static_analyzer/
ERROR:django.request:Internal Server Error: /static_analyzer/

**Comment by superpoussin22** [comment]
please use slack channel instead for help
