### ISSUE TITLE
MacBook M2 Darwin 22.3.0 RELEASE_ARM64_T6020 arm64 fails to ./setup.sh

### ISSUE THREAD

**Issue by thistehneisen** [MobSF/Mobile-Security-Framework-MobSF#2147]
## ENVIRONMENT

```
OS and Version: Darwin 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6020 arm64
Python Version: Python 3.9.6
MobSF Version: v3.6.0
```

## EXPLANATION OF THE ISSUE

```
Successfully built lxml biplist bs4 http-tools libsast frida blinker urwid zstandard kaitaistruct pyperclip peewee
Failed to build cryptography
ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects
[INSTALL] Clean Up

=======================MobSF Clean Script for Unix=======================
Running this script will delete the Scan database, all files uploaded and generated.

Deleting all uploads
Deleting all downloads
Deleting Static Analyzer migrations
Deleting Dynamic Analyzer migrations
Deleting MobSF migrations
Deleting Python byte code files
Deleting temp and log files
Deleting Scan database
Deleting Secret file
Deleting MobSF data directory: /Users/npu/.MobSF
Done
[INSTALL] Migrating Database
Traceback (most recent call last):
  File "/Users/npu/Code/Python/Mobile-Security-Framework-MobSF/manage.py", line 12, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "/Users/npu/Code/Python/Mobile-Security-Framework-MobSF/manage.py", line 12, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "/Users/npu/Code/Python/Mobile-Security-Framework-MobSF/manage.py", line 12, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
./setup.sh: line 72: wkhtmltopdf: command not found
Download and Install wkhtmltopdf for PDF Report Generation - https://wkhtmltopdf.org/downloads.html
[INSTALL] Installation Complete
[ERROR] Installation Failed!
Please ensure that all the requirements mentioned in documentation are installed before you run setup script.
Scroll up to see any installation errors.

The 'decorator==4.4.2' distribution was not found and is required by the application
```

## STEPS TO REPRODUCE THE ISSUE

```
1. git clone repository
2. cd && ./setup.sh
3. it fails
```

## LOG FILE

```
➜  Mobile-Security-Framework-MobSF git:(master) cat ~/.MobSF/debug.log
cat: /Users/npu/.MobSF/debug.log: No such file or directory
```

**Comment by ajinabraham** [comment]
Please use slack channel for support
