### ISSUE TITLE
docker image does not start

### ISSUE THREAD

**Issue by javixeneize** [MobSF/Mobile-Security-Framework-MobSF#2165]
Hi

There are some issues with the docker image for mobsf. after starting it, there are lots of errors

  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/MobSF/urls.py", line 12, in <module>
    from mobsf.MobSF.views.api import api_static_analysis as api_sz
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/MobSF/views/api/api_static_analysis.py", line 11, in <module>
    from mobsf.StaticAnalyzer.views.android.static_analyzer import static_analyzer
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 33, in <module>
    from mobsf.StaticAnalyzer.views.android.binary_analysis import elf_analysis
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/binary_analysis.py", line 8, in <module>
    import lief
  File "/usr/local/lib/python3.8/dist-packages/lief/__init__.py", line 2, in <module>
    from . import _lief
ImportError: cannot import name '_lief' from partially initialized module 'lief' (most likely due to a circular import) (/usr/local/lib/python3.8/dist-packages/lief/__init__.py)

**Comment by ajinabraham** [comment]
Can you share reproduction steps. Doesn't see this on latest MobSF docker image with Android APK static analysis via UI and REST API.

**Comment by eabbott2b** [comment]
I am also getting this error. I am using a MacOS with Silicon M2 chip.

I ran the following two commands as described in easy setup

`docker pull opensecurity/mobile-security-framework-mobsf`

`docker run -it --rm -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest`

```
Traceback (most recent call last):
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/../manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 453, in execute
    self.check()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/MobSF/urls.py", line 12, in <module>
    from mobsf.MobSF.views.api import api_static_analysis as api_sz
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/MobSF/views/api/api_static_analysis.py", line 11, in <module>
    from mobsf.StaticAnalyzer.views.android.static_analyzer import static_analyzer
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 33, in <module>
    from mobsf.StaticAnalyzer.views.android.binary_analysis import elf_analysis
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/binary_analysis.py", line 8, in <module>
    import lief
  File "/usr/local/lib/python3.8/dist-packages/lief/__init__.py", line 2, in <module>
    from . import _lief
ImportError: cannot import name '_lief' from partially initialized module 'lief' (most likely due to a circular import) (/usr/local/lib/python3.8/dist-packages/lief/__init__.py)
Traceback (most recent call last):
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/../manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 453, in execute
    self.check()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/MobSF/urls.py", line 12, in <module>
    from mobsf.MobSF.views.api import api_static_analysis as api_sz
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/MobSF/views/api/api_static_analysis.py", line 11, in <module>
    from mobsf.StaticAnalyzer.views.android.static_analyzer import static_analyzer
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 33, in <module>
    from mobsf.StaticAnalyzer.views.android.binary_analysis import elf_analysis
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/binary_analysis.py", line 8, in <module>
    import lief
  File "/usr/local/lib/python3.8/dist-packages/lief/__init__.py", line 2, in <module>
    from . import _lief
ImportError: cannot import name '_lief' from partially initialized module 'lief' (most likely due to a circular import) (/usr/local/lib/python3.8/dist-packages/lief/__init__.py)
Traceback (most recent call last):
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/../manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/migrate.py", line 100, in handle
    self.check(databases=[database])
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/MobSF/urls.py", line 12, in <module>
    from mobsf.MobSF.views.api import api_static_analysis as api_sz
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/MobSF/views/api/api_static_analysis.py", line 11, in <module>
    from mobsf.StaticAnalyzer.views.android.static_analyzer import static_analyzer
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 33, in <module>
    from mobsf.StaticAnalyzer.views.android.binary_analysis import elf_analysis
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/binary_analysis.py", line 8, in <module>
    import lief
  File "/usr/local/lib/python3.8/dist-packages/lief/__init__.py", line 2, in <module>
    from . import _lief
ImportError: cannot import name '_lief' from partially initialized module 'lief' (most likely due to a circular import) (/usr/local/lib/python3.8/dist-packages/lief/__init__.py)
Traceback (most recent call last):
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/../manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/migrate.py", line 100, in handle
    self.check(databases=[database])
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/MobSF/urls.py", line 12, in <module>
    from mobsf.MobSF.views.api import api_static_analysis as api_sz
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/MobSF/views/api/api_static_analysis.py", line 11, in <module>
    from mobsf.StaticAnalyzer.views.android.static_analyzer import static_analyzer
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 33, in <module>
    from mobsf.StaticAnalyzer.views.android.binary_analysis import elf_analysis
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/binary_analysis.py", line 8, in <module>
    import lief
  File "/usr/local/lib/python3.8/dist-packages/lief/__init__.py", line 2, in <module>
    from . import _lief
ImportError: cannot import name '_lief' from partially initialized module 'lief' (most likely due to a circular import) (/usr/local/lib/python3.8/dist-packages/lief/__init__.py)
Traceback (most recent call last):
  File "manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 453, in execute
    self.check()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/MobSF/urls.py", line 12, in <module>
    from mobsf.MobSF.views.api import api_static_analysis as api_sz
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/MobSF/views/api/api_static_analysis.py", line 11, in <module>
    from mobsf.StaticAnalyzer.views.android.static_analyzer import static_analyzer
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 33, in <module>
    from mobsf.StaticAnalyzer.views.android.binary_analysis import elf_analysis
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/binary_analysis.py", line 8, in <module>
    import lief
  File "/usr/local/lib/python3.8/dist-packages/lief/__init__.py", line 2, in <module>
    from . import _lief
ImportError: cannot import name '_lief' from partially initialized module 'lief' (most likely due to a circular import) (/usr/local/lib/python3.8/dist-packages/lief/__init__.py)
```

I then get internal server error when browsing to http://localhost:8000/

**Comment by javixeneize** [comment]
It’s just pull and run, as per the instructions. That’s on an M1 too so maybe it’s a problem with the arch

**Comment by iosifache** [comment]
I encountered the same issue after installing the package through `pip`, on a system with an M-series processor :v:.

**Comment by ajinabraham** [comment]
I don't have an M1/M2 chip to replicate this. We have a ARM image available at docker hub. May be you can pin to the ARM sha and try using that image https://hub.docker.com/layers/opensecurity/mobile-security-framework-mobsf/latest/images/sha256-19b90a2b7495967f7fa1cc2cd681080ff39c6a3828ee868c5a9ad2b2bd0608a9?context=explore

Otherwise, this looks like an internal LIEF issue in the said arch.

```
 File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/binary_analysis.py", line 8, in <module>
    import lief
  File "/usr/local/lib/python3.8/dist-packages/lief/__init__.py", line 2, in <module>
    from . import _lief
ImportError: cannot import name '_lief' from partially initialized module 'lief' (most likely due to a circular import) (/usr/local/lib/python3.8/dist-packages/lief/__init__.py)
Traceback (most recent call last):
```

You should replicate it with something like

```
pip install lief
python3
>>import lief
```

And report to the lief project here: https://github.com/lief-project/LIEF

**Comment by javixeneize** [comment]
Hi

I have tried that image and still failing. However, if i checkout the repo and install all the dependencies in my local machine, it works, so thats not a lief issue or an incompatibility issue with ARM chips

**Comment by ajinabraham** [comment]
The latest image works fine on my intel machine, in-fact the same is auto deployed to mobsf.live

**Comment by TAC911** [comment]
Facing same issues on two different M1 machines.

**Comment by srhtshn** [comment]
https://github.com/lief-project/LIEF/issues/901 
This seems like a problem with lief. The fix is merged but not released yet. I was able to run docker image by changing lief version to previous one.

**Comment by gustysap** [comment]
@lauritzh thank you currently works on m1 machine using `--platform linux/amd64` .

**Comment by falconws** [comment]
Same issue happened to me.
Can I run without `--platform linux/amd64` option?
This option is very poor performance...

**Comment by falconws** [comment]
```bash
docker run -it --rm --name mobsf -p 8001:8000 opensecurity/mobile-security-framework-mobsf:v3.6.0
```
Is working on M1 arch.

**Comment by ajinabraham** [comment]
Closing this as it's a LIEF issue on M1/M2

**Comment by ajinabraham** [comment]
There is nothing we can do from our end unless LIEF fixes this. You could run with `--platform linux/amd64` on M1/M2 at the cost of degraded performance.

**Comment by CarlesLlobet** [comment]
> There is nothing we can do from our end unless LIEF fixes this. You could run with `--platform linux/amd64` on M1/M2 at the cost of degraded performance.

Couldn't we set this change in `requirements.txt` until [lief-project/LIEF#901](https://github.com/lief-project/LIEF/issues/901)  fix is merged to master:
~lief>=0.12.3~
lief==0.12.3

This would get a MobSF docker image working in all platforms until lief is fixed.

**Comment by ajinabraham** [comment]
This issue exist in `lief==0.12.3` as well. The latest docker image seems to have `lief==0.12.3` installed.
I just merged a PR to update lief to 0.13.1. Hopefully this will fix the issue on M1/M2 after the new images are built.

**Comment by ajinabraham** [comment]
Unfortunately the variant is not available in pip yet.
```
#17 7.988 ERROR: Could not find a version that satisfies the requirement lief>=0.13.1 (from -r requirements.txt (line 18)) (from versions: 0.8.0.post7, 0.8.1.post1, 0.8.2.post1, 0.8.3.post3, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.11.4, 0.11.5, 0.12.0, 0.12.1, 0.12.2, 0.12.3)
#17 8.159 ERROR: No matching distribution found for lief>=0.13.1 (from -r requirements.txt (line 18))
```

**Comment by CarlesLlobet** [comment]
Hey @ajinabraham,

Could you try again now? 
It's weird cause [0.13.1 is available in pip since May 28th, but 2 days ago they released also 0.13.2](https://pypi.org/project/lief/#history), let's see if now we could fix this with lief update and get MobSF running on any ARM device 👍

**Comment by ajinabraham** [comment]
I think they probably haven't released the architecture specific wheels.
pip cannot find the correct version still.

<img width="945" alt="Screenshot 2023-06-21 at 3 58 24 PM" src="https://github.com/MobSF/Mobile-Security-Framework-MobSF/assets/4301109/28c522d9-e6e8-4178-9925-9efc316debc1">

**Comment by clintmod** [comment]
In docker desktop you can enable the new beta Rosetta feature in "Features under development"

```
Use Rosetta for x86/amd64 emulation on Apple Silicon
Turns on Rosetta to accelerate x86/amd64 binary emulation on Apple Silicon. Note - you must have the Virtualization Framework enabled (via the toggle on the General panel).
```
