### ISSUE TITLE
unable to run dynamic analysis

### ISSUE THREAD

**Issue by jwjungjwjung** [MobSF/Mobile-Security-Framework-MobSF#2169]
## ENVIRONMENT

```
OS and Version: Windows OS 19045.2846
Python Version: 3.10.9
MobSF Version: 3.6.6 Beta
```

## EXPLANATION OF THE ISSUE

```
After successfully running static analysis, I tried to run dynamic analysis, but it didn't work. I checked my cmd and it looked like this.

[INFO] 22/Apr/2023 01:01:12 - Starting HTTPs Proxy on 1337
[ERROR] 22/Apr/2023 01:01:16 - Dynamic Analyzer
Traceback (most recent call last):
  File "C:\Users\mysti\Downloads\MobSF\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\mobsf\DynamicAnalyzer\views\android\dynamic_analyzer.py", line 185, in dynamic_analyzer
    env.configure_proxy(package, request)
  File "C:\Users\mysti\Downloads\MobSF\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\mobsf\DynamicAnalyzer\views\android\environment.py", line 184, in configure_proxy
    start_proxy(proxy_port, project)
  File "C:\Users\mysti\Downloads\MobSF\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\mobsf\DynamicAnalyzer\tools\webproxy.py", line 46, in start_proxy
    subprocess.Popen(argz, stdout=fnull, stderr=subprocess.STDOUT)
  File "C:\Users\mysti\anaconda3\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\mysti\anaconda3\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,

## STEPS TO REPRODUCE THE ISSUE

1. run setup.bat
2. run run.bat 127.0.0.1:8000
3. finish static analysis
4. attempt to run dynamic analysis


## LOG FILE

[INFO] 22/Apr/2023 00:59:39 - 
  __  __       _    ____  _____       _____  __   
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / /_  
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| '_ \ 
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | (_) |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/ 

[INFO] 22/Apr/2023 00:59:39 - Mobile Security Framework v3.6.6 Beta
[INFO] 22/Apr/2023 00:59:39 - OS: Windows
[INFO] 22/Apr/2023 00:59:39 - Platform: Windows-10-10.0.19045-SP0
[INFO] 22/Apr/2023 00:59:39 - MobSF Basic Environment Check
[INFO] 22/Apr/2023 00:59:39 - Checking for Update.
[INFO] 22/Apr/2023 00:59:40 - No updates available.
[INFO] 22/Apr/2023 00:59:41 - 
  __  __       _    ____  _____       _____  __   
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / /_  
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| '_ \ 
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | (_) |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/ 

[INFO] 22/Apr/2023 00:59:41 - Mobile Security Framework v3.6.6 Beta
[INFO] 22/Apr/2023 00:59:41 - OS: Windows
[INFO] 22/Apr/2023 00:59:41 - Platform: Windows-10-10.0.19045-SP0
[INFO] 22/Apr/2023 00:59:41 - MobSF Basic Environment Check
[INFO] 22/Apr/2023 00:59:41 - Checking for Update.
[INFO] 22/Apr/2023 00:59:41 - No updates available.
[INFO] 22/Apr/2023 00:59:43 - 
  __  __       _    ____  _____       _____  __   
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / /_  
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| '_ \ 
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | (_) |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/ 

[INFO] 22/Apr/2023 00:59:43 - Mobile Security Framework v3.6.6 Beta
[INFO] 22/Apr/2023 00:59:43 - OS: Windows
[INFO] 22/Apr/2023 00:59:43 - Platform: Windows-10-10.0.19045-SP0
[INFO] 22/Apr/2023 00:59:43 - MobSF Basic Environment Check
[INFO] 22/Apr/2023 00:59:43 - Checking for Update.
[INFO] 22/Apr/2023 00:59:43 - No updates available.
[INFO] 22/Apr/2023 00:59:45 - 
  __  __       _    ____  _____       _____  __   
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / /_  
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| '_ \ 
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | (_) |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/ 

[INFO] 22/Apr/2023 00:59:45 - Mobile Security Framework v3.6.6 Beta
[INFO] 22/Apr/2023 00:59:45 - OS: Windows
[INFO] 22/Apr/2023 00:59:45 - Platform: Windows-10-10.0.19045-SP0
[INFO] 22/Apr/2023 00:59:45 - MobSF Basic Environment Check
[INFO] 22/Apr/2023 00:59:45 - Checking for Update.
[INFO] 22/Apr/2023 00:59:45 - No updates available.
[INFO] 22/Apr/2023 00:59:56 - 
  __  __       _    ____  _____       _____  __   
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / /_  
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| '_ \ 
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | (_) |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/ 

[INFO] 22/Apr/2023 00:59:56 - Mobile Security Framework v3.6.6 Beta
[INFO] 22/Apr/2023 00:59:56 - OS: Windows
[INFO] 22/Apr/2023 00:59:56 - Platform: Windows-10-10.0.19045-SP0
[INFO] 22/Apr/2023 00:59:56 - MobSF Basic Environment Check
[INFO] 22/Apr/2023 00:59:56 - Checking for Update.
[INFO] 22/Apr/2023 00:59:56 - No updates available.
[INFO] 22/Apr/2023 00:59:57 - 
  __  __       _    ____  _____       _____  __   
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / /_  
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| '_ \ 
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | (_) |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/ 

[INFO] 22/Apr/2023 00:59:57 - Mobile Security Framework v3.6.6 Beta
[INFO] 22/Apr/2023 00:59:57 - OS: Windows
[INFO] 22/Apr/2023 00:59:57 - Platform: Windows-10-10.0.19045-SP0
[INFO] 22/Apr/2023 00:59:57 - MobSF Basic Environment Check
[INFO] 22/Apr/2023 00:59:58 - Checking for Update.
[INFO] 22/Apr/2023 00:59:58 - No updates available.
[INFO] 22/Apr/2023 00:59:59 - 
  __  __       _    ____  _____       _____  __   
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / /_  
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| '_ \ 
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | (_) |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/ 

[INFO] 22/Apr/2023 00:59:59 - Mobile Security Framework v3.6.6 Beta
[INFO] 22/Apr/2023 00:59:59 - OS: Windows
[INFO] 22/Apr/2023 00:59:59 - Platform: Windows-10-10.0.19045-SP0
[INFO] 22/Apr/2023 00:59:59 - MobSF Basic Environment Check
[INFO] 22/Apr/2023 00:59:59 - Checking for Update.
[INFO] 22/Apr/2023 00:59:59 - No updates available.
[INFO] 22/Apr/2023 01:00:52 - 
  __  __       _    ____  _____       _____  __   
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / /_  
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| '_ \ 
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | (_) |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/ 

[INFO] 22/Apr/2023 01:00:52 - Mobile Security Framework v3.6.6 Beta
[INFO] 22/Apr/2023 01:00:52 - OS: Windows
[INFO] 22/Apr/2023 01:00:52 - Platform: Windows-10-10.0.19045-SP0
[INFO] 22/Apr/2023 01:00:52 - MobSF Basic Environment Check
[INFO] 22/Apr/2023 01:00:52 - Checking for Update.
[INFO] 22/Apr/2023 01:00:52 - No updates available.
[INFO] 22/Apr/2023 01:00:58 - Creating Dynamic Analysis Environment for com.baedalyakgook_user
[WARNING] 22/Apr/2023 01:00:58 - Failed to get Activities. Static Analysis not completed for the app.
[INFO] 22/Apr/2023 01:01:03 - ADB Restarted
[INFO] 22/Apr/2023 01:01:03 - Waiting for 2 seconds...
[INFO] 22/Apr/2023 01:01:05 - Connecting to Android 192.168.124.101:5555
[INFO] 22/Apr/2023 01:01:05 - Waiting for 2 seconds...
[INFO] 22/Apr/2023 01:01:07 - Restarting ADB Daemon as root
[INFO] 22/Apr/2023 01:01:07 - Waiting for 2 seconds...
[INFO] 22/Apr/2023 01:01:09 - Reconnecting to Android Device
[INFO] 22/Apr/2023 01:01:09 - Waiting for 2 seconds...
[INFO] 22/Apr/2023 01:01:11 - Found Genymotion x86 Android VM
[INFO] 22/Apr/2023 01:01:11 - Remounting
[INFO] 22/Apr/2023 01:01:11 - Performing System check
[INFO] 22/Apr/2023 01:01:11 - Android API Level identified as 27
[INFO] 22/Apr/2023 01:01:11 - Android Version identified as 8.1
[INFO] 22/Apr/2023 01:01:11 - Environment MobSFyed Check
[INFO] 22/Apr/2023 01:01:12 - Installing MobSF RootCA
[INFO] 22/Apr/2023 01:01:12 - Starting HTTPs Proxy on 1337
[ERROR] 22/Apr/2023 01:01:16 - Dynamic Analyzer
Traceback (most recent call last):
  File "C:\Users\mysti\Downloads\MobSF\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\mobsf\DynamicAnalyzer\views\android\dynamic_analyzer.py", line 185, in dynamic_analyzer
    env.configure_proxy(package, request)
  File "C:\Users\mysti\Downloads\MobSF\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\mobsf\DynamicAnalyzer\views\android\environment.py", line 184, in configure_proxy
    start_proxy(proxy_port, project)
  File "C:\Users\mysti\Downloads\MobSF\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\mobsf\DynamicAnalyzer\tools\webproxy.py", line 46, in start_proxy
    subprocess.Popen(argz, stdout=fnull, stderr=subprocess.STDOUT)
  File "C:\Users\mysti\anaconda3\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\mysti\anaconda3\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
[ERROR] 22/Apr/2023 01:01:16 - Dynamic Analysis Failed.
[ERROR] 22/Apr/2023 01:01:16 - Internal Server Error: /android_dynamic/d7efdb102a288a1642842752804b582a
[INFO] 22/Apr/2023 01:06:25 - MobSFying Android instance
[INFO] 22/Apr/2023 01:06:30 - ADB Restarted
[INFO] 22/Apr/2023 01:06:30 - Waiting for 2 seconds...
[INFO] 22/Apr/2023 01:06:32 - Connecting to Android 192.168.124.101:5555
[INFO] 22/Apr/2023 01:06:32 - Waiting for 2 seconds...
[INFO] 22/Apr/2023 01:06:34 - Restarting ADB Daemon as root
[INFO] 22/Apr/2023 01:06:34 - Waiting for 2 seconds...
[INFO] 22/Apr/2023 01:06:36 - Reconnecting to Android Device
[INFO] 22/Apr/2023 01:06:36 - Waiting for 2 seconds...
[INFO] 22/Apr/2023 01:06:39 - Found Genymotion x86 Android VM
[INFO] 22/Apr/2023 01:06:39 - Remounting
[INFO] 22/Apr/2023 01:06:39 - Performing System check
[INFO] 22/Apr/2023 01:06:39 - Android API Level identified as 27
[INFO] 22/Apr/2023 01:06:39 - Android Version identified as 8.1
[INFO] 22/Apr/2023 01:06:39 - Android OS architecture identified as x86
[INFO] 22/Apr/2023 01:06:39 - Downloading binary frida-server-15.2.2-android-x86
[INFO] 22/Apr/2023 01:06:41 - Copying frida server for x86
[INFO] 22/Apr/2023 01:06:42 - Installing MobSF RootCA
[INFO] 22/Apr/2023 01:06:42 - Installing MobSF Clipboard Dumper
[INFO] 22/Apr/2023 01:06:43 - MobSFying Completed!

**Comment by ajinabraham** [comment]
Duplicate https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/2166

**Comment by jwjungjwjung** [comment]
sorry for writing my comment in this section, I can't use slack in my current status. I've read through #2166 and it apparently looks like I have to install mitproxy/mitdump inside of venv. I am not used to coding, so can you copy and paste a link or give me an instruction how to do it? Thank you and sorry for the inconvenience.
