### ISSUE TITLE
Unzipping Error

### ISSUE THREAD

**Issue by azhar-999** [MobSF/Mobile-Security-Framework-MobSF#2170]
## ENVIRONMENT

```
OS and Version: Windows 10
Python Version: 3.9
MobSF Version:  Mobile Security Framework v3.6.6 Beta
```

## EXPLANATION OF THE ISSUE

```
I run the static analyzer and got this error message. The apk file I uploaded is not a zipped file, this message confuses me. 
```

## LOG FILE

```
[ERROR] 24/Apr/2023 10:53:06 - Unzipping Error
Traceback (most recent call last):
  File "D:\Mobile-Security-Framework-MobSF-master\mobsf\StaticAnalyzer\views\common\shared_func.py", line 66, in unzip
    zipptr.extract(filename, ext_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1625, in extract
    return self._extract_member(member, path, pwd)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1696, in _extract_member
    open(targetpath, "wb") as target:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\.MobSF\\uploads\\309786281afb7c39ef1e2752afaa5dc1\\res\\Prn.png'
```

**Comment by lzl-l** [comment]
### I have the same error with docker:
`[ERROR] 22/May/2024 07:57:41 - Unzipping Error

OSError: [Errno 36] File name too long: '/home/mobsf/.MobSF/uploads/323c5c6e22ac21de537e06daf484a141/assets/d6xth05c7CyBNPKF0hUB1DHSA3zNP2xe6El6Gr4JTGRBmz1BftLJqwB0yP3pArxeetGjEO0IolTuXgGbb9HvqZYJclH1zPjBiNx33R8CudufOgnsj1nCUbYpF7gshjjKcrmkTOjvafbnFS679oSIBRRgZhx6LPvl4Vdx4dJFS3BPaKVXbju3BMivKfvMqnUwV1uVPJc6Qm0JqcgowK5BvCUrMTXZS8pFif4jpaiDgznoXKeI0hpQssasgdj6WonS8uAki79wCBu6pFEbOp0LTJm1eLdm2mR3'

warning [/home/mobsf/.MobSF/uploads/323c5c6e22ac21de537e06daf484a141/323c5c6e22ac21de537e06daf484a141.apk]:  zipfile claims to be last disk of a multi-part archive;
2024-05-22 15:57:41   attempting to process anyway, assuming all parts have been concatenated
2024-05-22 15:57:41   together in order.  Expect "errors" and warnings...true multi-part support
2024-05-22 15:57:41   doesn't exist yet (coming soon).
2024-05-22 15:57:41 /home/mobsf/.MobSF/uploads/323c5c6e22ac21de537e06daf484a141/AndroidManifest.xml:  unknown compression method
2024-05-22 15:57:41 /home/mobsf/.MobSF/uploads/323c5c6e22ac21de537e06daf484a141/oaPIwlYWbf:  unknown compression method
2024-05-22 15:57:41 /home/mobsf/.MobSF/uploads/323c5c6e22ac21de537e06daf484a141/onysiL7Tbf:  unknown compression method
2024-05-22 15:57:41 /home/mobsf/.MobSF/uploads/323c5c6e22ac21de537e06daf484a141/of0y0a9Dbf:  unknown compression method
......

OSError: [Errno 36] File name too long: '/home/mobsf/.MobSF/uploads/13e17832fa6f2830887e71280ed75e7a/assets/tSAyTxr0HNdZdXZ0jE0jXP1L1n0JbOY0EMNHZaip9Fkz24nS7L0uXMXt20HFxTY30euBjrbjwKksEBT80rNAPEn30tQ9EN2qRsKYJXJPK19nBEZAgJGgfyov1CL1McPTS5Mm16zmT91ZFaCvEp35gWktdp7glScHlpFH3NKlkuygHA01aqwwkVM7UtjM9saa6uNqG5C2QSUXxeWNzfg6wRxAOIYKD9m2txlnXKvfYFRDa0KQHHm3mfPp8nN8h3yRF3Ea3J0ZVbh104zY9ic7XtQoT6qK8x85ga8iwKX9Rxik'
2024-05-22 15:57:36 
2024-05-22 15:57:36 During handling of the above exception, another exception occurred:
2024-05-22 15:57:36 
2024-05-22 15:57:36 Traceback (most recent call last):
2024-05-22 15:57:36   File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/common/shared_func.py", line 95, in unzip
2024-05-22 15:57:36     dat = subprocess.check_output([unzip_b, '-qq', '-l', app_path])
2024-05-22 15:57:36   File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
2024-05-22 15:57:36     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
2024-05-22 15:57:36   File "/usr/lib/python3.10/subprocess.py", line 526, in run
2024-05-22 15:57:36     raise CalledProcessError(retcode, process.args,
2024-05-22 15:57:36 subprocess.CalledProcessError: Command '['/bin/unzip', '-qq', '-l', '/home/mobsf/.MobSF/uploads/13e17832fa6f2830887e71280ed75e7a/13e17832fa6f2830887e71280ed75e7a.apk']' returned non-zero exit status 1.
2024-05-22 15:57:36 [INFO] 22/May/2024 07:57:36 - APK Extracted
2024-05-22 15:57:36 [ERROR] 22/May/2024 07:57:36 - APK file is invalid or corrupt
2024-05-22 15:57:36 [ERROR] 22/May/2024 07:57:36 - Internal Server Error: /static_analyzer/13e17832fa6f2830887e71280ed75e7a/`
