### ISSUE TITLE
adb install returned non-zero exit status 1

### ISSUE THREAD

**Issue by nam3lum** [MobSF/Mobile-Security-Framework-MobSF#2193]
## ENVIRONMENT

```
OS and Version: Docker version of MOBSF (opensecurity/mobile-security-framework-mobsf:latest) / Linux 5b9b5bd3c044 5.19.0-1025-aws #26~22.04.1-Ubuntu SMP Mon Apr 24 01:58:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Python Version: Python 3.8.10
MobSF Version: v3.6.7 Beta
```

## EXPLANATION OF THE ISSUE

```
I am trying to automate mobsf Dynamic Analysis into CI/CD pipeline, I want to use docker ubuntu image with correct setup of android emulator through avdmanager, thus I use "system-images;android-28;google_apis;x86_64" to install android vm there. Mobsf is able to connect through adb, it required me to use some port forwarding rules to bypass local port listening issue. Thus, I get an error when I click on Mobsfy button in the Dynamic analysis page, I get this error:
subprocess.CalledProcessError: Command '['/usr/lib/android-sdk/platform-tools/adb', '-s', 'emulator:5556', 'install', '-r', '/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/DynamicAnalyzer/tools/onDevice/mobsf_agents/ClipDump.apk']' returned non-zero exit status 1.

In order to run emulator in docker container, I use command below:
emulator -avd test -port 5554 -no-audio -no-boot-anim -no-window -writable-system -no-snapshot -accel off -gpu off -skin 1440x2880

Have you integrated MobSF with avd? Which version have you used? Which image was it? Please do not suggest Genymotion, I would do it if had a chance.

```

## STEPS TO REPRODUCE THE ISSUE

```
1. Follow these steps to deploy AVD in docker: https://devpress.csdn.net/cloudnative/62f2df6b7e66823466185ca1.html
2. Configure port forwarding in your container and link both mobsf & emulator.
3. Go to dynamic analysis and enter IP:PORT.
```

## LOG FILE

```
[INFO] 21/Jun/2023 08:15:30 - 
  __  __       _    ____  _____       _____  __   
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / /_  
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| '_ \ 
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | (_) |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/ 

[INFO] 21/Jun/2023 08:15:30 - Mobile Security Framework v3.6.7 Beta
[INFO] 21/Jun/2023 08:15:30 - OS: Linux
[INFO] 21/Jun/2023 08:15:30 - Platform: Linux-5.19.0-1025-aws-x86_64-with-glibc2.29
[INFO] 21/Jun/2023 08:15:30 - Dist: ubuntu 20.04 Focal Fossa
[INFO] 21/Jun/2023 08:15:30 - MobSF Basic Environment Check
[WARNING] 21/Jun/2023 08:15:30 - Dynamic Analysis related functions will not work. 
Make sure a Genymotion Android VM/Android Studio Emulator is running before performing Dynamic Analysis.
[INFO] 21/Jun/2023 08:15:30 - Checking for Update.
[INFO] 21/Jun/2023 08:15:30 - No updates available.
[INFO] 21/Jun/2023 08:15:32 - 
  __  __       _    ____  _____       _____  __   
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / /_  
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| '_ \ 
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | (_) |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/ 

[INFO] 21/Jun/2023 08:15:32 - Mobile Security Framework v3.6.7 Beta
[INFO] 21/Jun/2023 08:15:32 - OS: Linux
[INFO] 21/Jun/2023 08:15:32 - Platform: Linux-5.19.0-1025-aws-x86_64-with-glibc2.29
[INFO] 21/Jun/2023 08:15:32 - Dist: ubuntu 20.04 Focal Fossa
[INFO] 21/Jun/2023 08:15:32 - MobSF Basic Environment Check
[WARNING] 21/Jun/2023 08:15:32 - Dynamic Analysis related functions will not work. 
Make sure a Genymotion Android VM/Android Studio Emulator is running before performing Dynamic Analysis.
[INFO] 21/Jun/2023 08:15:32 - Checking for Update.
[INFO] 21/Jun/2023 08:15:32 - No updates available.
[INFO] 21/Jun/2023 08:15:33 - 
  __  __       _    ____  _____       _____  __   
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / /_  
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| '_ \ 
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | (_) |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/ 

[INFO] 21/Jun/2023 08:15:33 - Mobile Security Framework v3.6.7 Beta
[INFO] 21/Jun/2023 08:15:33 - OS: Linux
[INFO] 21/Jun/2023 08:15:33 - Platform: Linux-5.19.0-1025-aws-x86_64-with-glibc2.29
[INFO] 21/Jun/2023 08:15:33 - Dist: ubuntu 20.04 Focal Fossa
[INFO] 21/Jun/2023 08:15:33 - MobSF Basic Environment Check
[WARNING] 21/Jun/2023 08:15:33 - Dynamic Analysis related functions will not work. 
Make sure a Genymotion Android VM/Android Studio Emulator is running before performing Dynamic Analysis.
[INFO] 21/Jun/2023 08:15:33 - Checking for Update.
[INFO] 21/Jun/2023 08:15:33 - No updates available.
[INFO] 21/Jun/2023 08:15:35 - 
  __  __       _    ____  _____       _____  __   
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / /_  
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| '_ \ 
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | (_) |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/ 

[INFO] 21/Jun/2023 08:15:35 - Mobile Security Framework v3.6.7 Beta
[INFO] 21/Jun/2023 08:15:35 - OS: Linux
[INFO] 21/Jun/2023 08:15:35 - Platform: Linux-5.19.0-1025-aws-x86_64-with-glibc2.29
[INFO] 21/Jun/2023 08:15:35 - Dist: ubuntu 20.04 Focal Fossa
[INFO] 21/Jun/2023 08:15:35 - MobSF Basic Environment Check
[WARNING] 21/Jun/2023 08:15:35 - Dynamic Analysis related functions will not work. 
Make sure a Genymotion Android VM/Android Studio Emulator is running before performing Dynamic Analysis.
[INFO] 21/Jun/2023 08:15:35 - Checking for Update.
[INFO] 21/Jun/2023 08:15:35 - No updates available.
[INFO] 21/Jun/2023 08:15:36 - 
  __  __       _    ____  _____       _____  __   
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / /_  
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| '_ \ 
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | (_) |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/ 

[INFO] 21/Jun/2023 08:15:36 - Mobile Security Framework v3.6.7 Beta
[INFO] 21/Jun/2023 08:15:36 - OS: Linux
[INFO] 21/Jun/2023 08:15:36 - Platform: Linux-5.19.0-1025-aws-x86_64-with-glibc2.29
[INFO] 21/Jun/2023 08:15:36 - Dist: ubuntu 20.04 Focal Fossa
[INFO] 21/Jun/2023 08:15:36 - MobSF Basic Environment Check
[WARNING] 21/Jun/2023 08:15:36 - Dynamic Analysis related functions will not work. 
Make sure a Genymotion Android VM/Android Studio Emulator is running before performing Dynamic Analysis.
[INFO] 21/Jun/2023 08:15:36 - Checking for Update.
[INFO] 21/Jun/2023 08:15:37 - No updates available.
[INFO] 21/Jun/2023 08:15:38 - 
  __  __       _    ____  _____       _____  __   
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / /_  
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| '_ \ 
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | (_) |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/ 

[INFO] 21/Jun/2023 08:15:38 - Mobile Security Framework v3.6.7 Beta
[INFO] 21/Jun/2023 08:15:38 - OS: Linux
[INFO] 21/Jun/2023 08:15:38 - Platform: Linux-5.19.0-1025-aws-x86_64-with-glibc2.29
[INFO] 21/Jun/2023 08:15:38 - Dist: ubuntu 20.04 Focal Fossa
[INFO] 21/Jun/2023 08:15:38 - MobSF Basic Environment Check
[WARNING] 21/Jun/2023 08:15:38 - Dynamic Analysis related functions will not work. 
Make sure a Genymotion Android VM/Android Studio Emulator is running before performing Dynamic Analysis.
[INFO] 21/Jun/2023 08:15:38 - Checking for Update.
[INFO] 21/Jun/2023 08:15:38 - No updates available.
[INFO] 21/Jun/2023 08:15:39 - 
  __  __       _    ____  _____       _____  __   
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / /_  
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| '_ \ 
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | (_) |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/ 

[INFO] 21/Jun/2023 08:15:39 - Mobile Security Framework v3.6.7 Beta
[INFO] 21/Jun/2023 08:15:39 - OS: Linux
[INFO] 21/Jun/2023 08:15:39 - Platform: Linux-5.19.0-1025-aws-x86_64-with-glibc2.29
[INFO] 21/Jun/2023 08:15:39 - Dist: ubuntu 20.04 Focal Fossa
[INFO] 21/Jun/2023 08:15:39 - MobSF Basic Environment Check
[WARNING] 21/Jun/2023 08:15:39 - Dynamic Analysis related functions will not work. 
Make sure a Genymotion Android VM/Android Studio Emulator is running before performing Dynamic Analysis.
[INFO] 21/Jun/2023 08:15:40 - Checking for Update.
[INFO] 21/Jun/2023 08:15:40 - No updates available.
[INFO] 21/Jun/2023 08:16:00 - 
  __  __       _    ____  _____       _____  __   
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / /_  
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| '_ \ 
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | (_) |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/ 

[INFO] 21/Jun/2023 08:16:00 - Mobile Security Framework v3.6.7 Beta
[INFO] 21/Jun/2023 08:16:00 - OS: Linux
[INFO] 21/Jun/2023 08:16:00 - Platform: Linux-5.19.0-1025-aws-x86_64-with-glibc2.29
[INFO] 21/Jun/2023 08:16:00 - Dist: ubuntu 20.04 Focal Fossa
[INFO] 21/Jun/2023 08:16:00 - MobSF Basic Environment Check
[WARNING] 21/Jun/2023 08:16:00 - Dynamic Analysis related functions will not work. 
Make sure a Genymotion Android VM/Android Studio Emulator is running before performing Dynamic Analysis.
[WARNING] 21/Jun/2023 08:16:00 - Dynamic Analysis related functions will not work. 
Make sure a Genymotion Android VM/Android Studio Emulator is running before performing Dynamic Analysis.
[INFO] 21/Jun/2023 08:16:00 - Checking for Update.
[INFO] 21/Jun/2023 08:16:01 - No updates available.
[ERROR] 21/Jun/2023 08:16:03 - Error Running ADB Command
Traceback (most recent call last):
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/DynamicAnalyzer/views/android/environment.py", line 154, in adb_command
    result = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['adb', '-s', 'emulator:5556', 'shell', 'pm', 'list', 'packages', '-f', '-3']' returned non-zero exit status 1.
[INFO] 21/Jun/2023 08:16:07 - MobSFying Android instance
[INFO] 21/Jun/2023 08:16:10 - ADB Restarted
[INFO] 21/Jun/2023 08:16:10 - Waiting for 2 seconds...
[INFO] 21/Jun/2023 08:16:12 - Connecting to Android emulator:5556
[INFO] 21/Jun/2023 08:16:12 - Waiting for 2 seconds...
[INFO] 21/Jun/2023 08:16:14 - Restarting ADB Daemon as root
[INFO] 21/Jun/2023 08:16:14 - Waiting for 2 seconds...
[INFO] 21/Jun/2023 08:16:16 - Reconnecting to Android Device
[INFO] 21/Jun/2023 08:16:16 - Waiting for 2 seconds...
[INFO] 21/Jun/2023 08:16:27 - Found Android Studio Emulator
[INFO] 21/Jun/2023 08:16:27 - Remounting
[INFO] 21/Jun/2023 08:16:28 - Performing System check
[INFO] 21/Jun/2023 08:16:29 - Android API Level identified as 28
[INFO] 21/Jun/2023 08:16:30 - Android Version identified as 9.0
[INFO] 21/Jun/2023 08:16:30 - Android OS architecture identified as x86_64
[INFO] 21/Jun/2023 08:16:31 - Downloading binary frida-server-15.2.2-android-x86_64
[INFO] 21/Jun/2023 08:16:34 - Copying frida server for x86_64
[INFO] 21/Jun/2023 08:16:50 - Installing MobSF RootCA
[INFO] 21/Jun/2023 08:16:51 - Installing MobSF Clipboard Dumper
[ERROR] 21/Jun/2023 08:16:52 - Error Running ADB Command
Traceback (most recent call last):
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/DynamicAnalyzer/views/android/environment.py", line 154, in adb_command
    result = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/lib/android-sdk/platform-tools/adb', '-s', 'emulator:5556', 'install', '-r', '/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/DynamicAnalyzer/tools/onDevice/mobsf_agents/ClipDump.apk']' returned non-zero exit status 1.
[INFO] 21/Jun/2023 08:16:52 - MobSFying Completed!
```

**Comment by ajinabraham** [comment]
Please use slack for support. Also make sure you follow the docs for how to use an AVD with MobSFhttps://mobsf.github.io/docs/#/dynamic_analyzer?id=android-studio-emulator
