### ISSUE TITLE
latest MobSF | dynamic testing docker support error using genemotion

### ISSUE THREAD

**Issue by niyosh** [MobSF/Mobile-Security-Framework-MobSF#2222]
CMD: docker run -it --rm -p 8000:8000 -p 1337:1337 -e MOBSF_ANALYZER_IDENTIFIER=127.0.0.1:6555 opensecurity/mobile-security-framework-mobsf:latest

Error:
Traceback (most recent call last):
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/DynamicAnalyzer/views/android/environment.py", line 163, in adb_command
    result = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/adb', '-s', 'host.docker.internal:6555', 'shell', 'getprop', 'ro.build.version.release']' returned non-zero exit status 1.

**Comment by ajinabraham** [comment]
Can we please move this conversation to our slack channel to troubleshoot this
