### ISSUE TITLE
Static analysis of Androguard Hardened APK fails when minSDK / maxSDK are non-numeric.

### ISSUE THREAD

**Issue by tilver** [MobSF/Mobile-Security-Framework-MobSF#2230]
## ENVIRONMENT

```
OS and Version:  Docker  latest pulled on 08/04/2023
[INFO] 04/Aug/2023 13:47:43 - Mobile Security Framework v3.7.1 Beta                                                                                                                 
REST API Key: 46826a0f7e2feb574a3a90fbf18e4d52d679fae42730981315353e581b0814e3            
[INFO] 04/Aug/2023 13:47:43 - OS: Linux                                                   
[INFO] 04/Aug/2023 13:47:43 - Platform: Linux-6.1.0-kali9-amd64-x86_64-with-glibc2.29     
[INFO] 04/Aug/2023 13:47:43 - Dist: ubuntu 20.04 Focal Fossa           
```

## EXPLANATION OF THE ISSUE

```
I'm submitting an apk that appears to be hardended (Androguard?) and the following python error appears.  I'm guessing that it's because the minSDK is assumed to be numeric, but it's a string.  This is further complicated by the exception handler assuming it will be numeric.

[ERROR] 04/Aug/2023 13:47:56 - Error Performing Static Analysis                           
Traceback (most recent call last):           
  File "/usr/local/lib/python3.8/dist-packages/androguard/core/bytecodes/apk.py", line 419, in _get_permission_maxsdk
    maxSdkVersion = int(self.get_value_from_tag(item, "maxSdkVersion"))                   
ValueError: invalid literal for int() with base 10: '@7F0A0017'                           

During handling of the above exception, another exception occurred:                       

Traceback (most recent call last):           
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 169, in static_analyzer
    app_dic['real_name'] = get_app_name(     
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 590, in get_app_name
    a = apk.APK(app_path)                    
  File "/usr/local/lib/python3.8/dist-packages/androguard/core/bytecodes/apk.py", line 291, in __init__
    self._apk_analysis()                     
  File "/usr/local/lib/python3.8/dist-packages/androguard/core/bytecodes/apk.py", line 341, in _apk_analysis
    self._get_permission_maxsdk(uses_permission)                                          
  File "/usr/local/lib/python3.8/dist-packages/androguard/core/bytecodes/apk.py", line 421, in _get_permission_maxsdk
    log.warning(self.get_max_sdk_version() + 'is not a valid value for <uses-permission> maxSdkVersion')
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'                        
[ERROR] 04/Aug/2023 13:47:56 - unsupported operand type(s) for +: 'NoneType' and 'str'    
[ERROR] 04/Aug/2023 13:47:56 - Internal Server Error: /static_analyzer/                   
[INFO] 04/Aug/2023 13:47:56 - Scan Hash: 907d5ebbd0334e85629b57ba7ef629e9                 
[INFO] 04/Aug/2023 13:47:56 - Starting Analysis on: com.seic.pentest.apk                  
[INFO] 04/Aug/2023 13:47:56 - Generating Hashes                                           
[INFO] 04/Aug/2023 13:47:56 - Unzipping      
[INFO] 04/Aug/2023 13:47:57 - APK Extracted  
[INFO] 04/Aug/2023 13:47:57 - Getting Hardcoded Certificates/Keystores                    
[INFO] 04/Aug/2023 13:47:57 - Getting AndroidManifest.xml from APK                        
[INFO] 04/Aug/2023 13:47:57 - Parsing AndroidManifest.xml                                 
[ERROR] 04/Aug/2023 13:47:57 - Error Performing Static Analysis                           
Traceback (most recent call last):           
  File "/usr/local/lib/python3.8/dist-packages/androguard/core/bytecodes/apk.py", line 419, in _get_permission_maxsdk
    maxSdkVersion = int(self.get_value_from_tag(item, "maxSdkVersion"))                   
ValueError: invalid literal for int() with base 10: '@7F0A0017'                           

During handling of the above exception, another exception occurred:                       

Traceback (most recent call last):           
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 169, in static_analyzer
    app_dic['real_name'] = get_app_name(     
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 590, in get_app_name
    a = apk.APK(app_path)                    
  File "/usr/local/lib/python3.8/dist-packages/androguard/core/bytecodes/apk.py", line 291, in __init__
    self._apk_analysis()                     
  File "/usr/local/lib/python3.8/dist-packages/androguard/core/bytecodes/apk.py", line 341, in _apk_analysis
    self._get_permission_maxsdk(uses_permission)                                          
  File "/usr/local/lib/python3.8/dist-packages/androguard/core/bytecodes/apk.py", line 421, in _get_permission_maxsdk
    log.warning(self.get_max_sdk_version() + 'is not a valid value for <uses-permission> maxSdkVersion')
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'                        
[ERROR] 04/Aug/2023 13:47:57 - unsupported operand type(s) for +: 'NoneType' and 'str'    
[ERROR] 04/Aug/2023 13:47:57 - Internal Server Error: /static_analyzer/                   
[





```
Setup appears to run fine.

## STEPS TO REPRODUCE THE ISSUE

```
1. Attempt to analyze an androguard hardened file with a non-numeric MaxSDK.
```

## LOG FILE

```
The debug.log is buried in docker, and I don't know how to get to it, but I think the python error above will be enough.
```

**Comment by ajinabraham** [comment]
Hi @tilver 

This error originates from Androguard. 

```
Traceback (most recent call last):           
  File "/usr/local/lib/python3.8/dist-packages/androguard/core/bytecodes/apk.py", line 419, in _get_permission_maxsdk
    maxSdkVersion = int(self.get_value_from_tag(item, "maxSdkVersion"))                   
ValueError: invalid literal for int() with base 10: '@7F0A0017'        
```

The fix has to happen at their side. Please consider reporting this to https://github.com/androguard/androguard
