### ISSUE TITLE
Multiple Error happend While Installing the Tool on Windows 11

### ISSUE THREAD

**Issue by slaxedu** [MobSF/Mobile-Security-Framework-MobSF#2237]
## ENVIRONMENT

OS and Version: Windows 11
Python Version: 3.10.11
MobSF Version: latest

## EXPLANATION OF THE ISSUE

I encountered an issue during the installation process of MobSF on my Windows 11 system. Below are the details of the problem I encountered, the expected behavior, and any relevant information.

## STEPS TO REPRODUCE THE ISSUE

Installed all the required Dependencies, including Python 3.10.11, pip, and Visual Studio.
Executed the installation process following the instructions provided in the MobSF documentation.
Encountered the issue while installing specific packages, such as zstandard, during the "Getting requirements to build wheel" step.
The error message indicated a requirement for Microsoft Visual C++ 14.0 or greater.

## LOG FILE
```ps
.\setup.bat
[INSTALL] Checking for Python version 3.8+
[INSTALL] Found Python 3.10.11
[INSTALL] Found pip
Requirement already satisfied: pip in c:\users\boooo\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (23.2.1)
[INSTALL] Found OpenSSL executable
[INSTALL] Found Visual Studio Build Tools
[INSTALL] Creating venv
Requirement already satisfied: pip in d:\0. cyber sec\(appsec) application security\toolkit\mobile-security-framework-mobsf\venv\lib\site-packages (23.0.1)
Collecting pip
  Using cached pip-23.2.1-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.0.1
    Uninstalling pip-23.0.1:
      Successfully uninstalled pip-23.0.1
Successfully installed pip-23.2.1
[INSTALL] Installing Requirements
Collecting wheel
  Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/28/f5/6955d7b3a5d71ce6bac104f9cf98c1b0513ad656cdaca8ea7d579196f771/wheel-0.41.1-py3-none-any.whl.metadata
  Downloading wheel-0.41.1-py3-none-any.whl.metadata (2.2 kB)
Downloading wheel-0.41.1-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.8/64.8 kB 865.3 kB/s eta 0:00:00
Installing collected packages: wheel
Successfully installed wheel-0.41.1
Ignoring gunicorn: markers 'platform_system != "Windows"' don't match your environment
Collecting Django>=3.1.5 (from -r requirements.txt (line 1))
  Downloading Django-4.2.4-py3-none-any.whl (8.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 2.6 MB/s eta 0:00:00
Collecting lxml>=4.6.2 (from -r requirements.txt (line 2))
  Downloading lxml-4.9.3-cp310-cp310-win_amd64.whl (3.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 2.8 MB/s eta 0:00:00
Collecting rsa>=4.7 (from -r requirements.txt (line 3))
  Downloading rsa-4.9-py3-none-any.whl (34 kB)
Collecting biplist>=1.0.3 (from -r requirements.txt (line 4))
  Downloading biplist-1.0.3.tar.gz (21 kB)
  Preparing metadata (setup.py) ... done
Collecting requests>=2.25.1 (from -r requirements.txt (line 5))
  Downloading requests-2.31.0-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 3.5 MB/s eta 0:00:00
Collecting bs4>=0.0.1 (from -r requirements.txt (line 6))
  Downloading bs4-0.0.1.tar.gz (1.1 kB)
  Preparing metadata (setup.py) ... done
Collecting colorlog>=4.7.2 (from -r requirements.txt (line 7))
  Downloading colorlog-6.7.0-py2.py3-none-any.whl (11 kB)
Collecting macholib>=1.14 (from -r requirements.txt (line 8))
  Downloading macholib-1.16.2-py2.py3-none-any.whl (38 kB)
Collecting whitenoise>=5.2.0 (from -r requirements.txt (line 9))
  Downloading whitenoise-6.5.0-py3-none-any.whl (19 kB)
Collecting waitress>=1.4.4 (from -r requirements.txt (line 10))
  Downloading waitress-2.1.2-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 3.2 MB/s eta 0:00:00
Collecting psutil>=5.8.0 (from -r requirements.txt (line 12))
  Downloading psutil-5.9.5-cp36-abi3-win_amd64.whl (255 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 255.1/255.1 kB 3.1 MB/s eta 0:00:00
Collecting shelljob>=0.6.2 (from -r requirements.txt (line 13))
  Downloading shelljob-0.6.3-py3-none-any.whl (9.9 kB)
Collecting asn1crypto>=1.4.0 (from -r requirements.txt (line 14))
  Downloading asn1crypto-1.5.1-py2.py3-none-any.whl (105 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.0/105.0 kB 3.1 MB/s eta 0:00:00
Collecting oscrypto>=1.2.1 (from -r requirements.txt (line 15))
  Downloading oscrypto-1.3.0-py2.py3-none-any.whl (194 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.6/194.6 kB 2.4 MB/s eta 0:00:00
Collecting distro>=1.5.0 (from -r requirements.txt (line 16))
  Downloading distro-1.8.0-py3-none-any.whl (20 kB)
Collecting IP2Location==8.10.0 (from -r requirements.txt (line 17))
  Downloading IP2Location-8.10.0-py3-none-any.whl (16 kB)
Collecting lief>=0.12.3 (from -r requirements.txt (line 18))
  Downloading lief-0.13.2-cp310-cp310-win_amd64.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 2.7 MB/s eta 0:00:00
Collecting http-tools>=2.1.1 (from -r requirements.txt (line 19))
  Downloading http-tools-2.1.1.tar.gz (550 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 550.3/550.3 kB 2.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting libsast>=1.5.1 (from -r requirements.txt (line 20))
  Downloading libsast-1.5.2.tar.gz (36 kB)
  Preparing metadata (setup.py) ... done
Collecting pdfkit>=0.6.1 (from -r requirements.txt (line 21))
  Downloading pdfkit-1.0.0-py3-none-any.whl (12 kB)
Collecting google-play-scraper>=0.1.2 (from -r requirements.txt (line 22))
  Downloading google_play_scraper-1.2.4-py3-none-any.whl (28 kB)
Collecting androguard==3.4.0a1 (from -r requirements.txt (line 23))
  Downloading androguard-3.4.0a1-py3-none-any.whl (918 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 918.1/918.1 kB 2.6 MB/s eta 0:00:00
Collecting apkid==2.1.5 (from -r requirements.txt (line 24))
  Downloading apkid-2.1.5-py2.py3-none-any.whl (137 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.8/137.8 kB 2.7 MB/s eta 0:00:00
Collecting quark-engine==23.5.1 (from -r requirements.txt (line 25))
  Downloading quark_engine-23.5.1-py3-none-any.whl (94 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.4/94.4 kB 2.7 MB/s eta 0:00:00
Collecting frida==15.2.2 (from -r requirements.txt (line 26))
  Downloading frida-15.2.2.tar.gz (11 kB)
  Preparing metadata (setup.py) ... done
Collecting tldextract==3.4.4 (from -r requirements.txt (line 27))
  Downloading tldextract-3.4.4-py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.3/93.3 kB 2.6 MB/s eta 0:00:00
Collecting openstep-parser==1.5.4 (from -r requirements.txt (line 28))
  Downloading openstep_parser-1.5.4-py3-none-any.whl (4.5 kB)
Collecting svgutils==0.3.4 (from -r requirements.txt (line 29))
  Downloading svgutils-0.3.4-py3-none-any.whl (10 kB)
Collecting ruamel.yaml==0.16.13 (from -r requirements.txt (line 31))
  Downloading ruamel.yaml-0.16.13-py2.py3-none-any.whl (111 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.9/111.9 kB 2.2 MB/s eta 0:00:00
Collecting click==8.0.1 (from -r requirements.txt (line 32))
  Downloading click-8.0.1-py3-none-any.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.4/97.4 kB 2.8 MB/s eta 0:00:00
Collecting decorator==4.4.2 (from -r requirements.txt (line 33))
  Downloading decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting asgiref<4,>=3.6.0 (from Django>=3.1.5->-r requirements.txt (line 1))
  Downloading asgiref-3.7.2-py3-none-any.whl (24 kB)
Collecting sqlparse>=0.3.1 (from Django>=3.1.5->-r requirements.txt (line 1))
  Downloading sqlparse-0.4.4-py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.2/41.2 kB 2.1 MB/s eta 0:00:00
Collecting tzdata; sys_platform == "win32" (from Django>=3.1.5->-r requirements.txt (line 1))
  Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 3.0 MB/s eta 0:00:00
Collecting pyasn1>=0.1.3 (from rsa>=4.7->-r requirements.txt (line 3))
  Downloading pyasn1-0.5.0-py2.py3-none-any.whl (83 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.9/83.9 kB 4.9 MB/s eta 0:00:00
Collecting charset-normalizer<4,>=2 (from requests>=2.25.1->-r requirements.txt (line 5))
  Downloading charset_normalizer-3.2.0-cp310-cp310-win_amd64.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.9/96.9 kB 2.8 MB/s eta 0:00:00
Collecting idna<4,>=2.5 (from requests>=2.25.1->-r requirements.txt (line 5))
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 3.2 MB/s eta 0:00:00
Collecting urllib3<3,>=1.21.1 (from requests>=2.25.1->-r requirements.txt (line 5))
  Downloading urllib3-2.0.4-py3-none-any.whl (123 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.9/123.9 kB 2.4 MB/s eta 0:00:00
Collecting certifi>=2017.4.17 (from requests>=2.25.1->-r requirements.txt (line 5))
  Downloading certifi-2023.7.22-py3-none-any.whl (158 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.3/158.3 kB 2.4 MB/s eta 0:00:00
Collecting beautifulsoup4 (from bs4>=0.0.1->-r requirements.txt (line 6))
  Downloading beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.0/143.0 kB 2.8 MB/s eta 0:00:00
Collecting colorama; sys_platform == "win32" (from colorlog>=4.7.2->-r requirements.txt (line 7))
  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting altgraph>=0.17 (from macholib>=1.14->-r requirements.txt (line 8))
  Downloading altgraph-0.17.3-py2.py3-none-any.whl (21 kB)
Collecting mitmproxy==6.0.2 (from http-tools>=2.1.1->-r requirements.txt (line 19))
  Downloading mitmproxy-6.0.2-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 2.7 MB/s eta 0:00:00
Collecting markupsafe==2.0.1 (from http-tools>=2.1.1->-r requirements.txt (line 19))
  Downloading MarkupSafe-2.0.1-cp310-cp310-win_amd64.whl (15 kB)
Collecting pyyaml>=6.0 (from libsast>=1.5.1->-r requirements.txt (line 20))
  Downloading PyYAML-6.0.1-cp310-cp310-win_amd64.whl (145 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.3/145.3 kB 2.9 MB/s eta 0:00:00
Collecting networkx>=2.2 (from androguard==3.4.0a1->-r requirements.txt (line 23))
  Downloading networkx-3.1-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 2.7 MB/s eta 0:00:00
Collecting pygments>=2.3.1 (from androguard==3.4.0a1->-r requirements.txt (line 23))
  Downloading Pygments-2.16.1-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 2.6 MB/s eta 0:00:00
Collecting matplotlib>=3.0.2 (from androguard==3.4.0a1->-r requirements.txt (line 23))
  Downloading matplotlib-3.7.2-cp310-cp310-win_amd64.whl (7.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 2.7 MB/s eta 0:00:00
Collecting pydot>=1.4.1 (from androguard==3.4.0a1->-r requirements.txt (line 23))
  Downloading pydot-1.4.2-py2.py3-none-any.whl (21 kB)
Collecting ipython>=5.0.0 (from androguard==3.4.0a1->-r requirements.txt (line 23))
  Downloading ipython-8.14.0-py3-none-any.whl (798 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 798.7/798.7 kB 2.7 MB/s eta 0:00:00
Collecting yara-python-dex>=1.0.1 (from apkid==2.1.5->-r requirements.txt (line 24))
  Downloading yara_python_dex-1.0.4-cp310-cp310-win_amd64.whl (130 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 2.6 MB/s eta 0:00:00
Collecting prettytable>=1.0.0 (from quark-engine==23.5.1->-r requirements.txt (line 25))
  Downloading prettytable-3.8.0-py3-none-any.whl (27 kB)
Collecting tqdm (from quark-engine==23.5.1->-r requirements.txt (line 25))
  Downloading tqdm-4.66.1-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB 2.2 MB/s eta 0:00:00
Collecting graphviz (from quark-engine==23.5.1->-r requirements.txt (line 25))
  Downloading graphviz-0.20.1-py3-none-any.whl (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.0/47.0 kB ? eta 0:00:00
Collecting prompt-toolkit (from quark-engine==23.5.1->-r requirements.txt (line 25))
  Downloading prompt_toolkit-3.0.39-py3-none-any.whl (385 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 385.2/385.2 kB 2.7 MB/s eta 0:00:00
Collecting plotly (from quark-engine==23.5.1->-r requirements.txt (line 25))
  Downloading plotly-5.16.0-py2.py3-none-any.whl (15.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.6/15.6 MB 2.6 MB/s eta 0:00:00
Collecting rzpipe (from quark-engine==23.5.1->-r requirements.txt (line 25))
  Downloading rzpipe-0.6.0-py3-none-any.whl (12 kB)
Requirement already satisfied: setuptools in d:\0. cyber sec\(appsec) application security\toolkit\mobile-security-framework-mobsf\venv\lib\site-packages (from frida==15.2.2->-r requirements.txt (line 26)) (65.5.0)
Collecting requests-file>=1.4 (from tldextract==3.4.4->-r requirements.txt (line 27))
  Downloading requests_file-1.5.1-py2.py3-none-any.whl (3.7 kB)
Collecting filelock>=3.0.8 (from tldextract==3.4.4->-r requirements.txt (line 27))
  Downloading filelock-3.12.2-py3-none-any.whl (10 kB)
Collecting typing-extensions>=4; python_version < "3.11" (from asgiref<4,>=3.6.0->Django>=3.1.5->-r requirements.txt (line 1))
  Downloading typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Collecting soupsieve>1.2 (from beautifulsoup4->bs4>=0.0.1->-r requirements.txt (line 6))
  Downloading soupsieve-2.4.1-py3-none-any.whl (36 kB)
Collecting blinker<1.5,>=1.4 (from mitmproxy==6.0.2->http-tools>=2.1.1->-r requirements.txt (line 19))
  Downloading blinker-1.4.tar.gz (111 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.5/111.5 kB 3.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting Brotli<1.1,>=1.0 (from mitmproxy==6.0.2->http-tools>=2.1.1->-r requirements.txt (line 19))
  Downloading Brotli-1.0.9-cp310-cp310-win_amd64.whl (383 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.3/383.3 kB 2.7 MB/s eta 0:00:00
Collecting cryptography<3.4,>=3.3 (from mitmproxy==6.0.2->http-tools>=2.1.1->-r requirements.txt (line 19))
  Downloading cryptography-3.3.2-cp36-abi3-win_amd64.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 2.7 MB/s eta 0:00:00
Collecting flask<1.2,>=1.1.1 (from mitmproxy==6.0.2->http-tools>=2.1.1->-r requirements.txt (line 19))
  Downloading Flask-1.1.4-py2.py3-none-any.whl (94 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.6/94.6 kB 5.3 MB/s eta 0:00:00
Collecting h2<5,>=4.0 (from mitmproxy==6.0.2->http-tools>=2.1.1->-r requirements.txt (line 19))
  Downloading h2-4.1.0-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 3.0 MB/s eta 0:00:00
Collecting hyperframe<7,>=6.0 (from mitmproxy==6.0.2->http-tools>=2.1.1->-r requirements.txt (line 19))
  Downloading hyperframe-6.0.1-py3-none-any.whl (12 kB)
Collecting kaitaistruct<0.10,>=0.7 (from mitmproxy==6.0.2->http-tools>=2.1.1->-r requirements.txt (line 19))
  Downloading kaitaistruct-0.9.tar.gz (5.5 kB)
  Preparing metadata (setup.py) ... done
Collecting ldap3<2.9,>=2.8 (from mitmproxy==6.0.2->http-tools>=2.1.1->-r requirements.txt (line 19))
  Downloading ldap3-2.8.1-py2.py3-none-any.whl (423 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.6/423.6 kB 2.6 MB/s eta 0:00:00
Collecting msgpack<1.1.0,>=1.0.0 (from mitmproxy==6.0.2->http-tools>=2.1.1->-r requirements.txt (line 19))
  Downloading msgpack-1.0.5-cp310-cp310-win_amd64.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 3.4 MB/s eta 0:00:00
Collecting passlib<1.8,>=1.6.5 (from mitmproxy==6.0.2->http-tools>=2.1.1->-r requirements.txt (line 19))
  Downloading passlib-1.7.4-py2.py3-none-any.whl (525 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 525.6/525.6 kB 2.8 MB/s eta 0:00:00
Collecting protobuf<3.15,>=3.14 (from mitmproxy==6.0.2->http-tools>=2.1.1->-r requirements.txt (line 19))
  Downloading protobuf-3.14.0-py2.py3-none-any.whl (173 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 173.5/173.5 kB 3.5 MB/s eta 0:00:00
Collecting pyOpenSSL<20.1,>=20.0 (from mitmproxy==6.0.2->http-tools>=2.1.1->-r requirements.txt (line 19))
  Downloading pyOpenSSL-20.0.1-py2.py3-none-any.whl (54 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.1/54.1 kB 2.7 MB/s eta 0:00:00
Collecting pyparsing<2.5,>=2.4.2 (from mitmproxy==6.0.2->http-tools>=2.1.1->-r requirements.txt (line 19))
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.8/67.8 kB 3.6 MB/s eta 0:00:00
Collecting pyperclip<1.9,>=1.6.0 (from mitmproxy==6.0.2->http-tools>=2.1.1->-r requirements.txt (line 19))
  Downloading pyperclip-1.8.2.tar.gz (20 kB)
  Preparing metadata (setup.py) ... done
Collecting sortedcontainers<2.4,>=2.3 (from mitmproxy==6.0.2->http-tools>=2.1.1->-r requirements.txt (line 19))
  Downloading sortedcontainers-2.3.0-py2.py3-none-any.whl (29 kB)
Collecting tornado<7,>=4.3 (from mitmproxy==6.0.2->http-tools>=2.1.1->-r requirements.txt (line 19))
  Downloading tornado-6.3.3-cp38-abi3-win_amd64.whl (429 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 429.2/429.2 kB 2.7 MB/s eta 0:00:00
Collecting urwid<2.2,>=2.1.1 (from mitmproxy==6.0.2->http-tools>=2.1.1->-r requirements.txt (line 19))
  Downloading urwid-2.1.2.tar.gz (634 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 634.6/634.6 kB 2.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting wsproto<1.1,>=1.0 (from mitmproxy==6.0.2->http-tools>=2.1.1->-r requirements.txt (line 19))
  Downloading wsproto-1.0.0-py3-none-any.whl (24 kB)
Collecting publicsuffix2<3,>=2.20190812 (from mitmproxy==6.0.2->http-tools>=2.1.1->-r requirements.txt (line 19))
  Downloading publicsuffix2-2.20191221-py2.py3-none-any.whl (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.0/89.0 kB 2.5 MB/s eta 0:00:00
Collecting zstandard<0.15,>=0.11 (from mitmproxy==6.0.2->http-tools>=2.1.1->-r requirements.txt (line 19))
  Downloading zstandard-0.14.1.tar.gz (676 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 676.8/676.8 kB 2.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "D:\0. Cyber Sec\(AppSec) Application Security\Toolkit\Mobile-Security-Framework-MobSF\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\0. Cyber Sec\(AppSec) Application Security\Toolkit\Mobile-Security-Framework-MobSF\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\0. Cyber Sec\(AppSec) Application Security\Toolkit\Mobile-Security-Framework-MobSF\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\boooo\AppData\Local\Temp\pip-build-env-i3bbtykl\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\boooo\AppData\Local\Temp\pip-build-env-i3bbtykl\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\boooo\AppData\Local\Temp\pip-build-env-i3bbtykl\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\boooo\AppData\Local\Temp\pip-build-env-i3bbtykl\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 63, in <module>
        File "C:\Users\boooo\AppData\Local\Temp\pip-install-jodhmi0w\zstandard\setup_zstd.py", line 164, in get_c_extension
          compiler.initialize()
        File "C:\Users\boooo\AppData\Local\Temp\pip-build-env-i3bbtykl\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
          vc_env = _get_vc_env(plat_spec)
        File "C:\Users\boooo\AppData\Local\Temp\pip-build-env-i3bbtykl\overlay\Lib\site-packages\setuptools\msvc.py", line 214, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
        File "C:\Users\boooo\AppData\Local\Temp\pip-build-env-i3bbtykl\overlay\Lib\site-packages\setuptools\msvc.py", line 168, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [25 lines of output]
    Traceback (most recent call last):
      File "D:\0. Cyber Sec\(AppSec) Application Security\Toolkit\Mobile-Security-Framework-MobSF\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
        main()
      File "D:\0. Cyber Sec\(AppSec) Application Security\Toolkit\Mobile-Security-Framework-MobSF\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "D:\0. Cyber Sec\(AppSec) Application Security\Toolkit\Mobile-Security-Framework-MobSF\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
        return hook(config_settings)
      File "C:\Users\boooo\AppData\Local\Temp\pip-build-env-i3bbtykl\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
        return self._get_build_requires(config_settings, requirements=['wheel'])
      File "C:\Users\boooo\AppData\Local\Temp\pip-build-env-i3bbtykl\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
        self.run_setup()
      File "C:\Users\boooo\AppData\Local\Temp\pip-build-env-i3bbtykl\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
        super(_BuildMetaLegacyBackend,
      File "C:\Users\boooo\AppData\Local\Temp\pip-build-env-i3bbtykl\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
        exec(code, locals())
      File "<string>", line 63, in <module>
      File "C:\Users\boooo\AppData\Local\Temp\pip-install-jodhmi0w\zstandard\setup_zstd.py", line 164, in get_c_extension
        compiler.initialize()
      File "C:\Users\boooo\AppData\Local\Temp\pip-build-env-i3bbtykl\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\Users\boooo\AppData\Local\Temp\pip-build-env-i3bbtykl\overlay\Lib\site-packages\setuptools\msvc.py", line 214, in msvc14_get_vc_env
        return _msvc14_get_vc_env(plat_spec)
      File "C:\Users\boooo\AppData\Local\Temp\pip-build-env-i3bbtykl\overlay\Lib\site-packages\setuptools\msvc.py", line 168, in _msvc14_get_vc_env
        raise distutils.errors.DistutilsPlatformError(
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
[INSTALL] Clean Up
=======================MobSF Clean Script for Windows=======================
Running this script will delete the Scan database, all files uploaded and generated.
D:\0. Cyber Sec\(AppSec) Application Security\Toolkit\Mobile-Security-Framework-MobSF\scripts
Deleting all uploads
Deleting all downloads
Deleting Static Analyzer migrations
Deleting Dynamic Analyzer migrations
Deleting MobSF migrations
Deleting temp and log files
Deleting Scan database
Deleting Secret file
Deleting Previous setup files
Deleting MobSF data directory: "C:\Users\boooo\.MobSF"
Done
[INSTALL] Migrating Database
Traceback (most recent call last):
  File "D:\0. Cyber Sec\(AppSec) Application Security\Toolkit\Mobile-Security-Framework-MobSF\manage.py", line 12, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "D:\0. Cyber Sec\(AppSec) Application Security\Toolkit\Mobile-Security-Framework-MobSF\manage.py", line 12, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "D:\0. Cyber Sec\(AppSec) Application Security\Toolkit\Mobile-Security-Framework-MobSF\manage.py", line 12, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
Download and Install wkhtmltopdf for PDF Report Generation - https://wkhtmltopdf.org/downloads.html
[INSTALL] Installation Complete
[ERROR] Installation Failed!
Please ensure that all the requirements mentioned in documentation are installed before you run setup script.
Scroll up to see any installation errors.

The 'decorator==4.4.2' distribution was not found and is required by the application
```

**Comment by ajinabraham** [comment]
The setup instructions have changed. please see the official updated documentation https://mobsf.github.io/docs/#/
