### ISSUE TITLE
setup problem

### ISSUE THREAD

**Issue by Nazmul8091** [MobSF/Mobile-Security-Framework-MobSF#2256]
=======================MobSF Clean Script for Unix=======================
Running this script will delete the Scan database, all files uploaded and generated.

Deleting all uploads
Deleting all downloads
Deleting Static Analyzer migrations
Deleting Dynamic Analyzer migrations
Deleting MobSF migrations
Deleting Python byte code files
Deleting temp and log files
Deleting Scan database
Deleting Secret file
Deleting MobSF data directory: /root/.MobSF
Done
[INSTALL] Migrating Database
Traceback (most recent call last):
  File "/home/nazmul/Tools/Android Pentest Tools/Mobile-Security-Framework-MobSF/mobsf/../manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/management/base.py", line 443, in execute
    self.check()
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nazmul/Tools/Android Pentest Tools/Mobile-Security-Framework-MobSF/mobsf/MobSF/urls.py", line 12, in <module>
    from mobsf.MobSF.views.api import api_static_analysis as api_sz
  File "/home/nazmul/Tools/Android Pentest Tools/Mobile-Security-Framework-MobSF/mobsf/MobSF/views/api/api_static_analysis.py", line 11, in <module>
    from mobsf.StaticAnalyzer.views.android.static_analyzer import static_analyzer
  File "/home/nazmul/Tools/Android Pentest Tools/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 40, in <module>
    from mobsf.StaticAnalyzer.views.android.cert_analysis import (
  File "/home/nazmul/Tools/Android Pentest Tools/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/cert_analysis.py", line 16, in <module>
    from oscrypto import asymmetric
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/oscrypto/asymmetric.py", line 19, in <module>
    from ._asymmetric import _unwrap_private_key_info
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/oscrypto/util.py", line 14, in <module>
    from ._openssl.util import rand_bytes
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/oscrypto/_openssl/util.py", line 6, in <module>
    from ._libcrypto import libcrypto, libcrypto_version_info, handle_openssl_error
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/oscrypto/_openssl/_libcrypto.py", line 9, in <module>
    from ._libcrypto_cffi import (
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/oscrypto/_openssl/_libcrypto_cffi.py", line 44, in <module>
    raise LibraryNotFoundError('Error detecting the version of libcrypto')
oscrypto.errors.LibraryNotFoundError: Error detecting the version of libcrypto
Traceback (most recent call last):
  File "/home/nazmul/Tools/Android Pentest Tools/Mobile-Security-Framework-MobSF/mobsf/../manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/management/base.py", line 443, in execute
    self.check()
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nazmul/Tools/Android Pentest Tools/Mobile-Security-Framework-MobSF/mobsf/MobSF/urls.py", line 12, in <module>
    from mobsf.MobSF.views.api import api_static_analysis as api_sz
  File "/home/nazmul/Tools/Android Pentest Tools/Mobile-Security-Framework-MobSF/mobsf/MobSF/views/api/api_static_analysis.py", line 11, in <module>
    from mobsf.StaticAnalyzer.views.android.static_analyzer import static_analyzer
  File "/home/nazmul/Tools/Android Pentest Tools/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 40, in <module>
    from mobsf.StaticAnalyzer.views.android.cert_analysis import (
  File "/home/nazmul/Tools/Android Pentest Tools/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/cert_analysis.py", line 16, in <module>
    from oscrypto import asymmetric
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/oscrypto/asymmetric.py", line 19, in <module>
    from ._asymmetric import _unwrap_private_key_info
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/oscrypto/util.py", line 14, in <module>
    from ._openssl.util import rand_bytes
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/oscrypto/_openssl/util.py", line 6, in <module>
    from ._libcrypto import libcrypto, libcrypto_version_info, handle_openssl_error
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/oscrypto/_openssl/_libcrypto.py", line 9, in <module>
    from ._libcrypto_cffi import (
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/oscrypto/_openssl/_libcrypto_cffi.py", line 44, in <module>
    raise LibraryNotFoundError('Error detecting the version of libcrypto')
oscrypto.errors.LibraryNotFoundError: Error detecting the version of libcrypto
Traceback (most recent call last):
  File "/home/nazmul/Tools/Android Pentest Tools/Mobile-Security-Framework-MobSF/mobsf/../manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 97, in handle
    self.check(databases=[database])
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nazmul/Tools/Android Pentest Tools/Mobile-Security-Framework-MobSF/mobsf/MobSF/urls.py", line 12, in <module>
    from mobsf.MobSF.views.api import api_static_analysis as api_sz
  File "/home/nazmul/Tools/Android Pentest Tools/Mobile-Security-Framework-MobSF/mobsf/MobSF/views/api/api_static_analysis.py", line 11, in <module>
    from mobsf.StaticAnalyzer.views.android.static_analyzer import static_analyzer
  File "/home/nazmul/Tools/Android Pentest Tools/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/static_analyzer.py", line 40, in <module>
    from mobsf.StaticAnalyzer.views.android.cert_analysis import (
  File "/home/nazmul/Tools/Android Pentest Tools/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/cert_analysis.py", line 16, in <module>
    from oscrypto import asymmetric
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/oscrypto/asymmetric.py", line 19, in <module>
    from ._asymmetric import _unwrap_private_key_info
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/oscrypto/util.py", line 14, in <module>
    from ._openssl.util import rand_bytes
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/oscrypto/_openssl/util.py", line 6, in <module>
    from ._libcrypto import libcrypto, libcrypto_version_info, handle_openssl_error
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/oscrypto/_openssl/_libcrypto.py", line 9, in <module>
    from ._libcrypto_cffi import (
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/oscrypto/_openssl/_libcrypto_cffi.py", line 44, in <module>
    raise LibraryNotFoundError('Error detecting the version of libcrypto')
oscrypto.errors.LibraryNotFoundError: Error detecting the version of libcrypto
Traceback (most recent call last):
  File "/home/nazmul/Tools/Android Pentest Tools/Mobile-Security-Framework-MobSF/mobsf/../manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/mobsf-wttquxP3-py3.11/lib/python3.11/site-packages/django/core/management/commands/m

**Comment by ajinabraham** [comment]
Please use slack for support

**Comment by baptx** [comment]
@rushbruh Please share the Slack link to your comment if you got your issue fixed, for future reference if people have the same issue.
Anyway, I got the issue fixed with this solution: https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/2286
