### ISSUE TITLE
Problem with run MobSF

### ISSUE THREAD

**Issue by alexisdinamarcab** [MobSF/Mobile-Security-Framework-MobSF#2264]
HI i run after ./setup.sh in kali linux an then execute script ./run.sh, and show me problem. i dont know what it is. please help. ty

└─$ ./run.sh               
[2023-09-07 11:23:32 -0400] [1502294] [INFO] Starting gunicorn 21.2.0
[2023-09-07 11:23:32 -0400] [1502294] [INFO] Listening at: http://[::]:8000 (1502294)
[2023-09-07 11:23:32 -0400] [1502294] [INFO] Using worker: gthread
[2023-09-07 11:23:32 -0400] [1502308] [INFO] Booting worker with pid: 1502308
[2023-09-07 15:23:32 +0000] [1502308] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/config.py", line 396, in resolve
    found = self.importer(used)
            ^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'colorlog'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/config.py", line 552, in configure
    formatters[name] = self.configure_formatter(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/config.py", line 664, in configure_formatter
    result = self.configure_custom(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/config.py", line 479, in configure_custom
    c = self.resolve(c)
        ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/config.py", line 407, in resolve
    raise v from e
ValueError: Cannot resolve 'colorlog.ColoredFormatter': No module named 'colorlog'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/kali/.local/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 95, in init_process
    super().init_process()
  File "/home/kali/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/kali/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Mobile-Security-Framework-MobSF/mobsf/MobSF/wsgi.py", line 23, in <module>
    application = WhiteNoise(get_wsgi_application(),
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/lib/python3/dist-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/lib/python3/dist-packages/django/utils/log.py", line 75, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python3.11/logging/config.py", line 823, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.11/logging/config.py", line 555, in configure
    raise ValueError('Unable to configure '
ValueError: Unable to configure formatter 'color'
[2023-09-07 15:23:32 +0000] [1502308] [INFO] Worker exiting (pid: 1502308)
[2023-09-07 11:23:32 -0400] [1502294] [ERROR] Worker (pid:1502308) exited with code 3
[2023-09-07 11:23:32 -0400] [1502294] [ERROR] Shutting down: Master
[2023-09-07 11:23:32 -0400] [1502294] [ERROR] Reason: Worker failed to boot.

**Comment by rishirajput07** [comment]
my error alueError: Unable to configure formatter 'color'
is not solved pls help to solve it

**Comment by KimmAmy** [comment]
──(root㉿Kali)-[/home/kali/Downloads/Mobile-Security-Framework-MobSF-master]
└─# ./run.sh
Command not found: gunicorn


Can someone help out, i tried installing python3-gunicorn but it still bring out this error after installation.
