### ISSUE TITLE
Error Reading Code Signing Certificate

### ISSUE THREAD

**Issue by EvilWatermelon** [MobSF/Mobile-Security-Framework-MobSF#2324]
## ENVIRONMENT

```
OS and Version: Linux (ubuntu 22.04 Jammy Jellyfish) Linux-6.1.0-16-amd64-x86_64-with-glibc2.35
Python Version:
MobSF Version: v3.9.2 Beta
```

## EXPLANATION OF THE ISSUE
I ran a static scan of `com.whatsapp` with the version 2.24.1.9 and got the error during `Reading Code Signing Certificate`.

```
Traceback (most recent call last):
File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/cert_analysis.py", line 263, in cert_info
cert_data = get_cert_data(
File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/cert_analysis.py", line 237, in get_cert_data
certlist.extend(get_pub_key_details(public_key))
File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/views/android/cert_analysis.py", line 107, in get_pub_key_details
p = dsa_parameters.p
AttributeError: 'cryptography.hazmat.bindings._rust.openssl.dsa.DSA' object has no attribute 'p'
```

**Comment by ajinabraham** [comment]
Thanks for your report. I will take a look at this.
