### ISSUE TITLE
Trackers DB never get updated

### ISSUE THREAD

**Issue by JamesOsborn-SE** [MobSF/Mobile-Security-Framework-MobSF#2337]
## ENVIRONMENT

```
OS and Version: n/a
Python Version: n/a
MobSF Version: latest
```

## EXPLANATION OF THE ISSUE

```
What happens, under which versions, under what conditions, when, and what were you expecting instead.
```

Trackers DB never get updated

```
[INFO] 07/Feb/2024 18:26:36 - Running APKiD 2.1.5
[INFO] 07/Feb/2024 18:26:37 - Trackers Database is outdated!
[ERROR] 07/Feb/2024 18:26:37 - [ERROR] Trackers DB Update
Traceback (most recent call last):
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/MalwareAnalyzer/views/Trackers.py", line 56, in _update_tracker_db
    data = json.loads(resp.decode('utf-8', 'ignore'))
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

## STEPS TO REPRODUCE THE ISSUE

```
1. docker pull opensecurity/mobile-security-framework-mobsf:latest
2. docker run -it --rm -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest
3. Upload APK to test
```

**Comment by ajinabraham** [comment]
Working fine at my end. It's probably that the exodus server has some issues when the db update is happening at your end.

```
[INFO] 09/Feb/2024 18:11:58 - Getting Signature Versions
[INFO] 09/Feb/2024 18:11:58 - Running APKiD 2.1.5
[INFO] 09/Feb/2024 18:12:02 - Trackers Database is outdated!
[INFO] 09/Feb/2024 18:12:02 - Updating Trackers Database....
[INFO] 09/Feb/2024 18:12:02 - Detecting Trackers
[INFO] 09/Feb/2024 18:12:05 - APK -> JAVA
[INFO] 09/Feb/2024 18:12:05 - Decompiling to Java with jadx
```

**Comment by JamesOsborn-SE** [comment]
It started with this:
https://gitlab.com/fdroid/fdroiddata/-/jobs/6119488786

Maybe it's regional?
