### ISSUE TITLE
No such file or directory: 'C:\\Users\\<UserName>\\.MobSF\signatures/exodus_trackers'

### ISSUE THREAD

**Issue by chosenonehacks** [MobSF/Mobile-Security-Framework-MobSF#2411]
While performing static analysis MobSF errors

[WARNING] 19/Jul/2024 14:30:48 - Failed to download Trackers DB.
[INFO] 19/Jul/2024 14:30:48 - Detecting Trackers
[ERROR] 19/Jul/2024 14:30:48 - Error Performing Static Analysis
Traceback (most recent call last):
  File "C:\Users\Admin.PUREW10STPGIM.000\Downloads\Mobile-Security-Framework-MobSF-3.9.7\mobsf\StaticAnalyzer\views\android\static_analyzer.py", line 249, in static_analyzer
    tracker_res = tracker.get_trackers()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin.PUREW10STPGIM.000\Downloads\Mobile-Security-Framework-MobSF-3.9.7\mobsf\MalwareAnalyzer\views\Trackers.py", line 218, in get_trackers
    trackers = self.detect_trackers()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin.PUREW10STPGIM.000\Downloads\Mobile-Security-Framework-MobSF-3.9.7\mobsf\MalwareAnalyzer\views\Trackers.py", line 193, in detect_trackers
    self.load_trackers_signatures()
  File "C:\Users\Admin.PUREW10STPGIM.000\Downloads\Mobile-Security-Framework-MobSF-3.9.7\mobsf\MalwareAnalyzer\views\Trackers.py", line 103, in load_trackers_signatures
    with io.open(self.tracker_db,
         ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin.PUREW10STPGIM.000\\.MobSF\\signatures/exodus_trackers'
[ERROR] 19/Jul/2024 14:30:48 - [Errno 2] No such file or directory: 'C:\\Users\\Admin.PUREW10STPGIM.000\\.MobSF\\signatures/exodus_trackers'
[ERROR] 19/Jul/2024 14:30:48 - Internal Server Error: /static_analyzer/3731f64e284eb55ddee345d9130f50a3/
ERROR:django.request:Internal Server Error: /static_analyzer/3731f64e284eb55ddee345d9130f50a3/

## ENVIRONMENT

```
OS and Version: Windows 10 22H2
Python Version: 3.11.9
MobSF Version: v3.9.7 Beta
```

## STEPS TO REPRODUCE THE ISSUE

```
1. Upload sample APK for static anaysis
2. Receive Error as on screenshots
![error1](https://github.com/user-attachments/assets/36f48e9a-9f86-40dd-9cf2-92447ba3e1fa)
![error2](https://github.com/user-attachments/assets/d8106cd8-3fb2-420e-a80f-521f8a605fdf)

```

## LOG FILE

```
Paste the contents of ~/.MobSF/debug.log here or attach the log file.
```
[debug.log](https://github.com/user-attachments/files/16312809/debug.log)

**Comment by chosenonehacks** [comment]
![error1](https://github.com/user-attachments/assets/9f199a1a-e977-4fbb-bb41-f7ef7e8881b3)

**Comment by chosenonehacks** [comment]
![error2](https://github.com/user-attachments/assets/fb639b21-09c5-45bf-beb3-558caf1a72ea)
