### ISSUE TITLE
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file

### ISSUE THREAD

**Issue by jairwen** [MobSF/Mobile-Security-Framework-MobSF#328]
Hey~ Great Work.
Got this error,
```
[INFO] Extracting Strings from APK
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:54)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:540)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:76)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:68)
        at strings.StringsXML.run(StringsXML.java:84)
        at strings.StringsXML.main(StringsXML.java:151)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000000
        at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:48)
        at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:43)
        at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:100)
        at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:81)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:49)
```

I guess this is from  string_from_apk.jar, is it an enhanced version of APKTools?

**Comment by ajinabraham** [comment]
This is known issue with string_from_apk.jar  It doesn't support all the apks some how. Closing this as it's a 3rd party issue.

**Comment by akhilporandla21041998** [comment]
Getting error while recompiling a APK


*******************************
Exception in thread "main" java.lang.NoSuchMethodError: brut.androlib.meta.StringExConstructor.constructScalar(Lorg/yaml/snakeyaml/nodes/ScalarNode;)Ljava/lang/Object;
        at brut.androlib.meta.StringExConstructor.access$100(StringExConstructor.java:25)
        at brut.androlib.meta.StringExConstructor$ConstructStringEx.construct(StringExConstructor.java:32)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193)
        at org.yaml.snakeyaml.constructor.SafeConstructor.processDuplicateKeys(SafeConstructor.java:85)
        at org.yaml.snakeyaml.constructor.SafeConstructor.flattenMapping(SafeConstructor.java:70)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:190)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:309)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:518)
        at brut.androlib.meta.MetaInfo.load(MetaInfo.java:70)
        at brut.androlib.Androlib.readMetaFile(Androlib.java:260)
        at brut.androlib.Androlib.build(Androlib.java:274)
        at brut.androlib.Androlib.build(Androlib.java:267)
        at brut.apktool.Main.cmdBuild(Main.java:238)
        at brut.apktool.Main.main(Main.java:76)




********************************
PLEASE GIVE ME A SOLUTION

**Comment by ajinabraham** [comment]
MobSF need Java 1.7 or above.

**Comment by ajinabraham** [comment]
I guess that's not oracle JDK. Try using Oracle JDK.

**Comment by akhilporandla21041998** [comment]
Ha yes it's not oracle jdk please send me link of oracle jdk

**Comment by ajinabraham** [comment]
Please Google. It varies with your OS and Architecture.

**Comment by akhilporandla21041998** [comment]
Please send me sir

**Comment by akhilporandla21041998** [comment]
I'm using aarch64

**Comment by akhilporandla21041998** [comment]
I have to download only jdk or both jdk and  jre

**Comment by zseha** [comment]
Stop bothering developers and learn it yourself. They have more important stuff to do, and even if they did they don't own you nothing.

**Comment by akhilporandla21041998** [comment]
What u r saying I can't understand

**Comment by akhilporandla21041998** [comment]
Did u have solution to my problem

**Comment by zseha** [comment]
Learn it your goddamn self.  Its not MobSF issue its hardware issue

**Comment by akhilporandla21041998** [comment]
I'm getting error while recompiling the original apk file

******************************
I: Using Apktool 2.2.0
I: Checking whether sources has changed...
[Fatal Error] AndroidManifest.xml:1:1: Content is not allowed in prolog.
I: Checking whether resources has changed...
I: Copying raw resources...
I: Building apk file...
I: Copying unknown files/dir...

***************************

PLEASE SLOVE  THIS
