### ISSUE TITLE
Problems with dynamic analyzer - MobSF

### ISSUE THREAD

**Issue by Icelannd** [MobSF/Mobile-Security-Framework-MobSF#349]
Hi Everyone, here its my problem:
When I want to do a dynamic analysis of an apk, comes out the following error in virtualbox and nothing happens: 

![virtualbox - error](https://cloud.githubusercontent.com/assets/25938677/23185168/30c2b560-f861-11e6-9890-e2493f8bf7aa.PNG)

Some suggestion?

Regards

**Comment by ajinabraham** [comment]
The is out of the scope of this project. However you can try deleting and adding your virtual adapters once. 
https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/6.-What-to-do-when-MobSF-VM-and-VirtualBox-Host-Only-Adapter-are-not-in-the-same-network-range

**Comment by kingjohntom** [comment]
Hi everyone，I was install Mobsf， but  it seemed something wrong,when I take the fellowing  step.
C:\MobSF>python manage.py runserver

[INFO] Running first time setup for windows.

[*] Reading config file..

[*] Downloading nuget..

[*] Saving to File nuget.exe

[*] Downloading and installing Binskim…

Unhandled Exception: System.NotSupportedException: The requested security protoc

ol is not supported.

   at System.Net.ServicePointManager.ValidateSecurityProtocol(SecurityProtocolTy

pe value)

   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)

   at NuGet.CommandLine.Program.Main(String[] args)

Traceback (most recent call last):

  File "manage.py", line 10, in <module>

    execute_from_command_line(sys.argv)

  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line

367, in execute_from_command_line

    utility.execute()

  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line

316, in execute

    settings.INSTALLED_APPS

  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 53, in __ge

tattr__

    self._setup(name)

  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 41, in _set

up

    self._wrapped = Settings(settings_module)

  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 97, in __in

it__

    mod = importlib.import_module(self.SETTINGS_MODULE)

  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module

    __import__(name)

  File "C:\MobSF\MobSF\settings.py", line 381, in <module>

    windows_setup.install_locally(MobSF_HOME)

  File "C:\MobSF\install\windows\setup.py", line 370, in install_locally

    tools_binskim()

  File "C:\MobSF\install\windows\setup.py", line 148, in tools_binskim

    ‘-o’, mobsf_subdir_tools

  File "C:\Python27\lib\subprocess.py", line 219, in check_output

    raise CalledProcessError(retcode, cmd, output=output)

subprocess.CalledProcessError: Command ‘[u'C:\\MobSF\\StaticAnalyzer\\tools\\win

dows\\nuget.exe', 'install', u'Microsoft.CodeAnalysis.BinSkim', '-Pre', '-o', u'

C:\\MobSF\\StaticAnalyzer\\tools\\windows\\']‘ returned non-zero exit status -53

2462766

C:\MobSF>
![default](https://cloud.githubusercontent.com/assets/23326652/23241280/33bd6420-f9ad-11e6-8692-d8e4f984c114.png)
Some suggestion?

Regards

**Comment by ajinabraham** [comment]
Read: https://github.com/MobSF/Mobile-Security-Framework-MobSF/tree/master/install/windows#faq

**Comment by Icelannd** [comment]
Hi!! I suggest you to install all again python and mobsf and delete all the files, then I recomend you to install python 2.7.13 and check also you have this lib: "python 2.7 lxml-3.2.3", here is the link of the library:
https://pypi.python.org/pypi/lxml/3.2.3

Check that you installed pip correctly first of all.

Hope this can help you
