### ISSUE TITLE
[ERROR] Saving to DB

### ISSUE THREAD

**Issue by unl1k3ly** [MobSF/Mobile-Security-Framework-MobSF#364]
Can't do static analysis from a kali 2016.2 fresh install.

I've tried clone back from master and install agan, same error. 

APK used, was Google Calculator.

I've also tried in diffrents Kalis and same error. 

See backlog for tracking.

Thank you

 

[INFO] Static Android Code Analysis Started
[INFO] Code Analysis Started on - /opt/Mobile-Security-Framework-MobSF/uploads/065c2f9e7f5c9112dd961700794161a6/java_source/
[INFO] Performing Malware Check on extracted Domains

[INFO] Malware Database is up-to-date.
[INFO] Finished Code Analysis, Email and URL Extraction

[INFO] Generating Java and Smali Downloads
[INFO] Generating Downloads
[INFO] Zipping
[INFO] Zipping
[INFO] Extracting Strings from APK
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:54)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:540)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:76)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:68)
	at strings.StringsXML.run(StringsXML.java:84)
	at strings.StringsXML.main(StringsXML.java:151)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000000
	at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:48)
	at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:43)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:100)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:81)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:49)
	... 5 more

[INFO] Connecting to Database

[INFO] Saving to Database

[2017-03-03 04:56:35]
[ERROR] Saving to DB (/opt/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py, LINE 219 "CERT_INFO=cert_dic['cert_info'],"): 'NoneType' object has no attribute '__getitem__'

[2017-03-03 04:56:35]
[ERROR] Rendering to Template (/opt/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py, LINE 104 "'certinfo': cert_dic['cert_info'],"): 'NoneType' object has no attribute '__getitem__'
[03/Mar/2017 04:56:35] "GET /StaticAnalyzer/?name=com.google.android.calculator.apk&type=apk&checksum=065c2f9e7f5c9112dd961700794161a6 HTTP/1.1" 200 35193
[03/Mar/2017 04:56:35] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 26711
[03/Mar/2017 04:56:35] "GET /static/css/style.css HTTP/1.1" 200 3463
[03/Mar/2017 04:56:35] "GET /static/dash/css/skins/_all-skins.min.css HTTP/1.1" 200 41878
[03/Mar/2017 04:56:35] "GET /static/css/ionicons.min.css HTTP/1.1" 200 51284
[03/Mar/2017 04:56:35] "GET /static/dash/css/AdminLTE.min.css HTTP/1.1" 200 89483
[03/Mar/2017 04:56:35] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 200 122540
[03/Mar/2017 04:56:36] "GET /static/bootstrap/js/bootstrap.min.js HTTP/1.1" 200 35951
[03/Mar/2017 04:56:36] "GET /static/plugins/fastclick/fastclick.min.js HTTP/1.1" 200 8776
[03/Mar/2017 04:56:36] "GET /static/dash/js/app.min.js HTTP/1.1" 200 9684
[03/Mar/2017 04:56:36] "GET /static/plugins/slimScroll/jquery.slimscroll.min.js HTTP/1.1" 200 6230
[03/Mar/2017 04:56:36] "GET /static/plugins/jQuery/jQuery-2.1.4.min.js HTTP/1.1" 200 84345
[03/Mar/2017 04:56:36] "GET /static/bootstrap/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 18028
[03/Mar/2017 04:56:36] "GET /static/js/docs.js HTTP/1.1" 200 1581
[03/Mar/2017 04:56:36] "GET /static/fonts/fontawesome-webfont.woff2?v=4.4.0 HTTP/1.1" 200 64464

**Comment by ajinabraham** [comment]
Fixed in the master https://github.com/MobSF/Mobile-Security-Framework-MobSF/commit/e849d234c3004cec5eef12c965df47a50685fa1f
