### ISSUE TITLE
 Requires OSX. iOS Application Security Analysis requires OSX. on Docker

### ISSUE THREAD

**Issue by chaohaiding** [MobSF/Mobile-Security-Framework-MobSF#369]
## EXPLANATION OF THE ISSUE

Using the Docker for iOS pen test:

I am using the Docker for iOS app test on a Mac. However, I get the following message:

Requires OSX. iOS Application Security Analysis requires OSX.

How can I use the docker on the Mact to test the iOS app test.

## CONSOLE OUTPUT

```
[INFO] MIME Type: application/octet-stream FILE: Nudge.ipa

[ERROR] Static Analysis of iOS IPA requires OSX
[08/Mar/2017 19:41:41] "POST /Upload/ HTTP/1.1" 200 60
[08/Mar/2017 19:41:41] "GET /MAC_ONLY/ HTTP/1.1" 200 4618
```

**Comment by ajinabraham** [comment]
You can't. For iOS IPA Analysis, MobSF needs to be running on Mac

**Comment by moha19** [comment]
if "itunes" installed on windows, it works properly?

**Comment by ajinabraham** [comment]
No. Some analysis apps works only on Mac

**Comment by sidgami** [comment]
@ajinabraham : Tried running the docker image on MacOS Sierra 10.12.6 - Gives me "Requires OSX. iOS Application Security Analysis requires OSX."

Is there an issue with the latest Sierra update?

**Comment by bugtest0101** [comment]
I have the same issue on MacOS High Sierra 10.13.1

**Comment by ajinabraham** [comment]
It's self explanatory. If you need to scan IPA, run MobSF on host and not the docker image which is Linux based.

**Comment by VijaySokkala** [comment]
i got this issue in mac, pls help out me

$ python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/Library/Python/2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/Library/Python/2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/Library/Python/2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/MOURITECH/Downloads/Mobile-Security-Framework-MobSF-master/MobSF/settings.py", line 13, in <module>
    from MobSF import utils
  File "/Users/MOURITECH/Downloads/Mobile-Security-Framework-MobSF-master/MobSF/utils.py", line 12, in <module>
    import urllib.request
ImportError: No module named request


Thanks
Vijay S

**Comment by VijaySokkala** [comment]
$ python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/Library/Python/2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/Library/Python/2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/Library/Python/2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/TECH/Downloads/Mobile-Security-Framework-MobSF-master/MobSF/settings.py", line 13, in <module>
    from MobSF import utils
  File "/Users/TECH/Downloads/Mobile-Security-Framework-MobSF-master/MobSF/utils.py", line 12, in <module>
    import urllib.request
ImportError: No module named request

**Comment by ajinabraham** [comment]
Use Python3 @VijaySokkala

**Comment by bshieh** [comment]
Wanted to clarify, can the docker image be used to do static analysis on iOS apps? 

Based on the documentation, it sounds like it can:
https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation
Installation

"Tip: Lazy to setup Static Analysis? Use the docker build from DockerHub

Tested on Windows (7, 8, 8.1, 10), Kali (2016.2), Ubuntu (14.04, 16.04) , OSX (Mavericks, Yosemite, El Capitan), OS (Sierra, High Sierra)"

I'm getting the error "Requires OSX. iOS Application Security Analysis requires OSX. You need to install and configure MobSF in an OSX host. This won't work if you are running inside a VM or Docker Container" when trying to upload an ipa file to analyze on macOS High Sierra v 10.13.5. Based on the error, it sounds like you must use the OSX host itself and not the Docker image, to run iOS security analysis. If this is the case, it could be helpful to modify the documentation tip to clarify that.

Is there any benefit to using the Docker image on Mac for iOS apps? Or does it only really work for other app types?

**Comment by ajinabraham** [comment]
Yeah will change the confusing docs. IPA analysis won't run inside docker. You need to set it up in a Mac host.

**Comment by rohitsn786** [comment]
![capture](https://user-images.githubusercontent.com/10944576/45760446-b7f84080-bc47-11e8-89ea-8238c7eb84d0.PNG)
Is this a mistake or does MobSF supports ipa analysis on linux? @ajinabraham

**Comment by ajinabraham** [comment]
We recently started to support Linux and Mac

**Comment by madhu92be** [comment]
@ajinabraham: I am using tamer in which MobSF is preinstalled, but for testing ipa app it is saying requires OSX. Please help me.

**Comment by ajinabraham** [comment]
I think Tamer is using an old version of MobSF. iOS support for Linux is introduced recently.

**Comment by madhu92be** [comment]
@ajinabraham OK, then please suggest should I go for latest Tamer or santoku or should i install latest MobSF ?

**Comment by ajinabraham** [comment]
I always recommend the latest `master` of MobSF or the latest docker image from here: https://hub.docker.com/r/opensecurity/mobile-security-framework-mobsf/

It's the most updated code base.

**Comment by madhu92be** [comment]
@ajinabraham Nice!!! the docker is awesome. I encountered an issue while performing Dynamic Analysis. It is finding some default IP which is not available. Please help me on this.

**Comment by ajinabraham** [comment]
Dynamic Analysis needs MobSF to be configured in host OS and not inside docker.
