### ISSUE TITLE
Unable to start MobSF

### ISSUE THREAD

**Issue by whitehatpanda** [MobSF/Mobile-Security-Framework-MobSF#379]
## EXPLANATION OF THE ISSUE

I can't start MobSF (runserver) after update to latest OSX.

## STEPS TO REPRODUCE THE ISSUE

```
1. git clone MobSF repo
2. pip install -r
3. python manage.py runserver -> got error
```

## CONSOLE OUTPUT

```
python manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x105fde2a8>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/whitehatpanda/Mobile-Security-Framework-MobSF/MobSF/urls.py", line 4, in <module>
    import DynamicAnalyzer.views.android
  File "/Users/whitehatpanda/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android.py", line 25, in <module>
    from DynamicAnalyzer.pyWebProxy.pywebproxy import *
  File "/Users/whitehatpanda/Mobile-Security-Framework-MobSF/DynamicAnalyzer/pyWebProxy/pywebproxy.py", line 33, in <module>
    import tornado.httpserver
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/httpserver.py", line 34, in <module>
    from tornado.http1connection import HTTP1ServerConnection, HTTP1ConnectionParameters
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/http1connection.py", line 28, in <module>
    from tornado import gen
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/gen.py", line 1243, in <module>
    import tornado.platform.asyncio
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/platform/asyncio.py", line 33, in <module>
    import asyncio # type: ignore
  File "/Users/whitehatpanda/Library/Python/2.7/lib/python/site-packages/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/Users/whitehatpanda/Library/Python/2.7/lib/python/site-packages/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None
                               ^
SyntaxError: invalid syntax
```

**Comment by ajinabraham** [comment]
Not a MobSF issue. Something to do with Python or the dependencies. You should try using latest python 2.7
