### ISSUE TITLE
python 2.7.13 https issue.

### ISSUE THREAD

**Issue by 99ttz** [MobSF/Mobile-Security-Framework-MobSF#390]
hi,

when performing dynamic analysis on an apk that requires use of https communications, the communications times out and the following gets written to logs:

[E 170412 09:09:59 ioloop:633] Exception in callback None
    Traceback (most recent call last):
      File "/Users/99TTZ/Library/Python/2.7/lib/python/site-packages/tornado/ioloop.py", line 887, in start
        handler_func(fd_obj, events)
      File "/Users/99TTZ/Library/Python/2.7/lib/python/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/Users/99TTZ/Library/Python/2.7/lib/python/site-packages/tornado/iostream.py", line 507, in _handle_events
        self._handle_connect()
      File "/Users/99TTZ/Library/Python/2.7/lib/python/site-packages/tornado/iostream.py", line 1376, in _handle_connect
        do_handshake_on_connect=False)
      File "/Users/99TTZ/Library/Python/2.7/lib/python/site-packages/tornado/netutil.py", line 522, in ssl_wrap_socket
        return context.wrap_socket(socket, **kwargs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 352, in wrap_socket
        _context=self)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 550, in __init__
        raise ValueError("check_hostname requires server_hostname")
    ValueError: check_hostname requires server_hostname

the environment is running python 2.6.13 on a macos.

the issue seems to be linked to this: https://github.com/shazow/urllib3/issues/543

can you please help with the issue?

best
Theodor

**Comment by ajinabraham** [comment]
Not a MobSF issue. Third party issues can't be addressed here.
