### ISSUE TITLE
Unable to run manage script 

### ISSUE THREAD

**Issue by parag85** [MobSF/Mobile-Security-Framework-MobSF#392]
an error comes after installing all dependency When try to run manage.py file 

## STEPS TO REPRODUCE THE ISSUE

```
1. Extract the MobSF compressed file to C:\MobSF
2. pip install -r requirements.txt
3. Add the folder that contains wkhtmltopdf binary to environment variable PATH.
4. python manage.py runserver

## CONSOLE OUTPUT
C:\MobSF>python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
  execute_from_command_line(sys.argv)
  File "C:\Users\Pass\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\django\core\management\__init__.py", line 367, in execute_from_command_line
  utility.execute()
  File "C:\Users\Pass\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\django\core\management\__init__.py", line 316, in execute
  settings.INSTALLED_APPS
  File "C:\Users\Pass\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\django\conf\__init__.py", line 53, in __getattr__
  self._setup(name)
  File "C:\Users\Pass\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\django\conf\__init__.py", line 41, in _setup
  self._wrapped = Settings(settings_module)
  File "C:\Users\Pass\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\django\conf\__init__.py", line 97, in __init__
  mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\Pass\AppData\Local\Programs\Python\Python36-32\lib\importlib\__
init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\MobSF\MobSF\settings.py", line 214
  print '[INFO] Loading User config from: '
  ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by ajinabraham** [comment]
Wiki Says use Python 2.7
