### ISSUE TITLE
Code Nature obfuscation allways false

### ISSUE THREAD

**Issue by mibaldi** [MobSF/Mobile-Security-Framework-MobSF#442]
## EXPLANATION OF THE ISSUE

Obfuscation flag in code nature is allways false 

## STEPS TO REPRODUCE THE ISSUE

```
1. Create a new empty Android project and activate proguard
2. Upload apk
3. Obfuscation flag is false
```

## CONSOLE OUTPUT

```
[INFO] MIME Type: application/octet-stream FILE: app-release.apk

[INFO] Performing Static Analysis of Android APK
[13/Jul/2017 07:59:21] "POST /upload/ HTTP/1.1" 200 138
[INFO] Starting Analysis on : app-release.apk
[INFO] Generating Hashes
[INFO] Unzipping
[INFO] Getting Hardcoded Certificates/Keystores
[INFO] APK Extracted
[INFO] Getting Manifest from Binary
[INFO] AXML -> XML
[INFO] Parsing AndroidManifest.xml
[INFO] Extracting Manifest Data
[INFO] Manifest Analysis Started
[INFO] Static Android Binary Analysis Started
[INFO] Static Android Resourse Analysis Started
[INFO] Reading Code Signing Certificate
[INFO] DEX -> JAR
[INFO] Using JAR converter - dex2jar
dex2jar /Users/mbalduciel/MobSF/uploads/b74c827bd1adf66204d179587e1d6996/classes.dex -> /Users/mbalduciel/MobSF/uploads/b74c827bd1adf66204d179587e1d6996/classes.jar
[INFO] DEX -> SMALI
[INFO] JAR -> JAVA
Processing /Users/mbalduciel/MobSF/uploads/b74c827bd1adf66204d179587e1d6996/classes.jar (use silent to silence)
Processing android.support.a.a.a
Processing android.support.v4.c.a.f
Processing android.support.a.a.d
Processing android.support.a.a.b
Processing android.support.a.a.c
Processing android.support.a.a.e
Processing android.support.annotation.Keep
Processing android.support.constraint.ConstraintLayout
Processing android.support.constraint.a.a.a
Processing android.support.constraint.a.a.b
Processing android.support.constraint.a.a.c
Processing android.support.constraint.a.a.h
Processing android.support.constraint.a.a.d
Processing android.support.constraint.a.a.e
Processing android.support.constraint.a.a.f
Processing android.support.constraint.a.a.g
Processing android.support.constraint.a.a
Processing android.support.constraint.a.b
Processing android.support.constraint.a.c
Processing android.support.constraint.a.d
Processing android.support.constraint.a.e
Processing android.support.constraint.a.f
Processing android.support.constraint.a.g
Processing android.support.constraint.a
Processing android.support.constraint.b
Processing android.support.v4.b.a
Processing android.support.v4.a.a
Processing android.support.v4.a.aa
Processing android.support.v4.a.ab
Processing android.support.v4.a.ac
Processing android.support.v4.a.ad
Processing android.support.v4.a.b
Processing android.support.v4.a.c
Processing android.support.v4.a.d
Processing android.support.v4.a.s
Processing android.support.v4.a.e
Processing android.support.v4.a.f
Processing android.support.v4.a.g
Processing android.support.v4.a.h
Processing android.support.v4.a.k
Processing android.support.v4.a.i
Processing android.support.v4.a.m
Processing android.support.v4.a.j
Processing android.support.v4.a.l
Processing android.support.v4.a.n
Processing android.support.v4.a.o
Processing android.support.v4.a.p
Processing android.support.v4.a.q
Processing android.support.v4.a.r
Processing android.support.v4.a.t
Processing android.support.v4.a.u
Processing android.support.v4.a.v
Processing android.support.v4.a.w
Processing android.support.v4.a.x
Processing android.support.v4.a.y
Processing android.support.v4.a.z
Processing android.support.v4.b.a.a
Processing android.support.v4.b.a.b
Processing android.support.v4.b.b
Processing android.support.v4.b.c
Processing android.support.v4.c.a.a
Processing android.support.v4.c.a.b
Processing android.support.v4.c.a.c
Processing android.support.v4.c.a.d
Processing android.support.v4.c.a.e
Processing android.support.v4.c.a
Processing android.support.v4.d.a.a
Processing android.support.v4.d.a.b
Processing android.support.v4.d.a.c
Processing android.support.v4.e.a
Processing android.support.v4.e.b
Processing android.support.v4.e.c
Processing android.support.v4.e.d
Processing android.support.v4.e.e
Processing android.support.v4.f.h
Processing android.support.v4.f.j
Processing android.support.v4.f.a
Processing android.support.v4.f.b
Processing android.support.v4.f.c
Processing android.support.v4.f.d
Processing android.support.v4.f.e
Processing android.support.v4.f.f
Processing android.support.v4.f.g
Processing android.support.v4.f.i
Processing android.support.v4.f.k
Processing android.support.v4.g.a
Processing android.support.v4.g.a.a
Processing android.support.v4.g.a.b
Processing android.support.v4.g.a.c
Processing android.support.v4.g.a.d
Processing android.support.v4.g.a.e
Processing android.support.v4.g.a.f
Processing android.support.v4.g.a.g
Processing android.support.v4.g.a.h
Processing android.support.v4.g.a.i
Processing android.support.v4.g.a.j
Processing android.support.v4.g.a.k
Processing android.support.v4.g.a.l
Processing android.support.v4.g.aa
Processing android.support.v4.g.ab
Processing android.support.v4.g.ac
Processing android.support.v4.g.b
Processing android.support.v4.g.c
Processing android.support.v4.g.d
Processing android.support.v4.g.e
Processing android.support.v4.g.f
Processing android.support.v4.g.g
Processing android.support.v4.g.h
Processing android.support.v4.g.i
Processing android.support.v4.g.j
Processing android.support.v4.g.k
Processing android.support.v4.g.l
Processing android.support.v4.g.m
Processing android.support.v4.g.n
Processing android.support.v4.g.o
Processing android.support.v4.g.p
Processing android.support.v4.g.q
Processing android.support.v4.g.r
Processing android.support.v4.g.s
Processing android.support.v4.g.t
Processing android.support.v4.g.y
Processing android.support.v4.g.u
Processing android.support.v4.g.v
Processing android.support.v4.g.w
Processing android.support.v4.g.x
Processing android.support.v4.g.z
Processing android.support.v4.widget.NestedScrollView
Processing android.support.v4.widget.Space
Processing android.support.v4.widget.a
Processing android.support.v4.widget.b
Processing android.support.v4.widget.c
Processing android.support.v4.widget.d
Processing android.support.v4.widget.e
Processing android.support.v4.widget.f
Processing android.support.v4.widget.g
Processing android.support.v4.widget.h
Processing android.support.v4.widget.i
Processing android.support.v4.widget.j
Processing android.support.v4.widget.k
Processing android.support.v4.widget.l
Processing android.support.v4.widget.m
Processing android.support.v7.a.a
Processing android.support.v7.app.AlertController
Processing android.support.v7.app.a
Processing android.support.v7.app.d
Processing android.support.v7.app.l
Processing android.support.v7.app.b
Processing android.support.v7.app.c
Processing android.support.v7.app.e
Processing android.support.v7.view.i
Processing android.support.v7.app.f
Processing android.support.v7.app.k
Processing android.support.v7.app.h
Processing android.support.v7.app.i
Processing android.support.v7.app.j
Processing android.support.v7.app.g
Processing android.support.v7.widget.ContentFrameLayout
Processing android.support.v7.app.m
Processing android.support.v7.app.n
Processing android.support.v7.app.o
Processing android.support.v7.app.p
Processing android.support.v7.app.q
Processing android.support.v7.view.b
Processing android.support.v7.app.r
Processing android.support.v7.b.a.a
Processing android.support.v7.b.a.b
Processing android.support.v7.b.a.c
Processing android.support.v7.c.a.a
Processing android.support.v7.d.a
Processing android.support.v7.e.a
Processing android.support.v7.view.a
Processing android.support.v7.view.c
Processing android.support.v7.view.d
Processing android.support.v7.view.e
Processing android.support.v7.view.f
Processing android.support.v7.view.g
Processing android.support.v7.view.h
Processing android.support.v7.widget.ag
Processing android.support.v7.widget.aa
Processing android.support.v7.view.menu.ActionMenuItemView
Processing android.support.v7.view.menu.p
Processing android.support.v7.view.menu.ExpandedMenuView
Processing android.support.v7.view.menu.ListMenuItemView
Processing android.support.v7.view.menu.a
Processing android.support.v7.view.menu.o
Processing android.support.v7.view.menu.b
Processing android.support.v7.view.menu.d
Processing android.support.v7.view.menu.c
Processing android.support.v7.widget.ak
Processing android.support.v7.view.menu.s
Processing android.support.v7.view.menu.m
Processing android.support.v7.view.menu.e
Processing android.support.v7.view.menu.f
Processing android.support.v7.view.menu.g
Processing android.support.v7.view.menu.h
Processing android.support.v7.view.menu.i
Processing android.support.v7.view.menu.j
Processing android.support.v7.view.menu.k
Processing android.support.v7.view.menu.l
Processing android.support.v7.view.menu.n
Processing android.support.v7.view.menu.q
Processing android.support.v7.view.menu.r
Processing android.support.v7.view.menu.t
Processing android.support.v7.view.menu.u
Processing android.support.v7.view.menu.v
Processing android.support.v7.widget.ActionBarContainer
Processing android.support.v7.widget.a
Processing android.support.v7.widget.ActionBarContextView
Processing android.support.v7.widget.ab
Processing android.support.v7.widget.ActionBarOverlayLayout
Processing android.support.v7.widget.ah
Processing android.support.v7.widget.ActionMenuView
Processing android.support.v7.widget.ActivityChooserView
Processing android.support.v7.widget.AlertDialogLayout
Processing android.support.v7.widget.ButtonBarLayout
Processing android.support.v7.widget.DialogTitle
Processing android.support.v7.widget.af
Processing android.support.v7.widget.FitWindowsFrameLayout
Processing android.support.v7.widget.FitWindowsLinearLayout
Processing android.support.v7.widget.f
Processing android.support.v7.widget.SearchView
Processing android.support.v7.widget.Toolbar
Processing android.support.v7.widget.ViewStubCompat
Processing android.support.v7.widget.ac
Processing android.support.v7.widget.ad
Processing android.support.v7.widget.aj
Processing android.support.v7.widget.ae
Processing android.support.v7.widget.ai
Processing android.support.v7.widget.al
Processing android.support.v7.widget.am
Processing android.support.v7.widget.an
Processing android.support.v7.widget.ao
Processing android.support.v7.widget.ap
Processing android.support.v7.widget.aq
Processing android.support.v7.widget.ar
Processing android.support.v7.widget.as
Processing android.support.v7.widget.at
Processing android.support.v7.widget.au
Processing android.support.v7.widget.av
Processing android.support.v7.widget.aw
Processing android.support.v7.widget.ax
Processing android.support.v7.widget.ay
Processing android.support.v7.widget.b
Processing android.support.v7.widget.c
Processing android.support.v7.widget.p
Processing android.support.v7.widget.d
Processing android.support.v7.widget.e
Processing android.support.v7.widget.g
Processing android.support.v7.widget.h
Processing android.support.v7.widget.i
Processing android.support.v7.widget.j
Processing android.support.v7.widget.k
Processing android.support.v7.widget.l
Processing android.support.v7.widget.m
Processing android.support.v7.widget.n
Processing android.support.v7.widget.o
Processing android.support.v7.widget.q
Processing android.support.v7.widget.r
Processing android.support.v7.widget.s
Processing android.support.v7.widget.t
Processing android.support.v7.widget.u
Processing android.support.v7.widget.v
Processing android.support.v7.widget.w
Processing android.support.v7.widget.x
Processing android.support.v7.widget.y
Processing android.support.v7.widget.z
Processing com.example.mbalduciel.myapplication.MainActivity
Classes with case insensitive name clashes seen, and your FS appears to be case insensitive - consider using --caseinsensitivefs true
[INFO] Static Android Code Analysis Started
[INFO] Code Analysis Started on - /Users/mbalduciel/MobSF/uploads/b74c827bd1adf66204d179587e1d6996/java_source/
[INFO] Performing Malware Check on extracted Domains
[INFO] Finished Code Analysis, Email and URL Extraction

[INFO] Generating Java and Smali Downloads
[INFO] Generating Downloads
[INFO] Zipping
[INFO] Zipping
[INFO] Extracting Strings from APK
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:54)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:540)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:76)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:68)
	at strings.StringsXML.run(StringsXML.java:84)
	at strings.StringsXML.main(StringsXML.java:151)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000000
	at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:48)
	at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:43)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:100)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:81)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:49)
	... 5 more

[INFO] Connecting to Database

[INFO] Saving to Database
[13/Jul/2017 07:59:38] "GET /StaticAnalyzer/?name=app-release.apk&type=apk&checksum=b74c827bd1adf66204d179587e1d6996 HTTP/1.1" 200 79080

```

**Comment by ajinabraham** [comment]
Obfuscation is detected by a third party component, androguard. We don't have control on that.
