### ISSUE TITLE
HTTPS traffic not going through the proxy

### ISSUE THREAD

**Issue by Sub0knowledge** [MobSF/Mobile-Security-Framework-MobSF#466]
## EXPLANATION OF THE ISSUE
HTTPS traffic is not going through the proxy. I see plain HTTP GET requests being sent and printed into the proxy log but nothing happens when HTTPS is used.

I am running v0.9.5.4 Beta on Kali 2. None of the HTTPS traffic from the app is going through the proxy.

## STEPS TO REPRODUCE THE ISSUE

```
1. After setup, starts dynamic analysis.
2. Configure device's proxy to the Kali machine running MOBSF
3. Click on create environment... when the app is opened on the phone, HTTPS connections don't go through the proxy.

(Also pointed my browser in Kali to the proxy and same behavior. HTTP works but HTTPS doesn't)
```

## CONSOLE OUTPUT

Console shows nothing strange.

## CONTENTS OF LOG FILES

The only error on the webproxy.log is (a bunch of them):
[E 170810 17:38:13 ioloop:638] Exception in callback None
    Traceback (most recent call last):
      File "/root/.local/lib/python2.7/site-packages/tornado/ioloop.py", line 888, in start
        handler_func(fd_obj, events)
      File "/root/.local/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/root/.local/lib/python2.7/site-packages/tornado/iostream.py", line 515, in _handle_events
        self._handle_connect()
      File "/root/.local/lib/python2.7/site-packages/tornado/iostream.py", line 1427, in _handle_connect
        do_handshake_on_connect=False)
      File "/root/.local/lib/python2.7/site-packages/tornado/netutil.py", line 526, in ssl_wrap_socket
        return context.wrap_socket(socket, **kwargs)
      File "/usr/lib/python2.7/ssl.py", line 363, in wrap_socket
        _context=self)
      File "/usr/lib/python2.7/ssl.py", line 582, in __init__
        raise ValueError("check_hostname requires server_hostname")
    ValueError: check_hostname requires server_hostname

**Comment by ajinabraham** [comment]
Some thing to do with the update in Python or OpenSSL. Investigating the issue.

**Comment by ajinabraham** [comment]
Fixed in latest master
