### ISSUE TITLE
mobSF fails to launch

### ISSUE THREAD

**Issue by Nitzeb** [MobSF/Mobile-Security-Framework-MobSF#467]
## EXPLANATION OF THE ISSUE
mobSF fails to launch

## STEPS TO REPRODUCE THE ISSUE
Launch mobSF with command:
C:\MobSF>python manage.py runserver

## CONSOLE OUTPUT

C:\MobSF>python manage.py runserver
 Traceback (most recent call last):   File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line
363, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line
307, in execute
    settings.INSTALLED_APPS
  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 56, in __getattr__
    self._setup(name)
  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module    __import__(name)
  File "C:\MobSF\MobSF\settings.py", line 1
    """
    ^
IndentationError: unexpected indent

**Comment by ajinabraham** [comment]
You might have modified something in settings.py it's a python syntax error. Nothing to do with MobSF though
