### ISSUE TITLE
Im still getting this issue what am i doing wrong ?..

### ISSUE THREAD

**Issue by alldayi420** [MobSF/Mobile-Security-Framework-MobSF#530]
## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step
2. This is the second step
3. Further steps, etc.
```

## CONSOLE OUTPUT

```
Paste the output generated at your console/terminal while scanning the mobile app.
The console log should contain the error or bug you are seeing
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

## CONTENTS OF LOG FILES

```
Paste the contents of logs/MobSF.log here
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

```
If you have issues with API Fuzzer,
Paste the contents of logs/webproxy.log here
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```
root@kali:~/w3af# ./w3af_gui
Traceback (most recent call last):
  File "./w3af_gui", line 12, in <module>
    from w3af.core.ui.gui.dependency_check.dependency_check import dependency_check
  File "/root/w3af/w3af/core/ui/gui/dependency_check/dependency_check.py", line 25, in <module>
    from w3af.core.controllers.dependency_check.dependency_check import dependency_check as mdep_check
  File "/root/w3af/w3af/core/controllers/dependency_check/dependency_check.py", line 31, in <module>
    import pip
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 64, in <module>
    vendored("cachecontrol")
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 4, in <module>
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/__init__.py", line 52, in <module>
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/packages/__init__.py", line 59, in <module>
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/packages/__init__.py", line 32, in vendored
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 47, in <module>
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

**Comment by ajinabraham** [comment]
Are you confused? This is MobSF issue tracker!
Post w3af here: https://github.com/andresriancho/w3af/issues

But anyways since you asked, This is how you should solve this: https://github.com/andresriancho/w3af/issues/14895#issuecomment-286285074
