### ISSUE TITLE
Get icon function Error

### ISSUE THREAD

**Issue by alimp5** [MobSF/Mobile-Security-Framework-MobSF#536]
## EXPLANATION OF THE ISSUE
I got an warning message in get-icon-error-function.
log attached in LOG_SECTION.

## STEPS TO REPRODUCE THE ISSUE

```
1. today I installed MobSF from git:
https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#updating-mobsf
git clone https://github.com/MobSF/Mobile-Security-Framework-MobSF.git
2. I installed all requirements and dependencies and extra packages for MobSF without problem.
3. Version: Mobile Security Framework v0.9.5.5 Beta
4. python  manage.py  runserver  192.168.100.23:5050
```

## CONSOLE OUTPUT

```
Mobile Security Framework v0.9.5.5 Beta

REST API Key: a760ac09ac1641ec713e0ebe94c8f2244ab56673b06fb4554c9d67bb4fe12514
OS: Linux
Platform: Linux-4.14.0-kali3-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
Dist: ('Kali', 'kali-rolling', 'kali-rolling')

[INFO] Finding JDK Location in Linux/MAC....

[INFO] JDK 1.7 or above is available

[INFO] Checking for Update.

[INFO] No updates available.
System check identified no issues (0 silenced).
January 27, 2018 - 08:38:51
Django version 1.11.7, using settings 'MobSF.settings'
Starting development server at http://192.168.100.23:5050/
Quit the server with CONTROL-C.
Not Found: /robots.txt
[27/Jan/2018 08:39:37] "GET /robots.txt HTTP/1.1" 404 7021
[27/Jan/2018 08:39:37] "GET / HTTP/1.1" 200 7727
[27/Jan/2018 08:39:38] "GET /static/js/ie-emulation-modes-warning.js HTTP/1.1" 200 2132
[27/Jan/2018 08:39:38] "GET /static/js/dropzone.js HTTP/1.1" 200 64400
[27/Jan/2018 08:39:38] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 109518
[27/Jan/2018 08:39:38] "GET /static/css/cover.css HTTP/1.1" 200 2850
[27/Jan/2018 08:39:38] "GET /static/css/dropzone.css HTTP/1.1" 200 12587
[27/Jan/2018 08:39:38] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[27/Jan/2018 08:39:38] "GET /static/js/jquery.min.js HTTP/1.1" 200 95786
[27/Jan/2018 08:39:38] "GET /static/js/ie10-viewport-bug-workaround.js HTTP/1.1" 200 694
[27/Jan/2018 08:39:38] "GET /static/img/MobSF_Logo_small.png HTTP/1.1" 200 32351
[27/Jan/2018 08:39:38] "GET /static/favicon.ico HTTP/1.1" 200 370070
[27/Jan/2018 08:39:38] "GET /static/fonts/glyphicons-halflings-regular.woff HTTP/1.1" 200 23320
[INFO] MIME Type: application/vnd.android.package-archive FILE: Sample.apk

[INFO] Performing Static Analysis of Android APK
[27/Jan/2018 08:40:01] "POST /upload/ HTTP/1.1" 200 133
[INFO] Starting Analysis on : Sample.apk
[INFO] Generating Hashes
[INFO] Unzipping
[INFO] Getting Hardcoded Certificates/Keystores
[INFO] APK Extracted
[INFO] Getting Manifest from Binary
[INFO] AXML -> XML
[INFO] Parsing AndroidManifest.xml
[INFO] Fetching icon path
W/ziparchive( 2876): Zip: 2048 extraneous bytes at the end of the central directory
W/zipro   ( 2876): Error opening archive /root/Desktop/fata/Mobile-Security-Framework-MobSF/uploads/50db3dd5ca87ab02fca40570c481a329/50db3dd5ca87ab02fca40570c481a329.apk: Invalid file
ERROR: dump failed because no AndroidManifest.xml found

[2018-01-27 08:40:01]
[ERROR] Get icon function (/root/Desktop/fata/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/icon_analysis.py, LINE 88 "aapt_output = subprocess.check_output(args, env=env)"): Command '['/root/Desktop/fata/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/aapt/linux/aapt', 'd', 'badging', u'/root/Desktop/fata/Mobile-Security-Framework-MobSF/uploads/50db3dd5ca87ab02fca40570c481a329/50db3dd5ca87ab02fca40570c481a329.apk']' returned non-zero exit status 1
[INFO] Extracting Manifest Data
[INFO] Manifest Analysis Started
[INFO] Static Android Binary Analysis Started
[INFO] Static Android Resourse Analysis Started
[INFO] Reading Code Signing Certificate
[INFO] DEX -> JAR
[INFO] Using JAR converter - dex2jar
dex2jar /root/Desktop/fata/Mobile-Security-Framework-MobSF/uploads/50db3dd5ca87ab02fca40570c481a329/classes.dex -> /root/Desktop/fata/Mobile-Security-Framework-MobSF/uploads/50db3dd5ca87ab02fca40570c481a329/classes.jar
[INFO] DEX -> SMALI
[INFO] JAR -> JAVA
Processing /root/Desktop/fata/Mobile-Security-Framework-MobSF/uploads/50db3dd5ca87ab02fca40570c481a329/classes.jar (use silent to silence)
Processing com.comforters.trashy.DeconvolveApplication
Processing com.comforters.trashy.Disincentives
Processing com.comforters.trashy.xi
Processing com.pdfjet.BarCode
Processing com.pdfjet.Font
Processing com.pdfjet.OpenTypeFont
Processing com.pdfjet.PNGImage
[INFO] Static Android Code Analysis Started
[INFO] Code Analysis Started on - /root/Desktop/fata/Mobile-Security-Framework-MobSF/uploads/50db3dd5ca87ab02fca40570c481a329/java_source/
[INFO] Performing Malware Check on extracted Domains

[INFO] Updating Malware Database....
[INFO] Finished Code Analysis, Email and URL Extraction

[INFO] Generating Java and Smali Downloads
[INFO] Generating Downloads
[INFO] Zipping
[INFO] Zipping
[INFO] Extracting Strings from APK
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:54)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:540)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:76)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:68)
	at strings.StringsXML.run(StringsXML.java:84)
	at strings.StringsXML.main(StringsXML.java:151)
Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000000
	at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:56)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:219)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:179)
	at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:167)
	at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:133)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:108)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:81)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:49)
	... 5 more
```

## CONTENTS OF LOG FILES

```
[2018-01-27 08:40:01]
[ERROR] Get icon function (/root/Desktop/fata/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/icon_analysis.py, LINE 88 "aapt_output = subprocess.check_output(args, env=env)"): Command '['/root/Desktop/fata/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/aapt/linux/aapt', 'd', 'badging', u'/root/Desktop/fata/Mobile-Security-Framework-MobSF/uploads/50db3dd5ca87ab02fca40570c481a329/50db3dd5ca87ab02fca40570c481a329.apk']' returned non-zero exit status 1
```

**Comment by ajinabraham** [comment]
Please share the APK in our slack group via private message or by mail

**Comment by alimp5** [comment]
@ajinabraham 
Here you are:
https://ufile.io/a08xm

**Comment by ajinabraham** [comment]
@alimp5 I just verified the issue. This looks like an issue with aapt in unzipping the binary and results in failure. @matandobr Can you look into this. (Caution: This is android locker malware.)

@matandobr Do we have other ways to get the icon path. Now that we have apktool, does that add any advantage?

**Comment by ajinabraham** [comment]
If we don't have a reliable solution, we will consider this as a third party bug and close it.

**Comment by matandobr** [comment]
"The free hosting period for this file has now expired, only premium users can download it."
@alimp5 Could you upload it once again or send it to me directly?

**Comment by ajinabraham** [comment]
@alimp5 do mind sharing the APK once more?

**Comment by ajinabraham** [comment]
Alright, that's fine. Thanks.

**Comment by ajinabraham** [comment]
Fixed in python3 branch
