### ISSUE TITLE
[Suggest] ImportError: bad magic number in 'MobSF.migrations': b'\x03\xf3\r\n'

### ISSUE THREAD

**Issue by aancw** [MobSF/Mobile-Security-Framework-MobSF#577]
## EXPLANATION OF THE ISSUE

When i'm trying to update from old version with `git pull` and migrating the project with `python manage.py migrate`. It will produce an error `ImportError: bad magic number in 'MobSF.migrations': b'\x03\xf3\r\n'`

## STEPS TO REPRODUCE THE ISSUE

```
1. Git pull from old version
2. Migrate project with python manage.py migrate
```

## CONSOLE OUTPUT

```
↳ python manage.py migrate

  __  __       _    ____  _____         _   ___  
 |  \/  | ___ | |__/ ___||  ___| __   _/ | / _ \ 
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / || | | |
 | |  | | (_) | |_) |__) |  _|    \ V /| || |_| |
 |_|  |_|\___/|_.__/____/|_|       \_/ |_(_)___/ 
        



Mobile Security Framework v1.0 Beta

REST API Key: afbb4accbf0fce6c7599021ecdccab85090cea8ba622b2118231c160f42e7b98
OS: Linux
Platform: Linux-4.15.4-1-ARCH-x86_64-with-arch-Arch-Linux
Dist: ('arch', 'Arch', 'Linux')

[INFO] Finding JDK Location in Linux/MAC....

[INFO] JDK 1.7 or above is available

[INFO] Checking for Update.

[INFO] No updates available.
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 79, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/lib/python3.6/site-packages/django/db/migrations/loader.py", line 200, in build_graph
    self.load_disk()
  File "/usr/lib/python3.6/site-packages/django/db/migrations/loader.py", line 77, in load_disk
    module = import_module(module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 888, in get_code
  File "<frozen importlib._bootstrap_external>", line 455, in _validate_bytecode_header
ImportError: bad magic number in 'MobSF.migrations': b'\x03\xf3\r\n'
```
## Remediation

Delete all *.pyc file:
```
find . -name \*.pyc -delete
```
## Suggestion

Include all *.pyc file in gitignore. I'm listing all *.pyc file:

```
↳ find . -name \*.pyc
./APITester/migrations/__init__.pyc
./APITester/migrations/0001_initial.pyc
./APITester/migrations/0002_auto_20161130_1207.pyc
./APITester/models.pyc
./APITester/__init__.pyc
./APITester/views.pyc
./MalwareAnalyzer-lama/models.pyc
./MalwareAnalyzer-lama/__init__.pyc
./MalwareAnalyzer-lama/views.pyc
./MobSF/utils.pyc
./MobSF/forms.pyc
./MobSF/migrations/__init__.pyc
./MobSF/migrations/0001_initial.pyc
./MobSF/migrations/0002_auto_20161130_1207.pyc
./MobSF/models.pyc
./MobSF/wsgi.pyc
./MobSF/rest_api.pyc
./MobSF/__init__.pyc
./MobSF/settings.pyc
./MobSF/views.pyc
./MobSF/urls.pyc
./MobSF/__pycache__/__init__.cpython-36.pyc
./MobSF/__pycache__/models.cpython-36.pyc
./MobSF/__pycache__/urls.cpython-36.pyc
./MobSF/__pycache__/settings.cpython-36.pyc
./MobSF/__pycache__/rest_api.cpython-36.pyc
./MobSF/__pycache__/forms.cpython-36.pyc
./MobSF/__pycache__/utils.cpython-36.pyc
./MobSF/__pycache__/views.cpython-36.pyc
./install/__init__.pyc
./install/windows/setup.pyc
./install/windows/__init__.pyc
./install/windows/__pycache__/__init__.cpython-36.pyc
./install/windows/__pycache__/setup.cpython-36.pyc
./install/__pycache__/__init__.cpython-36.pyc
./MalwareAnalyzer/__pycache__/__init__.cpython-36.pyc
./MalwareAnalyzer/__pycache__/models.cpython-36.pyc
./MalwareAnalyzer/__pycache__/views.cpython-36.pyc
./StaticAnalyzer/views/shared_func.pyc
./StaticAnalyzer/views/windows.pyc
./StaticAnalyzer/views/__init__.pyc
./StaticAnalyzer/views/android/binary_analysis.pyc
./StaticAnalyzer/views/android/view_source.pyc
./StaticAnalyzer/views/android/icon_analysis.pyc
./StaticAnalyzer/views/android/converter.pyc
./StaticAnalyzer/views/android/VirusTotal.pyc
./StaticAnalyzer/views/android/dvm_permissions.pyc
./StaticAnalyzer/views/android/static_analyzer.pyc
./StaticAnalyzer/views/android/strings.pyc
./StaticAnalyzer/views/android/__init__.pyc
./StaticAnalyzer/views/android/android_apis.pyc
./StaticAnalyzer/views/android/manifest_view.pyc
./StaticAnalyzer/views/android/find.pyc
./StaticAnalyzer/views/android/code_analysis.pyc
./StaticAnalyzer/views/android/smali.pyc
./StaticAnalyzer/views/android/android_rules.pyc
./StaticAnalyzer/views/android/win_fixes.pyc
./StaticAnalyzer/views/android/cert_analysis.pyc
./StaticAnalyzer/views/android/manifest_analysis.pyc
./StaticAnalyzer/views/android/java.pyc
./StaticAnalyzer/views/android/__pycache__/static_analyzer.cpython-36.pyc
./StaticAnalyzer/views/android/__pycache__/java.cpython-36.pyc
./StaticAnalyzer/views/android/__pycache__/android_apis.cpython-36.pyc
./StaticAnalyzer/views/android/__pycache__/converter.cpython-36.pyc
./StaticAnalyzer/views/android/__pycache__/binary_analysis.cpython-36.pyc
./StaticAnalyzer/views/android/__pycache__/__init__.cpython-36.pyc
./StaticAnalyzer/views/android/__pycache__/manifest_view.cpython-36.pyc
./StaticAnalyzer/views/android/__pycache__/view_source.cpython-36.pyc
./StaticAnalyzer/views/android/__pycache__/android_rules.cpython-36.pyc
./StaticAnalyzer/views/android/__pycache__/cert_analysis.cpython-36.pyc
./StaticAnalyzer/views/android/__pycache__/code_analysis.cpython-36.pyc
./StaticAnalyzer/views/android/__pycache__/find.cpython-36.pyc
./StaticAnalyzer/views/android/__pycache__/manifest_analysis.cpython-36.pyc
./StaticAnalyzer/views/android/__pycache__/VirusTotal.cpython-36.pyc
./StaticAnalyzer/views/android/__pycache__/icon_analysis.cpython-36.pyc
./StaticAnalyzer/views/android/__pycache__/win_fixes.cpython-36.pyc
./StaticAnalyzer/views/android/__pycache__/strings.cpython-36.pyc
./StaticAnalyzer/views/android/__pycache__/dvm_permissions.cpython-36.pyc
./StaticAnalyzer/views/android/__pycache__/db_interaction.cpython-36.pyc
./StaticAnalyzer/views/android/__pycache__/smali.cpython-36.pyc
./StaticAnalyzer/views/android/db_interaction.pyc
./StaticAnalyzer/views/ios/binary_analysis.pyc
./StaticAnalyzer/views/ios/ios_apis.pyc
./StaticAnalyzer/views/ios/plist_analysis.pyc
./StaticAnalyzer/views/ios/static_analyzer.pyc
./StaticAnalyzer/views/ios/__init__.pyc
./StaticAnalyzer/views/ios/code_analysis.pyc
./StaticAnalyzer/views/ios/ios_rules.pyc
./StaticAnalyzer/views/ios/__pycache__/static_analyzer.cpython-36.pyc
./StaticAnalyzer/views/ios/__pycache__/binary_analysis.cpython-36.pyc
./StaticAnalyzer/views/ios/__pycache__/__init__.cpython-36.pyc
./StaticAnalyzer/views/ios/__pycache__/ios_rules.cpython-36.pyc
./StaticAnalyzer/views/ios/__pycache__/code_analysis.cpython-36.pyc
./StaticAnalyzer/views/ios/__pycache__/ios_apis.cpython-36.pyc
./StaticAnalyzer/views/ios/__pycache__/plist_analysis.cpython-36.pyc
./StaticAnalyzer/views/ios/__pycache__/db_interaction.cpython-36.pyc
./StaticAnalyzer/views/ios/db_interaction.pyc
./StaticAnalyzer/views/__pycache__/__init__.cpython-36.pyc
./StaticAnalyzer/views/__pycache__/windows.cpython-36.pyc
./StaticAnalyzer/views/__pycache__/shared_func.cpython-36.pyc
./StaticAnalyzer/migrations/__init__.pyc
./StaticAnalyzer/migrations/0001_initial.pyc
./StaticAnalyzer/migrations/__pycache__/__init__.cpython-36.pyc
./StaticAnalyzer/migrations/__pycache__/0001_initial.cpython-36.pyc
./StaticAnalyzer/tools/strings.pyc
./StaticAnalyzer/tools/__init__.pyc
./StaticAnalyzer/tools/__pycache__/__init__.cpython-36.pyc
./StaticAnalyzer/tools/__pycache__/strings.cpython-36.pyc
./StaticAnalyzer/tests.pyc
./StaticAnalyzer/models.pyc
./StaticAnalyzer/__init__.pyc
./StaticAnalyzer/__pycache__/__init__.cpython-36.pyc
./StaticAnalyzer/__pycache__/models.cpython-36.pyc
./StaticAnalyzer/__pycache__/tests.cpython-36.pyc
./DynamicAnalyzer/pyWebProxy/gen_cert.pyc
./DynamicAnalyzer/pyWebProxy/__init__.pyc
./DynamicAnalyzer/pyWebProxy/socket_wrapper.pyc
./DynamicAnalyzer/pyWebProxy/pywebproxy.pyc
./DynamicAnalyzer/views/__init__.pyc
./DynamicAnalyzer/views/android/android_dyn_shared.pyc
./DynamicAnalyzer/views/android/android_avd.pyc
./DynamicAnalyzer/views/android/android_dynamic.pyc
./DynamicAnalyzer/views/android/__init__.pyc
./DynamicAnalyzer/views/android/android_virtualbox_vm.pyc
./DynamicAnalyzer/views/android/__pycache__/__init__.cpython-36.pyc
./DynamicAnalyzer/views/android/__pycache__/dynamic.cpython-36.pyc
./DynamicAnalyzer/views/android/__pycache__/shared.cpython-36.pyc
./DynamicAnalyzer/views/android/__pycache__/analysis.cpython-36.pyc
./DynamicAnalyzer/views/android/__pycache__/virtualbox_vm.cpython-36.pyc
./DynamicAnalyzer/views/android/__pycache__/avd.cpython-36.pyc
./DynamicAnalyzer/views/android_standalone.pyc
./DynamicAnalyzer/views/__pycache__/__init__.cpython-36.pyc
./DynamicAnalyzer/tools/__pycache__/webproxy.cpython-36.pyc
./DynamicAnalyzer/tools/__pycache__/__init__.cpython-36.pyc
./DynamicAnalyzer/models.pyc
./DynamicAnalyzer/__init__.pyc
./DynamicAnalyzer/__pycache__/__init__.cpython-36.pyc
./DynamicAnalyzer/__pycache__/models.cpython-36.pyc
```
## Success Output
```
↳ python manage.py migrate   

  __  __       _    ____  _____         _   ___  
 |  \/  | ___ | |__/ ___||  ___| __   _/ | / _ \ 
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / || | | |
 | |  | | (_) | |_) |__) |  _|    \ V /| || |_| |
 |_|  |_|\___/|_.__/____/|_|       \_/ |_(_)___/ 
        



Mobile Security Framework v1.0 Beta

REST API Key: afbb4accbf0fce6c7599021ecdccab85090cea8ba622b2118231c160f42e7b98
OS: Linux
Platform: Linux-4.15.4-1-ARCH-x86_64-with-arch-Arch-Linux
Dist: ('arch', 'Arch', 'Linux')

[INFO] Finding JDK Location in Linux/MAC....

[INFO] JDK 1.7 or above is available

[INFO] Checking for Update.

[INFO] No updates available.
Operations to perform:
  Apply all migrations: StaticAnalyzer, auth, contenttypes, sessions
Running migrations:
  Applying auth.0009_alter_user_last_name_max_length... OK
```

CMIIW

**Comment by ajinabraham** [comment]
This probably happened because you upgraded from python 2.7 to python3 version of MobSF without cleaning the pyc files created by old version . We don't have `*.pyc` in our git repo.
