### ISSUE TITLE
ImportError: cannot import name 'settings'

### ISSUE THREAD

**Issue by jabberwock** [MobSF/Mobile-Security-Framework-MobSF#580]
Using Python 3.4.8 via pyenv.

Error while running manage.py:

ImportError: cannot import name 'settings'

$ python manage.py runserver
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/XXXXXXXX/.pyenv/versions/3.4.8/lib/python3.4/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/XXXXXXXX/.pyenv/versions/3.4.8/lib/python3.4/site-packages/django/core/management/__init__.py", line 317, in execute
    settings.INSTALLED_APPS
  File "/Users/XXXXXXXX/.pyenv/versions/3.4.8/lib/python3.4/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/Users/XXXXXXXX/.pyenv/versions/3.4.8/lib/python3.4/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/XXXXXXXX/.pyenv/versions/3.4.8/lib/python3.4/site-packages/django/conf/__init__.py", line 106, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/XXXXXXXX/.pyenv/versions/3.4.8/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/XXXXXXXX/Development/Mobile-Security-Framework-MobSF/MobSF/settings.py", line 13, in <module>
    from MobSF import utils
  File "/Users/XXXXXXXX/Development/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 20, in <module>
    from . import settings
ImportError: cannot import name 'settings'

**Comment by ajinabraham** [comment]
Looks like pyenv is causing issues with relative imports.
Try virtualenv or try replacing `from . import settings` with `from MobSF import settings` in `/MobSF/utils.py`

**Comment by jabberwock** [comment]
I obliterated pyenv and instead used HomeBrew's python3 package and all seems to be okay in the world. Thank you!

**Comment by venkatas** [comment]
replaced from . import settings with from MobSF import settings in /MobSF/utils.py but no joy

**Comment by ajinabraham** [comment]
@venkatas Are you using pyenv. It might be causing the trouble.

**Comment by niansa** [comment]
@venkatas sudo apt install virtualenv solved the problem for me. sudo pip3 install virtualenv should also work.
