### ISSUE TITLE
unsupported operand type(s) for -=: 'Retry' and 'int'

### ISSUE THREAD

**Issue by nice9uy** [MobSF/Mobile-Security-Framework-MobSF#583]
Hi..

I have a problem with installation of MobSf.

this are my step installation MobSf

1. git clone https://github.com/MobSF/Mobile-Security-Framework-MobSF.git
2. cd Mobile-Security-Framework-MobSF
3. python3 -m pip install -r requirements.txt --user

I got an error like this

root@mobsf:/home/mobsf/Mobile-Security-Framework-MobSF# python3 -m pip install -r requirements.txt --user
Collecting git+https://github.com/MobSF/CapFuzz.git (from -r requirements.txt (line 7))
  Cloning https://github.com/MobSF/CapFuzz.git to /tmp/pip-ceo1_6st-build
Collecting Django==2.0.3 (from -r requirements.txt (line 1))
Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connection.py", line 138, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/connection.py", line 75, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 837, in _validate_conn
    conn.connect()
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connection.py", line 281, in connect
    conn = self._new_conn()
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connection.py", line 147, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fbcb2b800b8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'

**Comment by ajinabraham** [comment]
You have a network problem
```
ocket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

```

**Comment by jvasanthbalaji** [comment]
hi please,
Give me solution for the Issue,Is there any problem with the network.

C:\Python27\Scripts>python2.7 -m pip install -r requirements.txt --user
Collecting git+https://github.com/MobSF/CapFuzz.git (from -r requirements.txt (l
ine 7))
  Cloning https://github.com/MobSF/CapFuzz.git to c:\users\z020310\appdata\local
\temp\pip-3ofpro-build
fatal: UriFormatException encountered.
   queryUrl
Collecting Django==2.0.5 (from -r requirements.txt (line 1))
Exception:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Python27\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\Python27\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Python27\lib\site-packages\pip\req\req_set.py", line 380, in prepare_
files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Python27\lib\site-packages\pip\req\req_set.py", line 554, in _prepare
_file
    require_hashes
  File "C:\Python27\lib\site-packages\pip\req\req_install.py", line 278, in popu
late_link
    self.link = finder.find_requirement(self, upgrade)
  File "C:\Python27\lib\site-packages\pip\index.py", line 465, in find_requireme
nt
    all_candidates = self.find_all_candidates(req.name)
  File "C:\Python27\lib\site-packages\pip\index.py", line 423, in find_all_candi
dates
    for page in self._get_pages(url_locations, project_name):
  File "C:\Python27\lib\site-packages\pip\index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "C:\Python27\lib\site-packages\pip\index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "C:\Python27\lib\site-packages\pip\index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "C:\Python27\lib\site-packages\pip\_vendor\requests\sessions.py", line 48
8, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\pip\download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "C:\Python27\lib\site-packages\pip\_vendor\requests\sessions.py", line 47
5, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\pip\_vendor\requests\sessions.py", line 59
6, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line
 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "C:\Python27\lib\site-packages\pip\_vendor\requests\adapters.py", line 39
0, in send
    conn = self.get_connection(request.url, proxies)
  File "C:\Python27\lib\site-packages\pip\_vendor\requests\adapters.py", line 29
0, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "C:\Python27\lib\site-packages\pip\_vendor\requests\adapters.py", line 19
4, in proxy_manager_for
    **proxy_kwargs)
  File "C:\Python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\pool
manager.py", line 367, in proxy_from_url
    return ProxyManager(proxy_url=url, **kw)
  File "C:\Python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\pool
manager.py", line 312, in __init__
    proxy = parse_url(proxy_url)
  File "C:\Python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\util
\url.py", line 189, in parse_url
    raise LocationParseError(url)
LocationParseError: Failed to parse: 10.244.3.249:3128

**Comment by ajinabraham** [comment]
One should read documentation clearly before opening issues like this. It's clearly defined we need python 3
