### ISSUE TITLE
ERROR in Setting up Dynamic Analysis Environment 

### ISSUE THREAD

**Issue by FaezehM** [MobSF/Mobile-Security-Framework-MobSF#604]
[INFO] Refreshing MobSF VM
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%

[INFO] VM Closed
Restoring snapshot 'SAVED_STATE' (426b04e2-ca22-4f5a-9f5e-bf8cd6ae6fd7)
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%

[INFO] VM Restore Snapshot
Waiting for VM "8de9c5e6-9a9b-400e-9d43-dcaa75c41e66" to power on...
VM "8de9c5e6-9a9b-400e-9d43-dcaa75c41e66" has been successfully started.

[INFO] VM Starting
[23/Apr/2018 11:41:03] "POST /DynamicAnalyzer/ HTTP/1.1" 200 32355
[23/Apr/2018 11:41:03] "GET /download/screen/screen.png HTTP/1.1" 302 0
[23/Apr/2018 11:41:03] "GET /static/css/devices.min.css HTTP/1.1" 200 8192
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\wsgiref\handlers.py", line 332, in send_headers
    self.send_preamble()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\wsgiref\handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\socketserver.py", line 775, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
[23/Apr/2018 11:41:03] "GET /static/css/devices.min.css HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 54889)
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\wsgiref\handlers.py", line 332, in send_headers
    self.send_preamble()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\wsgiref\handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\socketserver.py", line 775, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\wsgiref\handlers.py", line 141, in run
    self.handle_error()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\servers\basehttp.py", line 86, in handle_error
    super().handle_error()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\wsgiref\handlers.py", line 368, in handle_error
    self.finish_response()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\wsgiref\handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\wsgiref\handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\socketserver.py", line 639, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\socketserver.py", line 696, in __init__
    self.handle()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\servers\basehttp.py", line 154, in handle
    handler.run(self.server.get_app())
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\wsgiref\handlers.py", line 144, in run
    self.close()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\wsgiref\simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
[23/Apr/2018 11:41:03] "GET /error/ HTTP/1.1" 200 4749
[23/Apr/2018 11:41:03] "GET /static/img/loading.jpg HTTP/1.1" 200 3221

[INFO] Setting up Dynamic Analysis Environment

[2018-04-23 11:41:29]
[ERROR] Setting up Dynamic Analysis Environment (D:\MobSF2018.3\DynamicAnalyzer\views\android\dynamic.py, LINE 158 "start_proxy(settings.PORT, package)"): [WinError 2] The system cannot find the file specified
[23/Apr/2018 11:41:29] "POST /GetEnv/ HTTP/1.1" 302 0
[23/Apr/2018 11:41:29] "GET /error/ HTTP/1.1" 200 4749

**Comment by ajinabraham** [comment]
You are not running from MobSF root directory. Add python3 and libs to path. MobSF can't find capfuzz. Follow the documentation as it is.

**Comment by luolin2611** [comment]
[05/May/2018 07:31:21] "GET /error/ HTTP/1.1" 200 4749
[05/May/2018 07:31:22] "GET /download/screen/screen.png?1525505482910 HTTP/1.1" 302 0
[05/May/2018 07:31:22] "GET /error/ HTTP/1.1" 200 4749
[05/May/2018 07:31:24] "GET /download/screen/screen.png?1525505483925 HTTP/1.1" 302 0
[05/May/2018 07:31:24] "GET /error/ HTTP/1.1" 200 4749
[05/May/2018 07:31:25] "GET /download/screen/screen.png?1525505485007 HTTP/1.1" 302 0
[05/May/2018 07:31:25] "GET /error/ HTTP/1.1" 200 4749
[05/May/2018 07:31:26] "GET /download/screen/screen.png?1525505486015 HTTP/1.1" 302 0
[05/May/2018 07:31:26] "GET /error/ HTTP/1.1" 200 4749
...........


Hello, I've been walking all the time. How to solve it

**Comment by kishore-kt** [comment]
Getting the above error for me too..... 

[INFO] 31/Jul/2019 16:46:44 - Dynamic Analysis Started
[INFO] 31/Jul/2019 16:46:46 - MobSF Dynamic Analysis on Real Android Device
[INFO] 31/Jul/2019 16:46:46 - "POST /DynamicAnalyzer/ HTTP/1.1" 200 32526
[ERROR] 31/Jul/2019 16:46:46 - Error Downloading File screen/screen.png
[ERROR] 31/Jul/2019 16:46:46 - Internal Server Error: /download/screen/screen.png
[ERROR] 31/Jul/2019 16:46:46 - "GET /download/screen/screen.png HTTP/1.1" 500 4831
