### ISSUE TITLE
Dynamic Analysis Result errors 

### ISSUE THREAD

**Issue by ghub101** [MobSF/Mobile-Security-Framework-MobSF#619]
## EXPLANATION OF THE ISSUE

The results for all API Monitor items are not captured in the report.

1.) The Report runs to completion, however there's no information  for  File IO, Networks, Binder Calls, Crypto etc.. All other sections of the report contains test results

2.) During the dynamic analysis process errors are displayed on the console. 

MobSF is using the  pre-built docker image on Ubuntu.

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step
2. This is the second step
3. Further steps, etc.
```

## CONSOLE OUTPUT

[INFO] Dynamic Analysis Started

[INFO] Refreshing MobSF VM
[ERROR] VirtualBox not found, Manually set VBOXMANAGE_BINARY in settings.py

[2018-05-01 20:19:16]
[ERROR] Refreshing MobSF VM (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/virtualbox_vm.py, LINE 14 "subprocess.call(args)"): expected str, bytes or os.PathLike object, not NoneType
[01/May/2018 20:19:16] "POST /DynamicAnalyzer/ HTTP/1.1" 200 32414
[01/May/2018 20:19:17] "GET /static/js/jquery.min.js HTTP/1.1" 200 16384
[01/May/2018 20:19:17] "GET /static/css/devices.min.css HTTP/1.1" 200 44241
[01/May/2018 20:19:17] "GET /download/screen/screen.png HTTP/1.1" 302 0
[01/May/2018 20:19:17] "GET /error/ HTTP/1.1" 200 4749
[01/May/2018 20:19:17] "GET /static/img/loading.jpg HTTP/1.1" 200 3221

[INFO] Setting up Dynamic Analysis Environment

[INFO] Connecting to VM/Device
* server not running *
* daemon not running. starting it now at tcp:5037 *
* daemon started successfully *
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 972, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 863, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (cryptography 2.2.2 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('cryptography<2.2,>=2.1.4'), {'mitmproxy'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/capfuzz", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3049, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3033, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3062, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 660, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 673, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 858, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cryptography<2.2,>=2.1.4' distribution was not found and is required by mitmproxy

[INFO] ADB Started

[INFO] Waiting for 5 seconds...

[INFO] Connecting to VM/Device

[INFO] Mounting
su: invalid option -- o

Usage: su [options] [--] [-] [LOGIN] [--] [args...]

Options:
  --daemon                      start the su daemon agent
  -c, --command COMMAND         pass COMMAND to the invoked shell
  -h, --help                    display this help message and exit
  -, -l, --login                pretend the shell to be a login shell
  -m, -p,
  --preserve-environment        do not change environment variables
  -s, --shell SHELL             use SHELL instead of the default /system/bin/sh
  -u                            display the multiuser mode and exit
  -v, --version                 display version number and exit
  -V                            display version code and exit,
                                this is used almost exclusively by Superuser.apk

[INFO] Starting App for Dynamic Analysis

[INFO] Installing APK
/root/.MobSF/uploads/c65f3db5f1b43883990c27d19ff3bced/c65f3db5f1b43883990c27d19ff3bced.apk: 1 file pushed. 22.2 MB/s (5866659 bytes in 0.252s)
        pkg: /data/local/tmp/c65f3db5f1b43883990c27d19ff3bced.apk
Success

[INFO] Launching APK Main Activity
```
Paste the output generated at your console/terminal while scanning the mobile app.
The console log should contain the error or bug you are seeing
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

## CONTENTS OF LOG FILES

```
Paste the contents of logs/MobSF.log here
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

```
If you have issues with API Fuzzer,
Paste the contents of logs/webproxy.log here
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

**Comment by ajinabraham** [comment]
Have you read the documentation?

> MobSF is using the pre-built docker image on Ubuntu.

Dockerized MobSF doesn't support dynamic analysis?
