### ISSUE TITLE
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

### ISSUE THREAD

**Issue by mehrant95** [MobSF/Mobile-Security-Framework-MobSF#633]
I tried to install MobSF v1.0 beta on Ubuntu 14.04 LTS. Python 2.7 and 3.4 are installed by default. After reading the documentation, I found that I need to install python3.6 (as it's a static analysis requirement), so installed it using [this link](https://askubuntu.com/questions/865554/how-do-i-install-python-3-6-using-apt-get). Then I installed Oracle Java 8 and then ran this command:
```
python3.6 -m pip install -r requirements.txt --user
```
But it gives the following error:
```
root@ubuntu-VirtualBox:/home/ubuntu/mobsf_test/mobsf# python3.6 -m pip install -r requirements.txt --user
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 59, in <module>
    from pip.log import logger
  File "/usr/lib/python3/dist-packages/pip/log.py", line 9, in <module>
    import colorama, pkg_resources
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 1479, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
```
Also I have installed pip3 using `sudo apt-get install python3-pip`. Any idea what's going wrong?

**Comment by ajinabraham** [comment]
Your environment is broken. Try re-installing python3
Use pyenv or virtualenv. This is not a MobSF issue.
From V1. Everything in MobSF supports only python3
