### ISSUE TITLE
Dynamic Analyzer - Failed

### ISSUE THREAD

**Issue by yasharne** [MobSF/Mobile-Security-Framework-MobSF#654]
Hi
When I open `DynamicAnalysis` there is a `Failed` text next to Dynamic Analyzer as shown in the picture:
![image](https://user-images.githubusercontent.com/7656049/41870179-8cea5320-78d0-11e8-8f81-cd4024deca88.png)
After I press create environment Everything seems to be fine and after I press finish, I get the failed label again.:
![image](https://user-images.githubusercontent.com/7656049/41870613-c274aaf8-78d1-11e8-84c1-e7f493748f67.png)

 I don't know if there is a problem with my mobsf but I didn't get any result even with APKs which I know have a problem.

**Comment by yasharne** [comment]
I don't know if it is relevant, but I get this error when I upload the file:
```
Exception in thread "main" brut.androlib.AndrolibException: java.io.FileNotFoundException: /home/yashar/.local/share/apktool/framework/1.apk (No such file or directory)
	at brut.androlib.res.AndrolibResources.getFrameworkApk(AndrolibResources.java:775)
	at brut.androlib.res.AndrolibResources.loadFrameworkPkg(AndrolibResources.java:116)
	at brut.androlib.res.data.ResTable.getPackage(ResTable.java:84)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:67)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:63)
	at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:62)
	at brut.androlib.res.data.value.ResReferenceValue.referentIsNull(ResReferenceValue.java:73)
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:49)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:697)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:263)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
	at brut.apktool.Main.cmdDecode(Main.java:164)
	at brut.apktool.Main.main(Main.java:73)
Caused by: java.io.FileNotFoundException: /home/yashar/.local/share/apktool/framework/1.apk (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at brut.androlib.res.AndrolibResources.getFrameworkApk(AndrolibResources.java:771)
	... 13 more

[2018-06-25 19:45:58]
[ERROR]Getting Manifest file (/home/yashar/mobsf/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/manifest_analysis.py, LINE 1304 "subprocess.check_output(args)"): Command '['/usr/bin/java', '-jar', '/home/yashar/mobsf/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/apktool_2.3.3.jar', '--match-original', '-f', '-s', 'd', '/home/yashar/mobsf/Mobile-Security-Framework-MobSF/uploads/5c5eb14c8da1b161f9abfd15d59e19e6/5c5eb14c8da1b161f9abfd15d59e19e6.apk', '-o', '/home/yashar/mobsf/Mobile-Security-Framework-MobSF/uploads/5c5eb14c8da1b161f9abfd15d59e19e6/apktool_out']' returned non-zero exit status 1.

[2018-06-25 19:45:58]
[ERROR] Reading Manifest file (/home/yashar/mobsf/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/manifest_analysis.py, LINE 1259 "if isFileExists(manifest):"): stat: path should be string, bytes, os.PathLike or integer, not NoneType
[INFO] Parsing AndroidManifest.xml

[2018-06-25 19:45:58]
[ERROR] apktool failed to extract AndroidManifest.xml or parsing failed (/home/yashar/mobsf/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/manifest_analysis.py, LINE 28 "manifest = minidom.parseString(dat)"): a bytes-like object is required, not 'NoneType'
[WARNING] Using Fake XML to continue the Analysis
```
But I don't get any errors as I press `Start dynamic Analysis`

**Comment by ajinabraham** [comment]
Looks like APKtool is failing. Can you share the apk that you are trying to analyse?

**Comment by yasharne** [comment]
Sure, Its G G smart packing list I've downloaded from [here](https://apkpure.com/g-g-smart-packing-list-free/com.wizgenxsoft.GaGSmartPackingListnewfree/download/7-APK)

**Comment by ajinabraham** [comment]
The static analysis of G G Smart Packing works fine at my end. Looks like it's failing for you. Make sure you are using Oracle JDK 1.7 or above and the latest MobSF from master repository.

**Comment by zseha** [comment]
when apktool cant save generated files there, files will be saved in /tmp. look console output while static analysis is running

**Comment by yasharne** [comment]
I figured it out. Installing `apktool` from repositories solved the problem. I double checked the documents for the installation and didn't see apktool as the required dependency, so probably the local apktool (if any) caused the problem.
