### ISSUE TITLE
brotlipy unable to install

### ISSUE THREAD

**Issue by balramrexwal** [MobSF/Mobile-Security-Framework-MobSF#658]
I m installing it in mac.
(venv) Balrams-MacBook-Air:MobSF balramrexwal$ pwd
/Users/balramrexwal/MobSF
(venv) Balrams-MacBook-Air:MobSF balramrexwal$ which python
/Users/balramrexwal/venv/bin/python
(venv) Balrams-MacBook-Air:MobSF balramrexwal$ which python3
/Library/Frameworks/Python.framework/Versions/3.7/bin/python3

while running either 
`pip3 install requirements.txt or python3 manage.py runserver`
it always fails to this error
`Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/s0/361b42n937j2bymn6frk6m6h0000gn/T/pip-install-g6qvp828/brotlipy/`

**also tryied to install it same error**

`$ pip3 install brotlipy==0.7.0
Collecting brotlipy==0.7.0
  Using cached https://files.pythonhosted.org/packages/d9/91/bc79b88590e4f662bd40a55a2b6beb0f15da4726732efec5aa5a3763d856/brotlipy-0.7.0.tar.gz
    Complete output from command python setup.py egg_info:
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
    zip_safe flag not set; analyzing archive contents...
    pycparser.ply.__pycache__.lex.cpython-37: module references __file__
    pycparser.ply.__pycache__.lex.cpython-37: module MAY be using inspect.getsourcefile
    pycparser.ply.__pycache__.yacc.cpython-37: module references __file__
    pycparser.ply.__pycache__.yacc.cpython-37: module MAY be using inspect.getsourcefile
    pycparser.ply.__pycache__.yacc.cpython-37: module MAY be using inspect.stack
    pycparser.ply.__pycache__.ygen.cpython-37: module references __file__
    
    Installed /private/var/folders/s0/361b42n937j2bymn6frk6m6h0000gn/T/pip-install-0gnzuini/brotlipy/.eggs/pycparser-2.18-py3.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/s0/361b42n937j2bymn6frk6m6h0000gn/T/pip-install-0gnzuini/brotlipy/setup.py", line 83, in <module>
        "Programming Language :: Python :: 3.6",
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/dist.py", line 372, in __init__
        _Distribution.__init__(self, attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/dist.py", line 528, in finalize_options
        ep.load()(self, ep.name, value)
      File "/private/var/folders/s0/361b42n937j2bymn6frk6m6h0000gn/T/pip-install-0gnzuini/brotlipy/.eggs/cffi-1.11.5-py3.7-macosx-10.9-x86_64.egg/cffi/setuptools_ext.py", line 204, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/private/var/folders/s0/361b42n937j2bymn6frk6m6h0000gn/T/pip-install-0gnzuini/brotlipy/.eggs/cffi-1.11.5-py3.7-macosx-10.9-x86_64.egg/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/private/var/folders/s0/361b42n937j2bymn6frk6m6h0000gn/T/pip-install-0gnzuini/brotlipy/.eggs/cffi-1.11.5-py3.7-macosx-10.9-x86_64.egg/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "src/brotli/build.py", line 5, in <module>
        ffi = FFI()
      File "/private/var/folders/s0/361b42n937j2bymn6frk6m6h0000gn/T/pip-install-0gnzuini/brotlipy/.eggs/cffi-1.11.5-py3.7-macosx-10.9-x86_64.egg/cffi/api.py", line 46, in __init__
        import _cffi_backend as backend
    ImportError: dlopen(/private/var/folders/s0/361b42n937j2bymn6frk6m6h0000gn/T/pip-install-0gnzuini/brotlipy/.eggs/cffi-1.11.5-py3.7-macosx-10.9-x86_64.egg/_cffi_backend.so, 2): Symbol not found: __PyThreadState_Current
      Referenced from: /private/var/folders/s0/361b42n937j2bymn6frk6m6h0000gn/T/pip-install-0gnzuini/brotlipy/.eggs/cffi-1.11.5-py3.7-macosx-10.9-x86_64.egg/_cffi_backend.so
      Expected in: flat namespace
     in /private/var/folders/s0/361b42n937j2bymn6frk6m6h0000gn/T/pip-install-0gnzuini/brotlipy/.eggs/cffi-1.11.5-py3.7-macosx-10.9-x86_64.egg/_cffi_backend.so
    
    ----------------------------------------
**`Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/s0/361b42n937j2bymn6frk6m6h0000gn/T/pip-install-0gnzuini/brotlipy/`**

**Comment by ajinabraham** [comment]
Sorry this is a bug tracker for MobSF and not Python or python dependencies
