### ISSUE TITLE
ModuleNotFoundError: No module named 'capfuzz'

### ISSUE THREAD

**Issue by netajisunil** [MobSF/Mobile-Security-Framework-MobSF#678]
When I try to start the MobSF in Windows 10 by giving the command like - python manage.py runserver
Getting the below error trace - Request you to help to rectify the below issue - 

c:\Users\sunil_m\Mobile-Security-Framework-MobSF>python manage.py runserver
Performing system checks...
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x000001C247E189D8>
Traceback (most recent call last):
  File "C:\Users\sunil_m\AppData\Roaming\Python\Python37\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\sunil_m\AppData\Roaming\Python\Python37\site-packages\django\core\management\commands\runserver.py", line 120, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\sunil_m\AppData\Roaming\Python\Python37\site-packages\django\core\management\base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\sunil_m\AppData\Roaming\Python\Python37\site-packages\django\core\management\base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\sunil_m\AppData\Roaming\Python\Python37\site-packages\django\core\checks\registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\sunil_m\AppData\Roaming\Python\Python37\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\sunil_m\AppData\Roaming\Python\Python37\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\sunil_m\AppData\Roaming\Python\Python37\site-packages\django\urls\resolvers.py", line 397, in check
    for pattern in self.url_patterns:
  File "C:\Users\sunil_m\AppData\Roaming\Python\Python37\site-packages\django\utils\functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\sunil_m\AppData\Roaming\Python\Python37\site-packages\django\urls\resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\sunil_m\AppData\Roaming\Python\Python37\site-packages\django\utils\functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\sunil_m\AppData\Roaming\Python\Python37\site-packages\django\urls\resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Program Files\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\Users\sunil_m\Mobile-Security-Framework-MobSF\MobSF\urls.py", line 4, in <module>
    import DynamicAnalyzer.views.android.dynamic
  File "c:\Users\sunil_m\Mobile-Security-Framework-MobSF\DynamicAnalyzer\views\android\dynamic.py", line 24, in <module>
    from DynamicAnalyzer.tools.webproxy import (
  File "c:\Users\sunil_m\Mobile-Security-Framework-MobSF\DynamicAnalyzer\tools\webproxy.py", line 6, in <module>
    import capfuzz as cp
ModuleNotFoundError: No module named 'capfuzz'

**Comment by ajinabraham** [comment]
Care to read docs??

**Comment by netajisunil** [comment]
I have done as per the steps provided in the document but no luck. Also, I tried to install the "capfuzz" but the error is getting like -
"C:\Users\username\Mobile-Security-Framework-MobSF>pip3 install capfuzz
Collecting capfuzz
  Could not find a version that satisfies the requirement capfuzz (from versions: )
No matching distribution found for capfuzz"
Please help me to resolve this issue.

**Comment by justincase101** [comment]
I also received this error in my macOS. What should be the command to install CapFuzz in that?

**Comment by ajinabraham** [comment]
from venv,
Run 
`pip install -r requirements.txt` or `pip3 install -r requirements.txt`
