### ISSUE TITLE
An Error just popped in!'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by Polibus** [MobSF/Mobile-Security-Framework-MobSF#727]
## EXPLANATION OF THE ISSUE

When I upload an apk an error pop in
`Don't Play Around. An Error just popped in!
Inappropriate argument type.

'NoneType' object does not support item assignment`
i Belive the console output gave all the information needed 
Thanks fot the patience, i show the other issues but nothing help me 
## CONSOLE OUTPUT

```
sudo docker run -it -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest
na[INFO] Loading User config from: /root/.MobSF/config.py
 
  __  __       _    ____  _____         _   ___  
 |  \/  | ___ | |__/ ___||  ___| __   _/ | / _ \ 
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / || | | |
 | |  | | (_) | |_) |__) |  _|    \ V /| || |_| |
 |_|  |_|\___/|_.__/____/|_|       \_/ |_(_)___/ 
        



Mobile Security Framework v1.0.1 Beta

REST API Key: eb7c0d705abac5083b6a650ddaea6fc5db4d484d985624ff650505fe3efa7f1a
OS: Linux
Platform: Linux-4.15.0-34-generic-x86_64-with-Ubuntu-18.04-bionic
Dist: ('Ubuntu', '18.04', 'bionic')
[INFO] Finding JDK Location in Linux/MAC....
[INFO] JDK 1.7 or above is available

[WARNING] Could not find VirtualBox path.
[INFO] MobSF Basic Environment Check
[INFO] Checking for Update.
[INFO] No updates available.
No changes detected
[INFO] Loading User config from: /root/.MobSF/config.py

  __  __       _    ____  _____         _   ___  
 |  \/  | ___ | |__/ ___||  ___| __   _/ | / _ \ 
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / || | | |
 | |  | | (_) | |_) |__) |  _|    \ V /| || |_| |
 |_|  |_|\___/|_.__/____/|_|       \_/ |_(_)___/ 
        



Mobile Security Framework v1.0.1 Beta

REST API Key: eb7c0d705abac5083b6a650ddaea6fc5db4d484d985624ff650505fe3efa7f1a
OS: Linux
Platform: Linux-4.15.0-34-generic-x86_64-with-Ubuntu-18.04-bionic
Dist: ('Ubuntu', '18.04', 'bionic')
[INFO] Finding JDK Location in Linux/MAC....
[INFO] JDK 1.7 or above is available

[WARNING] Could not find VirtualBox path.
[INFO] MobSF Basic Environment Check
[INFO] Checking for Update.
[INFO] No updates available.
No changes detected in app 'StaticAnalyzer'
[INFO] Loading User config from: /root/.MobSF/config.py

  __  __       _    ____  _____         _   ___  
 |  \/  | ___ | |__/ ___||  ___| __   _/ | / _ \ 
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / || | | |
 | |  | | (_) | |_) |__) |  _|    \ V /| || |_| |
 |_|  |_|\___/|_.__/____/|_|       \_/ |_(_)___/ 
        



Mobile Security Framework v1.0.1 Beta

REST API Key: eb7c0d705abac5083b6a650ddaea6fc5db4d484d985624ff650505fe3efa7f1a
OS: Linux
Platform: Linux-4.15.0-34-generic-x86_64-with-Ubuntu-18.04-bionic
Dist: ('Ubuntu', '18.04', 'bionic')
[INFO] Finding JDK Location in Linux/MAC....
[INFO] JDK 1.7 or above is available

[WARNING] Could not find VirtualBox path.
[INFO] MobSF Basic Environment Check
[INFO] Checking for Update.
[INFO] No updates available.
Operations to perform:
  Apply all migrations: StaticAnalyzer, auth, contenttypes, sessions
Running migrations:
  Applying StaticAnalyzer.0001_initial... OK
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying sessions.0001_initial... OK
[INFO] Loading User config from: /root/.MobSF/config.py
[INFO] Loading User config from: /root/.MobSF/config.py
Performing system checks...


  __  __       _    ____  _____         _   ___  
 |  \/  | ___ | |__/ ___||  ___| __   _/ | / _ \ 
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / || | | |
 | |  | | (_) | |_) |__) |  _|    \ V /| || |_| |
 |_|  |_|\___/|_.__/____/|_|       \_/ |_(_)___/ 
        



Mobile Security Framework v1.0.1 Beta

REST API Key: eb7c0d705abac5083b6a650ddaea6fc5db4d484d985624ff650505fe3efa7f1a
OS: Linux
Platform: Linux-4.15.0-34-generic-x86_64-with-Ubuntu-18.04-bionic
Dist: ('Ubuntu', '18.04', 'bionic')
[INFO] Finding JDK Location in Linux/MAC....
[INFO] JDK 1.7 or above is available

[WARNING] Could not find VirtualBox path.
[INFO] MobSF Basic Environment Check
[INFO] Checking for Update.
[INFO] No updates available.
System check identified no issues (0 silenced).
September 14, 2018 - 06:41:08
Django version 2.1.1, using settings 'MobSF.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[14/Sep/2018 06:42:48] "GET / HTTP/1.1" 200 7723
[INFO] MIME Type: application/vnd.android.package-archive FILE: itsme-1.32.0004.apk

[INFO] Performing Static Analysis of Android APK
[14/Sep/2018 06:43:02] "POST /upload/ HTTP/1.1" 200 142
[INFO] Starting Analysis on : itsme-1.32.0004.apk
[INFO] Generating Hashes
[INFO] Unzipping

[2018-09-14 06:43:02]
[ERROR] Unzipping Error (/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/shared_func.py, LINE 82 "zipptr.extract(fileinfo, str(ext_path))"): 'ascii' codec can't encode characters in position 54-56: ordinal not in range(128)

[INFO] Using the Default OS Unzip Utility.

[2018-09-14 06:43:02]
[ERROR] Unzipping Error (/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/shared_func.py, LINE 92 "['unzip', '-o', '-q', app_path, '-d', ext_path])"): [Errno 2] No such file or directory: 'unzip': 'unzip'
[INFO] Getting Hardcoded Certificates/Keystores

[2018-09-14 06:43:02]
[ERROR] Getting Hardcoded Certificates/Keystores (/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/cert_analysis.py, LINE 23 "for file_name in files:"): 'NoneType' object is not iterable
[INFO] APK Extracted
[INFO] Converting AXML to XML
W: Multiple types detected! anim ignored!
W: Multiple types detected! color ignored!
W: Multiple types detected! dimen ignored!
W: Multiple types detected! dimen ignored!
W: Multiple types detected! drawable ignored!
W: Multiple types detected! drawable ignored!
W: Multiple types detected! drawable ignored!
W: Multiple types detected! drawable ignored!
W: Multiple types detected! drawable ignored!
W: Multiple types detected! layout ignored!
W: Multiple types detected! string ignored!
W: Multiple types detected! string ignored!
W: Multiple types detected! style ignored!
W: Multiple types detected! style ignored!
W: Multiple types detected! style ignored!
W: Multiple types detected! style ignored!
S: WARNING: Could not write to (/root/.local/share/apktool/framework), using /tmp instead...
S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable
Exception in thread "main" java.lang.NullPointerException
	at brut.androlib.res.data.value.ResFlagsAttr$FlagItem.getValue(ResFlagsAttr.java:158)
	at brut.androlib.res.data.value.ResFlagsAttr.renderFlags(ResFlagsAttr.java:102)
	at brut.androlib.res.data.value.ResFlagsAttr.convertToResXmlFormat(ResFlagsAttr.java:73)
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:71)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:697)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:263)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
	at brut.apktool.Main.cmdDecode(Main.java:164)
	at brut.apktool.Main.main(Main.java:73)

[2018-09-14 06:43:05]
[ERROR]Getting Manifest file (/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/manifest_analysis.py, LINE 1312 "subprocess.check_output(args)"): Command '['/usr/bin/java', '-jar', '/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/apktool_2.3.4.jar', '--match-original', '-f', '-s', 'd', '/root/.MobSF/uploads/c0bcc0185fe7869d598617e1a35d4c99/c0bcc0185fe7869d598617e1a35d4c99.apk', '-o', '/root/.MobSF/uploads/c0bcc0185fe7869d598617e1a35d4c99/apktool_out']' returned non-zero exit status 1.

[2018-09-14 06:43:05]
[ERROR] Reading Manifest file (/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/manifest_analysis.py, LINE 1267 "if isFileExists(manifest):"): stat: path should be string, bytes, os.PathLike or integer, not NoneType
[INFO] Parsing AndroidManifest.xml

[2018-09-14 06:43:05]
[ERROR] apktool failed to extract AndroidManifest.xml or parsing failed (/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/manifest_analysis.py, LINE 28 "manifest = minidom.parseString(dat)"): a bytes-like object is required, not 'NoneType'
[WARNING] Using Fake XML to continue the Analysis
[INFO] Extracting Manifest Data
[INFO] Manifest Analysis Started
[INFO] Static Android Binary Analysis Started
[INFO] Static Android Resourse Analysis Started
[INFO] Reading Code Signing Certificate

[2018-09-14 06:43:05]
[ERROR] Reading Code Signing Certificate (/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/cert_analysis.py, LINE 79 "manidat = manifile.read()"): 'ascii' codec can't decode byte 0xe2 in position 117: ordinal not in range(128)
[INFO] APKiD - Package does not contains classes.dex file!
[INFO] DEX -> JAR
[INFO] Using JAR converter - dex2jar
[INFO] DEX -> SMALI
[INFO] JAR -> JAVA
[INFO] Static Android Code Analysis Started
[INFO] Code Analysis Started on - /root/.MobSF/uploads/c0bcc0185fe7869d598617e1a35d4c99/java_source/
[INFO] Performing Malware Check on extracted Domains
[INFO] Finished Code Analysis, Email and URL Extraction

[INFO] Generating Java and Smali Downloads
[INFO] Generating Downloads
[INFO] Zipping
[INFO] Zipping
[INFO] Extracting Strings from APK
Styles Offset given, but styleCount is zero.
Styles Offset given, but styleCount is zero.
Styles Offset given, but styleCount is zero.
Styles Offset given, but styleCount is zero.

[INFO] Connecting to Database

[INFO] Saving to Database

[2018-09-14 06:43:06]
[ERROR] Saving to DB (/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py, LINE 218 "CERT_INFO=cert_dic['cert_info'],"): 'NoneType' object is not subscriptable

[2018-09-14 06:43:06]
[ERROR] Rendering to Template (/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/db_interaction.py, LINE 105 "'certinfo': cert_dic['cert_info'],"): 'NoneType' object is not subscriptable
[ERROR] 'NoneType' object does not support item assignment
Internal Server Error: /StaticAnalyzer/
[14/Sep/2018 06:43:06] "GET /StaticAnalyzer/?name=itsme-1.32.0004.apk&type=apk&checksum=c0bcc0185fe7869d598617e1a35d4c99 HTTP/1.1" 500 4836

```

## CONTENTS OF LOG FILES

```
Paste the contents of logs/MobSF.log here
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

**Comment by ajinabraham** [comment]
Something strange with the APK, Please share the APK so that we can debug at our end

**Comment by Polibus** [comment]
Thanks for the answer ,but i cannot give You the apk ,is a bug bounty One

Il mar 18 set 2018, 07:51 Ajin Abraham <notifications@github.com> ha
scritto:

**Comment by ajinabraham** [comment]
We can't investigate further. Closing the report
