### ISSUE TITLE
dynamic analysis does not work on physical device

### ISSUE THREAD

**Issue by sali123** [MobSF/Mobile-Security-Framework-MobSF#772]
## EXPLANATION OF THE ISSUE

I am not able to run dyanamic analysis on windows 10. I am using physical mobile nexus 4 android 5.1.1
## STEPS TO REPRODUCE THE ISSUE
1- open any previously scanned APK file
2-  click "Dynamic Analysis"
3- click Create enviinment
```
1. This is the first step
2. This is the second step
3. Further steps, etc.
```

## CONSOLE OUTPUT

```
Paste the output generated at your console/terminal while scanning the mobile app.
The console log should contain the error or bug you are seeing
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```
Traceback (most recent call last):
  File "c:\Users\suzan\Mobile-Security-Framework-MobSF\venv\Scripts\capfuzz-script.py", line 11, in <module>
    load_entry_point('capfuzz==0.0.1', 'console_scripts', 'capfuzz')()
  File "c:\Users\suzan\Mobile-Security-Framework-MobSF\venv\lib\site-packages\pkg_resources\__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\Users\suzan\Mobile-Security-Framework-MobSF\venv\lib\site-packages\pkg_resources\__init__.py", line 2725, in load_entry_point
    return ep.load()
  File "c:\Users\suzan\Mobile-Security-Framework-MobSF\venv\lib\site-packages\pkg_resources\__init__.py", line 2343, in load
    return self.resolve()
  File "c:\Users\suzan\Mobile-Security-Framework-MobSF\venv\lib\site-packages\pkg_resources\__init__.py", line 2349, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\Users\suzan\Mobile-Security-Framework-MobSF\venv\lib\site-packages\capfuzz\__main__.py", line 12, in <module>
    from mitmproxy import (
  File "c:\Users\suzan\Mobile-Security-Framework-MobSF\venv\lib\site-packages\mitmproxy\options.py", line 5, in <module>
    from mitmproxy.net import tls
  File "c:\Users\suzan\Mobile-Security-Framework-MobSF\venv\lib\site-packages\mitmproxy\net\tls.py", line 13, in <module>
    from OpenSSL import SSL
  File "c:\Users\suzan\Mobile-Security-Framework-MobSF\venv\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "c:\Users\suzan\Mobile-Security-Framework-MobSF\venv\lib\site-packages\OpenSSL\crypto.py", line 16, in <module>
    from OpenSSL._util import (
  File "c:\Users\suzan\Mobile-Security-Framework-MobSF\venv\lib\site-packages\OpenSSL\_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "c:\Users\suzan\Mobile-Security-Framework-MobSF\venv\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: DLL load failed: The specified procedure could not be found.

[INFO] Connecting to VM/Device
* daemon not running; starting now at tcp:5037
* daemon started successfully
## CONTENTS OF LOG FILES

```
Paste the contents of logs/MobSF.log here
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

[2018-11-07 23:38:11]
[ERROR] adb_command (c:\Users\suzan\Mobile-Security-Framework-MobSF\DynamicAnalyzer\views\android\shared.py, LINE 67 "result = subprocess.check_output(args)"): Command '['C:\\Users\\suzan\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe', '-s', '192.168.2.30:5555', 'shell', 'su', '-c', 'mount', '-o', 'rw,remount,rw', '/system']' returned non-zero exit status 1.

**Comment by ajinabraham** [comment]
The modules are not installed capfuzz and pyOpenSSL ?
