### ISSUE TITLE
Postgresql not work

### ISSUE THREAD

**Issue by ramirezversion** [MobSF/Mobile-Security-Framework-MobSF#782]
## EXPLANATION OF THE ISSUE

MobSF with Postgre does not work.

## STEPS TO REPRODUCE THE ISSUE

This is the settings configuration with psycopg2 and al requirements already installed

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'mobsf',
        'USER': 'postgres',
        'PASSWORD': 'XXXXX',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

```

I run 

```
python manage.py makemigrations
python manage.py migrate



mobsf@host:~/Desktop/Mobile-Security-Framework-MobSF$ python manage.py makemigrations

  __  __       _    ____  _____         _   ___  
 |  \/  | ___ | |__/ ___||  ___| __   _/ | / _ \ 
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / || | | |
 | |  | | (_) | |_) |__) |  _|    \ V /| || |_| |
 |_|  |_|\___/|_.__/____/|_|       \_/ |_(_)___/ 
        



Mobile Security Framework v1.0.3 Beta

REST API Key:
OS: Linux
Platform: Linux-4.9.0-8-amd64-x86_64-with-debian-9.6
Dist: ('debian', '9.6', '')
[INFO] MobSF Basic Environment Check
[INFO] Checking for Update.
[INFO] No updates available.
No changes detected
mobsf@host:~/Desktop/Mobile-Security-Framework-MobSF$ python manage.py migrate

  __  __       _    ____  _____         _   ___  
 |  \/  | ___ | |__/ ___||  ___| __   _/ | / _ \ 
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / || | | |
 | |  | | (_) | |_) |__) |  _|    \ V /| || |_| |
 |_|  |_|\___/|_.__/____/|_|       \_/ |_(_)___/ 
        



Mobile Security Framework v1.0.3 Beta

REST API Key:
OS: Linux
Platform: Linux-4.9.0-8-amd64-x86_64-with-debian-9.6
Dist: ('debian', '9.6', '')
[INFO] MobSF Basic Environment Check
[INFO] Checking for Update.
[INFO] No updates available.
Operations to perform:
  Apply all migrations: auth, contenttypes, sessions
Running migrations:
  No migrations to apply.


```

and then 

```
./run.sh
```

## CONSOLE OUTPUT

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f6213005268>
Traceback (most recent call last):
  File "/home/mobsf/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 20, in <module>
    import psycopg2 as Database
ModuleNotFoundError: No module named 'psycopg2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mobsf/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/mobsf/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/mobsf/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/home/mobsf/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/home/mobsf/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/mobsf/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mobsf/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/mobsf/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/mobsf/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mobsf/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/home/mobsf/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/home/mobsf/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/db/models/base.py", line 101, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/home/mobsf/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/db/models/base.py", line 305, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/mobsf/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/db/models/options.py", line 203, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/home/mobsf/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/db/__init__.py", line 33, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/home/mobsf/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/db/utils.py", line 202, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/home/mobsf/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/db/utils.py", line 110, in load_backend
    return import_module('%s.base' % backend_name)
  File "/home/mobsf/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/mobsf/Desktop/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 24, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
```

## CONTENTS OF LOG FILES

```
The log is empty for this issue

```

**Comment by superpoussin22** [comment]
sounds like pyscopg2 is missing :  
'''
ModuleNotFoundError: No module named 'psycopg2'
'''
di you install it ?

'''
pip3 install psycopg2-binary
'''

**Comment by ramirezversion** [comment]
Yes sure, it was already installed and it does not work anyway.

```
mobsf@host:~/Desktop/Mobile-Security-Framework-MobSF$ pip3 install psycopg2-binary
Collecting psycopg2-binary
  Using cached https://files.pythonhosted.org/packages/cd/eb/4e872a11edd82079b4163035389051668c58cd2acc30777b6bee73f5f8a3/psycopg2_binary-2.7.6.1-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.7.6.1
```

**Comment by superpoussin22** [comment]
if you try 

``
python3 manage.py makemigrations
python3 manage.py migrate
``

**Comment by ramirezversion** [comment]
I tried too but it gave me the same error message.

**Comment by superpoussin22** [comment]
which os are you using ?

**Comment by ramirezversion** [comment]
Debian9
Linux host 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

At least I could make SQLite database mode working...

**Comment by superpoussin22** [comment]
you are in your venv when you install psycopg2-binary ?

**Comment by ramirezversion** [comment]
I am just installing all python modulesover the host directly, not in any specific Venv. Is it possible that Mobsf uses some venv and i have to install psycopg2 over it?

**Comment by ramirezversion** [comment]
Yes, i saw it. I'll try tomorrow this way. I have not so much experience with the python venv. Thanks for your help.

**Comment by ajinabraham** [comment]
As pointed out by @superpoussin22 `No module named 'psycopg2'`. Ensure that's installed

**Comment by ramirezversion** [comment]
Module is installed but it does not work.

**Comment by ramirezversion** [comment]
yes, it was because the venv python. Now i think it is working.
