### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by sidtech120** [MobSF/Mobile-Security-Framework-MobSF#809]
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 307, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/Desktop/Android/Mobile-Security-Framework-MobSF/MobSF/settings.py", line 14, in <module>
    from MobSF import utils
  File "/root/Desktop/Android/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 25, in <module>
    from . import settings
ImportError: cannot import name settings

I have tried solutions but not able to resolve please help @ajinabraham

**Comment by ajinabraham** [comment]
MobSF needs Python3. You are trying on Python 2.7
