### ISSUE TITLE
On Parrot 4.4 I get the below when running sudo ./run.sh

### ISSUE THREAD

**Issue by m2ura** [MobSF/Mobile-Security-Framework-MobSF#841]
On Parrot 4.4 I get the below when running sudo ./run.sh

Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

Even though I installed django, I cloned the project.

**Comment by ajinabraham** [comment]
You need to run setup.sh first and make sure to use Python 3

**Comment by m2ura** [comment]
Still having some issues...

┌─[offensive@parrot]─[~/Desktop/mobile-sec/Mobile-Security-Framework-MobSF]
└──╼ $sudo ./setup.sh
[INSTALL] Found Python3
[INSTALL] Installing Virtualenv
Requirement already satisfied: virtualenv in /usr/local/lib/python3.6/dist-packages (16.2.0)
Requirement already satisfied: setuptools>=18.0.0 in /usr/lib/python3/dist-packages (from virtualenv) (40.6.2)
[INSTALL] Using Virtualenv
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/offensive/Desktop/mobile-sec/Mobile-Security-Framework-MobSF/venv/bin/python3
Not overwriting existing python script /home/offensive/Desktop/mobile-sec/Mobile-Security-Framework-MobSF/venv/bin/python (you must use /home/offensive/Desktop/mobile-sec/Mobile-Security-Framework-MobSF/venv/bin/python3)
Installing setuptools, pip, wheel...
done.
./setup.sh: 10: ./setup.sh: source: not found
./setup.sh: 13: ./setup.sh: [[: not found
[INSTALL] Installing Requirements
Collecting git+https://github.com/MobSF/CapFuzz.git (from -r requirements.txt (line 8))
  Cloning https://github.com/MobSF/CapFuzz.git to /tmp/pip-req-build-TqX2Fd
Collecting Django==2.1.5 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement Django==2.1.5 (from -r requirements.txt (line 1)) (from versions: 1.1.3, 1.1.4, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.4.16, 1.4.17, 1.4.18, 1.4.19, 1.4.20, 1.4.21, 1.4.22, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.6, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.10, 1.6.11, 1.7, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.7.10, 1.7.11, 1.8a1, 1.8b1, 1.8b2, 1.8rc1, 1.8, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.8.8, 1.8.9, 1.8.10, 1.8.11, 1.8.12, 1.8.13, 1.8.14, 1.8.15, 1.8.16, 1.8.17, 1.8.18, 1.8.19, 1.9a1, 1.9b1, 1.9rc1, 1.9rc2, 1.9, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 1.9.7, 1.9.8, 1.9.9, 1.9.10, 1.9.11, 1.9.12, 1.9.13, 1.10a1, 1.10b1, 1.10rc1, 1.10, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.10.5, 1.10.6, 1.10.7, 1.10.8, 1.11a1, 1.11b1, 1.11rc1, 1.11, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.11.5, 1.11.6, 1.11.7, 1.11.8, 1.11.9, 1.11.10, 1.11.11, 1.11.12, 1.11.13, 1.11.14, 1.11.15, 1.11.16, 1.11.17, 1.11.18)
No matching distribution found for Django==2.1.5 (from -r requirements.txt (line 1))
[INSTALL] Clean Up

=======================MobSF Clean Script for Unix=======================
Running this script will delete the Scan database, all files uploaded and generated.

Deleting all Uploads
Deleting all Downloads
Deleting Static Analyzer Migrations
Deleting Dynamic Analyzer Migrations
Deleting MobSF Migrations
Deleting python byte code files
Deleting temp and log files
Deleting DB
Deleting Secret File
Done
[INSTALL] Migrating Database
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/offensive/Desktop/mobile-sec/Mobile-Security-Framework-MobSF/MobSF/settings.py", line 14, in <module>
    from MobSF import utils
  File "/home/offensive/Desktop/mobile-sec/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 25, in <module>
    from . import settings
ImportError: cannot import name settings
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/offensive/Desktop/mobile-sec/Mobile-Security-Framework-MobSF/MobSF/settings.py", line 14, in <module>
    from MobSF import utils
  File "/home/offensive/Desktop/mobile-sec/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 25, in <module>
    from . import settings
ImportError: cannot import name settings
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/offensive/Desktop/mobile-sec/Mobile-Security-Framework-MobSF/MobSF/settings.py", line 14, in <module>
    from MobSF import utils
  File "/home/offensive/Desktop/mobile-sec/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 25, in <module>
    from . import settings
ImportError: cannot import name settings
Download and Install wkhtmltopdf for PDF Report Generation - https://wkhtmltopdf.org/downloads.html
[INSTALL] Installation Complete


Then whe running sudo ./run.sh

┌─[offensive@parrot]─[~/Desktop/mobile-sec/Mobile-Security-Framework-MobSF]
└──╼ $sudo ./run.sh
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
