### ISSUE TITLE
Dynamic Analysis Error! Clientdisconnect

### ISSUE THREAD

**Issue by zahideroglu** [MobSF/Mobile-Security-Framework-MobSF#846]
## EXPLANATION OF THE ISSUE

I use MAC Mojave. We have analyzed other issues about dynamic analysis module. openssl, capfuzz, django etc. already installed but still got this error.

## STEPS TO REPRODUCE THE ISSUE

```
1.) Successfully run static analysis,
2.) when it comes to dynamic analysis by clicking it, I got this error.
```

## CONSOLE OUTPUT

[INFO] Dynamic Analysis Started

[INFO] Refreshing MobSF VM
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%

[INFO] VM Closed

[INFO] Dynamic Analysis Started

[INFO] Refreshing MobSF VM
VBoxManage: error: Machine 'e6b14249-ff95-4b54-bc60-e2cd13f425f6' is not currently running

[INFO] VM Closed
Restoring snapshot 'Snapshot 1' (9379a3c1-1e7b-42d1-adaf-13454278a949)
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%

[INFO] VM Restore Snapshot
Waiting for VM "e6b14249-ff95-4b54-bc60-e2cd13f425f6" to power on...
Restoring snapshot 'Snapshot 1' (9379a3c1-1e7b-42d1-adaf-13454278a949)
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%

[INFO] VM Restore Snapshot
VBoxManage: error: The machine 'MobSF_VM_0.2' is already locked by a session (or being locked or unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LaunchVMProcess(a->session, sessionType.raw(), Bstr(strEnv).raw(), progress.asOutParam())" at line 726 of file VBoxManageMisc.cpp

[INFO] VM Starting
[18/Jan/2019 09:08:08] "POST /DynamicAnalyzer/ HTTP/1.1" 200 32510
[18/Jan/2019 09:08:08] "GET /download/screen/screen.png HTTP/1.1" 302 0
[18/Jan/2019 09:08:08] "GET /error/ HTTP/1.1" 200 4774
VM "e6b14249-ff95-4b54-bc60-e2cd13f425f6" has been successfully started.

[INFO] VM Starting
[18/Jan/2019 09:08:09] "POST /DynamicAnalyzer/ HTTP/1.1" 200 32510
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/handlers.py", line 332, in send_headers
    self.send_preamble()
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 799, in write
    self._sock.sendall(b)
OSError: [Errno 41] Protocol wrong type for socket
[18/Jan/2019 09:08:09] "POST /DynamicAnalyzer/ HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 57608)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/handlers.py", line 332, in send_headers
    self.send_preamble()
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 799, in write
    self._sock.sendall(b)
OSError: [Errno 41] Protocol wrong type for socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/Users/meeroglu/Downloads/Mobile-Security-Framework-MobSF-master/venv/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 116, in handle_error
    super().handle_error()
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/Users/meeroglu/Downloads/Mobile-Security-Framework-MobSF-master/venv/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
  File "/Users/meeroglu/Downloads/Mobile-Security-Framework-MobSF-master/venv/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/Users/meeroglu/Downloads/Mobile-Security-Framework-MobSF-master/venv/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 111, in close
    super().close()
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------

[INFO] Setting up Dynamic Analysis Environment

[INFO] Connecting to VM/Device
* daemon not running. starting it now at tcp:5037 *
* daemon started successfully *
Capture Module Loaded
Proxy server listening at http://*:1337

[INFO] ADB Started

[INFO] Waiting for 5 seconds...
192.168.56.101:54957: clientconnect

[INFO] Connecting to VM/Device
[18/Jan/2019 09:10:21] "POST /GetEnv/ HTTP/1.1" 200 166
192.168.56.101:50960: clientconnect
192.168.56.101:50960: clientdisconnect
192.168.56.101:49331: clientconnect
192.168.56.101:49331: clientdisconnect
192.168.56.101:57794: clientconnect
192.168.56.101:57794: clientdisconnect
192.168.56.101:37257: clientconnect
192.168.56.101:37257: clientdisconnect

```

```

## CONTENTS OF LOG FILES

```
Paste the contents of logs/MobSF.log here
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

**Comment by ajinabraham** [comment]
clientdisconnected is fine. That's from capfuzz.
`The machine 'MobSF_VM_0.2' is already locked by a session (or being locked or unlocked)`
Try removing the vm from virtualbox and add it again.
