### ISSUE TITLE
mitmproxy is incompatible click 7.0

### ISSUE THREAD

**Issue by 4val0v** [MobSF/Mobile-Security-Framework-MobSF#866]
## STEPS TO REPRODUCE THE ISSUE

```
pip3 install -r requirements.txt
```

## CONSOLE OUTPUT

```
mitmproxy 3.0.2 has requirement click<7,>=6.2 but you'll have click 7.0 which is incompatible
```

## OS Info
Python 3.6.7
Ubuntu 18.04 LTS

**Comment by ITmustang** [comment]
pip3 install click==6.2 fixed it for me.

**Comment by ajinabraham** [comment]
This comes from CapFuzz and needs to be reported here: https://github.com/MobSF/CapFuzz

**Comment by flamecopper** [comment]
Any advise?

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Click 7.0 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('click<7,>=6.2'), {'mitmproxy'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/capfuzz", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'click<7,>=6.2' distribution was not found and is required by mitmproxy

**Comment by DustinTheGreat** [comment]
Any luck?
