### ISSUE TITLE
no such table: StaticAnalyzer_staticanalyzerandroid issue

### ISSUE THREAD

**Issue by madevaprasad** [MobSF/Mobile-Security-Framework-MobSF#877]
Hi , Please help on below issue:

[INFO] 27/Feb/2019 18:38:03 - Mobile Security Framework v1.0.5 Beta
REST API Key: 4cbe319a66e3cd8e74946b70286f1fd25971c6469a2b54fd13f63061e12e55c2
[INFO] 27/Feb/2019 18:38:03 - OS: Windows
[INFO] 27/Feb/2019 18:38:03 - Platform: Windows-10-10.0.16299-SP0
[INFO] 27/Feb/2019 18:38:03 - Finding JDK Location in Windows....
[INFO] 27/Feb/2019 18:38:03 - Oracle Java JDK is installed!
[INFO] 27/Feb/2019 18:38:03 - MobSF Basic Environment Check
[INFO] 27/Feb/2019 18:38:03 - Checking for Update.
[ERROR] 27/Feb/2019 18:38:04 -
Cannot Check for updates. (D:\AppTest\Mobile-Security-Framework-MobSF\MobSF\utils.py, LINE 100 "proxies=proxies, verify=verify)"): HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /MobSF/Mobile-Security-Framework-MobSF/master/MobSF/settings.py (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))
System check identified no issues (0 silenced).
February 27, 2019 - 18:38:04
Django version 2.1.7, using settings 'MobSF.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[INFO] 27/Feb/2019 18:38:19 - "GET / HTTP/1.1" 200 7723
[INFO] 27/Feb/2019 18:38:19 - "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[INFO] 27/Feb/2019 18:38:19 - "GET /static/js/ie-emulation-modes-warning.js HTTP/1.1" 304 0
[INFO] 27/Feb/2019 18:38:19 - "GET /static/css/cover.css HTTP/1.1" 304 0
[INFO] 27/Feb/2019 18:38:19 - "GET /static/js/jquery.min.js HTTP/1.1" 304 0
[INFO] 27/Feb/2019 18:38:19 - "GET /static/js/dropzone.js HTTP/1.1" 304 0
[INFO] 27/Feb/2019 18:38:19 - "GET /static/css/dropzone.css HTTP/1.1" 304 0
[INFO] 27/Feb/2019 18:38:19 - "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[INFO] 27/Feb/2019 18:38:19 - "GET /static/img/MobSF_Logo_small.png HTTP/1.1" 304 0
[INFO] 27/Feb/2019 18:38:19 - "GET /static/js/ie10-viewport-bug-workaround.js HTTP/1.1" 304 0
[INFO] 27/Feb/2019 18:38:19 - "GET /static/fonts/glyphicons-halflings-regular.woff HTTP/1.1" 304 0
[INFO] 27/Feb/2019 18:38:36 - MIME Type: application/vnd.android.package-archive FILE: myapp-dev-debug.apk
[ERROR] 27/Feb/2019 18:38:36 -
Adding Scan URL to Database (D:\AppTest\Mobile-Security-Framework-MobSF\MobSF\views\scanning.py, LINE 20 "if not db_obj.exists():"): no such table: StaticAnalyzer_recentscansdb
[INFO] 27/Feb/2019 18:38:36 - Performing Static Analysis of Android APK
[INFO] 27/Feb/2019 18:38:36 - "POST /upload/ HTTP/1.1" 200 231
[INFO] 27/Feb/2019 18:38:36 - Starting Analysis on : MYPP-DEV-debug.apk
[ERROR] 27/Feb/2019 18:38:36 - no such table: StaticAnalyzer_staticanalyzerandroid
[ERROR] 27/Feb/2019 18:38:36 - Internal Server Error: /StaticAnalyzer/
[ERROR] 27/Feb/2019 18:38:36 - "GET /StaticAnalyzer/?name=IQToolBox-DEV-debug.apk&type=apk&checksum=69ce81c350e180541280e442acfa3995 HTTP/1.1" 500 4829

**Comment by superpoussin22** [comment]
did you run setup.bat ?

**Comment by madevaprasad** [comment]
yes I did run setup.bat

**Comment by ajinabraham** [comment]
Database is not migrated properly.
See: https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#updating-mobsf

Do this from virtualenv

**Comment by madevaprasad** [comment]
Hi,

I am using Windows 10 machine and i ran the following commands.
but still face the issue.

D:\Security Testing\Mobile-Security-Framework-MobSF>python manage.py makemigrations
[INFO] 28/Feb/2019 21:09:31 -

  __  __       _    ____  _____         _   ___
 |  \/  | ___ | |__/ ___||  ___| __   _/ | / _ \
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / || | | |
 | |  | | (_) | |_) |__) |  _|    \ V /| || |_| |
 |_|  |_|\___/|_.__/____/|_|       \_/ |_(_)___/



[INFO] 28/Feb/2019 21:09:31 - Mobile Security Framework v1.0.5 Beta
REST API Key: 4be188249702779ef01cc470d8e71b1d44bf0486c82b5b53b017301659498d38
[INFO] 28/Feb/2019 21:09:31 - OS: Windows
[INFO] 28/Feb/2019 21:09:31 - Platform: Windows-10-10.0.17134-SP0
[INFO] 28/Feb/2019 21:09:31 - Finding JDK Location in Windows....
[INFO] 28/Feb/2019 21:09:31 - Oracle Java JDK is installed!
[WARNING] 28/Feb/2019 21:09:31 - Could not find VirtualBox path.
[INFO] 28/Feb/2019 21:09:31 - MobSF Basic Environment Check
[INFO] 28/Feb/2019 21:09:31 - Checking for Update.
[INFO] 28/Feb/2019 21:09:32 - No updates available.
No changes detected

D:\Security Testing\Mobile-Security-Framework-MobSF>python manage.py migrate
[INFO] 28/Feb/2019 21:12:39 -

  __  __       _    ____  _____         _   ___
 |  \/  | ___ | |__/ ___||  ___| __   _/ | / _ \
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / || | | |
 | |  | | (_) | |_) |__) |  _|    \ V /| || |_| |
 |_|  |_|\___/|_.__/____/|_|       \_/ |_(_)___/



[INFO] 28/Feb/2019 21:12:39 - Mobile Security Framework v1.0.5 Beta
REST API Key: 4be188249702779ef01cc470d8e71b1d44bf0486c82b5b53b017301659498d38
[INFO] 28/Feb/2019 21:12:39 - OS: Windows
[INFO] 28/Feb/2019 21:12:39 - Platform: Windows-10-10.0.17134-SP0
[INFO] 28/Feb/2019 21:12:39 - Finding JDK Location in Windows....
[INFO] 28/Feb/2019 21:12:39 - Oracle Java JDK is installed!
[WARNING] 28/Feb/2019 21:12:39 - Could not find VirtualBox path.
[INFO] 28/Feb/2019 21:12:39 - MobSF Basic Environment Check
[INFO] 28/Feb/2019 21:12:39 - Checking for Update.
[INFO] 28/Feb/2019 21:12:40 - No updates available.
Operations to perform:
  Apply all migrations: auth, contenttypes, sessions
Running migrations:
  No migrations to apply.

**Comment by ajinabraham** [comment]
Can you delete following directories and files first
```
StaticAnalyzer/migration
DynamicAnalyzer/migration
MobSF/migration
db.sqlite3
secret
```
And try migrating again. Please use virtualenv

**Comment by ajinabraham** [comment]
PS: previous scan results will be lost

**Comment by madevaprasad** [comment]
i am using windows machine and also installed virtualbox so should i need to do MobSF installation in virtualenv?

**Comment by ajinabraham** [comment]
You should be running
setup.bat and run.bat rather than running python commands. Follow the documentation.

**Comment by 7a** [comment]
Also happens in the latest docker image, any ideas?

```
[INFO] 30/Mar/2020 07:45:04 - 
  __  __       _    ____  _____       _____  ___  
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / _ \ 
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| | | |
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | |_| |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/

[INFO] 30/Mar/2020 07:45:04 - Mobile Security Framework v3.0.5 Beta
REST API Key: 71b0dd0457e995dd2d99ce3ba7daa00db4c4f1a8eb07352fdbc4d671e553e07a
[INFO] 30/Mar/2020 07:45:04 - OS: Linux
[INFO] 30/Mar/2020 07:45:04 - Platform: Linux-4.19.0-kali4-amd64-x86_64-with-Ubuntu-18.04-bionic
[INFO] 30/Mar/2020 07:45:04 - Dist: ubuntu 18.04 bionic
[INFO] 30/Mar/2020 07:45:04 - MobSF Basic Environment Check
[INFO] 30/Mar/2020 07:45:04 - Checking for Update.

[ERROR] 30/Mar/2020 07:45:04 - Cannot Check for updates.
Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 109, in check_update
    github_url = settings.GITHUB_URL
AttributeError: module 'MobSF.settings' has no attribute 'GITHUB_URL'

...
[INFO] 30/Mar/2020 07:45:52 - MIME Type: application/octet-stream FILE: some.ipa
[ERROR] 30/Mar/2020 07:45:52 - Adding Scan URL to Database
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: table StaticAnalyzer_recentscansdb has no column named FILE_NAME

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/MobSF/views/scanning.py", line 21, in add_to_recent_scan
    new_db_obj.save()
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 746, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 784, in save_base
    force_update, using, update_fields,
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 926, in _do_insert
    using=using, raw=raw,
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/compiler.py", line 1391, in execute_sql
```
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: table StaticAnalyzer_recentscansdb has no column named FILE_NAME

**Comment by ajinabraham** [comment]
@7a works fine for me
```
$ docker pull opensecurity/mobile-security-framework-mobsf
Using default tag: latest
latest: Pulling from opensecurity/mobile-security-framework-mobsf
Digest: sha256:271b301350174f62ad5a0cf17e119ef8502f1286547bbb548fa3939945852259
Status: Downloaded newer image for opensecurity/mobile-security-framework-mobsf:latest
docker.io/opensecurity/mobile-security-framework-mobsf:latest

$ docker run -it -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest
[2020-03-30 21:42:45 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2020-03-30 21:42:45 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2020-03-30 21:42:45 +0000] [1] [INFO] Using worker: threads
[2020-03-30 21:42:45 +0000] [9] [INFO] Booting worker with pid: 9
[INFO] 30/Mar/2020 21:42:50 -
  __  __       _    ____  _____       _____  ___
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / _ \
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| | | |
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | |_| |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/

[INFO] 30/Mar/2020 21:42:50 - Mobile Security Framework v3.0.6 Beta
REST API Key: 618941ebdec42a7f519ed5dca40d9b3c5f17606ca6142fc2fc725f36cce06c40
[INFO] 30/Mar/2020 21:42:50 - OS: Linux
[INFO] 30/Mar/2020 21:42:50 - Platform: Linux-4.19.76-linuxkit-x86_64-with-Ubuntu-18.04-bionic
[INFO] 30/Mar/2020 21:42:50 - Dist: ubuntu 18.04 bionic
[INFO] 30/Mar/2020 21:42:50 - MobSF Basic Environment Check
[INFO] 30/Mar/2020 21:42:50 - Checking for Update.
[INFO] 30/Mar/2020 21:42:50 - No updates available.
[INFO] 30/Mar/2020 21:43:24 - MIME Type: application/vnd.android.package-archive FILE: android.apk
[INFO] 30/Mar/2020 21:43:24 - Performing Static Analysis of Android APK
[INFO] 30/Mar/2020 21:43:24 - Starting Analysis on : android.apk
[INFO] 30/Mar/2020 21:43:24 - Generating Hashes
[INFO] 30/Mar/2020 21:43:24 - Unzipping
[INFO] 30/Mar/2020 21:43:24 - Getting Hardcoded Certificates/Keystores
[INFO] 30/Mar/2020 21:43:24 - APK Extracted
[INFO] 30/Mar/2020 21:43:24 - Converting AXML to XML
[INFO] 30/Mar/2020 21:43:27 - Reading Android Manifest
[INFO] 30/Mar/2020 21:43:27 - Parsing AndroidManifest.xml
[INFO] 30/Mar/2020 21:43:27 - Fetching icon path
[INFO] 30/Mar/2020 21:43:27 - Extracting Manifest Data
[INFO] 30/Mar/2020 21:43:27 - Fetching Details from Play Store: opensecurity.helloworld
[INFO] 30/Mar/2020 21:43:28 - Manifest Analysis Started
[INFO] 30/Mar/2020 21:43:28 - Static Android Binary Analysis Started
[INFO] 30/Mar/2020 21:43:28 - Static Android Resource Analysis Started
[INFO] 30/Mar/2020 21:43:28 - Reading Code Signing Certificate
[INFO] 30/Mar/2020 21:43:28 - Running APKiD 2.1.0
[INFO] 30/Mar/2020 21:43:34 - Updating Trackers Database....
[INFO] 30/Mar/2020 21:43:34 - Detecting Trackers
[INFO] 30/Mar/2020 21:43:34 - APK -> JAVA
[INFO] 30/Mar/2020 21:43:34 - Decompiling to Java with jadx
[INFO] 30/Mar/2020 21:43:38 - DEX -> SMALI
[INFO] 30/Mar/2020 21:43:38 - Converting classes.dex to Smali Code
[INFO] 30/Mar/2020 21:43:38 - Static Android Code Analysis Started
[INFO] 30/Mar/2020 21:43:38 - Code Analysis Started on - java_source
[INFO] 30/Mar/2020 21:43:38 - Finished Code Analysis, Email and URL Extraction
[INFO] 30/Mar/2020 21:43:38 - Extracting Strings from APK
[INFO] 30/Mar/2020 21:43:38 - Detecting Firebase URL(s)
[INFO] 30/Mar/2020 21:43:38 - Performing Malware Check on extracted Domains
[INFO] 30/Mar/2020 21:43:39 - Updating Malware Database....
[INFO] 30/Mar/2020 21:43:39 - Connecting to Database
[INFO] 30/Mar/2020 21:43:39 - Saving to Database
```

**Comment by 7a** [comment]
That works thanks!

I was running it like this:
```
docker run -it --name mobsf -p 8000:8000 -v /root/.MobSF:/root/.MobSF opensecurity/mobile-security-framework-mobsf:latest
```

Before upgrading I deleted all mobsf docker images and rm -rf /root/.MobSF, but still got that error.
Did I forget some step to run MobSF with persistence without errors?

**Comment by ajinabraham** [comment]
@7a Working fine at my end

```$ docker run -it -p 8000:8000 -v /tmp:/root/.MobSF opensecurity/mobile-security-framework-mobsf:latest
[2020-04-03 16:52:44 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2020-04-03 16:52:44 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2020-04-03 16:52:44 +0000] [1] [INFO] Using worker: threads
[2020-04-03 16:52:44 +0000] [9] [INFO] Booting worker with pid: 9
[INFO] 03/Apr/2020 16:52:45 -
  __  __       _    ____  _____       _____  ___
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / _ \
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| | | |
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | |_| |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/

[INFO] 03/Apr/2020 16:52:45 - Mobile Security Framework v3.0.6 Beta
REST API Key: 6e14ece3fd443d700e89ba98b41a09e615822d916647d7a845b2dd1168907ca9
[INFO] 03/Apr/2020 16:52:45 - OS: Linux
[INFO] 03/Apr/2020 16:52:45 - Platform: Linux-4.19.76-linuxkit-x86_64-with-Ubuntu-18.04-bionic
[INFO] 03/Apr/2020 16:52:45 - Dist: ubuntu 18.04 bionic
[INFO] 03/Apr/2020 16:52:45 - MobSF Basic Environment Check
[INFO] 03/Apr/2020 16:52:45 - Checking for Update.
No changes detected
[INFO] 03/Apr/2020 16:52:45 - No updates available.
[INFO] 03/Apr/2020 16:52:46 -
  __  __       _    ____  _____       _____  ___
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / _ \
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| | | |
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | |_| |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/

[INFO] 03/Apr/2020 16:52:46 - Mobile Security Framework v3.0.6 Beta
REST API Key: 6e14ece3fd443d700e89ba98b41a09e615822d916647d7a845b2dd1168907ca9
[INFO] 03/Apr/2020 16:52:46 - OS: Linux
[INFO] 03/Apr/2020 16:52:46 - Platform: Linux-4.19.76-linuxkit-x86_64-with-Ubuntu-18.04-bionic
[INFO] 03/Apr/2020 16:52:46 - Dist: ubuntu 18.04 bionic
[INFO] 03/Apr/2020 16:52:46 - MobSF Basic Environment Check
[INFO] 03/Apr/2020 16:52:46 - Checking for Update.
No changes detected in app 'StaticAnalyzer'
[INFO] 03/Apr/2020 16:52:46 - No updates available.
[INFO] 03/Apr/2020 16:52:47 -
  __  __       _    ____  _____       _____  ___
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / _ \
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| | | |
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | |_| |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/

[INFO] 03/Apr/2020 16:52:47 - Mobile Security Framework v3.0.6 Beta
REST API Key: 6e14ece3fd443d700e89ba98b41a09e615822d916647d7a845b2dd1168907ca9
[INFO] 03/Apr/2020 16:52:47 - OS: Linux
[INFO] 03/Apr/2020 16:52:47 - Platform: Linux-4.19.76-linuxkit-x86_64-with-Ubuntu-18.04-bionic
[INFO] 03/Apr/2020 16:52:47 - Dist: ubuntu 18.04 bionic
[INFO] 03/Apr/2020 16:52:47 - MobSF Basic Environment Check
[INFO] 03/Apr/2020 16:52:47 - Checking for Update.
Operations to perform:
  Apply all migrations: StaticAnalyzer, auth, contenttypes, sessions
Running migrations:
  Applying StaticAnalyzer.0001_initial... OK
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
[INFO] 03/Apr/2020 16:52:47 - No updates available.
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying sessions.0001_initial... OK
[INFO] 03/Apr/2020 16:52:48 -
  __  __       _    ____  _____       _____  ___
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / _ \
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| | | |
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | |_| |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/

[INFO] 03/Apr/2020 16:52:48 - Mobile Security Framework v3.0.6 Beta
REST API Key: 6e14ece3fd443d700e89ba98b41a09e615822d916647d7a845b2dd1168907ca9
[INFO] 03/Apr/2020 16:52:48 - OS: Linux
[INFO] 03/Apr/2020 16:52:48 - Platform: Linux-4.19.76-linuxkit-x86_64-with-Ubuntu-18.04-bionic
[INFO] 03/Apr/2020 16:52:48 - Dist: ubuntu 18.04 bionic
[INFO] 03/Apr/2020 16:52:48 - MobSF Basic Environment Check
[INFO] 03/Apr/2020 16:52:48 - Checking for Update.
Operations to perform:
  Synchronize unmigrated apps: DynamicAnalyzer, MalwareAnalyzer, MobSF, messages, staticfiles
  Apply all migrations: StaticAnalyzer, auth, contenttypes, sessions
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  No migrations to apply.
[INFO] 03/Apr/2020 16:52:49 - No updates available.
[INFO] 03/Apr/2020 16:52:56 -
  __  __       _    ____  _____       _____  ___
 |  \/  | ___ | |__/ ___||  ___|_   _|___ / / _ \
 | |\/| |/ _ \| '_ \___ \| |_  \ \ / / |_ \| | | |
 | |  | | (_) | |_) |__) |  _|  \ V / ___) | |_| |
 |_|  |_|\___/|_.__/____/|_|     \_/ |____(_)___/

[INFO] 03/Apr/2020 16:52:56 - Mobile Security Framework v3.0.6 Beta
REST API Key: 6e14ece3fd443d700e89ba98b41a09e615822d916647d7a845b2dd1168907ca9
[INFO] 03/Apr/2020 16:52:56 - OS: Linux
[INFO] 03/Apr/2020 16:52:56 - Platform: Linux-4.19.76-linuxkit-x86_64-with-Ubuntu-18.04-bionic
[INFO] 03/Apr/2020 16:52:56 - Dist: ubuntu 18.04 bionic
[INFO] 03/Apr/2020 16:52:56 - MobSF Basic Environment Check
[INFO] 03/Apr/2020 16:52:56 - Checking for Update.
[INFO] 03/Apr/2020 16:52:56 - No updates available.
[INFO] 03/Apr/2020 16:53:00 - MIME Type: application/vnd.android.package-archive FILE: android.apk
[INFO] 03/Apr/2020 16:53:00 - Performing Static Analysis of Android APK
[INFO] 03/Apr/2020 16:53:00 - Starting Analysis on : android.apk
[INFO] 03/Apr/2020 16:53:00 - Generating Hashes
[INFO] 03/Apr/2020 16:53:01 - Unzipping
[INFO] 03/Apr/2020 16:53:02 - Getting Hardcoded Certificates/Keystores
[INFO] 03/Apr/2020 16:53:02 - APK Extracted
[INFO] 03/Apr/2020 16:53:02 - Converting AXML to XML
[INFO] 03/Apr/2020 16:53:08 - Reading Android Manifest
[INFO] 03/Apr/2020 16:53:09 - Parsing AndroidManifest.xml
[INFO] 03/Apr/2020 16:53:09 - Fetching icon path
[INFO] 03/Apr/2020 16:53:09 - Extracting Manifest Data
[INFO] 03/Apr/2020 16:53:09 - Fetching Details from Play Store: opensecurity.helloworld
[INFO] 03/Apr/2020 16:53:09 - Manifest Analysis Started
[INFO] 03/Apr/2020 16:53:09 - Static Android Binary Analysis Started
[INFO] 03/Apr/2020 16:53:09 - Static Android Resource Analysis Started
[INFO] 03/Apr/2020 16:53:09 - Reading Code Signing Certificate
[INFO] 03/Apr/2020 16:53:09 - Running APKiD 2.1.0
[INFO] 03/Apr/2020 16:53:12 - Updating Trackers Database....
[INFO] 03/Apr/2020 16:53:12 - Detecting Trackers
[INFO] 03/Apr/2020 16:53:12 - APK -> JAVA
[INFO] 03/Apr/2020 16:53:12 - Decompiling to Java with jadx
[INFO] 03/Apr/2020 16:53:18 - DEX -> SMALI
[INFO] 03/Apr/2020 16:53:18 - Converting classes.dex to Smali Code
[INFO] 03/Apr/2020 16:53:18 - Static Android Code Analysis Started
[INFO] 03/Apr/2020 16:53:18 - Code Analysis Started on - java_source
[INFO] 03/Apr/2020 16:53:19 - Finished Code Analysis, Email and URL Extraction
[INFO] 03/Apr/2020 16:53:19 - Extracting Strings from APK
[INFO] 03/Apr/2020 16:53:19 - Detecting Firebase URL(s)
[INFO] 03/Apr/2020 16:53:19 - Performing Malware Check on extracted Domains
[INFO] 03/Apr/2020 16:53:20 - Updating Malware Database....
[INFO] 03/Apr/2020 16:53:20 - Connecting to Database
[INFO] 03/Apr/2020 16:53:20 - Saving to Database
```

For some reason in your case DB migration is not happening. Try running
```
docker exec -it mobsf python3 manage.py makemigrations
docker exec -it mobsf python3 manage.py makemigrations StaticAnalyzer
docker exec -it mobsf python3 manage.py migrate
```
Also see https://mobsf.github.io/docs/#/docker for troubleshooting.
