### ISSUE TITLE
500 Error on /api/v1/report_json

### ISSUE THREAD

**Issue by ashutoshccfis** [MobSF/Mobile-Security-Framework-MobSF#896]
While I hit the API  - /api/v1/report_json , with accurate parameters and headers , I get 500. 
While all other API are working perfectly. 

Help appreciated. 

Logs - 
[INFO] 18/Mar/2019 09:50:28 - Fetching data from DB for PDF Report Generation (Android)
[INFO] 18/Mar/2019 09:50:28 - Analysis is already Done. Fetching data from the DB...
[ERROR] 18/Mar/2019 09:50:29 - Internal Server Error: /api/v1/report_json
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/some/mobsf/Mobile-Security-Framework-MobSF/MobSF/views/helpers.py", line 71, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/some/mobsf/Mobile-Security-Framework-MobSF/MobSF/views/api/rest_api.py", line 168, in api_json_report
    response = make_api_response(resp["report_dat"], 200)
  File "/home/some/mobsf/Mobile-Security-Framework-MobSF/MobSF/views/api/rest_api.py", line 47, in make_api_response
    resp = JsonResponse(data=data, status=status)
  File "/usr/local/lib/python3.5/dist-packages/django/http/response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.5/dist-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")

**Comment by tartan75** [comment]
I have what appears to be the same issue (I'm using Docker if thats relevant)

[INFO] 19/Mar/2019 16:23:50 - Fetching data from DB for PDF Report Generation (Android)
[INFO] 19/Mar/2019 16:23:50 - Analysis is already Done. Fetching data from the DB...
[ERROR] 19/Mar/2019 16:23:56 - Internal Server Error: /api/v1/report_json
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/Mobile-Security-Framework-MobSF/MobSF/views/helpers.py", line 71, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/root/Mobile-Security-Framework-MobSF/MobSF/views/api/rest_api.py", line 168, in api_json_report
    response = make_api_response(resp["report_dat"], 200)
  File "/root/Mobile-Security-Framework-MobSF/MobSF/views/api/rest_api.py", line 47, in make_api_response
    resp = JsonResponse(data=data, status=status)
  File "/usr/local/lib/python3.6/dist-packages/django/http/response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/dist-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
2019-03-19 16:23:56 ERROR    Internal Server Error: /api/v1/report_json
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/Mobile-Security-Framework-MobSF/MobSF/views/helpers.py", line 71, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/root/Mobile-Security-Framework-MobSF/MobSF/views/api/rest_api.py", line 168, in api_json_report
    response = make_api_response(resp["report_dat"], 200)
  File "/root/Mobile-Security-Framework-MobSF/MobSF/views/api/rest_api.py", line 47, in make_api_response
    resp = JsonResponse(data=data, status=status)
  File "/usr/local/lib/python3.6/dist-packages/django/http/response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/dist-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable

**Comment by ajinabraham** [comment]
Can you share an APK or IPA or ZIP so that I can reproduce this?

**Comment by ajinabraham** [comment]
There was a small bug. Added a hotfix to latest master. Do a git pull!

**Comment by shreyagarwal** [comment]
@ajinabraham : Can we pull the master and proceed here ?

**Comment by ajinabraham** [comment]
Yes
