### ISSUE TITLE
could not translate host name "postgres" to address: Name or service not known

### ISSUE THREAD

**Issue by dreadlocked** [MobSF/Mobile-Security-Framework-MobSF#922]
Docker version: 18.06.1-ce build e68fc7a
Docker-compose version: 1.22.0, build f46880fe
OS: Ubuntu 18.04.1 LTS

Steps to reproduce:
git clone the whole repository.
cd repository
docker-compose up

When starting the MobSF app, the following error appears:
```
[INFO] 22/Apr/2019 10:19:44 - 

  __  __       _    ____  _____         _   ___  
 |  \/  | ___ | |__/ ___||  ___| __   _/ | / _ \ 
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / || | | |
 | |  | | (_) | |_) |__) |  _|    \ V /| || |_| |
 |_|  |_|\___/|_.__/____/|_|       \_/ |_(_)___/ 
        


[INFO] 22/Apr/2019 10:19:44 - Mobile Security Framework v1.0.7 Beta
REST API Key: ff91ada86d67d74d0c5b3baf75e0f5cfce53ba2cbb1b893cc65d630e7aa0ada3
[INFO] 22/Apr/2019 10:19:44 - OS: Linux
[INFO] 22/Apr/2019 10:19:44 - Platform: Linux-5.0.2-050002-generic-x86_64-with-Ubuntu-18.04-bionic
[INFO] 22/Apr/2019 10:19:44 - Dist: ('Ubuntu', '18.04', 'bionic')
[INFO] 22/Apr/2019 10:19:44 - Finding JDK Location in Linux/MAC....
[INFO] 22/Apr/2019 10:19:45 - JDK 1.7 or above is available
[WARNING] 22/Apr/2019 10:19:45 - Could not find VirtualBox path.
[INFO] 22/Apr/2019 10:19:45 - MobSF Basic Environment Check
[INFO] 22/Apr/2019 10:19:45 - Checking for Update.
[INFO] 22/Apr/2019 10:19:45 - No updates available.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/dist-`packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/dist-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/Mobile-Security-Framework-MobSF/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/commands/makemigrations.py", line 101, in handle
    loader.check_consistent_history(connection)
  File "/usr/local/lib/python3.6/dist-packages/django/db/migrations/loader.py", line 283, in check_consistent_history
    applied = recorder.applied_migrations()
  File "/usr/local/lib/python3.6/dist-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.6/dist-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/base/base.py", line 217, in ensure_connection`
    self.connect()
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/dist-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known
```

**Comment by dreadlocked** [comment]
The same occurs on macOS 14.04

**Comment by superpoussin22** [comment]
did you do a docker-compose build  first ?

**Comment by dreadlocked** [comment]
Excatly the same error on `docker-compose build` for macOS and for Linux

**Comment by superpoussin22** [comment]
ok
can you try this and let me know ?

docker-compose up -d postgres
docker-compose up

**Comment by ajinabraham** [comment]
This error is caused by MobSF not able to communicate to postgres. Is your postgres container running?

**Comment by ajinabraham** [comment]
25 days response period is over
