### ISSUE TITLE
Report generation error

### ISSUE THREAD

**Issue by bhavikp43** [MobSF/Mobile-Security-Framework-MobSF#929]
PDF report generation error.

error - " 'bool' object has no attribute 'dumps'
Internal Server Error: /PDF/
"GET /PDF/?md5=f4b4e27d612aa4c6aeecf75da93de8f5&type=APK HTTP/1.1" 500 4848
"

pls help
![1](https://user-images.githubusercontent.com/50038794/56878808-86fcab80-6a73-11e9-99ed-da0f69d540d3.PNG)

**Comment by superpoussin22** [comment]
can you provide more details ?

- are you sing the last version of mobsf ?

- did you run the setup script

**Comment by bhavikp43** [comment]
yes. I did.
installed wkhtmltopdf n set binary to environment variable path.
still not running.
now another error occured for dynamic analysis setup.

""
./run.sh 
[2019-05-02 08:47:20 +0530] [5846] [INFO] Starting gunicorn 19.9.0
[2019-05-02 08:47:20 +0530] [5846] [INFO] Listening at: http://0.0.0.0:8000 (5846)
[2019-05-02 08:47:20 +0530] [5846] [INFO] Using worker: sync
[2019-05-02 08:47:20 +0530] [5849] [INFO] Booting worker with pid: 5849
[2019-05-02 08:47:20 +0530] [5849] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/DL/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/root/DL/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/root/DL/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/DL/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/DL/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/root/DL/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/DL/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/root/DL/Mobile-Security-Framework-MobSF/MobSF/wsgi.py", line 16, in <module>
    application = WhiteNoise(get_wsgi_application(),
  File "/root/DL/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/root/DL/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/root/DL/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/root/DL/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/root/DL/Mobile-Security-Framework-MobSF/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/root/DL/Mobile-Security-Framework-MobSF/venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/root/DL/Mobile-Security-Framework-MobSF/MobSF/settings.py", line 122
    'binary/octet-stream',currentSnapshot="{5ba8fe40-c525-46c9-955d-7586c1700a49}"
                                         ^
SyntaxError: invalid syntax
[2019-05-02 08:47:20 +0530] [5849] [INFO] Worker exiting (pid: 5849)
[2019-05-02 08:47:20 +0530] [5846] [INFO] Shutting down: Master
[2019-05-02 08:47:20 +0530] [5846] [INFO] Reason: Worker failed to boot.

""

i configured the following setting.
1)
#====ANDROID MOBSF VIRTUALBOX VM SETTINGS =====
    # VM UUID
    UUID = '0d52fca6-4336-41e3-b108-db0ce96544a7'
    # Snapshot UUID
    SUUID = '5ba8fe40-c525-46c9-955d-7586c1700a49'
    # IP of the MobSF VM
    VM_IP = '192.168.56.101'
    VM_ADB_PORT = 5555
    VM_TIMEOUT = 100
    VBOX_HEADLESS = False
2)
![2](https://user-images.githubusercontent.com/50038794/57055237-bf8cc700-6cb7-11e9-83ec-49e78cfaa6aa.PNG)

""

**Comment by ajinabraham** [comment]
Also please share the file for further debugging.

**Comment by ajinabraham** [comment]
I am kind of sure that this is due to the fact that wkhtmltopdf is not installed properly. Use latest MobSF 1.0.9. I am closing this. Feel free to comment with logs if you still see the issue.
