### ISSUE TITLE
docker compose install fail

### ISSUE THREAD

**Issue by sicko4sec** [MobSF/Mobile-Security-Framework-MobSF#945]
## ENVIRONMENT

```
OS and Version:Ubuntu 18.04
Python Version:
MobSF Version:Docker
```

## EXPLANATION OF THE ISSUE

```
Docker compose install error
```

## STEPS TO REPRODUCE THE ISSUE

```
1. git clone https://github.com/MobSF/Mobile-Security-Framework-MobSF.git
2. cd Mobile-Security-Framework-MobSF
3. docker-compose -f docker-compose.yml up -d
```

## LOG FILE

```
Step 23/30 : RUN git clone https://github.com/rednaga/APKiD.git &&     cd APKiD &&     python3 prep-release.py &&     cp apkid/rules/rules.yarc /root/Mobile-Security-Framework-MobSF/MalwareAnalyzer/ &&     sed -i 's#RULES_DIR =.*#RULES_DIR =  "/root/Mobile-Security-Framework-MobSF/MalwareAnalyzer"#' /usr/local/lib/python3.6/dist-packages/apkid/rules.py &&     cd .. &&     rm -fr APKiD
 ---> Running in c7681e047bb8
Cloning into 'APKiD'...
[*] Compiling Yara files
Traceback (most recent call last):
  File "prep-release.py", line 49, in <module>
    rules = rules_manager.compile()
  File "/root/Mobile-Security-Framework-MobSF/APKiD/apkid/rules.py", line 58, in compile
    self.rules = yara.compile(filepaths=yara_files)
yara.SyntaxError: /root/Mobile-Security-Framework-MobSF/APKiD/apkid/rules/dex/obfuscators.yara(66): invalid field name "header"
ERROR: Service 'mobsf' failed to build: The command '/bin/sh -c git clone https://github.com/rednaga/APKiD.git &&     cd APKiD &&     python3 prep-release.py &&     cp apkid/rules/rules.yarc /root/Mobile-Security-Framework-MobSF/MalwareAnalyzer/ &&     sed -i 's#RULES_DIR =.*#RULES_DIR =  "/root/Mobile-Security-Framework-MobSF/MalwareAnalyzer"#' /usr/local/lib/python3.6/dist-packages/apkid/rules.py &&     cd .. &&
rm -fr APKiD' returned a non-zero code: 1


```

**Comment by ajinabraham** [comment]
Use the latest MobSF Dockerfile. You are using an old version.

```
Step 21/30 : RUN pip3 install wheel
 ---> Running in 2fc8e1d6aaab
Collecting wheel
  Downloading https://files.pythonhosted.org/packages/bb/10/44230dd6bf3563b8f227dbf344c908d412ad2ff48066476672f3a72e174e/wheel-0.33.4-py2.py3-none-any.whl
Installing collected packages: wheel
Successfully installed wheel-0.33.4
Removing intermediate container 2fc8e1d6aaab
 ---> 15936af69bd9
Step 22/30 : RUN pip3 wheel --wheel-dir=/tmp/yara-python --build-option="build" --build-option="--enable-dex" git+https://github.com/VirusTotal/yara-python.git@v3.10.0
 ---> Running in 6d155fd903b3
Collecting git+https://github.com/VirusTotal/yara-python.git@v3.10.0
  Cloning https://github.com/VirusTotal/yara-python.git (to revision v3.10.0) to /tmp/pip-req-build-uigo8ls2
/usr/local/lib/python3.6/dist-packages/pip-19.1.1-py3.6.egg/pip/_internal/commands/wheel.py:109: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
  Running command git clone -q https://github.com/VirusTotal/yara-python.git /tmp/pip-req-build-uigo8ls2
  Running command git checkout -q 740af50dd57943e64af06c642f375ed8f70035ee
  Running command git submodule update --init --recursive -q
Building wheels for collected packages: yara-python
  Building wheel for yara-python (setup.py): started
  Building wheel for yara-python (setup.py): finished with status 'done'
  Stored in directory: /tmp/yara-python
Successfully built yara-python
```
