### ISSUE TITLE
ValueError: Unable to configure formatter 'color'

### ISSUE THREAD

**Issue by nick2root** [MobSF/Mobile-Security-Framework-MobSF#950]
i have a ValueError: Unable to configure formatter 'color' issue after running ./run.sh script from Kali Linux machine.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/gthread.py", line 104, in init_process
    super(ThreadWorker, self).init_process()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/opt/mobile/Mobile-Security-Framework-MobSF/MobSF/wsgi.py", line 16, in <module>
    application = WhiteNoise(get_wsgi_application(),
  File "/usr/local/lib/python3.7/dist-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.7/dist-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python3.7/dist-packages/django/utils/log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python3.7/logging/config.py", line 799, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.7/logging/config.py", line 545, in configure
    'formatter %r' % name) from e
**ValueError: Unable to configure formatter 'color'**
[2019-05-23 08:47:21 +0000] [6890] [INFO] Worker exiting (pid: 6890)
[2019-05-23 11:47:21 +0300] [6887] [INFO] Shutting down: Master
[2019-05-23 11:47:21 +0300] [6887] [INFO] Reason: Worker failed to boot.

![Capture](https://user-images.githubusercontent.com/25618690/58239284-75947f80-7d51-11e9-8e10-4fd575dc3c25.PNG)

**Comment by superpoussin22** [comment]
did you run a setup.sh 1st ?

**Comment by nick2root** [comment]
yes i already run setup.sh script. all log is attached.
[mobsf-log-all.txt](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/3211548/mobsf-log-all.txt)

**Comment by superpoussin22** [comment]
can you try before setup.sh :
sudo apt-get install libfreetype6-dev

**Comment by nick2root** [comment]
thanks a lot bro, everything is fine :)

**Comment by Fathima704** [comment]
I have a Mac 10.13.6 and am facing the same issue. I tried getting freetype, still no luck. Help please?

**Comment by ajinabraham** [comment]
@Fathima704 Please use our slack channel for support
