### ISSUE TITLE
Application error on iOS app scan

### ISSUE THREAD

**Issue by sanjogpandasp** [MobSF/Mobile-Security-Framework-MobSF#952]
## ENVIRONMENT

```
OS and Version: macOS Mojave
Python Version: Python 2.7.10
MobSF Version: Mobile Security Framework v1.0.7 Beta
```

## EXPLANATION OF THE ISSUE

When I upload an iOS app I get the below error after the upload is complete. 

## STEPS TO REPRODUCE THE ISSUE

```
1. Run the docker of mobsf
2. upload the ios file from the browser
3. You get the error on the browser `Don't Play Around. An Error just popped in!`
```
Screenshots attached. 

<img width="1409" alt="error- log" src="https://user-images.githubusercontent.com/5404943/58400103-cc62c780-8077-11e9-9953-683e7036f5d3.png">

<img width="1431" alt="browser_error" src="https://user-images.githubusercontent.com/5404943/58400149-ebf9f000-8077-11e9-880e-56c1f2911b20.png">

**Comment by superpoussin22** [comment]
can you update to last version ?  MobSF is now 1.1.1

**Comment by ajinabraham** [comment]
Too old version. MobSF is Python3 now, please use latest master.

**Comment by s2339956** [comment]
Mobile Security Framework v1.1.6 Beta


```
[INFO] 23/Aug/2019 07:43:24 - MIME Type: application/octet-stream FILE: 123_ios_7_4_0_20190819_123_sec.ipa
[INFO] 23/Aug/2019 07:43:24 - Performing Static Analysis of iOS IPA
[INFO] 23/Aug/2019 07:43:24 - iOS Static Analysis Started
[INFO] 23/Aug/2019 07:43:24 - iOS Binary (IPA) Analysis Started
[INFO] 23/Aug/2019 07:43:24 - Generating Hashes
[INFO] 23/Aug/2019 07:43:25 - Extracting IPA
[INFO] 23/Aug/2019 07:43:25 - Unzipping
[INFO] 23/Aug/2019 07:43:25 - Get Files, BIN Plist -> XML, and Normalize
[INFO] 23/Aug/2019 07:43:26 - iOS Info.plist Analysis Started
[INFO] 23/Aug/2019 07:43:26 - Finding Info.plist in iOS Binary
[INFO] 23/Aug/2019 07:43:26 - Checking Permissions
[INFO] 23/Aug/2019 07:43:26 - Checking for Insecure Connections
[INFO] 23/Aug/2019 07:43:26 - Fetching Details from App Store: tw.gov.post.guard
[WARNING] 23/Aug/2019 07:43:26 - Unable to get app details
[INFO] 23/Aug/2019 07:43:26 - Starting Binary Analysis
[WARNING] 23/Aug/2019 07:43:26 - MobSF Cannot find binary in /Users/digicentre/Mobile-Security-Framework-MobSF/uploads/5b6cb1a59623d5018690eb80992e4a1d/Payload/Θâ╡Σ┐¥Θæú.app/123
[WARNING] 23/Aug/2019 07:43:26 - Skipping Otool, Classdump and Strings
[INFO] 23/Aug/2019 07:43:26 - Connecting to DB
[INFO] 23/Aug/2019 07:43:26 - Saving to Database
[ERROR] 23/Aug/2019 07:43:26 - Saving to DB
Traceback (most recent call last):
  File "/Users/digicentre/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/db_interaction.py", line 174, in create_db_entry_ipa
    MACHOINFO=bin_dict['macho'],
KeyError: 'macho'
[ERROR] 23/Aug/2019 07:43:26 - Rendering to Template
Traceback (most recent call last):
  File "/Users/digicentre/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/db_interaction.py", line 46, in get_context_from_analysis_ipa
    'binary_info': bin_dict['macho'],
KeyError: 'macho'
[ERROR] 23/Aug/2019 07:43:26 - Error Perfroming Static Analysis
Traceback (most recent call last):
  File "/Users/digicentre/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios/static_analyzer.py", line 181, in static_analyzer_ios
    context['VT_RESULT'] = None
TypeError: 'NoneType' object does not support item assignment
[ERROR] 23/Aug/2019 07:43:26 - 'NoneType' object does not support item assignment
[ERROR] 23/Aug/2019 07:43:26 - Internal Server Error: /StaticAnalyzer_iOS/
```
