### ISSUE TITLE
Cannot Run Process utils.py

### ISSUE THREAD

**Issue by aaaaaaaaabbbbbbbbbbbbbbb** [MobSF/Mobile-Security-Framework-MobSF#956]
Linux  python 3.6  jdk8
./run.bat
The error logs:

Finding Java path - Cannot Run Process (/usr/mobsf/MobSF/utils.py, LINE 364 "args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,)"): [Errno 13] Permission denied

Finding Java path - Cannot Run Process (/usr/mobsf/MobSF/utils.py, LINE 364 "args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,)"): [Errno 13] Permission denied
[2019-05-29 10:19:18 +0800] [27989] [INFO] Shutting down: Master
[2019-05-29 10:19:18 +0800] [27989] [INFO] Reason: Worker failed to boot.

Please help to see what the problem is

**Comment by superpoussin22** [comment]
if you are on linux, why do you run .bat files ?
you shoulkd run :
./setup.sh
./run.sh

**Comment by Toetoise** [comment]
run  ./setup.sh  and  ./run.sh
the error still exist

error logs:
Finding Java path - Cannot Run Process (/opt/Mobile-Security-Framework-MobSF-master/MobSF/utils.py, LINE 364 "args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,)"): [Errno 13] Permission denied: '/usr/bin/java'

**Comment by superpoussin22** [comment]
is java installed and with correct permission ?

**Comment by Toetoise** [comment]
i don't know what is the correct permission.
According to the tutorial installation, there will still be this problem.
maybe u can give me a complete installation tutorial ?

error logs：
Finding Java path - Cannot Run Process (/opt/Mobile-Security-Framework-MobSF-master/MobSF/utils.py, LINE 366 "args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,)"): [Errno 2] No such file or directory: '/usr/bin/java'

Finding Java path - Cannot Run Process (/opt/Mobile-Security-Framework-MobSF-master/MobSF/utils.py, LINE 366 "args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,)"): [Errno 2] No such file or directory: '/usr/bin/java'

**Comment by ajinabraham** [comment]
You don't have Java available on that path. Set JAVA path in settings.py

**Comment by Toetoise** [comment]
there are so many files named setting.py , modify which one?

./MobSF/settings.py
./venv/lib/python3.6/site-packages/jedi/settings.py
./venv/lib/python3.6/site-packages/play_scraper/settings.py
./venv/lib/python3.6/site-packages/h2/settings.py
./venv/lib/python3.6/site-packages/capfuzz/settings.py

and modify which line in that file ?

**Comment by ajinabraham** [comment]
It's MobSF settings.

**Comment by Toetoise** [comment]
The last problem was solved.But now the logs like this.
[root@zlglb-server7 Mobile-Security-Framework-MobSF-master]# ./run.sh 
[2019-06-13 11:07:39 +0800] [17516] [INFO] Starting gunicorn 19.9.0
[2019-06-13 11:07:39 +0800] [17516] [INFO] Listening at: http://0.0.0.0:8000 (17516)
[2019-06-13 11:07:39 +0800] [17516] [INFO] Using worker: threads
[2019-06-13 11:07:39 +0800] [17519] [INFO] Booting worker with pid: 17519
[2019-06-13 11:07:40 +0800] [17516] [INFO] Shutting down: Master
[2019-06-13 11:07:40 +0800] [17516] [INFO] Reason: Worker failed to boot.

**Comment by ajinabraham** [comment]
Looks like the changes you made are causing a syntax error.

**Comment by ajinabraham** [comment]
You might want to try activate virtualenv and run the Dev server to see what's the error.
```. venv/bin/activate
pyrhon manage.py runserver
```

**Comment by Toetoise** [comment]
i do it. logs like this
[INFO] 13/Jun/2019 03:19:51 - Watching for file changes with StatReloader
[DEBUG] 13/Jun/2019 03:19:51 - Waiting for apps ready_event.
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/bin/python3.6.2/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/bin/python3.6.2/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/Mobile-Security-Framework-MobSF-master/venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/opt/Mobile-Security-Framework-MobSF-master/venv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/opt/Mobile-Security-Framework-MobSF-master/venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File "/opt/Mobile-Security-Framework-MobSF-master/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/opt/Mobile-Security-Framework-MobSF-master/venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/opt/Mobile-Security-Framework-MobSF-master/venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/Mobile-Security-Framework-MobSF-master/venv/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/opt/Mobile-Security-Framework-MobSF-master/venv/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/Mobile-Security-Framework-MobSF-master/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/opt/Mobile-Security-Framework-MobSF-master/venv/lib/python3.6/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/opt/Mobile-Security-Framework-MobSF-master/venv/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/opt/Mobile-Security-Framework-MobSF-master/venv/lib/python3.6/site-packages/django/db/models/base.py", line 117, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/opt/Mobile-Security-Framework-MobSF-master/venv/lib/python3.6/site-packages/django/db/models/base.py", line 321, in add_to_class
    value.contribute_to_class(cls, name)
  File "/opt/Mobile-Security-Framework-MobSF-master/venv/lib/python3.6/site-packages/django/db/models/options.py", line 204, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/opt/Mobile-Security-Framework-MobSF-master/venv/lib/python3.6/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/opt/Mobile-Security-Framework-MobSF-master/venv/lib/python3.6/site-packages/django/db/utils.py", line 201, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/opt/Mobile-Security-Framework-MobSF-master/venv/lib/python3.6/site-packages/django/db/utils.py", line 110, in load_backend
    return import_module('%s.base' % backend_name)
  File "/opt/Mobile-Security-Framework-MobSF-master/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/Mobile-Security-Framework-MobSF-master/venv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 13, in <module>
    from sqlite3 import dbapi2 as Database
  File "/usr/bin/python3.6.2/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/bin/python3.6.2/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

**Comment by ajinabraham** [comment]
you don't have the proper dependencies required by the project
``
ModuleNotFoundError: No module named '_sqlite3'
```
Install all the required dependencies.

**Comment by Toetoise** [comment]
What required dependencies are needed for this project ? can you enumerate

**Comment by ajinabraham** [comment]
See requirements.txt.
The setup script tries to install that by default. If it fails that means you have some missing libs in your system. You will have to figure out via logs and install them separately
