### ISSUE TITLE
Unhandled Exception, System.InvalidOperationException while analyzing .appx file

### ISSUE THREAD

**Issue by Kirthikmr** [MobSF/Mobile-Security-Framework-MobSF#957]
Hi Team, 

I'm facing an issue while analyzing .appx files 

`Unhandled Exception: System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable'1 source, Func'2 predicate)
   at CommandLine.Core.TypeLookup.FindTypeDescriptorAndSibling(String name, IEnumerable'1 specifications, StringComparer comparer)
   at CommandLine.Core.Switch.<>c__DisplayClass0_0.<Partition>b__0(Token t)
   at System.Linq.Enumerable.WhereArrayIterator'1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable'1 source)
   at CSharpx.EnumerableExtensions.Memorize[T](IEnumerable'1 source)
   at CommandLine.Core.TokenPartitioner.Partition(IEnumerable'1 tokens, Func'2 typeLookup)
   at CommandLine.Core.InstanceBuilder.<>c__DisplayClass0_0'1.<Build>b__7()
   at CommandLine.Core.InstanceChooser.MatchVerb(Func'3 tokenizer, IEnumerable'1 verbs, IEnumerable'1 arguments, StringComparer nameComparer, CultureInfo parsingCulture, IEnumerable'1 nonFatalErrors)
   at CommandLine.Core.InstanceChooser.<>c__DisplayClass0_0.<Choose>b__0()
   at CommandLine.Parser.ParseArguments(IEnumerable'1 args, Type[] types)
   at Microsoft.CodeAnalysis.IL.BinSkim.Main(String[] args)
[ERROR] 29/May/2019 17:54:12 - [Errno 2] No such file or directory: 'C:\\Users\\kiruthiga.k.r\\Mobile-Security-Framework-MobSF\\uploads/126900321753d4acd0bec54a13d0ed38/MusicFolder.exe_binskim'
[ERROR] 29/May/2019 17:54:12 - Internal Server Error: /StaticAnalyzer_Windows/
ERROR:django.request:Internal Server Error: /StaticAnalyzer_Windows/`

MobSF works fine when I analyze .apk files but it gives me error while I try to analyze .appx files. I have run the command `setup.py` in command prompt also and installed `Binskim` and other tools also like `BinScope` but it keeps giving me error. Please look at the above error and help me out of it so I can go for further. 

Attaching two screenshots also for the reference. 

Browser:

![error](https://user-images.githubusercontent.com/41776681/61106157-cdba4900-a499-11e9-910b-7a7045e2cfb6.png)

Cmd:

![image](https://user-images.githubusercontent.com/41776681/58558915-996b3000-823f-11e9-8672-1faf3308c8aa.png)

Thanks in advance.

**Comment by ajinabraham** [comment]
Please share the file that caused the issue.

**Comment by ajinabraham** [comment]
Related: https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/954

**Comment by ajinabraham** [comment]
Please share the file that causes this issue.

**Comment by Kiruthiga11246408** [comment]
Attached the file
[Core-Music-Player.zip](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/3233430/Core-Music-Player.zip)

**Comment by Kirthikmr** [comment]
Please let us know if there is any update on this

**Comment by ajinabraham** [comment]
Haven't triaged this yet. This will take some time.

**Comment by Kirthikmr** [comment]
Hi,
Could you please help on the below queries, observed during .appx analysis:
1) in bin_an_results section, "desc" seems to be incomplete for "rule_id": "BA3010", getting the below description:
  "desc": "This check ensures that some relocation data is marked as read only after the executable is loaded, and moved below the ." 

2) Getting below exception in log file:
Exception while resolving variable 'info' in template 'static_analysis/windows_binary_analysis.html'.

3)Also please help us understanding the "strings" section,

**Comment by ajinabraham** [comment]
Fixed in https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1043

@Kirthikmr The strings section contains strings extracted from the APPX, useful when analyzing malware or third party appx. Please use slack channel for discussion. Githib issues is strictly for bugs and feature request.
