### ISSUE TITLE
application getting aborted after an hour of execution

### ISSUE THREAD

**Issue by srivga** [MobSF/Mobile-Security-Framework-MobSF#977]
post request gives the following error after an hour of successful execution, seek help

__  __       _    ____  _____         _   ___
 |  \/  | ___ | |__/ ___||  ___| __   _/ | / _ \
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / || | | |
 | |  | | (_) | |_) |__) |  _|    \ V /| || |_| |
 |_|  |_|\___/|_.__/____/|_|       \_/ |_(_)___/

[INFO] 12/Jun/2019 08:30:44 - ESC[1mESC[34mMobile Security Framework v1.1.1 BetaESC[0m
[ERROR] 12/Jun/2019 08:30:44 - Internal Server Error: /
Traceback (most recent call last):
  File "/root/mobsf/Mobile-Security-Framework-MobSF/venv/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/mobsf/Mobile-Security-Framework-MobSF/venv/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 111, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/root/mobsf/Mobile-Security-Framework-MobSF/venv/local/lib/python3.6/dist-packages/django/urls/resolvers.py", line 491, in resolve
    for pattern in self.url_patterns:
  File "/root/mobsf/Mobile-Security-Framework-MobSF/venv/local/lib/python3.6/dist-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/mobsf/Mobile-Security-Framework-MobSF/venv/local/lib/python3.6/dist-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/root/mobsf/Mobile-Security-Framework-MobSF/venv/local/lib/python3.6/dist-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/mobsf/Mobile-Security-Framework-MobSF/venv/local/lib/python3.6/dist-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/root/mobsf/Mobile-Security-Framework-MobSF/venv/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/mobsf/Mobile-Security-Framework-MobSF/MobSF/urls.py", line 96, in <module>
    utils.printMobSFverison()
  File "/root/mobsf/Mobile-Security-Framework-MobSF/MobSF/utils.py", line 79, in printMobSFverison
:

**Comment by superpoussin22** [comment]
can you provide more details on the platform you use ? and also if you were analyzing an app ?
can you also upgrade to last version ?

**Comment by srivga** [comment]
Platform : Linux
Yes we are analyzing an app, however the problem arises when the server(on which mobsf tool is hosted) is idle for more than 30 mins

**Comment by srivga** [comment]
We are using Mobile Security Framework v1.1.1 Beta

**Comment by superpoussin22** [comment]
last version is 1.1.2 beta 
which linux is it ? Ubuntu ?
Hw many ram/ cpu do you have ?

on a tiny instance with docker in my case it never crash like this

**Comment by srivga** [comment]
Linux : Linux version 4.14.62-65.117.amzn1.x86_64 (mockbuild@gobi-build-60009) (gcc vers                                                                             ion 7.2.1 20170915 (Red Hat 7.2.1-2) (GCC))
Ram : 4gb
CPU : 2cpu = 2 physical cores

**Comment by ajinabraham** [comment]
Please report a bug after reading the guidelines
